// Host file system: the card layer under SharedFilePtr.
//
// SEAM LEVEL: SharedFilePtr::Load(). Everything above it -- LoadFile's
// refcounting, Release, func_02017c24, func_02017e0c, and every
// Model/Animation/Collider LoadFile -- is portable src/ and runs verbatim.
// Load itself is card hardware (overlay-file table, card streaming, CP15
// cache flushes), so the HAL reimplements its CONTRACT: resolve fileID to
// bytes, decompress if LZ77-tagged, allocate the result from the game's own
// heap (gate 3a), stash filePtr, return it.
//
// ID NAMESPACES (the trap): callers construct with an ov0 HANDLE; the ctor
// helper func_02017e0c stores func_02018a24(handle) -- the FAT file id --
// into this->fileID. The HAL provides func_02018a24 from the asset catalog
// (build/assets/handles.tsv: handle -> file_id -> path, generated by
// tools/asset_catalog.py from the ROM). File bytes come from
// extracted/dsd/files/<path>.
//
// Construct is HAL-owned for an ABI reason, not a hardware one: on the DS,
// _ZN13SharedFilePtr9ConstructEj passes ov0FileID to func_02017e48 by
// LEAVING IT IN r1 across a call that only names one argument -- a
// ride-through C cannot express. The host version calls func_02017e0c with
// both arguments spelled out; same result, portable ABI.
//
// COMPRESSION: 1,287 catalog files begin with ASCII "LZ77" followed by a
// standard type-0x10 stream (u32 header: 0x10 | decompressed_size << 8).
// DecompressLZ16 is an asm hatch in src/, so the HAL carries a byte-wise
// C decode; the DS asm's halfword write dance is VRAM-safety only, the
// output bytes are identical (smoke_fs cross-checks against values computed
// by an independent Python decoder).
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

#ifndef PORT_REPO_ROOT
#define PORT_REPO_ROOT "."
#endif

// ---- the asset catalog ---------------------------------------------------
enum { MAX_FILES = 4096, MAX_HANDLES = 4096, PATH_MAX_ = 260 };

static char g_paths[MAX_FILES][PATH_MAX_]; /* by FAT file id */
static u16 g_handle_to_id[MAX_HANDLES];    /* ov0 handle -> FAT file id */
static int g_catalog_loaded;

static const char *asset_root(void)
{
    const char *env = getenv("SM64DS_ASSET_ROOT");
    return env ? env : PORT_REPO_ROOT;
}

static void catalog_load(void)
{
    char line[512], path[PATH_MAX_];
    FILE *f;
    if (g_catalog_loaded)
        return;
    g_catalog_loaded = 1;

    snprintf(path, sizeof path, "%s/build/assets/files.tsv", asset_root());
    f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "FATAL: fs catalog missing: %s\n"
                "       run tools/asset_catalog.py generate <rom>\n", path);
        abort();
    }
    fgets(line, sizeof line, f); /* header row */
    while (fgets(line, sizeof line, f)) {
        unsigned id;
        char p[PATH_MAX_];
        if (sscanf(line, "%u\t%*s\t%259[^\t]", &id, p) == 2 && id < MAX_FILES)
            strcpy(g_paths[id], p);
    }
    fclose(f);

    snprintf(path, sizeof path, "%s/build/assets/handles.tsv", asset_root());
    f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "FATAL: fs catalog missing: %s\n", path);
        abort();
    }
    fgets(line, sizeof line, f);
    while (fgets(line, sizeof line, f)) {
        unsigned h, id;
        if (sscanf(line, "%u\t%*s\t%u", &h, &id) == 2 && h < MAX_HANDLES)
            g_handle_to_id[h] = (u16)id;
    }
    fclose(f);
}

// ---- the game-facing surface ---------------------------------------------
// The Memory:: layer is real C++ on host (gate-3a slice), so the HAL calls
// the namespace; the C-linkage name below serves the C TUs (func_02017c24).
namespace Memory {
void *Allocate(u32 size);
void *Allocate(u32 size, int align);
void Deallocate(void *p);
}
extern "C" void _ZN6Memory10DeallocateEPv(void *p) { Memory::Deallocate(p); }

extern "C" {
u32 data_0209d3bc; /* last fileID touched; the game's FS breadcrumb */

/* ov0 handle -> FAT file id (data_ov000_020bd4b8 on the DS) */
u16 func_02018a24(u32 handle)
{
    catalog_load();
    if (handle >= MAX_HANDLES || g_paths[g_handle_to_id[handle]][0] == 0) {
        fprintf(stderr, "FATAL: fs handle %u not in catalog\n", handle);
        abort();
    }
    return g_handle_to_id[handle];
}

/* LZ77 type-0x10 decode; src points at the u32 header */
void DecompressLZ16(void *src_, void *dst_)
{
    const u8 *s = (const u8 *)src_;
    u8 *d = (u8 *)dst_;
    u32 size = (s[0] | s[1] << 8 | s[2] << 16 | (u32)s[3] << 24) >> 8;
    u32 out = 0;
    s += 4;
    while (out < size) {
        u8 flags = *s++;
        for (int bit = 0; bit < 8 && out < size; ++bit) {
            if (flags & (0x80 >> bit)) {
                u32 len = (s[0] >> 4) + 3;
                u32 disp = ((s[0] & 0xF) << 8 | s[1]) + 1;
                s += 2;
                while (len-- && out < size) {
                    d[out] = d[out - disp];
                    ++out;
                }
            } else {
                d[out++] = *s++;
            }
        }
    }
}

/* SharedFilePtr::Load -- the seam. Same contract as 0x02017c54. */
struct SharedFilePtrC { u16 fileID; u8 numRefs; void *filePtr; };

void *_ZN13SharedFilePtr4LoadEv(struct SharedFilePtrC *self)
{
    char path[PATH_MAX_ * 2];
    FILE *f;
    long fsize;
    u8 *raw;
    void *dst;

    catalog_load();
    data_0209d3bc = self->fileID;
    if (self->fileID >= MAX_FILES || g_paths[self->fileID][0] == 0) {
        fprintf(stderr, "FATAL: fs fileID %u not in catalog "
                "(archive-interior ids >= 0x8000 not hosted yet)\n",
                self->fileID);
        abort();
    }
    snprintf(path, sizeof path, "%s/extracted/dsd/files/%s",
             asset_root(), g_paths[self->fileID]);
    f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "FATAL: fs cannot open %s\n", path);
        abort();
    }
    fseek(f, 0, SEEK_END);
    fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    raw = (u8 *)malloc(fsize);
    if ((long)fread(raw, 1, fsize, f) != fsize) {
        fclose(f);
        free(raw);
        return 0; /* real Load returns 0 on a short read */
    }
    fclose(f);

    if (fsize > 8 && memcmp(raw, "LZ77", 4) == 0) {
        u32 dec = (raw[4] | raw[5] << 8 | raw[6] << 16 | (u32)raw[7] << 24) >> 8;
        dst = Memory::Allocate(dec);
        DecompressLZ16(raw + 4, dst);
    } else {
        dst = Memory::Allocate((u32)fsize, 0x20);
        memcpy(dst, raw, fsize);
    }
    free(raw);
    self->filePtr = dst;
    return dst;
}

/* Construct: host ABI spells out both args (see header comment) */
void func_02017e0c(void *self, u32 arg); /* portable src/ */
struct SharedFilePtrC *_ZN13SharedFilePtr9ConstructEj(
        struct SharedFilePtrC *self, u32 ov0FileID)
{
    func_02017e0c(self, ov0FileID);
    return self;
}
} /* extern "C" */
