// ROM-CLEAN boot loader (2026-08-10).
//
// walk_window.exe embeds ZERO Nintendo ROM bytes. Every ROM-derived table that
// romdata.py / ovdata.py used to bake into the binary is now a ZEROED array in
// the generated C, and the real bytes travel in one runtime file,
// build/assets/romdata.bin, produced from the user's own ROM at first run (and
// from the repo's extracted/ at dev-build time). port_romdata_load() reads that
// file, verifies it against build/assets/romdata.manifest, and memcpys each
// slice into its array via the generated dispatch (port_romdata_load_all).
//
// SEAM / ORDER: this runs at the very top of the game's boot, right after the
// asset root is resolvable and BEFORE the first read of any ROM table
// (port_ov002_patch, the sinits, Heap::SetupRootHeap). The pointer-rebase passes
// that follow (port_ov002_patch, port_cross_patch, port_ovNNN_[syms_]patch, the
// hand seats) run over the freshly-loaded bytes exactly as they did when the
// bytes were a linker initialiser -- the change is only WHERE the bytes live.
//
// LOUD TRAP (release discipline): a missing, short, or wrong romdata.bin, or any
// manifest disagreement (whole-file sha, a part sha, or a symbol size), is a
// FATAL abort that NAMES the file. A ROM-clean exe with no romdata.bin cannot
// run the game -- it must say so, not limp along on zeroed tables.
//
// THE MANIFEST CHECK IS SELF-CONSISTENCY. IT IS NOT BUILD IDENTITY. (2026-08-26)
// -----------------------------------------------------------------------------
// NOT YET OBSERVED IN THE FIELD, and the note below says so where it matters.
// This guard came out of a crash investigation that turned out to be a
// different bug (see the end of this block); the hole it closes was found by
// reading the loader, not by a player falling into it. That is the right order
// and it is worth saying plainly, because a guard whose write-up claims a
// victim it does not have is a guard nobody re-derives.
// -----------------------------------------------------------------------------
// Everything above verifies romdata.bin against romdata.manifest -- and the
// manifest SHIPS BESIDE THE BLOB, in the same asset folder. So the whole check
// answers "is this blob intact", never "is this blob MINE". An asset folder
// from an older release carries an older romdata.bin AND the older manifest
// that describes it; every sha agrees, every size agrees, and this file prints
// its cheerful "[romdata] loaded N bytes" and hands the blob on.
//
// What it hands the blob to is port_romdata_load_all, generated by
// port/tools/romblob.py, whose per-part BASE OFFSETS ARE BAKED INTO THIS EXE.
// Another build's blob has another build's parts at other offsets, so every ROM
// table -- the sine table, the level tables, the path and floor records, every
// overlay's data -- is filled from the wrong slice, in silence.
//
// Measured, not argued: port/tools/install_mismatch_probe.py builds a second
// blob out of the same emitters' parts with one early part left out -- an
// internally perfect asset folder belonging to a different build -- and boots
// the window on it with the guard off. The world comes up with impossible level
// data and takes an access violation. That is the whole failure mode, on demand.
//
// HOW A PLAYER WOULD REACH IT, AND WHY NONE HAS YET. The shipped kit carries no
// romdata.bin: it ships romdata.recipe.tsv and a manifest, and the player's own
// machine builds the blob from their ROM at first run. So the blob in a player's
// folder is normally the one their own exe asked for. It takes a folder that
// outlives the build that filled it -- an in-place upgrade that replaces the exe
// and leaves build/assets, a hand-copied folder, an installer that reuses a
// path -- and the failure is then silent and total. No report has shown this
// yet. The guard is here because the mechanism is real and nothing looked at
// it, which is the only honest reason to write one.
//
// (This was written during the 2026-08-26 crash burst and was first believed to
// explain it. It does not: that install's data matched its exe. See the note at
// the top of hal/lk7_persist.cpp for what that burst actually was.)
//
// The fix is one equality. romblob.py now stamps the blob it computed the
// offsets from -- port_romdata_expect_sha / port_romdata_expect_len -- into the
// same generated dispatch TU that carries the offsets, so the two cannot drift.
// This file compares before it loads, and a disagreement is a POLITE REFUSAL
// (the plain-language startup_error.txt + dialog the missing-asset-root path
// already uses, exit 2) rather than a crash three seconds later. It names both
// blobs, so the person reading it -- a player, or us reading their report --
// can see it is an install problem and not a bug in the game.
//
// SM64DS_ROMDATA_NO_GUARD=1 downgrades the refusal to a warning, for the one
// case where somebody deliberately wants to look at a mismatched pair.
//
// WHY ROMDATA.BIN IS THE ONLY FILE HERE THAT NEEDS A BUILD STAMP
// -------------------------------------------------------------
// The asset root holds more than this: build/assets/files.tsv, handles.tsv,
// nitrofs.tsv and the two nitrofs images, plus the extracted/ tree the sdat and
// the open-by-name seam read. None of them gets a stamp, and that is a decision
// rather than an omission. Those files are ROM-DERIVED AND BUILD-INVARIANT --
// file ids, NitroFS offsets, sizes, all read out of the player's own ROM. Two
// different builds of the port produce byte-identical copies from the same ROM,
// so "which build wrote this" is not a question they can answer and a stamp on
// them would refuse installs that are perfectly fine.
// romdata.bin is the opposite: its layout IS this build's, decided by the
// emitter set in port/CMakeLists.txt and the offsets romblob.py computes from
// it. It is the artifact in the folder that changes when the build changes,
// which is exactly why it is the one that carries the identity.
// The residual, stated so it is somebody's to keep true: if the CATALOG FORMATS
// ever change shape, the guard here will not see it. Their readers must keep
// refusing an unrecognised header rather than misreading one.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef unsigned char u8;
typedef unsigned int u32;
typedef unsigned long long u64;

#ifndef PORT_REPO_ROOT
#define PORT_REPO_ROOT "."
#endif

// The generated dispatch (build/port/host-src/romdata_dispatch.c).
extern "C" void port_romdata_load_all(const u8 *blob);
// ...and, from the SAME generated file, which blob those offsets were computed
// from. Written by port/tools/romblob.py in the run that wrote the offsets.
extern "C" const char port_romdata_expect_sha[];
extern "C" const unsigned long long port_romdata_expect_len;

#ifdef PORT_ROM_CLEAN
// hal/asset_root_refuse.cpp: a shipping build refuses an unset asset root
// instead of falling back to the path cmake baked in, and refuses an asset
// folder that belongs to a different build of the game.
extern "C" void port_asset_root_refuse(const char *wanted);
extern "C" void port_asset_mismatch_refuse(const char *detail);
#endif

// hal/os_arena.cpp: the one-line install verdict the crash dump carries, and
// the record of WHICH GAME DATA this process booted from.
//
// hal/lk7_persist.cpp stamps a disk save state with that identity, because a
// save state is a snapshot of a world that romdata.bin produced -- the exe-side
// fields in that header (gittip, image base, section bounds) cannot see a
// changed asset folder at all. This file is the only writer; the storage lives
// in os_arena.cpp because lk7_persist is compiled into targets this file is
// not, and empty/zero is the right reading there.
extern "C" {
void port_install_verdict_add(const char *line);
extern char               port_romdata_sha[65];      // whole-blob sha256, hex, or ""
extern unsigned long long port_romdata_bytes;        // its length, or 0
extern char               port_asset_root_seen[512]; // the root it came from, or ""
}

// ---- a self-contained SHA-256 (no external crypto dependency) --------------
// Standard FIPS-180-4. Kept local so the exe carries no DLL/crypto import.
namespace {

struct Sha256 {
    u32 h[8];
    u64 len;
    u8 buf[64];
    unsigned n;
};

const u32 K256[64] = {
    0x428a2f98u,0x71374491u,0xb5c0fbcfu,0xe9b5dba5u,0x3956c25bu,0x59f111f1u,
    0x923f82a4u,0xab1c5ed5u,0xd807aa98u,0x12835b01u,0x243185beu,0x550c7dc3u,
    0x72be5d74u,0x80deb1feu,0x9bdc06a7u,0xc19bf174u,0xe49b69c1u,0xefbe4786u,
    0x0fc19dc6u,0x240ca1ccu,0x2de92c6fu,0x4a7484aau,0x5cb0a9dcu,0x76f988dau,
    0x983e5152u,0xa831c66du,0xb00327c8u,0xbf597fc7u,0xc6e00bf3u,0xd5a79147u,
    0x06ca6351u,0x14292967u,0x27b70a85u,0x2e1b2138u,0x4d2c6dfcu,0x53380d13u,
    0x650a7354u,0x766a0abbu,0x81c2c92eu,0x92722c85u,0xa2bfe8a1u,0xa81a664bu,
    0xc24b8b70u,0xc76c51a3u,0xd192e819u,0xd6990624u,0xf40e3585u,0x106aa070u,
    0x19a4c116u,0x1e376c08u,0x2748774cu,0x34b0bcb5u,0x391c0cb3u,0x4ed8aa4au,
    0x5b9cca4fu,0x682e6ff3u,0x748f82eeu,0x78a5636fu,0x84c87814u,0x8cc70208u,
    0x90befffau,0xa4506cebu,0xbef9a3f7u,0xc67178f2u,
};

inline u32 ror(u32 x, unsigned r) { return (x >> r) | (x << (32 - r)); }

void sha_init(Sha256 *s) {
    static const u32 iv[8] = {
        0x6a09e667u,0xbb67ae85u,0x3c6ef372u,0xa54ff53au,
        0x510e527fu,0x9b05688cu,0x1f83d9abu,0x5be0cd19u,
    };
    memcpy(s->h, iv, sizeof iv);
    s->len = 0;
    s->n = 0;
}

void sha_block(Sha256 *s, const u8 *p) {
    u32 w[64];
    for (int i = 0; i < 16; ++i)
        w[i] = (u32(p[i*4]) << 24) | (u32(p[i*4+1]) << 16) |
               (u32(p[i*4+2]) << 8) | u32(p[i*4+3]);
    for (int i = 16; i < 64; ++i) {
        u32 s0 = ror(w[i-15],7) ^ ror(w[i-15],18) ^ (w[i-15] >> 3);
        u32 s1 = ror(w[i-2],17) ^ ror(w[i-2],19) ^ (w[i-2] >> 10);
        w[i] = w[i-16] + s0 + w[i-7] + s1;
    }
    u32 a=s->h[0],b=s->h[1],c=s->h[2],d=s->h[3],
        e=s->h[4],f=s->h[5],g=s->h[6],hh=s->h[7];
    for (int i = 0; i < 64; ++i) {
        u32 S1 = ror(e,6) ^ ror(e,11) ^ ror(e,25);
        u32 ch = (e & f) ^ (~e & g);
        u32 t1 = hh + S1 + ch + K256[i] + w[i];
        u32 S0 = ror(a,2) ^ ror(a,13) ^ ror(a,22);
        u32 maj = (a & b) ^ (a & c) ^ (b & c);
        u32 t2 = S0 + maj;
        hh=g; g=f; f=e; e=d+t1; d=c; c=b; b=a; a=t1+t2;
    }
    s->h[0]+=a; s->h[1]+=b; s->h[2]+=c; s->h[3]+=d;
    s->h[4]+=e; s->h[5]+=f; s->h[6]+=g; s->h[7]+=hh;
}

void sha_update(Sha256 *s, const u8 *p, size_t n) {
    s->len += n;
    while (n) {
        unsigned take = 64 - s->n;
        if (take > n) take = (unsigned)n;
        memcpy(s->buf + s->n, p, take);
        s->n += take; p += take; n -= take;
        if (s->n == 64) { sha_block(s, s->buf); s->n = 0; }
    }
}

void sha_final(Sha256 *s, char out[65]) {
    u64 bits = s->len * 8;
    u8 pad = 0x80;
    sha_update(s, &pad, 1);
    u8 zero = 0;
    while (s->n != 56) sha_update(s, &zero, 1);
    u8 lenbe[8];
    for (int i = 0; i < 8; ++i) lenbe[i] = (u8)(bits >> (56 - i*8));
    sha_update(s, lenbe, 8);
    for (int i = 0; i < 8; ++i)
        snprintf(out + i*8, 9, "%08x", s->h[i]);
    out[64] = 0;
}

void sha256_hex(const u8 *p, size_t n, char out[65]) {
    Sha256 s; sha_init(&s); sha_update(&s, p, n); sha_final(&s, out);
}

const char *asset_root() {
    const char *env = getenv("SM64DS_ASSET_ROOT");
#ifdef PORT_ROM_CLEAN
    /* No PORT_REPO_ROOT fallback in a shipping build; hal/asset_root_refuse.cpp
       is the write-up. This file is only ever compiled into a PORT_ROM_CLEAN
       target, so the guard is belt and braces -- it keeps the shape identical
       to the other three seams rather than making this one the exception. */
    if (!env)
        port_asset_root_refuse("build/assets/romdata.bin");
#endif
    return env ? env : PORT_REPO_ROOT;
}

// Read an entire file. Returns malloc'd bytes + length, or NULL on any error.
u8 *read_all(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) return 0;
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return 0; }
    fseek(f, 0, SEEK_SET);
    u8 *buf = (u8 *)malloc((size_t)sz ? (size_t)sz : 1);
    size_t got = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (got != (size_t)sz) { free(buf); return 0; }
    *out_len = (size_t)sz;
    return buf;
}

void fatal_missing(const char *path) {
    fprintf(stderr,
        "FATAL: ROM data file missing or unreadable: %s\n"
        "       The port is ROM-clean: this file carries the ROM tables the\n"
        "       exe no longer embeds. Run the first-run extraction on your own\n"
        "       Super Mario 64 DS ROM to produce build/assets/romdata.bin:\n"
        "         python port/tools/romextract.py <your.nds> --root <dir>\n"
        "       (the launcher does this for you on first run).\n", path);
    abort();
}

} // namespace

// ---- the boot entry point --------------------------------------------------
extern "C" void port_romdata_load(void) {
    static int done;
    if (done) return;
    done = 1;

    char bin_path[1024], man_path[1024];
    const char *root = asset_root();
    snprintf(port_asset_root_seen, sizeof port_asset_root_seen, "%s", root);
    snprintf(bin_path, sizeof bin_path, "%s/build/assets/romdata.bin", root);
    snprintf(man_path, sizeof man_path, "%s/build/assets/romdata.manifest",
             root);

    size_t blob_len = 0, man_len = 0;
    u8 *blob = read_all(bin_path, &blob_len);
    if (!blob) fatal_missing(bin_path);
    u8 *man = read_all(man_path, &man_len);
    if (!man) fatal_missing(man_path);

    // Header: "# romdata-manifest v1 <sha> <len>"
    char whole_sha[128]; unsigned long long want_len = 0;
    if (sscanf((char *)man, "# romdata-manifest v1 %127s %llu",
               whole_sha, &want_len) != 2) {
        fprintf(stderr, "FATAL: %s: unrecognised manifest header\n", man_path);
        abort();
    }
    if ((unsigned long long)blob_len != want_len) {
        fprintf(stderr, "FATAL: %s is %zu bytes; manifest says %llu -- "
                "wrong or truncated extraction\n", bin_path, blob_len, want_len);
        abort();
    }
    char got[65];
    sha256_hex(blob, blob_len, got);
    if (strcmp(got, whole_sha) != 0) {
        fprintf(stderr, "FATAL: %s sha256 %s != manifest %s -- corrupt or "
                "wrong-ROM extraction\n", bin_path, got, whole_sha);
        abort();
    }

    // The blob agrees with the manifest beside it. Now the OTHER question, the
    // one the manifest structurally cannot answer: is this the blob THIS EXE's
    // baked-in part offsets were computed from? See the note at the top.
    //
    // The identity is recorded either way, mismatch or not: hal/lk7_persist.cpp
    // stamps it into a disk save state, and the crash dump carries it, so a
    // report from a mixed install says so on its face.
    snprintf(port_romdata_sha, sizeof port_romdata_sha, "%s", got);
    port_romdata_bytes = (unsigned long long)blob_len;
    {
        char verdict[512];
        int same = (strcmp(got, port_romdata_expect_sha) == 0 &&
                    (unsigned long long)blob_len == port_romdata_expect_len);
        snprintf(verdict, sizeof verdict,
                 "asset root  %s\r\n"
                 "romdata     %llu bytes sha %.16s -- %s (exe built for %llu "
                 "bytes sha %.16s)",   /* the three labels pad to 12: a human
                                          reads this block as a table */
                 port_asset_root_seen, (unsigned long long)blob_len, got,
                 same ? "MATCH" : "MISMATCH",
                 port_romdata_expect_len, port_romdata_expect_sha);
        port_install_verdict_add(verdict);
        if (!same) {
            char detail[768];
            /* ONE indent level, carried by `detail` itself, because this exact
               string is shown in two places that cannot agree on a prefix: the
               stderr block below, and the message box + startup_error.txt a
               player reads (hal/asset_root_refuse.cpp). Baking the stderr
               block's indent into the format and then reusing it in a dialog is
               what made the first version of this ragged. */
            snprintf(detail, sizeof detail,
                     "  %s\n"
                     "  is %llu bytes (sha256 %s)\n"
                     "  this build of the game expects %llu bytes (sha256 %s)",
                     bin_path, (unsigned long long)blob_len, got,
                     port_romdata_expect_len, port_romdata_expect_sha);
            fprintf(stderr,
                "\n"
                "[romdata] THE GAME DATA IN THIS FOLDER BELONGS TO A DIFFERENT "
                "BUILD.\n"
                "%s\n"
                "  The offsets this exe reads the blob at were computed from a\n"
                "  different file, so every ROM table would be filled from the\n"
                "  wrong bytes. That does not fail loudly -- it produces a world\n"
                "  with impossible level data and dies a few seconds later.\n",
                detail);
            fflush(stderr);
#ifdef PORT_ROM_CLEAN
            if (!getenv("SM64DS_ROMDATA_NO_GUARD")) {
                free(man);
                free(blob);
                port_asset_mismatch_refuse(detail);   /* never returns */
            }
            /* AND IT IS NOT MERELY WRONG, IT IS UNSAFE, which is the honest
               label for what this switch turns back on. The manifest walk
               below bounds every part against the blob it describes, but the
               EXE's baked offsets are not in that manifest: if the other
               build's blob is SHORTER, port_romdata_load_all reads past the
               end of the malloc'd buffer. That is what the pre-fix binary did
               on every launch of a mixed install, and reproducing it exactly
               is the point of the switch -- it is for looking at the failure,
               never for playing. */
            fprintf(stderr, "[romdata] SM64DS_ROMDATA_NO_GUARD=1: loading it "
                            "anyway. Expect garbage, and reads off the end of "
                            "the blob if it is shorter than this build's.\n");
#endif
        }
    }

    // Verify each part sha and each symbol size against the blob. Walk the
    // manifest line by line; any disagreement is fatal and names the offender.
    char *line = strtok((char *)man, "\n");
    while (line) {
        if (strncmp(line, "part\t", 5) == 0) {
            char tag[128], psha[128];
            unsigned long long base = 0, size = 0;
            if (sscanf(line, "part\t%127[^\t]\t%llu\t%llu\t%127s",
                       tag, &base, &size, psha) == 4) {
                if (base + size > blob_len) {
                    fprintf(stderr, "FATAL: %s: part %s runs past the blob\n",
                            man_path, tag);
                    abort();
                }
                char c[65];
                sha256_hex(blob + base, (size_t)size, c);
                if (strcmp(c, psha) != 0) {
                    fprintf(stderr, "FATAL: %s: part %s sha mismatch\n",
                            man_path, tag);
                    abort();
                }
            }
        } else if (strncmp(line, "sym\t", 4) == 0) {
            char tag[128], name[256], ssha[128];
            unsigned long long off = 0, sz = 0;
            if (sscanf(line, "sym\t%127[^\t]\t%255[^\t]\t%llu\t%llu\t%127s",
                       tag, name, &off, &sz, ssha) == 5) {
                if (off + sz > blob_len) {
                    fprintf(stderr, "FATAL: %s: symbol %s runs past the blob\n",
                            man_path, name);
                    abort();
                }
            }
        }
        line = strtok(0, "\n");
    }
    free(man);

    // Verified. Fill every zeroed array from its slice.
    port_romdata_load_all(blob);
    // The arrays now hold their own copies; the blob buffer is no longer needed.
    // (The dispatch memcpys into the arrays, so the loaded file can be freed.)
    free(blob);

    fprintf(stderr, "[romdata] loaded %zu bytes from %s\n", blob_len, bin_path);
}
