/* ---- VS wiring lane: dScEntry_c, scene id 6 -- the VS / wireless entry
 * menu (ov075), and the ROM's own VS start.
 *
 * THE DERIVATION LIVES IN port/slice_vs.txt and is not repeated here: the
 * scene id (spawn-table slot 6, the loader's id-6 special case), the class
 * identity (RTTI "10dScEntry_c" at 0x0211c8f8, a DIRECT Scene subclass -- the
 * dScMiniGm_c shape, 18 slots), the TU inventory, the missing bodies (nine
 * when this seat was built, two after run rel0215's propagation -- section 2b
 * there), and the four contested names this file carries storage for.
 *
 * THE SEAT IS THE dScMiniGm_c SEAT'S SHAPE (hal/scene_mg_menu.cpp), with
 * three additions that overlay demanded and this one did not:
 *
 *   1. THE GENERATED DATA PATCH (vs_data_patch.inc). ov075's .data carries
 *      79 words that relocate to CODE (its own .text, or arm9) or to arm9
 *      data -- UI element records {fn, param} the arm9 helpers dispatch
 *      through, launch-table rows, the c800 record. The mount bakes the DS
 *      addresses; this seat patches every one to the host body BEFORE the
 *      sinits run, so records the sinits copy into bss inherit host
 *      pointers. Vtable words and SpawnInfo factory word0s are deliberately
 *      NOT in the table: the keyed fills and the registry install own those.
 *
 *   2. THE THREE STATIC INITIALISERS. ov005 had none; ov075 has three
 *      (.ctor at 0x0211c5a4), and they build the menu's SharedFilePtr
 *      registry and copy .data records into bss. They run once per process
 *      in the fill's gate, after the patches -- the ov089 sinit precedent.
 *
 *   3. TWO VTABLES, not one. The scene's own (data_ov075_0211d304) and
 *      _ZTV14UnknownVsEntry (0x0211c6a0) -- the menu's one sub-actor, id
 *      0x15a, SpawnInfo at 0x0211c610, which this fill also registers the
 *      way port_scene_registry_install registers a scene row.
 *
 * THE CONTESTED NAMES (slice_vs.txt section 6): four ov075 spellings are
 * live in OTHER overlays' TUs meaning those overlays' storage, so the mount
 * excludes them and the one ov075 TU that names them
 * (src/__sinit_ov075_0211bb00.c) is compiled with -D renames onto the
 * port_vs_* storage below. src/func_ov075_0211478c.c is the same race in
 * code: WorkElevator's TUs spell their vtable with that name
 * (hal/actor_classes_ov065.cpp aliases it), so the slice compiles ov075's
 * own body under port_vs_body_0211478c and the generated patch points the
 * one .data record that dispatches it (0x0211c618) at the renamed symbol.
 *
 * THERE ARE NO MISSING BODIES LEFT. Nine of ov075's functions had no source
 * anywhere when this seat was built and got loud faces below -- both streams,
 * flushed, the l2_trap discipline, never silent stubs. run rel0215 propagated
 * seven of them from the decomp's main by address (lane prop15) and the last
 * two plus a replaced 02116128 body in lane prop16; slice_vs.txt sections 2b
 * and 2c are the record. The face machinery is still here with an empty list,
 * and a zero out of it is a STRUCTURAL fact rather than a measurement -- the
 * block above the VS_FACE macro says what the linker does with it and why.
 * WHAT REPLACED THE FACES AS THE FIRST SUSPECT: four of the propagated bodies
 * reach the geometry engine through literal MMIO and are compiled raw out of
 * src/, so their register writes latch and trigger nothing. slice_vs.txt
 * section 2c names all eight TUs in that state and why this lane left them.
 *
 * THE ROM'S OWN VS START is at the bottom: port_vs_stage_and_start(map)
 * writes the lobby's own map-pick byte and calls func_ov075_02116c8c -- the
 * matched TU that does PrepareVsMode() then LoadLevelNoReturn(map, 0, 2, 0)
 * then the music stop. The port adds NO ordering of its own: one byte, one
 * call. The debug section and the SM64DS_VS_MAP env boot both come through
 * here, so headless proofs and the menu drive the same seam.
 */

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "dsstate_seg.h"
#include "comms_loopback.h"   /* lane vsnet: the VS radio seam (inert today) */

extern "C" {

/* the mount (port/ov075_syms.txt, generated by tools/ovdata.py) */
extern unsigned char data_ov075_0211c880[];      /* dScEntry_c SpawnInfo      */
extern unsigned char UnknownVsEntry_SpawnInfo[]; /* 0x0211c610, {fn, 015a015a} */
extern unsigned char _ZTV14UnknownVsEntry[];     /* 0x0211c6a0, 18 slots      */
extern unsigned char data_ov075_0211d304[];      /* dScEntry_c vtable, 18     */
extern unsigned char data_ov075_0211c7f8[];      /* pinned 0x10; +8 = c800    */
void port_ov075_pack_check(void);
void port_ov075_syms_patch(void);

/* the generic keyed fill and the registry (hal/scene_boot.cpp) */
unsigned port_scene_fill_rom(void **vt, unsigned n);
int port_scene_env_want(void);
extern void **data_020a4bb8;                     /* hal/actor_vtables.cpp     */

/* the class's own eight, all flat C names out of src/ */
int   func_ov075_0211a410(char *c);              /* slot  0  InitResources    */
void  func_ov075_0211a734(void);                 /* slot  1 veneer (unused by
                                                    the thunk; see vs_reset) */
int   _ZN5Scene19ResetFadersAndSoundEv(void *self);
int   func_ov075_0211a210(signed char r0);       /* slot  3  CleanupResources */
int   func_ov075_0211a2b8(void *c);              /* slot  6  Behavior         */
int   func_ov075_0211a26c(void *c);              /* slot  9  Render           */
void  func_ov075_0211a268(void);                 /* slot 12  OnPendingDestroy */
int   func_ov075_02115ab8(void *c);              /* slot 16  D2               */
int  *func_ov075_02115b28(int *t);               /* slot 17  D0               */
void *func_ov075_0211a854(void);                 /* the factory (matched src) */
/* SCENE 7, the VS RESULTS screen. Its own factory and its own SpawnInfo, both
   in the same ov075 .data run the mount already carries, and BOTH point at the
   class this file already seats: func_ov075_0211a740 is func_ov075_0211a854
   with a different pair of element-array constructors -- same
   ActorBase::operator new(0x288), same data_ov075_0211d304 vtable. The class
   tells the two scenes apart by its own id, in one branch:
   src/func_ov075_0211a410.cpp does `if (self->unk_00c == 6)` the lobby, else
   func_ov075_02116818 -- the results background, the winner calculation
   (func_ov075_021165b0) and the ranking. So scene 7 needs no vtable of its own
   and no fill of its own; it needs a row. */
void *func_ov075_0211a740(void);
extern unsigned char data_ov075_0211c788[];      /* dScEntry_c SpawnInfo, id 7 */

/* the entry actor's flat pieces */
char *UnknownVsEntry_Spawn(void);
void *_ZN14UnknownVsEntryD1Ev(void *self);       /* entry slot 16 */
int   _ZN14UnknownVsEntryD0Ev(void *self);       /* entry slot 17 */

/* the three static initialisers (matched src, run here by hand -- the DS
   runs them at overlay load; the port has no ov075 load event) */
void __sinit_ov075_0211b5e0(void);
void __sinit_ov075_0211bb00(void);
void __sinit_ov075_0211c51c(void);

/* the ROM's own VS start (matched src): PrepareVsMode + LoadLevelNoReturn */
void func_ov075_02116c8c(void);
extern unsigned char data_0209b2e4[];            /* the lobby's map pick      */

}  /* extern "C" */

#include "UnknownVsEntry.h"                      /* the 4 C++ methods */
#include "ActorBase.h"      /* the entry actor's shared-slot thunks */
#include "ActorDerived.h"

/* ---- contested-name storage (slice_vs.txt section 6) ----------------------
   src/__sinit_ov075_0211bb00.c is compiled with
     -Ddata_ov075_0211c800=port_vs_data_0211c800
     -Ddata_ov075_0211d608=port_vs_bss_0211d608
     -Ddata_ov075_0211d650=port_vs_bss_0211d650
   so ov075's own registrations land here while Snufit's and
   BowserPuzzleManager's spellings keep their ov065/ov064 bindings. Sizes are
   the config's own next-symbol deltas (d608..d610 = 8, d650..d65c = 0xc).
   In .dsstate: the sinit writes these once, but the c800 record and the
   SharedFilePtr slots are game state a save-state restore must roll back
   with everything else. */
extern "C" {
DSSTATE_BEGIN
struct { int fn, param; } port_vs_data_0211c800;
unsigned char port_vs_bss_0211d608[8];
unsigned char port_vs_bss_0211d650[0xc];
DSSTATE_END
}

/* ---- storage the 0.2.15 propagation made live -----------------------------
   run rel0215 lane prop15. Retiring seven faces put seven real ov075 bodies in
   the link, and they address four DS globals nothing in this tree had hosted:
   the ranking counters, the per-slot ready bytes and the ROM's null PMF pair.
   Every size below is the config's own next-symbol delta, not the width of the
   first reader.

   THE RANKING COUNTERS ARE A SPLIT-SYMBOL RUN, the data_0209f310 shape again.
   dsd names data_0209b2ec (1 byte) and data_0209b2ed (3), and 0x0209b2f0 is a
   different object. func_ov075_021165b0 walks BOTH names over the SAME four
   bytes -- `pb = data_0209b2ec` for i<4, then `pb = data_0209b2ed` for i in
   1..3 -- so they have to be the first two bytes of one block or the counters
   the first loop increments are not the ones the second loop reads.
   func_ov075_02116e00 clears data_0209b2ec[0..3] the same way. So this is the
   GXBANK arrangement, align(4) on the head and align(1) on the member, and
   port/tools/gxband_guard.py's 'vsrank' band asserts it against every target's
   map. It MOVED here out of hal/auto_bss.cpp's generic `int data_0209b2ec[8]`
   for the same reason data_0209f310 moved out of hal/actor_vtables.cpp: a
   split run cannot be hosted as two disjoint objects. Every consumer in the
   tree reads it as bytes (src/func_ov075_021165b0.c, _02116e00.c, _02117fe4.c),
   so the type change costs nothing. */
#pragma section(".dsstate$hvsrank0000", read, write)
#pragma section(".dsstate$hvsrank0001", read, write)
extern "C" {
__declspec(allocate(".dsstate$hvsrank0000")) __declspec(align(4))
unsigned char data_0209b2ec[1];
__declspec(allocate(".dsstate$hvsrank0001")) __declspec(align(1))
unsigned char data_0209b2ed[3];
}

/* THE PER-SLOT READY BYTES, the data_0209b2ec shape a third time and the one
   whose split was LIVE GAME-BREAKAGE rather than a latent hazard. dsd names
   data_0209fc5c (1 byte) and data_0209fc5d (3), 0x0209fc60 is the next
   object, and func_ov075_021165b0 walks both names over that one four-byte
   run exactly the way it walks the ranking pair.

   Until this pair moved here, data_0209fc5c was hal/auto_bss.cpp's generic
   `int data_0209fc5c[8]`, and hal/level_boot.cpp's VS seat wrote it at INT
   stride while every ROM body reads it at BYTE stride. Player::Behavior's
   own VS gate is `if (data_0209f2d8 == 1 && data_0209fc5c[mPlayerNo] == 0)
   return 1;` -- so byte 1 read 0, and player 2's actor froze in
   St_LevelEnter_Main on every VS map, forever, while level-1 controls (VS
   flag clear, gate never taken) looked fine. The same byte-0 read is why
   _Z19LoadEntranceObjects... discarded the second player it had already
   spawned into the world -- the orphan shadow-caster port_load1's count hold
   was built to hide. One stride bug, three symptoms.

   Now every accessor in the tree is on the byte view (the int-view externs in
   hal/comms_conductor.cpp, hal/level_boot.cpp and hal/player_bridges.cpp are
   converted; the seat itself is SetNumPlayers -> func_020308d0, the ROM's own
   byte writer), and the pair is one four-byte block, align(4) head and
   align(1) member, asserted by gxband_guard's 'ready' band. */
#pragma section(".dsstate$hready0000", read, write)
#pragma section(".dsstate$hready0001", read, write)
extern "C" {
__declspec(allocate(".dsstate$hready0000")) __declspec(align(4))
unsigned char data_0209fc5c[1];
__declspec(allocate(".dsstate$hready0001")) __declspec(align(1))
unsigned char data_0209fc5d[3];
}

/* The ROM's NULL pointer-to-member pair at 0x02086b58 (kind:data(any), 8 bytes
   to .p__sinit_02073a24 at 0x02086b60) needs NO definition here, and the link
   said so: romdata.c already emits it from the ROM's own bytes, so a host
   definition beside it is an LNK2005 (measured -- this file carried one for
   exactly one build). func_ov075_02119dc4 only needs its MSVC-mangled spelling
   pointed at that mount, which the alias below does. */

/* The C-linkage flip: eight spellings over six symbols, all of them this
   propagation's. The .cpp TUs from main declare these data names OUTSIDE
   extern "C", so MSVC mangles them while the ov075 mount, hal/auto_bss.cpp and
   romdata.c define the C name -- and 0x0211d71c arrives with TWO manglings in
   one build, `int` from func_ov075_02117d80 and `int *` from
   func_ov075_02119dc4, which is why it needs two lines and not one. Same
   object, second spelling; the
   /alternatename only binds because nothing defines the mangled LHS.
   port/tools/alternatename_guard.py is the check that stays true. */
#pragma comment(linker, "/alternatename:?data_ov075_0211d71c@@3HA=_data_ov075_0211d71c")
#pragma comment(linker, "/alternatename:?data_ov075_0211d71c@@3PAHA=_data_ov075_0211d71c")
#pragma comment(linker, "/alternatename:?data_ov075_0211d810@@3PAHA=_data_ov075_0211d810")
#pragma comment(linker, "/alternatename:?data_ov075_0211d920@@3PAHA=_data_ov075_0211d920")
#pragma comment(linker, "/alternatename:?data_ov075_0211d930@@3PAHA=_data_ov075_0211d930")
#pragma comment(linker, "/alternatename:?data_0209fc58@@3EA=_data_0209fc58")
#pragma comment(linker, "/alternatename:?data_0209fc5d@@3PAEA=_data_0209fc5d")
#pragma comment(linker, "/alternatename:?data_02086b58@@3PAHA=_data_02086b58")

/* ---- the face list is EMPTY, where it was nine ------------------------------
   The l2_trap discipline (hal/scene_boot.cpp): both streams, flushed, and a
   counter, because a fault usually follows and stderr goes to the playlog.

   run rel0215 lane prop15 retired SEVEN of the original nine (02115bcc,
   021165b0, 02116818, 0211705c, 0211867c, 02119dc4, 0211a948), all byte-matched
   on the decomp's main and brought across by address into src/ plus
   slice_vs.txt. LANE prop16 RETIRED THE LAST TWO. They were floors with names
   and the decomp's run vsdec closed both:

     func_ov075_0211621c  src/func_ov075_0211621c.c, from main 52d681683.
                          The VS results row. First source it has ever had;
                          NONMATCHING div 40 and the whole residue is routing
                          (30 register-field words, 10 sp displacements, no
                          opcode/immediate/mode/condition changed).
     func_ov075_0211afb0  src/func_ov075_0211afb0.c, from main 52d681683. The
                          grid-mesh renderer, and the 0x0211d35c pair-run
                          target. NONMATCHING div 4 -- the lsl/lsl/asr/asr
                          quartet at +0x164..+0x170, an allocator preference.
                          It is also the CALLER func_ov075_0211a948 was waiting
                          for: that body byte-matches and has been in this
                          slice since prop15, and /OPT:REF dropped it because
                          its one ov075 caller (relocs.txt from:0x0211b01c) was
                          inside this face. Both are in the map now.

   THE MACHINERY STAYS with no rows in it, and it is a SOURCE-LEVEL keepsake
   for the next overlay this seat grows into, NOT a live proof surface. Be
   exact about what an empty list does, because the obvious reading is wrong:
   with no VS_FACE row, nothing calls vs_face and nothing calls
   port_vs_face_hits, so both are gone from walk_window.map -- vs_face folded
   away as an unreferenced static, port_vs_face_hits by /OPT:REF -- and the
   only survivor is g_vs_face_hits, four bytes of .bss at 0x00b3ade0 that
   nothing reads or writes. The format string is not in the binary either:
   searching walk_window.exe for "MISSING ov075 body entered" finds nothing.

   SO A ZERO HERE IS A STRUCTURAL FACT, NOT A PRINTED MEASUREMENT. Grepping a
   run log for the face line cannot match, because no code that could emit it
   exists; the honest claim is "there are no faces", never "the faces did not
   fire". The two are the same number and completely different evidence, and a
   later lane that re-adds one row turns the counter back into a real
   measurement -- until then, read the map, not the log.

   src/func_ov075_02116128 also changed underneath this seat in the same lane:
   the tree carried main's pre-#1266 revision under the old .c spelling, banner
   scored div=31 against mwccarm 1.2/sp2p3 (the wrong compiler for this tree),
   and main's current .cpp is a different shape at the canonical 2004/b56 with a
   differential-execution audit behind it. Same six stores, same palette splice;
   nothing this file does changes. slice_vs.txt section 2c is the record. */
static unsigned g_vs_face_hits;
static void vs_face(const char *name)
{
    ++g_vs_face_hits;
    std::fprintf(stderr, "  [vs] MISSING ov075 body entered: %s (returns 0; "
                 "port/slice_vs.txt section 2)\n", name);
    std::fflush(stderr);
    std::printf("  [vs] MISSING ov075 body entered: %s (returns 0; "
                "port/slice_vs.txt section 2)\n", name);
    std::fflush(stdout);
}
extern "C" unsigned port_vs_face_hits(void) { return g_vs_face_hits; }
#define VS_FACE(sym)                                                           \
    extern "C" int sym(void);                                                  \
    extern "C" int sym(void) { vs_face(#sym); return 0; }
/* (no rows -- every ov075 function this scene reaches has a body in src/) */
#undef VS_FACE

/* THE FACES WERE ALSO THE DECLARATIONS, and that is why three of the seven
   prop15 retirements broke the compile rather than the link. vs_data_patch.inc
   below takes the ADDRESS of func_ov075_02115bcc, _0211705c, _0211867c and --
   at 0x0211d35c -- _0211afb0, to patch the mount's code-pointer records, and
   the VS_FACE macro's `extern "C" int sym(void);` line was the only declaration
   of those names in this TU. Deleting a face therefore deletes a declaration,
   and the .inc stops compiling.

   Declared here with their REAL signatures out of the propagated src TUs, not
   with the face's placeholder `int sym(void)`: a wrong arity in a live
   declaration is what port/tools/aritycheck.py exists to catch, and taking an
   address through a lie is how it gets in. */
extern "C" {
void func_ov075_02115bcc(char *self);   /* src/func_ov075_02115bcc.c */
void func_ov075_0211705c(void *thiz);   /* src/func_ov075_0211705c.c */
void func_ov075_0211867c(char *self);   /* src/func_ov075_0211867c.c */
void func_ov075_0211afb0(char *self);   /* src/func_ov075_0211afb0.c, and the
                                           0x0211d35c patch row takes this */
void func_ov075_0211621c(char *self);   /* src/func_ov075_0211621c.c */
int  port_vsstar_layout_check(void);    /* hal/actor_classes_star.cpp */
}

/* ---- the generated data patch --------------------------------------------- */
extern "C" {
#include "vs_data_patch.inc"
}

/* ---- ONE CALLING-CONVENTION THUNK, over the entry record's third PMF -------
   MEASURED, not predicted. Retiring the func_ov075_0211afb0 face made the ROM's
   own body live, and the first scene-6 boot after that faulted at
   func_ov075_0211afb0 +0xdc reading 0x15, under SM64DS_FAULTS_FATAL=1; without
   it the playlog reads

     [quarantine] actor 307FEE20 id 346 (?) faulted (code c0000005 +000dbb8c)
                  -- FROZEN, frame continues

   id 346 = 0x15a = UnknownVsEntry, frozen for the remaining 299 frames, which
   is why the run still exited 0 and looked clean. The face survived the same
   call for a year because it was `int(void)`: a cdecl body that reads no
   argument does not care that the caller passed none.

   THE SEAM IS THE ONE THIS SEAT ALREADY CROSSES EVERYWHERE (the thunks below,
   and hal/scene_mg_menu.cpp section 4). UnknownVsEntry::Render calls
   src/func_ov075_0211b3d8.cpp, a byte-matched TU whose whole body is
   `(c->*c->ep->pmf)()` over a complete single-inheritance class, so MSVC emits
   a __thiscall: the receiver rides in ecx and NOTHING goes to the stack. The
   word behind that member pointer is the mount's 0x0211d35c, which
   vs_apply_data_patch points at the plain cdecl C body, and a cdecl body reads
   its first argument off the stack. The receiver never arrives.
   __fastcall(self, edx) takes ecx as its first argument and cleans the same
   zero bytes __thiscall does, so the thunk is the exact shape of the seam.

   ONE ROW, DELIBERATELY. relocs.txt has exactly two references to 0x0211afb0
   and one of them is ov006's storage at the shared window, so this record word
   is the function's ONLY entry point and the thunk is complete.

   THE OTHER TWO PAIRS IN THE SAME RECORD ARE LEFT EXACTLY AS THE BASE HAS
   THEM, and the reason is SCOPE, not difficulty. __sinit_ov075_0211c51c copies
   three pairs into data_ov075_0211d994: 0x0211d354 (func_ov075_0211b260,
   dispatched by src/func_ov075_0211b458.cpp's own inline member call) and
   0x0211d34c (func_ov075_0211b1cc, dispatched by src/func_ov075_0211b418.cpp)
   are the other two, and both carry the identical receiver defect today.

   ALL THREE SITES ARE THUNK-REACHABLE. An earlier revision of this comment
   claimed 0211b458's was a third shape that a target-side thunk could not
   reach, because its `struct Foo;` is never completed and MSVC therefore gives
   that member pointer the most-general representation. The representation part
   is right and the conclusion was WRONG; corrected here after reading the
   emitted dispatch rather than reasoning about the language rule.

   Disassembled out of walk_window.exe (capstone, 32-bit):

     0211b3d8 / 0211b418   two-word form
       mov ecx,[edx+0x14]   ; the pair's SECOND word
       add ecx,eax          ; ecx = this + that word
       mov eax,[edx+0x10]   ; the pair's FIRST word
       call eax

     0211b458              four-word (most-general) form
       mov edx,[ep+0x0c]    ; vbtable index
       test edx,edx
       jne  <vbtable path>  ; NOT TAKEN
       mov eax,[ep+0x04]    ; the adjustment
       lea ecx,[eax+esi]    ; ecx = this + adjustment
       call dword ptr [ep]  ; the pair's FIRST word

   Every ROM pair in this record is {function, LITERAL ZERO} -- slice_vs.txt
   section 1 measures exactly that, three pairs at 8-byte stride with no
   relocation on any partner word -- and vs_apply_data_patch writes offset 0
   only. So for 0211b458, ep+0x0c and ep+0x04 are both zero: the vbtable branch
   is dead, the adjustment is zero, and `lea ecx,[eax+esi]` hands over `this`
   exactly. (The 16-byte read does span into the next pair, so ep+0x08 is
   pair[1]'s function word -- harmless, because ep+0x08 is only read on the
   dead branch.) The call goes through ep+0, which is the word the patch owns,
   so a __fastcall thunk at 0x0211d354 or 0x0211d34c would receive the correct
   receiver exactly the way the one at 0x0211d35c does.

   THE REASON THEY STAY IS THAT ENABLING THEM IS AN UNMEASURED RENDERING
   CHANGE. Neither faults today: 0211b1cc bails on DecIfAbove0_Short and
   0211b260 bails on a non-positive count, both off whatever the stack happened
   to hold. Handing them a real receiver wakes up code this lane did not run --
   0211b1cc's 400-element walk through func_ov075_0211addc, and 0211b260's
   20x20 vertex-grid initialisation -- and that is a picture change nobody has
   looked at, on a mesh whose register writes still latch (see slice_vs.txt 2c
   on the eight raw-MMIO TUs). This lane fixed the one site its own change made
   lethal and measured that. Named here so the lane that takes the entry record
   does all three together and measures what wakes up. */
/* (func_ov075_0211afb0 is declared with the other propagated bodies above) */
static void __fastcall vs_pmf_grid_render(void *self, void *)
{
    func_ov075_0211afb0((char *)self);
}

/* ---- AND THE OTHER TWO, BEHIND A SWITCH -----------------------------------
 *
 * Lane VSEND. The block above says the other two sites are left alone for
 * SCOPE and that the lane which takes the entry record should do all three
 * together. This is not that lane and this does not take them: the default is
 * unchanged, both records keep the base's word, and nothing about a shipped
 * boot moves. What this adds is the INSTRUMENT that block asks for, so the
 * measurement can be reproduced from a branch rather than from a build
 * somebody threw away.
 *
 * WHY IT CAME UP HERE. Booting scene 7 -- the VS results screen, the same
 * dScEntry_c the lobby is -- faults, and the fault is at the FIRST of those two
 * sites. Measured, C:\tmp\vsend-out\scene7:
 *
 *     FAULT code c0000005 accessing 000000a8, eax=0
 *     func_ov075_0211b260 +0x17
 *       <- func_ov075_0211b458 +0x77
 *       <- UnknownVsEntry::InitResources +0x1bf
 *       <- func_ov075_02116818 +0x259        the RESULTS branch
 *       <- func_ov075_0211a410 +0x1e7        dScEntry_c::InitResources
 *       <- vs_init <- Scene::SpawnIfNecessary <- port_scene_begin
 *
 * The block above predicted this exactly: "0211b260 bails on a non-positive
 * count, both off whatever the stack happened to hold". On the LOBBY path the
 * stack garbage happens to be a value that makes it bail. On the RESULTS path
 * it happens to be zero, and a zero receiver reads 0x000000a8. So the defect is
 * the one already named, and scene 7 is simply the path where it is lethal.
 *
 * SM64DS_VS_PMF_ALL=1 installs the thunk for THAT site -- the same
 * __fastcall(self, edx) shape as vs_pmf_grid_render, on the same first word of
 * the same kind of record, which the block above proves is the reachable entry
 * for all three. It stays OFF because turning it on wakes up a piece of drawing
 * code nobody has looked at, 0211b260's 20x20 vertex-grid initialisation, and
 * this lane does not judge pictures.
 *
 * AND ONLY THAT SITE. The third pair, 0x0211d34c -> func_ov075_0211b1cc, gets
 * no thunk here and must not: src/func_ov075_0211b1cc.c carries the "recovered
 * from vtable slot identity" marker, which makes it a GUESSED body, and
 * port/tools/inferred_stub_guard's standing ruling is that a guessed body may
 * not enter a live fill. It caught the first draft of this block doing exactly
 * that -- "NEW SEAT: func_ov075_0211b1cc" -- and the guard is right. Scene 7
 * does not need it: the results path reaches 0211b260 through
 * func_ov075_0211b458, and the only dispatcher for the other pair is
 * func_ov075_0211b418, which that path never enters. So the lane that takes the
 * entry record inherits that site along with its precondition -- the body has
 * to be a real decompilation before anything may point at it.
 *
 * THE BODY IS CALLED THROUGH A TYPED POINTER, not through a declaration of its
 * own, and that is forced rather than chosen. vs_data_patch.inc is GENERATED
 * and says so at the top -- regenerate, do not hand-edit -- and it already
 * declares the name as `void f(void)` because every row of that table only ever
 * takes an address. Re-declaring it here with its real `(self)` signature is
 * error C2733 on an extern "C" name. The four bodies that DO have real
 * declarations above are the four the generator was told to skip. A cast at the
 * one call site keeps the generated file generated; the body is cdecl and takes
 * exactly one pointer (src/func_ov075_0211b260.c), which is what the pointer
 * type says. */
extern "C" {
extern unsigned char data_ov075_0211d354[];
}
typedef void (*VsPmfBody)(void *self);
static void __fastcall vs_pmf_grid_init(void *self, void *)
{
    /* src/func_ov075_0211b260.c: the 20x20 vertex-grid initialisation */
    ((VsPmfBody)(void *)&func_ov075_0211b260)(self);
}
static void vs_install_remaining_pmf_thunks(void)
{
    if (!std::getenv("SM64DS_VS_PMF_ALL"))
        return;
    *(void **)data_ov075_0211d354 = (void *)vs_pmf_grid_init;
    std::fprintf(stderr, "  [vs] SM64DS_VS_PMF_ALL=1: the entry record's "
                 "0x0211d354 member-pointer site now gets its receiver "
                 "(-> func_ov075_0211b260). This is a DRAWING change nobody "
                 "has looked at; the default leaves the record alone. The "
                 "third site, 0x0211d34c, is NOT touched -- its body is "
                 "marked as recovered from vtable slot identity and the "
                 "inferred-stub guard forbids seating a guess.\n");
}

static void vs_apply_data_patch(void)
{
    const unsigned n = sizeof vs_data_patch / sizeof vs_data_patch[0];
    for (unsigned i = 0; i < n; ++i)
        std::memcpy(vs_data_patch[i].sym + vs_data_patch[i].off,
                    &vs_data_patch[i].host, sizeof(void *));
}

/* ---- the thunks -----------------------------------------------------------
   __fastcall (self, edx) -- the calling-convention seam every seat crosses
   (hal/scene_mg_menu.cpp section 4): the dispatchers are MSVC virtual calls,
   the bodies are cdecl C, and a bare body in a slot is the BNC defect. */
static unsigned g_vs_hits[18];
static unsigned g_ent_hits[18];

static int  __fastcall vs_init(void *s, void *)
{ ++g_vs_hits[0];  return func_ov075_0211a410((char *)s); }
static int __fastcall vs_reset(void *s, void *)
{ /* IMPLICIT-REGISTER DEFECT, the eighth of its class: slot 1's matched
     veneer (src/func_ov075_0211a734.c) is a void(void) tail-call and the
     ROM rides `self` through r0 into Scene::ResetFadersAndSound -- whose
     FIRST statement is `data_0209f5c0 = self`, the spawn parent every
     ActorDerived::Spawn in this scene hangs off. On x86 the void(void)
     chain drops it, data_0209f5c0 stays null, and the entry-actor spawn at
     func_ov075_02116ad4:63 quietly returns 0 (measured: Behavior state
     func_ov075_02119b34 then faults at +0x37 on the null +0x50). The thunk
     forwards self the way r0 did. */
  ++g_vs_hits[1];  return _ZN5Scene19ResetFadersAndSoundEv(s); }
static int  __fastcall vs_clean(void *s, void *)
{ /* the body reads r0 the way the ROM handed it -- forward self */
  ++g_vs_hits[3];  return func_ov075_0211a210((signed char)(long long)s); }
extern "C" { extern int data_0209f5c0[]; }
static int  __fastcall vs_beh(void *s, void *)
{ /* first-frame census: the two words every VS spawn hangs off. A null
     +0x50 is the entry actor failing to spawn; a null data_0209f5c0 is the
     spawn parent never seated (the slot-1 ride-through, or the dispatch
     order). Printed once, the port's census discipline. */
  if (!g_vs_hits[6]++)
      std::fprintf(stderr, "  [vs] first Behavior: self=%p parent(f5c0)=%08x "
                   "entry(+0x50)=%08x screen(+0xc)=%u\n", s,
                   (unsigned)data_0209f5c0[0],
                   *(unsigned *)((char *)s + 0x50),
                   (unsigned)*(unsigned short *)((char *)s + 0xc));
  return func_ov075_0211a2b8(s); }
static int  __fastcall vs_render(void *s, void *)
{ ++g_vs_hits[9];  return func_ov075_0211a26c(s); }
static void __fastcall vs_pdes(void *, void *)
{ ++g_vs_hits[12]; func_ov075_0211a268(); }
static void *__fastcall vs_d2(void *s, void *)
{ ++g_vs_hits[16]; func_ov075_02115ab8(s); return s; }
static void *__fastcall vs_d0(void *s, void *)
{ ++g_vs_hits[17]; return (void *)func_ov075_02115b28((int *)s); }

static int  __fastcall ent_init(void *s, void *)
{ ++g_ent_hits[0];  return ((UnknownVsEntry *)s)->UnknownVsEntry::InitResources(); }
static int  __fastcall ent_clean(void *s, void *)
{ ++g_ent_hits[3];  return ((UnknownVsEntry *)s)->UnknownVsEntry::CleanupResources(); }
static int  __fastcall ent_beh(void *s, void *)
{ ++g_ent_hits[6];  return ((UnknownVsEntry *)s)->UnknownVsEntry::Behavior(); }
static int  __fastcall ent_render(void *s, void *)
{ ++g_ent_hits[9];  return ((UnknownVsEntry *)s)->UnknownVsEntry::Render(); }
static void *__fastcall ent_d1(void *s, void *)
{ ++g_ent_hits[16]; return _ZN14UnknownVsEntryD1Ev(s); }
static void *__fastcall ent_d0(void *s, void *)
{ ++g_ent_hits[17]; _ZN14UnknownVsEntryD0Ev(s); return s; }

/* the nine ActorBase-shape shared slots, the hal/sub_actors.cpp law: every
   thunk __fastcall so ecx carries `this`, every call QUALIFIED */
static int  __fastcall ent_binit(void *s, void *)
{ return ((ActorBase *)s)->ActorBase::BeforeInitResources(); }
static void __fastcall ent_ainit(void *s, void *, unsigned a)
{ ((ActorDerived *)s)->ActorDerived::AfterInitResources(a); }
static int  __fastcall ent_bclean(void *s, void *)
{ return ((ActorBase *)s)->ActorBase::BeforeCleanupResources(); }
static void __fastcall ent_aclean(void *s, void *, unsigned a)
{ ((ActorBase *)s)->ActorBase::AfterCleanupResources(a); }
static int  __fastcall ent_bbeh(void *s, void *)
{ return ((ActorBase *)s)->ActorBase::BeforeBehavior(); }
static void __fastcall ent_abeh(void *s, void *, unsigned a)
{ ((ActorBase *)s)->ActorBase::AfterBehavior(a); }
static int  __fastcall ent_bren(void *s, void *)
{ return ((ActorBase *)s)->ActorBase::BeforeRender(); }
static void __fastcall ent_aren(void *s, void *, unsigned a)
{ ((ActorBase *)s)->ActorBase::AfterRender(a); }
static void __fastcall ent_pdes(void *s, void *)
{ ((ActorBase *)s)->ActorBase::OnPendingDestroy(); }


/* ---- the factories --------------------------------------------------------
   The registry's factory column is void *(*)(void); both matched factories
   already are. The forwarders exist so the rows name symbols this file owns. */
extern "C" void *port_vs_spawn(void)       { return func_ov075_0211a854(); }
extern "C" void *port_vs_results_spawn(void) { return func_ov075_0211a740(); }
extern "C" void *port_vs_entry_spawn(void) { return UnknownVsEntry_Spawn(); }

/* Scene 7's fill, and it is deliberately empty. The results screen is the SAME
   dScEntry_c the lobby row above seats -- same vtable at data_ov075_0211d304,
   same eighteen slots, same ov075 mount and the same three static initialisers
   -- so everything a scene 7 needs is already standing by the time this runs.
   The row exists to register the factory and the SpawnInfo record, which
   port_scene_registry_install does itself from the row's own columns.

   THE ORDER IS WHY THIS CAN BE EMPTY, and it is the same append rule every
   later row in that table states: the registry walks the table in order, and
   this row is appended after the SCENE_VS_MENU row, so port_scene_fill_vs has
   already run when this is reached. Doing the work twice would be harmless
   (its heavy half is behind a once-per-process gate) but not free: the vtable
   pass reports how many raw DS words the keyed fill left, and on a second pass
   there are none left to leave, so a real second call would print a shape
   warning about a table that is perfectly correct. */
extern "C" void port_scene_fill_vs_results(void) { }

/* ---- the fill -------------------------------------------------------------
   Called by port_scene_registry_install on every boot, table order. The gate
   runs once per process: pack check, the mount's own data-pointer rebase, the
   generated code-pointer patch, the c800 record copy (AFTER the patch, so it
   carries the host face pointer), then the three sinits. */
extern "C" void port_scene_fill_vs(void)
{
    static int done;
    if (!done) {
        done = 1;
        /* run rel0215 lane prop15: the VS carried-star array's host layout,
           read back once per process. data_0209f310 and data_0209f311 are the
           first two BYTES of one DS run and the port hosts them as two grouped
           sections; if the linker ever pads them apart again, every writer
           indexes f310[player] and NumVsStarsObtained reads from &f311, so
           players 1..3 score into bytes the win test never sums. The link-time
           answer is gxband_guard's 'vsstar' band, over every target's map;
           this is the same assertion from inside the one scene that uses it. */
        port_vsstar_layout_check();
        port_ov075_pack_check();
        port_ov075_syms_patch();
        vs_apply_data_patch();
        /* and then ONE word back over the generated table's own answer: the
           0x0211d35c pair is reached by an MSVC member-pointer call, so the
           record holds the __fastcall thunk rather than the bare cdecl body.
           It has to happen HERE, between the patch and the sinits, because
           __sinit_ov075_0211c51c copies this word into data_ov075_0211d994[2]
           and everything downstream reads the copy. The generated .inc is left
           alone on purpose -- it is the ROM's own mapping and says to
           regenerate rather than hand-edit; the convention seam is the seat's. */
        *(void **)data_ov075_0211d35c = (void *)vs_pmf_grid_render;
        /* the other two records, only if a run asked for them; same position in
           the order and for the same reason -- the sinit below copies all three
           pairs and everything downstream reads the copies. A no-op without the
           variable, which is every run but a lane's own. */
        vs_install_remaining_pmf_thunks();
        /* the excluded c800 record, rebuilt from the pinned mount extent --
           one code pointer (patched above) and a zero */
        std::memcpy(&port_vs_data_0211c800, data_ov075_0211c7f8 + 8, 8);
        __sinit_ov075_0211b5e0();
        __sinit_ov075_0211bb00();
        __sinit_ov075_0211c51c();
    }

    /* dScEntry_c: ten shared slots keyed on their ROM words, eight written. */
    void **vt = (void **)data_ov075_0211d304;
    const unsigned left = port_scene_fill_rom(vt, 18);
    vt[0]  = (void *)vs_init;
    vt[1]  = (void *)vs_reset;
    vt[3]  = (void *)vs_clean;
    vt[6]  = (void *)vs_beh;
    vt[9]  = (void *)vs_render;
    vt[12] = (void *)vs_pdes;
    vt[16] = (void *)vs_d2;
    vt[17] = (void *)vs_d0;
    if (left != 8)
        std::fprintf(stderr, "  [vs] VTABLE SHAPE: port_scene_fill_rom left "
                     "%u raw DS word(s) in dScEntry_c's 18-slot table, "
                     "expected 8 (the class's own overrides)\n", left);

    /* UnknownVsEntry: NOT a Scene -- an EIGHTEEN-slot ActorBase-shape actor,
       the dMeter_c arrangement hal/sub_actors.cpp reads out of the ROM (slot
       2 ActorDerived::AfterInitResources, every other shared slot
       ActorBase's own). The Scene-keyed fill above knows none of those
       words -- the first boot measured it as "left 15" -- so this table is
       filled EXPLICITLY, each slot's ROM word verified against the
       derivation before it is replaced; a word that disagrees is left
       standing and reported, never papered over. */
    static const unsigned kEntRom[18] = {
        0x021156e0u,   /*  0 InitResources        (class)  */
        0x02043c78u,   /*  1 ActorBase::BeforeInitResources */
        0x02013ef4u,   /*  2 ActorDerived::AfterInitResources */
        0x02115388u,   /*  3 CleanupResources     (class)  */
        0x02043bacu,   /*  4 ActorBase::BeforeCleanupResources */
        0x02043b2cu,   /*  5 ActorBase::AfterCleanupResources */
        0x0211555cu,   /*  6 Behavior             (class)  */
        0x02043afcu,   /*  7 ActorBase::BeforeBehavior */
        0x02043af8u,   /*  8 ActorBase::AfterBehavior */
        0x021154ccu,   /*  9 Render               (class)  */
        0x02043ac8u,   /* 10 ActorBase::BeforeRender */
        0x02043ac4u,   /* 11 ActorBase::AfterRender */
        0x02043ac0u,   /* 12 ActorBase::OnPendingDestroy */
        0x0204357cu,   /* 13 ActorBase::Virtual34 */
        0x0204349cu,   /* 14 ActorBase::Virtual38 */
        0x02043494u,   /* 15 ActorBase::OnHeapCreated */
        0x02113ee0u,   /* 16 D1                   (class)  */
        0x02113f54u,   /* 17 D0                   (class)  */
    };
    static void *const kEntHost[18] = {
        (void *)ent_init,  (void *)ent_binit, (void *)ent_ainit,
        (void *)ent_clean, (void *)ent_bclean,(void *)ent_aclean,
        (void *)ent_beh,   (void *)ent_bbeh,  (void *)ent_abeh,
        (void *)ent_render,(void *)ent_bren,  (void *)ent_aren,
        (void *)ent_pdes,  0,                 0,
        0,                 (void *)ent_d1,    (void *)ent_d0,
    };
    void **evt = (void **)_ZTV14UnknownVsEntry;
    /* slots 13/14/15 first, through the keyed fill: ActorBase::Virtual34/38
       are QAE-mangled bodies only hal/scene_boot.cpp's local-struct thunks
       can name (its own banner explains the QAE/UAE split), and its key
       table already maps exactly those three words. */
    (void)port_scene_fill_rom(evt + 13, 3);
    for (unsigned i = 0; i < 18; ++i) {
        if (!kEntHost[i])
            continue;      /* 13/14/15: the keyed pre-pass owns them */
        const unsigned ds = (unsigned)(size_t)evt[i];
        if (ds == kEntRom[i] || evt[i] == kEntHost[i]) {
            evt[i] = kEntHost[i];
        } else {
            std::fprintf(stderr, "  [vs] ENTRY VTABLE slot %u holds %08x, "
                         "the ROM says %08x -- left standing, not "
                         "replaced\n", i, ds, kEntRom[i]);
        }
    }

    /* the menu's one sub-actor, registered the way the scene rows are:
       identity checked against the record's own halfword, factory written
       into word0, record into the spawn table. */
    unsigned char *info = UnknownVsEntry_SpawnInfo;
    const unsigned rec = *(unsigned short *)(info + 4);
    if (rec != 0x15a) {
        std::fprintf(stderr, "  [vs] UnknownVsEntry SpawnInfo at %p says id "
                     "%u, the derivation says 0x15a -- WRONG RECORD, not "
                     "registered\n", (void *)info, rec);
    } else {
        *(void **)(info + 0) = (void *)port_vs_entry_spawn;
        data_020a4bb8[0x15a] = info;
    }
}

/* ---- the ROM's own VS start -----------------------------------------------
   ONE byte and ONE call, in the ROM's own order (port/slice_vs.txt section
   4): the lobby's map-pick index, then func_ov075_02116c8c --
   PrepareVsMode() (the VS flag, SetPlayerGlobals, StartSceneFade(3),
   SaveData defaults), LoadLevelNoReturn(map, 0, 2, 0), the music stop. The
   caller (tests/walk_window.cpp's VS section, or the SM64DS_VS_MAP env boot)
   owns what happens to the staged level next; nothing here fabricates
   ordering the ROM does not have.

   The map index is masked to the ROM's own list: data_ov075_0211c6ec is FOUR
   signed bytes (levels 51, 43, 29, 42) and the lobby's own picker never
   hands func_ov075_02116c8c anything past 3.

   ---- THE RADIO SEAM, AND IT IS INERT TODAY ---------------------------------
   Run rel0215, lane vsnet.

   READ THIS BEFORE BELIEVING THE COMMIT MESSAGE THAT ADDED IT. The commit
   "Engage the radio at the ROM's own VS start, not only at process start"
   presented the install below as the thing that makes a VS boot pair. IT IS
   NOT, AND THE CLAIM WAS WRONG. Review measured the ordering that the original
   banner should have measured and did not:

       tests/walk_window.cpp:5984   port::comms_loopback_install_from_env()
       tests/walk_window.cpp:6233   port_vs_stage_and_start(mi)

   main() installs 249 lines before the VS section reaches this function, on
   EVERY path that exists today -- the env boot, the debug row, and the
   relaunched child alike, because all three are processes whose main() ran.
   So the call below always finds g_installed already true and returns
   immediately, and a build with this line deleted passes all ten assertions in
   port/tools/vs_online_proof.py. What actually fixed the demo was the other two
   commits on this branch: the Winsock start that lets a hostname resolve, and
   the role spelling the relay's own README teaches.

   SO WHAT IS IT FOR. Two things, both real and neither of them a fix:

     IT IS WHERE THE DS'S RADIO COMES UP, written at the seam rather than in a
     comment. SM64DS VS is a wireless mode -- there is no offline VS on the
     cartridge. The ROM's route into a match is dScEntry_c (scene 6, this
     file's own seat) and its start conductor func_ov075_02118a84 WAITS OUT THE
     COMMS HANDSHAKE and a countdown before it calls func_ov075_02116c8c at all
     (slice_vs.txt section 4), so on the DS the start function runs on a console
     that is already in a session. This function is the port's one funnel into
     that start.

     IT IS THE HOOK A REAL LOBBY WILL NEED. The install living in main() is a
     property of the harness, not of the game: it happens because every process
     starts, not because anything asked for a session. When ov075's lobby is
     driven for real -- a player picking VS in-game rather than an env naming a
     map -- the session has to come up at THAT moment, and this is the line that
     will already be in the right place. Until then it is scaffolding.

   IT CANNOT MISBEHAVE, which is why it is kept rather than deleted.
   comms_loopback_install_from_env is documented safe to call more than once and
   returns early once a transport is in, so it cannot open a second socket or
   re-seat a live session. With no comms env in the environment it is a getenv
   and a return. Measured: a bare VS boot is rc 0, zero [comms] lines, and the
   same end position as the pre-change build.

   IF IT EVER STOPS BEING INERT, the ordering it needs is already right and here
   is why. It must be BEFORE func_ov075_02116c8c, because that call ends in
   LoadLevelNoReturn and the staged level is consumed by hal/level_boot.cpp,
   which asks port::comms_wait_for_session() who is in the session before it
   seats a world -- a world seated ahead of the join makes every console believe
   it is player 0. And it must be AFTER io_init, which both callers are:
   walk_window's VS section runs past the game-heap init and the debug row runs
   from a frame loop. */
extern "C" void port_vs_stage_and_start(int mapIdx)
{
    /* The radio, at the ROM's own moment for it. INERT TODAY -- main() has
       always already installed by the time any current caller arrives here --
       and kept for the lobby that will need it. The block above measures the
       ordering and says why this is not the fix the commit claimed. */
    port::comms_loopback_install_from_env();
    data_0209b2e4[0] = (unsigned char)(mapIdx & 3);
    func_ov075_02116c8c();
}

/* the map list, read for the debug row's display and the env boot's report */
extern "C" {
extern signed char data_ov075_0211c6ec[];
}
extern "C" int port_vs_map_level(int mapIdx)
{
    return (int)data_ov075_0211c6ec[mapIdx & 3];
}

/* ---- the closure pieces the first link asked for ---------------------------
   Enumerated from the link's own unresolved list (port/slice_vs.txt, the
   MEASURED GAP section); nothing below was added on speculation. */

/* decorated-spelling bridges, generated; see the include's own header */
#include "vs_aliases.inc"

extern "C" {

/* __aeabi_uidiv, ITCM 0x01ffadf0 -- ARM asm the pinned compiler links and
   MSVC cannot assemble; host body, the hal/cxx_aliases.cpp ITCM-block
   treatment. PORT_HOST_ABI: ARM asm primitive (ITCM soft-float/div block).
   EABI returns quotient in r0 AND remainder in r1, and ov075's own caller
   (src/func_ov075_021143e4.cpp) declares it `long long` to read BOTH, so the
   host body packs {rem, quot} exactly as the register pair would land. */
long long func_01ffadf0(unsigned a, unsigned b)
{
    unsigned q = b ? a / b : 0;
    unsigned r = b ? a % b : 0;
    return ((long long)r << 32) | q;
}

/* THREE arm9 TYPEINFO RECORDS, hosted as zeroed identity-only storage. The
   generated patch writes their addresses into ov075's own typeinfo records'
   base-class words (0x0211c674, 0x0211c8f4, 0x0211c900); the ROM compares
   typeinfo addresses for identity and nothing on the VS boot path walks the
   record CONTENTS. If a dynamic-cast chain walk ever does, it will read
   zeros and virtual-call nothing -- loud, and the honest floor until the
   RTTI records are hosted for real:
     data_02086e78   ActorBase-side base typeinfo (3 relocated words)
     data_0208ee04   the entry actor's base typeinfo (3 relocated words)
     data_020914d4   Scene's typeinfo (3 relocated words) */
DSSTATE_BEGIN
unsigned char data_02086e78[0xc];
unsigned char data_0208ee04[0x10];
unsigned char data_020914d4[0xc];
DSSTATE_END

/* THE VS SUB-SCREEN TILE TABLE, data_0208a0e4: five relocated pointers to
   LZ-compressed arm9 blobs, indexed by language (func_0200f0bc) and handed
   to DecompressLZ16 by src/func_ov075_02116ad4.c. The blobs are plain arm9
   .data with no relocations inside (checked over config/arm9/relocs.txt) and
   come out of the ROM image through port/tools/romdata.py NAMED; the table
   itself carries five DS addresses, so it is hosted HERE with host pointers
   rather than emitted as ROM bytes -- the data_02099fb4 lesson. */
extern unsigned char data_02096f08[], data_02097230[], data_020975d4[],
                     data_02097950[], data_02097ca4[];
DSSTATE_BEGIN
void *data_0208a0e4[5] = { data_02096f08, data_02097230, data_020975d4,
                           data_02097950, data_02097ca4 };
DSSTATE_END

}  /* extern "C" */

/* ShadowModel::InitModel, the ONE decorated spelling an alias cannot bridge:
   the ov075 TU declares it a real member (MSVC __thiscall, `this` in ecx) and
   the matched body is flat cdecl with self as the first stack argument. The
   method definition below emits exactly ?InitModel@ShadowModel@@QAEXPAUMatrix4x3@@HHHI@Z
   and forwards. */
struct Matrix4x3;
extern "C" int _ZN11ShadowModel9InitModelEP9Matrix4x35Fix12IiES3_S3_j(
    void *self, Matrix4x3 *m, int a, int b, int c, unsigned d);
struct ShadowModel {
    void InitModel(Matrix4x3 *m, int a, int b, int c, unsigned d);
};
void ShadowModel::InitModel(Matrix4x3 *m, int a, int b, int c, unsigned d)
{
    _ZN11ShadowModel9InitModelEP9Matrix4x35Fix12IiES3_S3_j(this, m, a, b, c, d);
}

/* data_020927a0: four relocated pointers (to data_02092780/88/90/98, each
   reloc-free and NAMED in port/tools/romdata.py); hosted here with host
   pointers for the data_02099fb4 reason. func_0203083c walks it. */
extern "C" {
extern unsigned char data_02092780[], data_02092788[], data_02092790[],
                     data_02092798[];
DSSTATE_BEGIN
void *data_020927a0[4] = { data_02092780, data_02092788, data_02092790,
                           data_02092798 };
DSSTATE_END
}

/* OS_InitContext (0x02058568), a HAND-ASM PRIMITIVE the pinned toolchain
   assembles and MSVC cannot -- src/func_02058568.c is excluded from the
   slice and this is its host body, a faithful C transcription of the asm
   (the stores, the pc+4, the sp_svc-0x40, the Thumb-bit CPSR derivation).
   PORT_HOST_ABI: ARM asm primitive. NOTE THE HONEST FLOOR BEHIND IT: the
   port runs no DS threads (hal/os_thread.cpp is a pump, not a scheduler), so
   a context initialised here is never context-switched INTO. The VS lobby's
   carousel worker (func_0201a244 -> func_02058200) is created and never
   runs; if the lobby scene stalls scrolling a selector, this is the floor,
   and it is a LOBBY floor only -- the match path never creates a thread. */
extern "C" void func_02058568(unsigned *ctx, unsigned pc, unsigned sp)
{
    unsigned entry = pc + 4;
    ctx[0x40 / 4] = entry;
    ctx[0x44 / 4] = sp;
    ctx[0x38 / 4] = sp - 0x40;
    ctx[0] = (entry & 1) ? 0x3f : 0x1f;
    for (unsigned off = 0x4; off <= 0x34; off += 4)
        ctx[off / 4] = 0;
    ctx[0x3c / 4] = 0;
}

/* ---- THE REFUSED-SUBTREE SEAM FACES ---------------------------------------
   The slice refuses the DS wireless-status wrappers, the DS thread scheduler
   and the card overlay-loader tail (port/slice_vs.txt, the refusal block;
   hal/scene_boot.cpp's LoadOverlay block is the precedent and the reasoning).
   These are the entry points ov075's own TUs call into those subtrees, faced
   LOUD-ONCE: the first call prints, every call answers the no-wireless /
   no-scheduler / nothing-to-unload value, and none pretends progress.

   THE VALUES ARE THE IDLE ONES, derived from the callers:
     func_0203d9f4   the one wireless-status wrapper that really calls the
                     wireless manager (func_020618b8); its eleven siblings
                     turned out to be leaf accessors over comms bss and are
                     COMPILED, not faced -- see the slice's correction note
     UnloadOverlay   nothing to unload: every hosted overlay is a static
                     build-time mount
     func_02058048 / func_02058158 / func_02058200 / func_02057f38
                     the carousel worker's queue-op, poll, thread-create and
                     reschedule -- 0. The port runs no DS threads (see the
                     OS_InitContext note above); a poll that answered "done"
                     would fabricate an animation that never ran.
   When the real netcode lane lands, the comms family here is its seam: these
   faces are exactly the names port::comms state should answer through. */
static unsigned g_vs_seam_hits;
static void vs_seam(const char *name)
{
    if (g_vs_seam_hits++ > 24) return;   /* loud, not a firehose */
    std::fprintf(stderr, "  [vs] refused-subtree seam entered: %s (idle "
                 "answer; port/slice_vs.txt refusal block)\n", name);
    std::fflush(stderr);
}
#define VS_SEAM(sym)                                                           \
    extern "C" int sym(void);                                                  \
    extern "C" int sym(void) { vs_seam(#sym); return 0; }
VS_SEAM(func_0203d9f4)
VS_SEAM(UnloadOverlay)
VS_SEAM(func_02057f38)
VS_SEAM(func_02058048)
VS_SEAM(func_02058158)
VS_SEAM(func_02058200)
#undef VS_SEAM

/* two more relocated arm9 tables, hosted with host pointers (the
   data_02099fb4 lesson, third and fourth applications):
     data_0208a0f8   five OamAttr-list pointers (records NAMED, reloc-free)
     data_02092830   three CODE pointers -- the sub-screen text-plot family
                     (func_0203128c / func_02031154 / func_020313d8, all
                     matched src in this slice) */
extern "C" {
extern unsigned char data_02098b58[], data_02098d20[], data_02098e60[],
                     data_02098fa0[], data_02099068[];
void func_0203128c(void); void func_02031154(void); void func_020313d8(void);
DSSTATE_BEGIN
void *data_0208a0f8[5] = { data_02098b58, data_02098d20, data_02098e60,
                           data_02098fa0, data_02099068 };
void *data_02092830[3] = { (void *)func_0203128c, (void *)func_02031154,
                           (void *)func_020313d8 };
DSSTATE_END
}
