/* THE STAGE-GEOMETRY MOD: serve a level's ground -- its stage model (.bmd) and
   its collision (.kcl) -- out of an external directory instead of out of the
   ROM's own files, at load, without the game learning anything.

   Same rules as every other mod in this tree (hal/fs_mods.cpp states them for
   the palette bridge and hal/stage_mods.cpp restates the whole-file half for
   level edits, so they are not restated per mod): OFF IS THE ROM, boot-latched,
   and every disagreement refuses OUT LOUD and serves stock. The whole-file rule
   applies here for stage_mods' reason, one step stronger: a level whose
   collision came from one file and whose model came from another is a shape
   nobody asked for and nobody can debug -- you fall through a floor you can
   see. So this file reads and validates EVERY file in the directory before it
   serves one byte, and any single complaint drops all of them.

   ---- THE SEAM -------------------------------------------------------------

   hal/fs.cpp's port_fs_mod_filter, which runs inside SharedFilePtr::Load on the
   DECOMPRESSED master, before the fs cache admits it and before the caller gets
   its copy. The contract there allows a filter to REPLACE the buffer outright
   (free the old master, point *data at a fresh malloc, return the new size),
   and it allows the new size to be larger. That is what a custom stage needs
   and it is what this file does.

   BOTH of the level's ground files reach that seam. Read off the matched TUs,
   not off a description of them:

     src/_ZN5Stage18LoadClsnAndObjectsER11LVL_OverlayjR12MeshCollider.cpp
         if (ovl->kclFileId != 0) { f = LoadFile(ovl->kclFileId); ... }
         LoadFile is SharedFilePtr, so the KCL is filtered.

     src/_ZN5Stage9LoadModelEv.cpp
         Model::LoadAndSetFile(self + 0x86c,
                               *(u16 *)(*(char **)data_0209f340 + 8), 1, -1)
         That +8 is LVL_Overlay's bmdFileId (hal/level_boot.cpp's PortLvlOverlay
         says +0x08 bmd, +0x0a kcl), and Model::LoadAndSetFile loads through
         SharedFilePtr too, so the BMD is filtered.

   The two ids in the overlay are ov0 HANDLES. The filter is handed the resolved
   FAT file id, which is the id this file reasons about.

   ---- HOW A FILE ID IS RECOGNISED AS A STAGE FILE ---------------------------

   BY CATALOG PATH, not by id and not by reaching into the mounted overlay.
   hal/fs.cpp exports port_fs_catalog_path(file_id): the path files.tsv gives
   that id, generated by tools/asset_catalog.py from the player's own dump. A
   stage file's path is exactly

       data/stage/<stage>/<basename>.bmd
       data/stage/<stage>/<basename>.kcl

   and the <basename> is NOT the stage name (bombhei_map's model is
   bombhei_map_all.bmd), which is why the directory component is what this file
   keys on and the basename is ignored.

   THE INVARIANT THAT MAKES THAT UNAMBIGUOUS, counted off the generated catalog
   rather than assumed: 48 stage directories, 48 rows ending .bmd under
   data/stage/, 48 rows ending .kcl, and 96 distinct (stage, extension) pairs.
   One model and one collision per stage, no duplicates. So naming a stage and
   an extension names exactly one ROM file.

   WHY THIS CANNOT MISFIRE ON AN ARCHIVE. port_fs_catalog_path only knows loose
   FAT ids (its table is MAX_FILES = 4096 entries) and archive-interior ids are
   0x8000 and up, so an interior id returns a null path and returns here
   untouched on the first test. A file called bombhei_map_all.bmd inside a NARC
   would never be offered this filter's substitution, and no ROM path outside
   data/stage/ passes the prefix test either. The other direction is checked
   too: a name in the directory that no stage in this ROM has is refused rather
   than ignored, because a typo that quietly does nothing is the mistake that
   costs an afternoon.

   ---- WHY THE MOD FILES ARE DECOMPRESSED ON THE WAY IN ----------------------

   The filter operates on the DECOMPRESSED master, and every stage file in the
   extraction is LZ77-tagged (checked: bombhei_map, main_garden and test_map all
   begin with the ASCII magic "LZ77"). Handing those bytes through as-is would
   serve a compressed image where the game expects a decoded one -- garbage
   geometry with no error anywhere. So a substitute that carries the magic is
   decoded here with hal/fs.cpp's own DecompressLZ16, exactly as fs_entry_store
   decodes a ROM file, and one that does not is used as it is. That is what lets
   the ROM's own files stand in as substitutes for a proof while a future writer
   emitting raw bytes works the same way. Which form each file took is reported.

   ---- HOW THIS TU CLAIMS THE FILTER WITHOUT EDITING hal/fs_mods.cpp ---------

   port_fs_mod_filter is ONE function pointer and hal/fs_mods.cpp already
   installs into it from a namespace-scope object's constructor, which MSVC
   places in .CRT$XCU with every other ordinary dynamic initializer. Two TUs
   both initialising in .CRT$XCU have no defined order between them, so the
   plain "save the old value, install mine" chain is a coin flip: lose it and
   fs_mods.cpp overwrites this file's pointer and this filter is simply never
   called.

   So this file's installer does not go in .CRT$XCU. It goes in .CRT$XCV, and
   the MS linker concatenates grouped sections (NAME$SUFFIX -> NAME) in
   ascending order of suffix. XCV sorts after XCU, so this runs after EVERY
   ordinary initializer including fs_mods.cpp's, whatever order the objects
   reach the linker in. That is the same mechanism the CRT itself uses for its
   XCA/XCU/XCZ bracket and the same one hal/dsstate_seg.cpp already depends on
   for .dsstate$aaa .. .dsstate$zzz, so it is load-bearing in this tree already
   rather than a new bet.

   By the time the constructor below runs, port_fs_mod_filter therefore holds
   whatever fs_mods.cpp installed (or null in a target that does not link it).
   It is saved and called at the END of this filter, so the file-layer mods
   compose instead of replacing each other. This one first for the reason
   fs_mods.cpp puts Loves Me first: it can REPLACE the buffer, and a filter that
   edits bytes in place wants to edit the bytes actually being served. In
   practice the order decides nothing, because no file is both a stage model or
   collision and one of the character models or palettes those filters touch.

   The latch line says which of the two happened ("chained onto" or "the only"),
   so a run proves its own installation rather than assuming it.

   ---- THE KNOB -------------------------------------------------------------

       SM64DS_STAGE_GEOM=<dir>

   <dir> holds <stage>.bmd and/or <stage>.kcl, named for the STAGE DIRECTORY
   (bombhei_map.bmd, bombhei_map.kcl). Either one alone is allowed: a model-only
   swap changes what you see and leaves the ground where it was, a
   collision-only swap changes where you can stand and leaves the level looking
   as it did. A directory may hold files for many stages at once; a level whose
   stage is not named in it boots stock.

   The directory is looked for as given first, then beside the exe, then under
   the asset root, which is hal/fs_mods.cpp's probe order for the palettes
   folder minus the working-directory step (the as-given open IS that step when
   the path is relative). A shipping build has no asset root unless
   SM64DS_ASSET_ROOT names one, so there the probe stops after two. The one
   that opened is named in the latch line. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <dirent.h>
#include <sys/stat.h>
#endif

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;

#ifndef PORT_REPO_ROOT
#define PORT_REPO_ROOT "."
#endif

extern "C" const char *port_fs_catalog_path(unsigned file_id); /* hal/fs.cpp */
extern "C" void DecompressLZ16(void *src, void *dst);          /* hal/fs.cpp */

extern "C" {
extern u32 (*port_fs_mod_filter)(unsigned fileID, u8 **data, u32 size);
}

namespace {

enum { K_BMD = 0, K_KCL = 1, KIND_COUNT = 2 };
const char *const KIND_EXT[KIND_COUNT] = { ".bmd", ".kcl" };

/* 48 stages, one model and one collision each, so 96 is the whole ROM's worth
   of substitutes in one directory and 64 names is comfortably past the 48 it
   can ever match. */
enum { MAX_SUB = 96, MAX_STAGE = 64, NAME_CAP = 64, PATH_CAP = 520,
       CATALOG_SCAN_MAX = 4096 };

/* A stage file is tens of kilobytes in the ROM (the largest .kcl in this dump
   is under 200 KB). The cap is not a format rule, it is the line past which a
   file is more likely to be the wrong file than a big level. */
enum { FILE_CAP = 16u * 1024u * 1024u };

struct Sub {
    char stage[NAME_CAP];
    int kind;
    u8 *bytes;          /* decompressed, owned here for the whole run */
    u32 len;
    char shown[PATH_CAP];
    int packed;         /* the source file carried the LZ77 magic */
    int said;
};

int g_state;            /* 0 not tried, 1 on, -1 off, absent or refused */
Sub g_sub[MAX_SUB];
unsigned g_nsub;
char g_dir[PATH_CAP];   /* the directory that actually opened */

char g_stage[MAX_STAGE][NAME_CAP];  /* stage names this ROM has */
unsigned g_nstage;
int g_stages_scanned;

u32 (*g_prev_filter)(unsigned fileID, u8 **data, u32 size);
int g_chained;          /* a filter was already installed when we claimed it */

/* Every refusal goes through here, so they all read the same way and they all
   say what happens instead. */
void refuse(const char *why)
{
    fprintf(stderr, "[mods] StageGeom: %s; every level keeps the model and "
                    "collision the ROM gives it\n", why);
    fflush(stderr);
}

void note(const char *what)
{
    fprintf(stderr, "[mods] StageGeom: %s\n", what);
    fflush(stderr);
}

void release(void)
{
    for (unsigned i = 0; i < g_nsub; ++i) {
        free(g_sub[i].bytes);
        g_sub[i].bytes = 0;
    }
    g_nsub = 0;
}

/* The third probe location, or 0 when there is not a trustworthy one.

   A SHIPPING BUILD GETS NO PORT_REPO_ROOT FALLBACK, for the reason
   hal/asset_root_refuse.cpp gives at length: a compiled-in repo path is
   invisible on every machine that can test it and wrong on every machine that
   cannot. It does not call that refusal, though, because that one aborts, and
   an optional mod's third-choice folder is not worth ending a run over -- the
   probe simply stops one step early and the caller refuses in words. */
const char *asset_root(void)
{
    const char *env = getenv("SM64DS_ASSET_ROOT");
    if (env && *env)
        return env;
#ifdef PORT_ROM_CLEAN
    return 0;
#else
    return PORT_REPO_ROOT;
#endif
}

/* ---- what stages this ROM actually has ---------------------------------- */

/* Walk the loose-file catalog once and collect the directory component of
   every data/stage/<name>/... row. Scanning is how the set stays the player's
   own dump's set: a hardcoded list would be a guess where the catalog is a
   fact. Called at latch, which is inside the first Load, so the catalog is
   already loaded and this cannot re-enter it from a static initializer. */
void scan_stage_names(void)
{
    if (g_stages_scanned)
        return;
    g_stages_scanned = 1;
    for (unsigned id = 0; id < CATALOG_SCAN_MAX; ++id) {
        const char *p = port_fs_catalog_path(id);
        const char *slash;
        size_t n;
        unsigned i;
        if (!p || strncmp(p, "data/stage/", 11) != 0)
            continue;
        slash = strchr(p + 11, '/');
        if (!slash)
            continue;
        n = (size_t)(slash - (p + 11));
        if (n == 0 || n >= NAME_CAP)
            continue;
        for (i = 0; i < g_nstage; ++i)
            if (strlen(g_stage[i]) == n && memcmp(g_stage[i], p + 11, n) == 0)
                break;
        if (i < g_nstage || g_nstage >= MAX_STAGE)
            continue;
        memcpy(g_stage[g_nstage], p + 11, n);
        g_stage[g_nstage][n] = '\0';
        ++g_nstage;
    }
}

/* The catalog's spelling of `name`, or 0. Case-insensitive on Windows because
   the file system there is: a folder holding Bombhei_Map.bmd should work, and
   the CANONICAL spelling is what gets stored, so the match in the filter below
   stays a plain strcmp against the catalog's own path. */
const char *stage_canonical(const char *name)
{
    for (unsigned i = 0; i < g_nstage; ++i)
#ifdef _WIN32
        if (_stricmp(g_stage[i], name) == 0)
#else
        if (strcmp(g_stage[i], name) == 0)
#endif
            return g_stage[i];
    return 0;
}

/* ---- finding the directory ---------------------------------------------- */

int is_dir(const char *path)
{
#ifdef _WIN32
    DWORD a = GetFileAttributesA(path);
    return a != INVALID_FILE_ATTRIBUTES && (a & FILE_ATTRIBUTE_DIRECTORY);
#else
    struct stat st;
    return stat(path, &st) == 0 && S_ISDIR(st.st_mode);
#endif
}

/* As given, then beside the exe, then under the asset root. Fills g_dir. */
int probe_dir(const char *want)
{
    char path[PATH_CAP];
    if (is_dir(want)) {
        snprintf(g_dir, sizeof g_dir, "%s", want);
        return 1;
    }
#ifdef _WIN32
    {
        char exe[MAX_PATH];
        DWORD n = GetModuleFileNameA(NULL, exe, MAX_PATH);
        if (n > 0 && n < MAX_PATH) {
            char *slash = strrchr(exe, '\\');
            char *fwd = strrchr(exe, '/');
            if (fwd && (!slash || fwd > slash))
                slash = fwd;
            if (slash) {
                *slash = '\0';
                snprintf(path, sizeof path, "%s\\%s", exe, want);
                if (is_dir(path)) {
                    snprintf(g_dir, sizeof g_dir, "%s", path);
                    return 1;
                }
            }
        }
    }
#endif
    {
        const char *root = asset_root();
        if (root) {
            snprintf(path, sizeof path, "%s/%s", root, want);
            if (is_dir(path)) {
                snprintf(g_dir, sizeof g_dir, "%s", path);
                return 1;
            }
        }
    }
    return 0;
}

/* ---- reading one substitute --------------------------------------------- */

/* Read <g_dir>/<leaf> into the slot, decompressing if it carries the LZ77
   magic. Returns 1, or 0 with `msg` filled in with the plain-words complaint.
   Whole-file by construction: the bytes are in memory and validated before
   anything can be served, so a substitution can never fail halfway. */
int load_sub(const char *leaf, const char *stage, int kind, Sub *s,
             char *msg, size_t cap)
{
    char full[PATH_CAP];
    FILE *f;
    long len;
    u8 *raw;

    snprintf(full, sizeof full, "%s/%s", g_dir, leaf);
    f = fopen(full, "rb");
    if (!f) {
        snprintf(msg, cap, "%s is there but will not open", full);
        return 0;
    }
    fseek(f, 0, SEEK_END);
    len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (len <= 0) {
        fclose(f);
        snprintf(msg, cap, "%s is empty", full);
        return 0;
    }
    if ((unsigned long)len > FILE_CAP) {
        fclose(f);
        snprintf(msg, cap, "%s is %ld bytes, past the %u byte limit a stage "
                           "file is allowed", full, len, (unsigned)FILE_CAP);
        return 0;
    }
    raw = (u8 *)malloc((size_t)len);
    if (!raw) {
        fclose(f);
        snprintf(msg, cap, "there was not enough memory to read %s", full);
        return 0;
    }
    if ((long)fread(raw, 1, (size_t)len, f) != len) {
        fclose(f);
        free(raw);
        snprintf(msg, cap, "%s stopped part way through reading", full);
        return 0;
    }
    fclose(f);

    if (len > 8 && memcmp(raw, "LZ77", 4) == 0) {
        /* the same header the ROM's files carry: u32 of 0x10 | size << 8,
           sitting just past the four-byte magic the extraction adds */
        u32 dec = (u32)(raw[4] | raw[5] << 8 | raw[6] << 16 |
                        (u32)raw[7] << 24) >> 8;
        if (dec == 0 || dec > FILE_CAP) {
            free(raw);
            snprintf(msg, cap, "%s says it unpacks to %u bytes, which is not a "
                               "size a stage file has", full, dec);
            return 0;
        }
        s->bytes = (u8 *)malloc(dec);
        if (!s->bytes) {
            free(raw);
            snprintf(msg, cap, "there was not enough memory to unpack %s", full);
            return 0;
        }
        DecompressLZ16(raw + 4, s->bytes);
        s->len = dec;
        s->packed = 1;
        free(raw);
    } else {
        s->bytes = raw;
        s->len = (u32)len;
        s->packed = 0;
    }
    snprintf(s->stage, sizeof s->stage, "%s", stage);
    snprintf(s->shown, sizeof s->shown, "%s", full);
    s->kind = kind;
    s->said = 0;
    return 1;
}

/* ---- the latch ----------------------------------------------------------

   Lazy, on the first load the filter sees, for two reasons. hal/fs.cpp's
   catalog is loaded by then, so scan_stage_names cannot run before there is a
   catalog to scan; and a directory that will not open says so on stderr in the
   middle of a running program rather than during static initialization, where
   the message competes with nothing that is listening yet. Read ONCE, like
   every mod in this tree: the fs cache keys master copies by file id, so a
   mid-run flip would serve half one level's ground and half another's. */
void latch(void)
{
    const char *want;
    char msg[PATH_CAP + 160];
    char list[512];
    size_t used = 0;

    list[0] = '\0';

    if (g_state)
        return;
    g_state = -1;

    want = getenv("SM64DS_STAGE_GEOM");
    if (!want || !*want)
        return;                 /* off, and off is silent like every mod's off */

    if (!probe_dir(want)) {
        snprintf(msg, sizeof msg, "SM64DS_STAGE_GEOM names %s and there is no "
                                  "folder there", want);
        refuse(msg);
        return;
    }

    scan_stage_names();
    if (g_nstage == 0) {
        refuse("the file catalog lists no stages at all, so there is nothing a "
               "substitute could be matched against");
        return;
    }

    /* Enumerate, validate and READ EVERYTHING before serving one byte. Any
       single complaint drops all of it, so `bad` breaks the walk rather than
       jumping out of it: the directory handle has to be closed either way. */
    msg[0] = '\0';
    {
        int bad = 0;
#ifdef _WIN32
        char glob[PATH_CAP];
        WIN32_FIND_DATAA fd;
        HANDLE h;
        snprintf(glob, sizeof glob, "%s/*", g_dir);
        h = FindFirstFileA(glob, &fd);
        if (h == INVALID_HANDLE_VALUE) {
            snprintf(msg, sizeof msg, "%s will not list", g_dir);
            refuse(msg);
            return;
        }
        do {
            const char *leaf = fd.cFileName;
            if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
                continue;
#else
        DIR *d = opendir(g_dir);
        struct dirent *de;
        if (!d) {
            snprintf(msg, sizeof msg, "%s will not list", g_dir);
            refuse(msg);
            return;
        }
        while ((de = readdir(d)) != 0) {
            const char *leaf = de->d_name;
#endif
            {
                const char *dot = strrchr(leaf, '.');
                const char *canon;
                char stage[NAME_CAP];
                size_t n;
                int kind = -1;
                unsigned i;

                if (!dot)
                    continue;
                for (i = 0; i < KIND_COUNT; ++i)
#ifdef _WIN32
                    if (_stricmp(dot, KIND_EXT[i]) == 0)
#else
                    if (strcmp(dot, KIND_EXT[i]) == 0)
#endif
                        kind = (int)i;
                if (kind < 0)
                    continue;   /* not ours; a folder may hold other things */

                n = (size_t)(dot - leaf);
                if (n == 0 || n >= NAME_CAP) {
                    snprintf(msg, sizeof msg, "%s/%s does not have a usable "
                                              "stage name in front of its "
                                              "extension", g_dir, leaf);
                    bad = 1;
                    break;
                }
                memcpy(stage, leaf, n);
                stage[n] = '\0';

                canon = stage_canonical(stage);
                if (!canon) {
                    snprintf(msg, sizeof msg, "%s/%s is named for a stage "
                                              "called '%s', and no level in "
                                              "this ROM has one", g_dir, leaf,
                             stage);
                    bad = 1;
                    break;
                }
                for (i = 0; i < g_nsub; ++i)
                    if (g_sub[i].kind == kind &&
                        strcmp(g_sub[i].stage, canon) == 0)
                        break;
                if (i < g_nsub) {
                    snprintf(msg, sizeof msg, "%s/%s is a second %s file for "
                                              "stage '%s'", g_dir, leaf,
                             KIND_EXT[kind], canon);
                    bad = 1;
                    break;
                }
                if (g_nsub >= MAX_SUB) {
                    snprintf(msg, sizeof msg, "%s holds more than %u stage "
                                              "files", g_dir, (unsigned)MAX_SUB);
                    bad = 1;
                    break;
                }
                if (!load_sub(leaf, canon, kind, &g_sub[g_nsub], msg,
                              sizeof msg)) {
                    bad = 1;
                    break;
                }
                ++g_nsub;
            }
#ifdef _WIN32
        } while (FindNextFileA(h, &fd));
        FindClose(h);
#else
        }
        closedir(d);
#endif
        if (bad) {
            release();
            refuse(msg);
            return;
        }
    }

    if (g_nsub == 0) {
        snprintf(msg, sizeof msg, "%s holds no .bmd or .kcl files, so there is "
                                  "nothing to put in a level", g_dir);
        refuse(msg);
        return;
    }

    for (unsigned i = 0; i < g_nsub; ++i) {
        const char *sep = used ? ", " : "";
        size_t need = strlen(sep) + strlen(g_sub[i].stage) + 4;
        if (used + need + 4 >= sizeof list) {
            memcpy(list + used, ", ...", 6);
            break;
        }
        used += (size_t)snprintf(list + used, sizeof list - used, "%s%s%s", sep,
                                 g_sub[i].stage, KIND_EXT[g_sub[i].kind]);
    }
    fprintf(stderr, "[mods] StageGeom: %s: %u file(s) ready (%s); %s the file "
                    "mod filter\n", g_dir, g_nsub, list,
            g_chained ? "chained onto" : "installed as the only");
    fflush(stderr);
    g_state = 1;
}

/* ---- the filter --------------------------------------------------------- */

u32 stage_geom_apply(unsigned fileID, u8 **data, u32 size)
{
    const char *path, *rest, *slash, *dot;
    char stage[NAME_CAP];
    size_t n;
    int kind = -1;
    unsigned i;

    latch();
    if (g_state != 1)
        return size;

    path = port_fs_catalog_path(fileID);
    if (!path)
        return size;            /* an archive interior, or an id with no row */
    if (strncmp(path, "data/stage/", 11) != 0)
        return size;
    rest = path + 11;
    slash = strchr(rest, '/');
    if (!slash)
        return size;
    n = (size_t)(slash - rest);
    if (n == 0 || n >= NAME_CAP)
        return size;
    if (strchr(slash + 1, '/'))
        return size;            /* deeper than one level: not a stage file */
    dot = strrchr(slash + 1, '.');
    if (!dot)
        return size;
    for (i = 0; i < KIND_COUNT; ++i)
        if (strcmp(dot, KIND_EXT[i]) == 0)
            kind = (int)i;
    if (kind < 0)
        return size;
    memcpy(stage, rest, n);
    stage[n] = '\0';

    for (i = 0; i < g_nsub; ++i) {
        Sub *s = &g_sub[i];
        u8 *copy;
        if (s->kind != kind || strcmp(s->stage, stage) != 0)
            continue;
        /* A COPY, not the latched image. The fs cache takes ownership of
           whatever this returns in *data and is free to free it; the latched
           image has to survive for the next load of the same level. */
        copy = (u8 *)malloc(s->len);
        if (!copy) {
            if (!s->said++)
                fprintf(stderr, "[mods] StageGeom: there was not enough memory "
                                "to put %s in place, so %s keeps its stock "
                                "file\n", s->shown, path);
            return size;
        }
        memcpy(copy, s->bytes, s->len);
        if (*data)
            free(*data);
        *data = copy;
        if (!s->said++)
            fprintf(stderr, "[mods] StageGeom: %s serves %s (%s, %u bytes in "
                            "place of %u)\n", s->shown, path,
                    s->packed ? "unpacked here" : "used as it is", s->len,
                    size);
        fflush(stderr);
        return s->len;
    }
    return size;
}

u32 geom_filter(unsigned fileID, u8 **data, u32 size)
{
    size = stage_geom_apply(fileID, data, size);
    if (g_prev_filter)
        size = g_prev_filter(fileID, data, size);
    return size;
}

/* Runs AFTER every ordinary dynamic initializer, hal/fs_mods.cpp's included,
   because .CRT$XCV sorts after .CRT$XCU and the linker concatenates grouped
   sections in suffix order. See the header's section on this. Whatever was
   installed is saved and called at the end of geom_filter above. */
void __cdecl geom_install(void)
{
    g_prev_filter = port_fs_mod_filter;
    g_chained = g_prev_filter != 0;
    port_fs_mod_filter = geom_filter;
}

} /* namespace */

#pragma section(".CRT$XCV", read)
extern "C" __declspec(allocate(".CRT$XCV"))
    void (__cdecl *port_stage_geom_ctor)(void) = geom_install;
/* /OPT:REF cannot see a pointer nothing references. The decoration is the
   32-bit one because port/build-port.cmd builds through vcvars32. */
#if defined(_M_IX86)
#pragma comment(linker, "/include:_port_stage_geom_ctor")
#else
#pragma comment(linker, "/include:port_stage_geom_ctor")
#endif
