//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov098/ArrowSignRight  (11 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled daObjKm2_Ami_Bou_c::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02137be0  src/_ZN14ArrowSignRightD1Ev.cpp
 *   [1] 0x02137c2c  src/_ZN14ArrowSignRightD0Ev.cpp
 *   [2] 0x02137c8c  src/func_ov098_02137c8c.c
 *   [3] 0x02137ccc  src/_ZN14ArrowSignRight4KillEv.cpp
 *   [4] 0x02137d40  src/_ZN14ArrowSignRight11OnAttacked1ER8dActor_c.cpp
 *   [5] 0x02137d80  src/_ZN14ArrowSignRight15OnHitByMegaCharER6Player.cpp
 *   [6] 0x02137dbc  src/_ZN14ArrowSignRight16CleanupResourcesEv.cpp
 *   [7] 0x02137e20  src/_ZN14ArrowSignRight6RenderEv.cpp
 *   [8] 0x02137e48  src/_ZN14ArrowSignRight8BehaviorEv.cpp
 *   [9] 0x02137eec  src/_ZN14ArrowSignRight13InitResourcesEv.cpp
 *   [10] 0x02137fd0  src/ArrowSignRight_Spawn.c
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "ArrowSignRight.h"
#include "Sound.h"
#include "SharedFilePtr.h"
#include "dBgW.h"
#include "decl_ActorBase.h"
#include "decl_Platform.h"
#include "decl_ShadowModel.h"

/* This class's own field access is real member syntax throughout (mModel,
 * mMeshCollider, mVariant -- ArrowSignRight.h); no shadow struct stands in for
 * a real project class. The one local type below is genuine ROM-table
 * recovery, not a workaround. */
/* shadow struct 'ArrowSignFileColumn' */
struct ArrowSignFileColumn {
    void *value;
    void *nextColumn1;
    void *nextColumn2;
};

extern "C" {
extern void Matrix4x3_FromRotationY(void *, int);
extern "C" void _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_( u32 id, Fix12i x, Fix12i y, Fix12i z);
int func_02012694(int, void*);
void _ZN6Player16IncMegaKillCountEv(void*);
void _ZN10dBgActor_c14KillByMegaCharER6Player(void*, void*);
int _ZN10dBgActor_c20UpdateKillByMegaCharEsss5Fix12IiE(void* c, short a, short b, short d, int e);
void func_02039394(int* p, int v);
void func_020393a4(int* p, int v);
void _ZN8dActor_c18DropShadowScaleXYZER11ShadowModelR9Matrix4x35Fix12IiES5_S5_j(void* c, void* sm, void* mtx, int s, int x, int y, unsigned int j);
int _ZN10dBgActor_c21IsClsnInRangeOnScreenE5Fix12IiES1_(void* c, int a, int b);
void *_ZN5Model8LoadFileER13SharedFilePtr(void *fp);
void _ZN9ModelBase7SetFileEP8BMD_Fileii(void *self, void *bmd, int a, int b);
void _ZN10dBgActor_c21UpdateModelPosAndRotYEv(void *self);
void _ZN10dBgActor_c19UpdateClsnPosAndRotEv(void *self);
void func_ov098_02137c8c(char *self);
void *_ZN7dBgW_Kc8LoadFileER13SharedFilePtr(void *fp);
void _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
void *self, void *kcl, void *mtx, int scale, short angle, void *clps);
/* Each row is model/KCL/CLPS, but the ROM gives each column its own symbol.
* These three overlapping stride-0xc views keep those relocation destinations
* distinct while still indexing the table as rows. */
extern ArrowSignFileColumn data_ov098_0213c380[];
extern ArrowSignFileColumn data_ov098_0213c384[];
extern ArrowSignFileColumn data_ov098_0213c388[];
extern int _ZTV14ArrowSignRight[];
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 10 -- ArrowSignRight_Spawn, 0x02137fd0, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol ArrowSignRight_Spawn
/* recovered: vtable identified, globals resolved, declarations from a shared header */
/* recovered: vtable identified, globals resolved */
/* resolved: VT0 = _ZTV14ArrowSignRight */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int *ArrowSignRight_Spawn(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(896);
    if (p) {
        _ZN10dBgActor_cC2Ev(p);
        p[0] = (int)(_ZTV14ArrowSignRight + 2);
        _ZN11ShadowModelC1Ev((char *)p + 0x320);
    }
    return p;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- _ZN14ArrowSignRight13InitResourcesEv, 0x02137eec, size 0xe4 */
/* -------------------------------------------------------------------------- */
int ArrowSignRight::InitResources()
{
    u16 id = actorID;
    if (id != 0x12b) {
        if (id == 0x12c)
            mVariant = 1;
    } else {
        mVariant = 0;
    }

    u32 modelIndex = mVariant;
    void *model = _ZN5Model8LoadFileER13SharedFilePtr(data_ov098_0213c380[modelIndex].value);
    _ZN9ModelBase7SetFileEP8BMD_Fileii(&mModel, model, 1, -1);
    mShadowModel.InitCuboid();
    _ZN10dBgActor_c21UpdateModelPosAndRotYEv(this);
    _ZN10dBgActor_c19UpdateClsnPosAndRotEv(this);
    func_ov098_02137c8c((char *)this);

    u32 collisionIndex = mVariant;
    void *kcl = _ZN7dBgW_Kc8LoadFileER13SharedFilePtr(data_ov098_0213c384[collisionIndex].value);
    _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
        &mMeshCollider, kcl, &mClsnMat, 0x199, mAngleY,
        data_ov098_0213c388[collisionIndex].value);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- _ZN14ArrowSignRight8BehaviorEv, 0x02137e48, size 0xa4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN14ArrowSignRight8BehaviorEv
/* recovered: named members + shared header, real C++ method */
int ArrowSignRight::Behavior()
{
    if (_ZN10dBgActor_c20UpdateKillByMegaCharEsss5Fix12IiE(((char*)this), -0x2000, 0, 0, 0x96000))
        return 1;
    func_02039394((int*)((char*)&(*(u8 *)&mMeshCollider)), 0xc0000);
    func_020393a4((int*)((char*)&(*(u8 *)&mMeshCollider)), 0xe0000);
    _ZN8dActor_c18DropShadowScaleXYZER11ShadowModelR9Matrix4x35Fix12IiES5_S5_j(
        ((char*)this), (void*)((char*)&mShadowModel), (void*)((char*)&mShadowMat), 0x10e000, 0x64000, 0x46000, 0xf);
    _ZN10dBgActor_c21IsClsnInRangeOnScreenE5Fix12IiES1_(((char*)this), 0x600000, 0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- _ZN14ArrowSignRight6RenderEv, 0x02137e20, size 0x28 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN14ArrowSignRight6RenderEv
/* recovered: named members + shared header, real C++ method */
int ArrowSignRight::Render()
{
    mModel.Render(0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN14ArrowSignRight16CleanupResourcesEv, 0x02137dbc, size 0x64 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN14ArrowSignRight16CleanupResourcesEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int ArrowSignRight::CleanupResources()
{
    if (mMeshCollider.IsEnabled())
        mMeshCollider.Disable();
    ((SharedFilePtr *)data_ov098_0213c380[mVariant].value)->Release();
    ((SharedFilePtr *)data_ov098_0213c384[mVariant].value)->Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN14ArrowSignRight15OnHitByMegaCharER6Player, 0x02137d80, size 0x3c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN14ArrowSignRight15OnHitByMegaCharER6Player
// recovered name: ArrowSignRight_OnHitByMegaChar
/* recovered: renamed to Class_Method */
/* daObjYajirusi_c::OnHitByMegaChar - recovered from vtable slot identity */
void ArrowSignRight::OnHitByMegaChar(Player &player)
{
    _ZN6Player16IncMegaKillCountEv(&player);
    func_02012694(0x1e, (char*)this + 0x74);
    _ZN10dBgActor_c14KillByMegaCharER6Player(this, &player);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN14ArrowSignRight11OnAttacked1ER8dActor_c, 0x02137d40, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN14ArrowSignRight11OnAttacked1ER8dActor_c
// recovered name: ArrowSignRight_OnAttacked1
/* recovered: renamed to Class_Method */
/* daObjYajirusi_c::OnAttacked1 - recovered from vtable slot identity. The
   draft indexed a raw 64-entry function-pointer vtable at word 0x7c/4 =
   31; that slot is Kill(), already a named virtual on this class, so
   this calls it directly. `other`'s actorID (offset 0xc) has no public
   C++ name on dActor_c (only the C-fallback flat struct names it), so it
   stays a raw offset read, matching every other sibling override in this
   tree that reads another actor's fields this way. */
int ArrowSignRight::OnAttacked1(dActor_c &other)
{
    unsigned r = (*(unsigned short*)((char*)&other + 0xc) == 0xce) ? 1u : 0u;
    if (r == 0) return;
    Kill();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN14ArrowSignRight4KillEv, 0x02137ccc, size 0x74 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN14ArrowSignRight4KillEv
/* ArrowSignRight::Kill() at ov098 0x02137ccc, 0x74 bytes -- vtable slot 31.
 *
 * ATTRIBUTED BY THE VTABLE. _ZTV14ArrowSignRight (ov098 0x0213c3d8) relocates
 * its word at +0x7c to 0x02137ccc, and _ZTV10dBgActor_c carries
 * _ZN10dBgActor_c4KillEv at the same slot, so this is this class's own override of
 * dBgActor_c's Kill. Slot 30 (+0x78) is the main-module 0x02010124 in both
 * tables, which is what makes 31 the first slot where they differ.
 *
 * The file used to carry `// recovered name: ArrowSignRight_Kill` alongside
 * `daObjYajirusi_c::Kill`. daObjYajirusi_c IS this class's RTTI name, so the
 * two agreed here; the comment is gone anyway because the vtable, not a
 * comment, is the source.
 *
 * Same shape as dBgActor_c::Kill, with three differences the ROM dictates: the
 * particle is 0xe rather than 0xa, it spawns 0x28000 -- forty 20.12 units --
 * above the sign rather than a hundred, and the poof is DisappearPoofDustAt
 * (particles 0x127/0x128) rather than PoofDustAt.
 *
 * The second Vector3 is memberwise on purpose: Vector3 declares a destructor
 * (types.h), so a whole-object assignment compiles to an ldm/stm pair, four
 * instructions where the ROM has six. Particle::System::NewSimple stays spelled
 * as its mangled name -- its parameters are Fix12<int> BY VALUE and declaring
 * the true types changes how the caller passes them. Both points are argued in
 * full in src/_ZN10dBgActor_c4KillEv.cpp. */
void ArrowSignRight::Kill()
{
    Vector3 pos;
    Vector3 dustPos;
    Fix12i x = mPosX;
    Fix12i y = mPosY + 0x28000;
    Fix12i z = mPosZ;
    pos.x = x;
    pos.y = y;
    pos.z = z;
    _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(0xe, pos.x, pos.y, pos.z);
    dustPos.x = pos.x;
    dustPos.y = pos.y;
    dustPos.z = pos.z;
    DisappearPoofDustAt(dustPos);
    Sound::PlayBank3(0x41, *(Vector3 *)&mCamSpacePosX);
    MarkForDestruction();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov098_02137c8c, 0x02137c8c, size 0x40 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov098_02137c8c(char *t)
{
    Matrix4x3_FromRotationY(t + 0x348, *(short *)(t + 0x8e));
    *(int *)(t + 0x36c) = *(int *)(t + 0x5c) >> 3;
    *(int *)(t + 0x370) = *(int *)(t + 0x60) >> 3;
    *(int *)(t + 0x374) = *(int *)(t + 0x64) >> 3;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN14ArrowSignRightD0Ev, 0x02137c2c, size 0x60 */
/* ROM ordinal 0 -- _ZN14ArrowSignRightD1Ev, 0x02137be0, size 0x4c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN14ArrowSignRightD0Ev
// @symbol _ZN14ArrowSignRightD1Ev
/* recovered: real C++ destructor -- the compiler emits D2, D0, and D1 together
 * from this ONE source definition (the TU-reconstruction D0/D1/D2 collapse
 * rule); the two legacy per-variant files were merging the same body twice,
 * which mwcc rejects as a redefinition. objisolate keeps each emitted .text
 * section bound to its own symbol.
 *
 * Two vtable stores and three destructor calls, every one a consequence of
 * `struct ArrowSignRight : dBgActor_c`: its own vptr, then dBgActor_c's --
 * inlined, because dBgActor_c's destructor is defined in its class body --
 * then dBgActor_c's Model and dBgW_KcMbg, then dActor_c. This class adds no
 * member with a destructor of its own. D0 additionally destroys through the
 * base and returns the object to its heap via an inline operator delete.
 */
ArrowSignRight::~ArrowSignRight()
{
}
