//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov056/BigMovingIceBlock  (6 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021111a0  src/_ZN17BigMovingIceBlockD1Ev.cpp
 *   [1] 0x021111e4  src/_ZN17BigMovingIceBlockD0Ev.cpp
 *   [2] 0x0211123c  src/_ZN17BigMovingIceBlock16CleanupResourcesEv.cpp
 *   [3] 0x02111284  src/_ZN17BigMovingIceBlock6RenderEv.cpp
 *   [4] 0x021112ac  src/_ZN17BigMovingIceBlock8BehaviorEv.cpp
 *   [5] 0x021114e0  src/_ZN17BigMovingIceBlock13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "BigMovingIceBlock.h"
#include "SharedFilePtr.h"
#include "decl_PathPtr.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow struct 'Base' */
struct Base { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void m(int); };

/* shadow struct 'Derived' */
struct Derived { char pad[0xd4]; Base base; };

/* shadow typedef 'Fix12Raw' */
typedef int Fix12Raw;

/* shadow struct 'V3' */
struct V3 { int x, y, z; };

extern "C" {
extern SharedFilePtr *data_ov056_02113314[];
extern void _ZNK7PathPtr7GetNodeER7Vector3j(void *p, void *out, unsigned idx);
extern void Vec3_Sub(void *out, void *a, void *b);
extern int LenVec3(void *v);
extern int _ZN4cstd4fdivEii(int a, int b);
extern void Vec3_MulScalar(void *out, void *v, int s);
extern void SubVec3(void *a, void *b, void *c);
extern void _ZN10dBgActor_c21UpdateModelPosAndRotYEv(void *p);
extern void _ZN10dBgActor_c19UpdateClsnPosAndRotEv(void *p);
extern int _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(void *p, Fix12Raw a, int b);
extern void* _ZN5Model8LoadFileER13SharedFilePtr(void* sfp);
extern void _ZN9ModelBase7SetFileEP8BMD_Fileii(void* self, void* f, int a, int b);
extern void* _ZN7dBgW_Kc8LoadFileER13SharedFilePtr(void* sfp);
extern void _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(void* self, void* kcl, void* mtx, int fix, short s, void* clps);
extern void func_020393d4(int* p, void* v);
extern void _ZN7PathPtr6FromIDEj(void* self, unsigned int id);
extern int _ZN4dBgW22UpdatePosWithTransformERS_P8dActor_cR5dBgPiR7Vector3P10Vector3_16S8_;
/* struct SFP DROPPED: it is the same object as data_ov056_02113314[] declared above,
 * whose spelling names SharedFilePtr and is the more complete observation.
 * .a/.b/.c are exactly [0]/[1]/[2]; the use sites below index instead. */
/* TUBUILD CONFLICT -- alternate declaration of _ZN10dBgActor_c21UpdateModelPosAndRotYEv, from the legacy file for _ZN17BigMovingIceBlock13InitResourcesEv, NOT applied: extern int _ZN10dBgActor_c21UpdateModelPosAndRotYEv(void*); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN10dBgActor_c19UpdateClsnPosAndRotEv, from the legacy file for _ZN17BigMovingIceBlock13InitResourcesEv, NOT applied: extern int _ZN10dBgActor_c19UpdateClsnPosAndRotEv(void*); */
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN17BigMovingIceBlock13InitResourcesEv, 0x021114e0, size 0xb4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17BigMovingIceBlock13InitResourcesEv
/* recovered: named members + shared header, real C++ method */
int BigMovingIceBlock::InitResources()
{
  void* f = _ZN5Model8LoadFileER13SharedFilePtr(data_ov056_02113314[0]);
  _ZN9ModelBase7SetFileEP8BMD_Fileii(((char*)this)+0xd4, f, 1, -1);
  _ZN10dBgActor_c21UpdateModelPosAndRotYEv(((char*)this));
  _ZN10dBgActor_c19UpdateClsnPosAndRotEv(((char*)this));
  void* f2 = _ZN7dBgW_Kc8LoadFileER13SharedFilePtr(data_ov056_02113314[1]);
  _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(((char*)this)+0x124, f2, ((char*)this)+0x2ec, 0x199, mAngleY, data_ov056_02113314[2]);
  func_020393d4((int*)((char*)&mMeshCollider), &_ZN4dBgW22UpdatePosWithTransformERS_P8dActor_cR5dBgPiR7Vector3P10Vector3_16S8_);
  _ZN7PathPtr6FromIDEj(((char*)this)+0x320, param1&0xff);
  mPathDir = 1;
  mHorzSpeed = 0xa000;
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN17BigMovingIceBlock8BehaviorEv, 0x021112ac, size 0x234 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17BigMovingIceBlock8BehaviorEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
/* Not `Fix12`: this actor's header now reaches math/Fix12.h, where Fix12 is a
   class template. Only the raw word matters at this call. */
int BigMovingIceBlock::Behavior()
{
    struct V3 prev;
    struct V3 node;
    struct V3 diff;
    struct V3 scaled1;
    struct V3 scaled2;
    int looped;
    int delta;
    int len;

    mHorzSpeed = 0xa000;
    delta = mPathNodeIdx - mPathDir;
    looped = 0;

    if (_ZNK7PathPtr5LoopsEv((char *)&mPath)) {
        if (mPathDir > 0) {
            if (delta < 0)
                delta = _ZNK7PathPtr8NumNodesEv((char *)&mPath) - 1;
        } else {
            if (delta >= _ZNK7PathPtr8NumNodesEv((char *)&mPath))
                delta = looped;
        }
        _ZNK7PathPtr7GetNodeER7Vector3j(((char *)this) + 0x320, &node, delta);
    } else {
        if (delta < 0 || delta >= _ZNK7PathPtr8NumNodesEv((char *)&mPath)) {
            node.x = mPosX;
            node.y = mPosY;
            node.z = mPosZ;
        } else {
            _ZNK7PathPtr7GetNodeER7Vector3j(((char *)this) + 0x320, &node, delta);
        }
    }

    _ZNK7PathPtr7GetNodeER7Vector3j(((char *)this) + 0x320, &prev, mPathNodeIdx);
    Vec3_Sub(&diff, ((char *)this) + 0x5c, &prev);
    len = LenVec3(&diff);
    if (len == 0 || len <= mHorzSpeed) {
        int q = _ZN4cstd4fdivEii(mHorzSpeed, len);
        Vec3_MulScalar(&scaled1, &diff, q);
        SubVec3(((char *)this) + 0x5c, &scaled1, ((char *)this) + 0x5c);
        looped = 1;
    } else {
        int q = _ZN4cstd4fdivEii(mHorzSpeed, len);
        Vec3_MulScalar(&scaled2, &diff, q);
        SubVec3(((char *)this) + 0x5c, &scaled2, ((char *)this) + 0x5c);
    }

    if (looped) {
        int *pn = (int *)(((int)((char *)this) + 0x328));
        *pn = *pn + mPathDir;
        if (mPathNodeIdx < 0) {
            if (_ZNK7PathPtr5LoopsEv((char *)&mPath))
                mPathNodeIdx = _ZNK7PathPtr8NumNodesEv((char *)&mPath) - 1;
            else {
                int *pn2;
                mPathDir = 1;
                pn2 = (int *)(((unsigned int)((char *)this) + 0x328));
                *pn2 = *pn2 + mPathDir * 2;
            }
        }
        if (mPathNodeIdx >= _ZNK7PathPtr8NumNodesEv((char *)&mPath)) {
            if (_ZNK7PathPtr5LoopsEv((char *)&mPath))
                mPathNodeIdx = 0;
            else {
                int *pn3;
                mPathDir = -1;
                pn3 = (int *)(((int)((char *)&mPathNodeIdx)));
                *pn3 = *pn3 + mPathDir * 2;
            }
        }
    }

    _ZN10dBgActor_c21UpdateModelPosAndRotYEv(((char *)this));
    _ZN10dBgActor_c19UpdateClsnPosAndRotEv(((char *)this));
    _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(((char *)this), 0x5dc000, 0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN17BigMovingIceBlock6RenderEv, 0x02111284, size 0x28 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17BigMovingIceBlock6RenderEv
/* recovered: named members + shared header, real C++ method */
int BigMovingIceBlock::Render()
{
 Base *b = &((Derived *)this)->base; b->m(0); return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN17BigMovingIceBlock16CleanupResourcesEv, 0x0211123c, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17BigMovingIceBlock16CleanupResourcesEv
/* BigMovingIceBlock::CleanupResources -- vtable slot 3. Takes the mesh collider
 * out of the collision world, then releases the block's two shared files. */
int BigMovingIceBlock::CleanupResources()
{
    if (mMeshCollider.IsEnabled()) {
        mMeshCollider.Disable();
    }
    data_ov056_02113314[0]->Release();
    data_ov056_02113314[1]->Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN17BigMovingIceBlockD1Ev, 0x021111a0, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17BigMovingIceBlockD1Ev
/* Real compiler-spelled complete destructor. BigMovingIceBlock's destructor
 * is inline in the class so its D1/D0 order and lack of a homeless D2 match
 * the original TU. This uncalled helper forces mwcc to materialize D1;
 * objisolate keeps the enrolled destructor and discards the helper. */
void BigMovingIceBlock_EmitDestructor(BigMovingIceBlock *p)
{
    p->~BigMovingIceBlock();
}
