//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov060/BowserShockwaves  (6 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02118cfc  src/_ZN16BowserShockwavesD1Ev.cpp
 *   [1] 0x02118d64  src/_ZN16BowserShockwavesD0Ev.cpp
 *   [2] 0x02118de0  src/_ZN16BowserShockwaves16CleanupResourcesEv.cpp
 *   [3] 0x02118e1c  src/_ZN16BowserShockwaves6RenderEv.cpp
 *   [4] 0x02118eb8  src/_ZN16BowserShockwaves8BehaviorEv.cpp
 *   [5] 0x02119004  src/_ZN16BowserShockwaves13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "BowserShockwaves.h"
#include "SharedFilePtr.h"
#include "decl_common.h"
#include "decl_MaterialChanger.h"
#include "MaterialChanger.h"
#include "TextureSequence.h"

extern "C" {
/* three `extern char` scalars dropped: include/decl_common.h (included above) is the
 * FIRST declaration and has all three as int[], which is the more complete observation --
 * this TU indexes them ([1]) as well as taking their address. */
extern "C" void* _ZN8dActor_c13ClosestPlayerEv(void* self);
extern "C" int Vec3_HorzDist(const void* a, const void* b);
extern "C" void _ZN6Player5ShockEj(void* p, unsigned int x);
extern "C" void _ZN9Animation7AdvanceEv(void* a);
extern "C" void Matrix4x3_FromTranslation(void* m, int x, int y, int z);
extern "C" int _ZN9Animation8FinishedEv(void* a);
extern "C" void _ZN7fBase_c18MarkForDestructionEv(void* a);
extern int _ZN5Model8LoadFileER13SharedFilePtr(void* sfp);
extern void _ZN9ModelBase7SetFileEP8BMD_Fileii(void* thiz, void* f, int a, int b);
extern int _ZN9Animation8LoadFileER13SharedFilePtr(void* sfp);
extern int _ZN15TextureSequence8LoadFileER13SharedFilePtr(void* sfp);
extern void func_02016b24(void* thiz, int a);
extern void _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(void* thiz, void* f, int a, int fix, unsigned int u);
extern void _ZN15TextureSequence7SetFileER8BTP_Filei5Fix12IiEj(void* thiz, void* f, int a, int fix, unsigned int u);
extern void _ZN18TextureTransformer7PrepareER8BMD_FileR8BTA_File(void* a, void* b);
extern void _ZN18TextureTransformer7SetFileER8BTA_Filei5Fix12IiEj(void* thiz, void* f, int a, int fix, unsigned int u);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN16BowserShockwaves13InitResourcesEv, 0x02119004, size 0x1f0 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16BowserShockwaves13InitResourcesEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int BowserShockwaves::InitResources()
{
    _ZN9ModelBase7SetFileEP8BMD_Fileii(((char*)this) + 0xd4, (void*)_ZN5Model8LoadFileER13SharedFilePtr(&data_ov060_0211b208), 1, 0x13);
    _ZN9ModelBase7SetFileEP8BMD_Fileii(((char*)this) + 0x174, (void*)data_ov060_0211b208[1], 1, 0x13);

    _ZN9Animation8LoadFileER13SharedFilePtr(&data_ov060_0211b1f8);
    _ZN15TextureSequence8LoadFileER13SharedFilePtr(&data_ov060_0211b200);

    func_02016b24(((char*)this) + 0xd4, 0x4000);
    func_02016b24(((char*)this) + 0x174, 0x4000);

    _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(((char*)this) + 0xd4, (void*)data_ov060_0211b1f8[1], 0x40000000, 0x1000, 0);
    _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(((char*)this) + 0x174, (void*)data_ov060_0211b1f8[1], 0x40000000, 0x1000, 0);

    TextureSequence::Prepare(*(BMD_File*)data_ov060_0211b208[1], *(BTP_File*)data_ov060_0211b200[1]);
    TextureSequence::Prepare(*(BMD_File*)data_ov060_0211b208[1], *(BTP_File*)data_ov060_0211b200[1]);

    _ZN15TextureSequence7SetFileER8BTP_Filei5Fix12IiEj(((char*)this) + 0x138, (void*)data_ov060_0211b200[1], 0x40000000, 0x1000, 0);
    _ZN15TextureSequence7SetFileER8BTP_Filei5Fix12IiEj(((char*)this) + 0x1d8, (void*)data_ov060_0211b200[1], 0x40000000, 0x1000, 0);

    MaterialChanger::Prepare(*(BMD_File*)data_ov060_0211b208[1], *(BMA_File*)func_021115e4);
    MaterialChanger::Prepare(*(BMD_File*)data_ov060_0211b208[1], *(BMA_File*)func_021115e4);

    _ZN15MaterialChanger7SetFileER8BMA_Filei5Fix12IiEj(((char*)this) + 0x14c, func_021115e4, 0x40000000, 0x1000, 0);
    _ZN15MaterialChanger7SetFileER8BMA_Filei5Fix12IiEj(((char*)this) + 0x1ec, func_021115e4, 0x40000000, 0x1000, 0);

    _ZN18TextureTransformer7PrepareER8BMD_FileR8BTA_File((void*)data_ov060_0211b208[1], func_021115f4);
    _ZN18TextureTransformer7PrepareER8BMD_FileR8BTA_File((void*)data_ov060_0211b208[1], func_021115f4);

    _ZN18TextureTransformer7SetFileER8BTA_Filei5Fix12IiEj(((char*)this) + 0x160, func_021115f4, 0x40000000, 0x1000, 0);
    _ZN18TextureTransformer7SetFileER8BTA_Filei5Fix12IiEj(((char*)this) + 0x200, func_021115f4, 0x40000000, 0x1000, 0);

    unk_214 = 0;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN16BowserShockwaves8BehaviorEv, 0x02118eb8, size 0x14c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16BowserShockwaves8BehaviorEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int BowserShockwaves::Behavior()
{
  char* pl;
  unsigned int n;
  int d;
  int s;
  int m0, m1, m2, m3;
  ((*(unsigned short *)(((int)((char*)this) + 0x214))))++;
  pl = (char*)_ZN8dActor_c13ClosestPlayerEv(((char*)this));
  n = *(unsigned short*)(((char*)this)+0x200+0x14);
  s = n * 0x22;
  if(pl != 0 && n < 0x46 && *(unsigned char*)(pl+0x6de) == 0){
    d = Vec3_HorzDist(((char*)this)+0x5c, pl+0x5c);
    m0 = s*data_ov060_0211ab20[0];
    m1 = s*data_ov060_0211ab20[1];
    m2 = s*data_ov060_0211ab20[2];
    m3 = s*data_ov060_0211ab20[3];
    if((m0 < d && d < m1) || (m2 < d && d < m3)){
      _ZN6Player5ShockEj(pl, 1);
    }
  }
  _ZN9Animation7AdvanceEv((char*)&mTextureSequence1);
  _ZN9Animation7AdvanceEv((char*)&mTextureSequence2);
  _ZN9Animation7AdvanceEv((char*)&mMaterialChanger1);
  _ZN9Animation7AdvanceEv((char*)&mMaterialChanger2);
  _ZN9Animation7AdvanceEv((char*)&mTextureTransformer1);
  _ZN9Animation7AdvanceEv((char*)&mTextureTransformer2);
  _ZN9Animation7AdvanceEv((char*)(Animation *)&mModelAnim1);
  _ZN9Animation7AdvanceEv((char*)(Animation *)&mModelAnim2);
  Matrix4x3_FromTranslation(((char*)this)+0xf0, mPosX>>3, mPosY>>3, mPosZ>>3);
  Matrix4x3_FromTranslation(((char*)this)+0x190, mPosX>>3, mPosY>>3, mPosZ>>3);
  if(_ZN9Animation8FinishedEv((char*)(Animation *)&mModelAnim1)){
    _ZN7fBase_c18MarkForDestructionEv(((char*)this));
  }
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN16BowserShockwaves6RenderEv, 0x02118e1c, size 0x9c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16BowserShockwaves6RenderEv
/* recovered: named members + shared header, real C++ method
 *
 * Two shockwave rings, each with its own model and its own set of three
 * animators, updated in lockstep and then drawn.
 *
 * Every member was already typed in BowserShockwaves.h from the destructor's
 * call list, so the six `Update` calls are member calls now and the two
 * `ModelComponents` arguments -- the placeholder's `c + 0xdc` and `c + 0x17c`
 * -- are each the ring's own `mModelAnimN.data` at +0x08. That is what the
 * six stand-in structs at the top of this file were standing in for.
 *
 * THE TWO DRAW CALLS ARE VIRTUAL HERE, and that is the opposite of ov085.
 * daKinopio_c::Render and daPeach_c::Render call Model::Render through a direct
 * `bl` and need `mModelAnim.Model::Render(0)` to suppress the dispatch; this
 * one genuinely dispatches -- `ldr r,[r]` / `ldr r,[r,#0x14]` / `blx`, slot 5
 * of _ZTV5Model -- so the plain unqualified call is what matches, and
 * qualifying it costs four words.
 *
 * Both placeholders were honest about which: ov085's declared Render
 * non-virtual on a bare `Model`, this one declared a six-slot `Obj` with `m()`
 * at 0x14. The stand-in's SHAPE is evidence, not noise.
 *
 * The second ring is drawn at 0x800 on every axis -- half scale in 20.12 --
 * while the first takes a null scale and renders at its own size.
 */
int BowserShockwaves::Render()
{
    mTextureSequence1.Update(mModelAnim1.data);
    mTextureSequence2.Update(mModelAnim2.data);
    mMaterialChanger1.Update(mModelAnim1.data);
    mMaterialChanger2.Update(mModelAnim2.data);
    mTextureTransformer1.Update(mModelAnim1.data);
    mTextureTransformer2.Update(mModelAnim2.data);
    mModelAnim1.Render(0);
    Vector3 scale;
    scale.x = 0x800;
    scale.y = 0x800;
    scale.z = 0x800;
    mModelAnim2.Render(&scale);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN16BowserShockwaves16CleanupResourcesEv, 0x02118de0, size 0x3c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16BowserShockwaves16CleanupResourcesEv
/* recovered: shared header, real C++ method
 *
 * Three releases. The first, data_ov060_0211b208, is also released by
 * Bowser::CleanupResources -- the shockwave and the fight that spawns it each
 * hold a reference to the same file.
 */
int BowserShockwaves::CleanupResources()
{
    ((SharedFilePtr *)(&data_ov060_0211b208))->Release();
    ((SharedFilePtr *)(&data_ov060_0211b1f8))->Release();
    ((SharedFilePtr *)(&data_ov060_0211b200))->Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN16BowserShockwavesD1Ev, 0x02118cfc, size 0x68 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16BowserShockwavesD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body
 *
 * The hand-written version listed all eight member destructors and the vtable
 * store by hand. Declaring the layout in BowserShockwaves.h instead lets the
 * compiler emit every one of them, and the ROM's order is the evidence that the
 * declaration order is right: 0x200, 0x1ec, 0x1d8, 0x174, 0x160, 0x14c, 0x138,
 * 0x0d4 -- exactly reverse declaration order -- then dActor_c's base-object
 * destructor.
 *
 * Those eight separate calls are also why the two identical four-member groups are
 * eight members and not a two-element array: an array member is torn down through
 * the runtime's array-cleanup helper, not by eight literal offsets.
 */
BowserShockwaves::~BowserShockwaves()
{
}
