//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov027/ChillBully  (7 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021115c4  src/_ZN10ChillBullyD1Ev.cpp
 *   [1] 0x02111618  src/_ZN10ChillBullyD0Ev.cpp
 *   [2] 0x02111680  src/_ZN10ChillBully14UpdateRunStateEv.cpp
 *   [3] 0x021116f0  src/_ZN10ChillBully16UpdateDeathStateEv.cpp
 *   [4] 0x02111770  src/_ZN10ChillBully8BehaviorEv.cpp
 *   [5] 0x0211181c  src/_ZN10ChillBully13InitResourcesEv.cpp
 *   [6] 0x0211186c  src/ChillBully_Spawn.c
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "ChillBully.h"
#include "decl_common.h"
#include "decl_ActorBase.h"
#include "decl_Enemy.h"
#include "decl_ModelAnim.h"
#include "decl_dCcAc_c.h"
#include "decl_ShadowModel.h"
#include "decl_dBgCh_Actr.h"

extern "C" {
extern "C" int func_ov064_02116110(char *self, s16 step);
extern "C" int func_ov064_0211616c(void *self);
extern "C" int func_ov064_02116d1c(char *c);
extern int func_ov064_02116ec0(void *);
extern int _ZN8dActor_c9TrackStarEjj(void *, unsigned int, unsigned int);
extern int data_ov064_0211b768[];
extern int data_ov027_02113930[];
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- ChillBully_Spawn, 0x0211186c, size 0x5c */
/* -------------------------------------------------------------------------- */
// @symbol ChillBully_Spawn
/* recovered: vtable identified, declarations from a shared header */
/* recovered: vtable identified */
/* vtable identified: VT0 = data_ov064_0211b768 */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int *ChillBully_Spawn(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(1020);
    if (p) {
        _ZN12dEnemyBase_cC2Ev(p);
        p[0] = (int)data_ov064_0211b768;
        _ZN9ModelAnimC1Ev((char *)p + 0x110);
        _ZN10dBgCh_ActrC1Ev((char *)p + 0x174);
        _ZN7dCcAc_cC1Ev((char *)p + 0x33c);
        _ZN11ShadowModelC1Ev((char *)p + 0x370);
        p[0] = (int)data_ov027_02113930;
    }
    return p;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN10ChillBully13InitResourcesEv, 0x0211181c, size 0x50 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10ChillBully13InitResourcesEv
/* recovered: real C++ method -- vtable slot 0, previously func_ov027_0211181c
 *
 * daOts_c leaves slot 0 pure virtual (the word in its vtable is a literal zero), so
 * every one of its three children has to supply this. ChillBully's points the shared
 * file table at its own list and then claims a star slot.
 */
int ChillBully::InitResources()
{
    mFileTable = (int)data_ov027_021138f4;
    int r = func_ov064_02116ec0((char *)this);
    mStarIdx = param1 & 0xf;
    mStarSlot = _ZN8dActor_c9TrackStarEjj((char *)this, mStarIdx, 2);
    return r;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN10ChillBully8BehaviorEv, 0x02111770, size 0xac */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10ChillBully8BehaviorEv
/* recovered: real C++ method -- vtable slot 6, previously func_ov027_02111770
 *
 * daOts_c leaves slot 6 pure virtual, so each of its three children supplies its own.
 * ChillBully's is the star-carrying one: if an invincible character killed it, it
 * poofs, drops its star a little above itself, and marks itself for destruction;
 * otherwise it falls through to the shared behaviour in ov064.
 *
 * Every call below is a real method now, so the compiler mangles the names and the
 * signatures become falsifiable -- including UntrackAndSpawnStar's `s8 &`, which is
 * why mStarSlot is signed. See the long note on that symbol in dActor_c.h.
 */
int ChillBully::Behavior()
{
    int r = UpdateKillByInvincibleChar(mWithMeshClsn, mModelAnim, 0);
    if (r != 0) {
        if (r == 2) {
            Vector3 v;
            TriplePoofDust();
            v.x = mPosX;
            v.y = mPosY;
            v.z = mPosZ;
            v.y = v.y + 0x64000;
            UntrackAndSpawnStar(mStarSlot, (mStarIdx | 0x40) & 0xff, v, 4);
            MarkForDestruction();
        }
        return 1;
    }
    return func_ov064_02116d1c((char *)this);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN10ChillBully16UpdateDeathStateEv, 0x021116f0, size 0x80 */
/* -------------------------------------------------------------------------- */
void ChillBully::UpdateDeathState()
{
    int result = func_ov064_0211616c(this);
    if (result == 0)
        return;
    TriplePoofDust();
    Vector3 pos;
    pos.x = mPosX;
    pos.y = mPosY;
    pos.z = mPosZ;
    pos.y += 0x64000;
    UntrackAndSpawnStar(mStarSlot, (mStarIdx | 0x40) & 0xff, pos, 4);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN10ChillBully14UpdateRunStateEv, 0x02111680, size 0x70 */
/* -------------------------------------------------------------------------- */
int ChillBully::UpdateRunState()
{
    if (*(u16 *)&mStateTimer < 0xa) {
        mHorzSpeed = 0;
        int result = func_ov064_02116110((char *)this, 0x700);
        if (result != 0)
            return result;
        u16 *timer = (u16 *)&mStateTimer;
        if (*timer == 9)
            *timer = 0;
        return (int)timer;
    }
    mHorzSpeed = 0x14000;
    u16 *timer = (u16 *)&mStateTimer;
    u32 value = *timer;
    if (value > 0x23) {
        value = 0;
        *timer = 0;
    }
    return value;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN10ChillBullyD0Ev, 0x02111618, size 0x68 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10ChillBullyD0Ev
/* recovered: real C++ deleting destructor -- the compiler emits the whole body
 *
 * D0 is vtable slot 17: destroy through ChillBully, daOts_c's four members in
 * reverse declaration order, and dEnemyBase_c, then return the object to the
 * actor heap. The hand-written version spelled that out -- store the vtable
 * twice, call the four member destructors, chain to dEnemyBase_c, call
 * Memory::Deallocate. All of it comes from the same `~ChillBully()` the D1
 * file declares; the deallocation is the inline dEnemyBase_c::operator
 * delete, which is why nothing here mentions the heap.
 *
 * The identical body in both files is not duplication: D1 and D0 are two of
 * the three functions the compiler emits from one destructor, and each file
 * is bound to one of them by config/arm9/overlays/ov027/delinks.txt.
 */
/* One real destructor definition emits both the D1 and D0 requested by this
   manifest. The definition is kept with ROM ordinal 0 below. */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN10ChillBullyD1Ev, 0x021115c4, size 0x54 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10ChillBullyD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body
 *
 * Vtable slot 16, and previously func_ov027_021115c4. Two vtable stores and five
 * destructor calls, none of them written here: its own vptr, then daOts_c's --
 * inlined, because that class's destructor is defined in its class body -- then the
 * base's four members in reverse declaration order, then dEnemyBase_c. ChillBully adds no
 * member with a destructor of its own, only two bytes.
 *
 * Byte-for-byte the same shape as Bully's and BigBully's, which is what three
 * siblings sharing a base look like.
 */
