//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov064/daBDonketu_c  (7 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021174a0  src/_ZN12daBDonketu_cD1Ev.cpp
 *   [1] 0x021174f4  src/_ZN12daBDonketu_cD0Ev.cpp
 *   [2] 0x0211755c  src/_ZN12daBDonketu_c14UpdateRunStateEv.cpp
 *   [3] 0x021175cc  src/_ZN12daBDonketu_c16UpdateDeathStateEv.cpp
 *   [4] 0x0211764c  src/_ZN12daBDonketu_c6RenderEv.cpp
 *   [5] 0x02117684  src/_ZN12daBDonketu_c8BehaviorEv.cpp
 *   [6] 0x02117784  src/_ZN12daBDonketu_c13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daBDonketu_c.h"
#include "types.h"
#include "decl_common.h"
#include "dBgCh_Gnd.h"

extern "C" {
extern "C" int func_ov064_02116110(char *self, s16 step);
extern "C" int func_ov064_0211616c(void *self);
extern int _ZN5Sound15PlaySecretSoundEP8dActor_cPt(void* a, u16* p);
extern void _ZN12dEnemyBase_c12UpdateWMClsnER10dBgCh_Actrj(void* c, void* clsn, unsigned f);
extern int _ZNK10dBgCh_Actr10IsOnGroundEv(void* c);
extern int _ZN8dActor_c9TrackStarEjj(dActor_c* self, unsigned int a, unsigned int b);
extern dActor_c* _ZN8dActor_c5SpawnEjjRK7Vector3PK10Vector3_16as(u32 actorID, u32 param1, const Vector3* pos, const Vector3_16* rot, s8 areaID, s16 deathTableID);
extern s16 data_02082214[];
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN12daBDonketu_c13InitResourcesEv, 0x02117784, size 0x198 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBDonketu_c13InitResourcesEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daBDonketu_c::InitResources()
{
    int saved;

    *(void**)((char*)&mFileTable) = &data_ov064_0211b93c;
    saved = InitResourcesCommon();
    mStarID = param1 & 0xf;
    unk_3fd = (u8)_ZN8dActor_c9TrackStarEjj((dActor_c*)((char*)this), mStarID, 2);
    mSecretSoundCounter = 0;

    if ((param1 & 0xff00) == 0x100) {
        mNumBulliesKilled = 0;

        dBgCh_Gnd ground;
        Vector3 pos;
        Vector3 v;
        int i;
        int ang;

        {
            int tz = mPosZ;
            int ty = mPosY + 0x32000;
            int tx = mPosX;
            v.x = tx;
            v.y = ty;
            v.z = tz;
        }
        ground.SetObjAndPos(v, this);

        if (ground.DetectClsn() != 0) {
            pos.y = ground.clsnY;
        }

        i = 0;
        ang = 0;
        do {
            int idx = (u16)(s16)ang >> 4;
            dActor_c* spawned;

            pos.x = mPosX + data_02082214[idx * 2] * 500 - 0x64000;
            pos.z = mPosZ - data_02082214[idx * 2 + 1] * 500;

            spawned = _ZN8dActor_c5SpawnEjjRK7Vector3PK10Vector3_16as(0xd7, -1, &pos, (Vector3_16*)0, mAreaId, -1);
            if (spawned != 0) {
                *(int*)((char*)spawned + 0x3fc) = uniqueID;
            } else {
                return 0;
            }

            i++;
            ang += 0x5555;
        } while (i < 3);

        goto done;
    }

    mNumBulliesKilled = 0xff;
done:
    return saved;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN12daBDonketu_c8BehaviorEv, 0x02117684, size 0x100 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBDonketu_c8BehaviorEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daBDonketu_c::Behavior()
{
    u8 s = mNumBulliesKilled;
    if (s >= 4) {
        if (mSecretSoundCounter != 0) {
            if (_ZN5Sound15PlaySecretSoundEP8dActor_cPt(((char*)this), (u16*)((char*)&mSecretSoundCounter)) != 0)
                mSecretSoundCounter = 0;
        }
        return BehaviorCommon();
    }
    if (s == 3) {
        int t;
        int m;
        int* p;
        if (_ZN5Sound15PlaySecretSoundEP8dActor_cPt(((char*)this), (u16*)((char*)&mSecretSoundCounter)) != 0)
            mSecretSoundCounter = 0;
        t = mVertSpeed + mVertAccel;
        m = mTerminalVelocity;
        if (t >= m) m = t;
        mVertSpeed = m;
        p = (int*)(((int)((char*)this) + 0x60));
        *p = *p + mVertSpeed;
        _ZN12dEnemyBase_c12UpdateWMClsnER10dBgCh_Actrj(((char*)this), ((char*)this) + 0x174, 0);
        if (_ZNK10dBgCh_Actr10IsOnGroundEv((char*)&mWithMeshClsn) != 0) {
            u8* q;
            func_0200fa8c(((char*)this), 0);
            q = (u8*)(((int)((char*)this) + 0x3fe));
            *q = *q + 1;
        }
        func_ov064_02116bac(((char*)this));
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN12daBDonketu_c6RenderEv, 0x0211764c, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBDonketu_c6RenderEv
/* recovered: named members + shared header, real C++ method */
int daBDonketu_c::Render()
{
  if(mNumBulliesKilled >= 3)
    mModelAnim.Render(0);
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN12daBDonketu_c16UpdateDeathStateEv, 0x021175cc, size 0x80 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBDonketu_c16UpdateDeathStateEv
void daBDonketu_c::UpdateDeathState()
{
    int result = func_ov064_0211616c(this);
    if (result == 0)
        return;
    TriplePoofDust();
    Vector3 pos;
    pos.x = mPosX;
    pos.y = mPosY;
    pos.z = mPosZ;
    pos.y += 0x64000;
    UntrackAndSpawnStar(*(s8 *)&unk_3fd, (mStarID | 0x40) & 0xff, pos, 4);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN12daBDonketu_c14UpdateRunStateEv, 0x0211755c, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBDonketu_c14UpdateRunStateEv
int daBDonketu_c::UpdateRunState()
{
    if (*(u16 *)&mStateTimer < 0xa) {
        mHorzSpeed = 0;
        int result = func_ov064_02116110((char *)this, 0x700);
        if (result != 0)
            return result;
        u16 *timer = (u16 *)&mStateTimer;
        if (*timer == 9)
            *timer = 0;
        return (int)timer;
    }
    mHorzSpeed = 0x14000;
    u16 *timer = (u16 *)&mStateTimer;
    u32 value = *timer;
    if (value > 0x23) {
        value = 0;
        *timer = 0;
    }
    return value;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN12daBDonketu_cD1Ev, 0x021174a0, size 0x54 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBDonketu_cD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body
 *
 * Identical in shape to daDonketu_c's, and for the identical reason: `struct daBDonketu_c :
 * daOts_c` with no member of its own that has a destructor. Its own vptr, daOts_c's
 * inlined, the base's four members backwards, then dEnemyBase_c.
 */
daBDonketu_c::~daBDonketu_c()
{
}
