//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov072/daBgSnmHed_c  (19 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x0211ff34  src/_ZN12daBgSnmHed_cD1Ev.cpp
 *   [1] 0x0211ff7c  src/_ZN12daBgSnmHed_cD0Ev.cpp
 *   [2] 0x0211ffd8  src/_ZN12daBgSnmHed_c11UpdateModelEv.cpp
 *   [3] 0x0212001c  src/_ZN12daBgSnmHed_c6State3Ev.cpp
 *   [4] 0x02120180  src/_ZN12daBgSnmHed_c10InitState3Ev.cpp
 *   [5] 0x021201d4  src/_ZN12daBgSnmHed_c6State2Ev.cpp
 *   [6] 0x02120308  src/_ZN12daBgSnmHed_c10InitState2Ev.cpp
 *   [7] 0x02120358  src/_ZN12daBgSnmHed_c6State1Ev.cpp
 *   [8] 0x02120430  src/_ZN12daBgSnmHed_c10InitState1Ev.cpp
 *   [9] 0x02120450  src/_ZN12daBgSnmHed_c6State0Ev.cpp
 *   [10] 0x02120514  src/_ZN12daBgSnmHed_c10InitState0Ev.cpp
 *   [11] 0x02120560  src/_ZN12daBgSnmHed_c17CallStateBehaviorEv.cpp
 *   [12] 0x0212059c  src/_ZN12daBgSnmHed_c13CallStateInitEv.cpp
 *   [13] 0x021205d4  src/_ZN12daBgSnmHed_c8SetStateEi.cpp
 *   [14] 0x021205f0  src/_ZN12daBgSnmHed_c16CleanupResourcesEv.cpp
 *   [15] 0x02120634  src/_ZN12daBgSnmHed_c16OnPendingDestroyEv.cpp
 *   [16] 0x02120638  src/_ZN12daBgSnmHed_c6RenderEv.cpp
 *   [17] 0x0212066c  src/_ZN12daBgSnmHed_c8BehaviorEv.cpp
 *   [18] 0x0212069c  src/_ZN12daBgSnmHed_c13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daBgSnmHed_c.h"
#include "Player.h"
#include "SharedFilePtr.h"
/* decl_common.h deliberately NOT included: it declares data_ov072_02122bc4
 * and data_ov072_02121ffc as plain void*, contradicting the stronger,
 * evidenced SharedFilePtr spellings this TU carries from its legacy
 * sources. Anything else this TU needed from it is restated below. */
#include "TextureSequence.h"
#include "dBgCh_Gnd.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow struct 'SnowmanHeadVec3' */
struct SnowmanHeadVec3 {
    s32 x;
    s32 y;
    s32 z;
};

/* shadow struct 'BMD_File' */
struct BMD_File;

/* shadow struct 'BTP_File' */
struct BTP_File;

extern "C" {
extern "C" void Matrix4x3_FromRotationY(void *matrix, int angle);
void _ZN15TextureSequence7SetFileER8BTP_Filei5Fix12IiEj(
void *self, void *file, int flags, int speed, unsigned int startFrame);
extern int data_ov072_02122bcc[];
void _ZN8dActor_c10EarthquakeERK7Vector35Fix12IiE(
void *self, const void *pos, int magnitude);
int func_0201267c(int id, void *pos);
void _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(
unsigned int id, int x, int y, int z);
int _ZN5Sound7PlaySubEjjj5Fix12IiEb(
unsigned int soundID, unsigned int volume, unsigned int pan,
int distance, int loop);
unsigned char DecIfAbove0_Byte(unsigned char *value);
extern int data_ov072_02122bd4[];
extern "C" daBgSnmHed_c::StateFunc data_ov072_02122c00[];
extern SharedFilePtr data_ov072_02122bc4;
extern SharedFilePtr *data_ov072_02121ffc[];
extern void *_ZN5Model8LoadFileER13SharedFilePtr(void *ref);
extern void _ZN9ModelBase7SetFileEP8BMD_Fileii(void *base, void *file, int a, int b);
extern void *_ZN15TextureSequence8LoadFileER13SharedFilePtr(void *ref);
extern void _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj(void *t, void *a, int b, int c, unsigned int d, unsigned int e);
extern void _ZN10dBgCh_Actr4InitEP8dActor_c5Fix12IiES3_P10Vector3_16S5_(void *t, void *a, int b, int c, void *d, void *e);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 18 -- _ZN12daBgSnmHed_c13InitResourcesEv, 0x0212069c, size 0x138 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c13InitResourcesEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daBgSnmHed_c::InitResources()
{
    struct Vector3 pos;
    int i;

    _ZN9ModelBase7SetFileEP8BMD_Fileii(((char *)this) + 0xd4,
        _ZN5Model8LoadFileER13SharedFilePtr(&data_ov072_02122bc4), 1, -1);

    for (i = 0; i < 2; i++) {
        void *tex = data_ov072_02121ffc[i];
        _ZN15TextureSequence8LoadFileER13SharedFilePtr(tex);
        TextureSequence::Prepare(*(BMD_File *)((void **)&data_ov072_02122bc4)[1],
                                 *(BTP_File *)((void **)tex)[1]);
    }

    _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj(((char *)this) + 0x138, ((char *)this), 0x96000, 0x12c000, 0x800004, 0);
    mScaleX = 0x1800;
    mScaleY = 0x1800;
    mScaleZ = 0x1800;
    _ZN10dBgCh_Actr4InitEP8dActor_c5Fix12IiES3_P10Vector3_16S5_(((char *)this) + 0x16c, ((char *)this), 0x96000, 0x96000, 0, 0);

    pos.x = mPosX;
    pos.y = mPosY;
    pos.z = mPosZ;
    pos.y += 0x14000;
    dBgCh_Gnd ground;
    ground.SetObjAndPos(pos, 0);
    if (ground.DetectClsn() != 0)
        mPosY = ground.clsnY;
    else
        mPosY = pos.y;

    SetState(0);
    UpdateModel();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 17 -- _ZN12daBgSnmHed_c8BehaviorEv, 0x0212066c, size 0x30 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c8BehaviorEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
int daBgSnmHed_c::Behavior()
{
    CallStateBehavior();
    mCylinder.Clear();
    mCylinder.Update();
    UpdateModel();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 16 -- _ZN12daBgSnmHed_c6RenderEv, 0x02120638, size 0x34 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c6RenderEv
/* recovered: named members + shared header, real C++ method */
int daBgSnmHed_c::Render()
{
    mTextureSequence.Update(mModel.data);
    mModel.Render((Vector3 *)&mScaleX);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 15 -- _ZN12daBgSnmHed_c16OnPendingDestroyEv, 0x02120634, size 0x4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c16OnPendingDestroyEv
/* daBgSnmHed_c::OnPendingDestroy -- vtable slot 12. The ROM body is empty: the
 * override exists only to occupy the slot. */
void daBgSnmHed_c::OnPendingDestroy()
{
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 14 -- _ZN12daBgSnmHed_c16CleanupResourcesEv, 0x021205f0, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c16CleanupResourcesEv
/* daBgSnmHed_c::CleanupResources -- vtable slot 3. Releases one shared file, then
 * the two-entry table; it never touches `this`. The legacy C form declared its own
 * `struct SharedFilePtr { int data[4]; }` to type the table; spelled here as void *
 * so the file does not shadow the real class of that name. */
int daBgSnmHed_c::CleanupResources()
{
    data_ov072_02122bc4.Release();
    int r5 = 0;
    do {
        data_ov072_02121ffc[r5]->Release();
        r5++;
    } while (r5 < 2);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 13 -- _ZN12daBgSnmHed_c8SetStateEi, 0x021205d4, size 0x1c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c8SetStateEi
void daBgSnmHed_c::SetState(int state)
{
    mStateFuncs = data_ov072_02122c00 + state * 2;
    CallStateInit();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 12 -- _ZN12daBgSnmHed_c13CallStateInitEv, 0x0212059c, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c13CallStateInitEv
void daBgSnmHed_c::CallStateInit()
{
    StateFunc *func = mStateFuncs;
    (this->**func)();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 11 -- _ZN12daBgSnmHed_c17CallStateBehaviorEv, 0x02120560, size 0x3c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c17CallStateBehaviorEv
void daBgSnmHed_c::CallStateBehavior()
{
    StateFunc *func = mStateFuncs + 1;
    (this->**func)();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 10 -- _ZN12daBgSnmHed_c10InitState0Ev, 0x02120514, size 0x4c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c10InitState0Ev
int daBgSnmHed_c::InitState0()
{
    _ZN15TextureSequence7SetFileER8BTP_Filei5Fix12IiEj(
        &mTextureSequence, (void *)data_ov072_02122bd4[1], 0, 0x1000, 0);
    mVertAccel = 0;
    mTerminalVelocity = 0;
    mStateValue = 0;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- _ZN12daBgSnmHed_c6State0Ev, 0x02120450, size 0xc4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c6State0Ev
int ApproachLinear(short &value, short target, short step);
extern "C" int Vec3_HorzDist(const void *a, const void *b);
extern "C" unsigned char DecIfAbove0_Byte(unsigned char *value);

int daBgSnmHed_c::State0()
{
    ApproachLinear(mAngleY, -0x4000, 0x514);
    mTextureSequence.Advance();
    if (unk_336) {
        SetState(2);
        return 1;
    }
    if (DecIfAbove0_Byte(&mStateTimer) == 0) {
        Player *player = ClosestPlayer();
        if (Vec3_HorzDist((char *)this + 0x5c, (char *)player + 0x5c) < 0x118000
            && player->StartTalk(*this, true) != 0) {
            mTalkPlayer = player;
            SetState(1);
        }
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- _ZN12daBgSnmHed_c10InitState1Ev, 0x02120430, size 0x20 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c10InitState1Ev
int daBgSnmHed_c::InitState1()
{
    mSubstate = 0;
    mStateTimer = 0x96;
    mStateValue = 1;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- _ZN12daBgSnmHed_c6State1Ev, 0x02120358, size 0xd8 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c6State1Ev
extern "C" short Vec3_HorzAngle(const void *a, const void *b);

int daBgSnmHed_c::State1()
{
    switch (mSubstate) {
    case 0:
    {
        short angle = Vec3_HorzAngle((char *)this + 0x5c,
                                    (char *)mTalkPlayer + 0x5c);
        if (ApproachLinear(mAngleY, angle, 0x514)) {
            SnowmanHeadVec3 pos;
            pos.x = mPosX;
            pos.y = mPosY;
            pos.z = mPosZ;
            pos.y += 0xfa000;
            if (mTalkPlayer->ShowMessage(
                    *this, 0xaf, (Vector3 *)&pos, 0, 0))
                mSubstate++;
        }
        break;
    }
    case 1:
        if (mTalkPlayer->GetTalkState() == -1)
            SetState(0);
        break;
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN12daBgSnmHed_c10InitState2Ev, 0x02120308, size 0x50 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c10InitState2Ev
int daBgSnmHed_c::InitState2()
{
    mFlags &= ~1;
    mVertAccel = -0x2000;
    mTerminalVelocity = -0x3c000;
    mVertSpeed = 0x2d000;
    mStateTimer = 0x78;
    mSubstate = 0;
    mStateValue = 2;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN12daBgSnmHed_c6State2Ev, 0x021201d4, size 0x134 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c6State2Ev
int daBgSnmHed_c::State2()
{
    SnowmanHeadVec3 pos;
    switch (mSubstate) {
    case 0:
        UpdatePos(&mCylinder);
        if (mVertSpeed < 0 && mPosY < (int)0xffc427c0) {
            pos.x = mPosX;
            pos.y = mPosY;
            pos.z = mPosZ;
            _ZN8dActor_c10EarthquakeERK7Vector35Fix12IiE(
                this, &pos, 0x5dc000);
            func_0201267c(0x115, (char *)this + 0x74);
            _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(
                0x10f, mPosX, mPosY, mPosZ);
            _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(
                0x110, mPosX, mPosY, mPosZ);
            _ZN5Sound7PlaySubEjjj5Fix12IiEb(
                0x20, 0x14, 0x7f, 0x15666, 0);
            mSubstate++;
        }
        break;
    case 1:
        if (DecIfAbove0_Byte(&mStateTimer) == 0) {
            _ZN5Sound7PlaySubEjjj5Fix12IiEb(
                0x20, 0x7f, 0, 0x15666, 0);
            SetState(3);
        }
        break;
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN12daBgSnmHed_c10InitState3Ev, 0x02120180, size 0x54 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c10InitState3Ev
int daBgSnmHed_c::InitState3()
{
    _ZN15TextureSequence7SetFileER8BTP_Filei5Fix12IiEj(
        &mTextureSequence, (void *)data_ov072_02122bcc[1], 0, 0x1000, 0);
    mVertAccel = 0;
    mTerminalVelocity = 0;
    mSubstate = 0;
    mStateValue = 3;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN12daBgSnmHed_c6State3Ev, 0x0212001c, size 0x164 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c6State3Ev
extern "C" int Vec3_HorzDist(const void *a, const void *b);

int daBgSnmHed_c::State3()
{
    SnowmanHeadVec3 pos;
    pos.x = mPosX;
    pos.y = mPosY;
    pos.z = mPosZ;
    pos.y += 0x1c2000;

    switch (mSubstate) {
    case 0:
        mTalkPlayer = ClosestPlayer();
        if (Vec3_HorzDist((char *)this + 0x5c,
                          (char *)mTalkPlayer + 0x5c) < 0x118000) {
            if (mTalkPlayer->StartTalk(*this, true))
                mSubstate++;
        }
        break;
    case 1:
        if (mTalkPlayer->ShowMessage(
                *this, 0xb1, (Vector3 *)&pos, 0, 2))
            mSubstate++;
        break;
    case 2:
        if (mTalkPlayer->GetTalkState() == -1) {
            unsigned int param = (*(int *)&param1) & 0xf;
            param = param & 0xff;
            param |= 0x40;
            Spawn(0xb2, param, *(Vector3 *)((char *)this + 0x5c),
                  0, mAreaId, -1);
            mSubstate++;
        }
        break;
    }
    mTextureSequence.Advance();
    ApproachLinear(mAngleY, -0x4000, 0x514);
    mPosY = (int)0xffc427c0;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN12daBgSnmHed_c11UpdateModelEv, 0x0211ffd8, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_c11UpdateModelEv
void daBgSnmHed_c::UpdateModel()
{
    Matrix4x3_FromRotationY((char *)this + 0xf0, mAngleY);
    *(s32 *)((char *)this + 0x114) = mPosX >> 3;
    *(s32 *)((char *)this + 0x118) = (mPosY + 0x96000) >> 3;
    *(s32 *)((char *)this + 0x11c) = mPosZ >> 3;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN12daBgSnmHed_cD0Ev, 0x0211ff7c, size 0x5c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_cD0Ev
/* Real compiler-spelled deleting destructor. dActor_c's inline operator delete
 * supplies the actor-heap release after complete daBgSnmHed_c destruction. */
/* (no separate definition: the single ~daBgSnmHed_c() below emits the D0 and D1
 * variants together -- a hand-mangled D0 next to a real destructor is the
 * known mwccarm ICE, ELFgen.c:483.) */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN12daBgSnmHed_cD1Ev, 0x0211ff34, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daBgSnmHed_cD1Ev
/* Real compiler-spelled complete destructor. mwccarm synthesises reverse
 * member teardown and the dActor_c base chain from daBgSnmHed_c's layout. */
daBgSnmHed_c::~daBgSnmHed_c()
{
}
