//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov064/daDonketu_c  (10 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02117070  src/_ZN11daDonketu_cD1Ev.cpp
 *   [1] 0x021170c4  src/_ZN11daDonketu_cD0Ev.cpp
 *   [2] 0x0211712c  src/_ZN11daDonketu_c14PlayDeathSoundEv.cpp
 *   [3] 0x02117140  src/_ZN11daDonketu_c17PlayShellHitSoundEv.cpp
 *   [4] 0x02117154  src/_ZN11daDonketu_c12PlayHitSoundEv.cpp
 *   [5] 0x02117168  src/_ZN11daDonketu_c13PlayStepSoundEv.cpp
 *   [6] 0x021171b0  src/_ZN11daDonketu_c14UpdateRunStateEv.cpp
 *   [7] 0x02117220  src/_ZN11daDonketu_c16UpdateDeathStateEv.cpp
 *   [8] 0x02117310  src/_ZN11daDonketu_c8BehaviorEv.cpp
 *   [9] 0x02117424  src/_ZN11daDonketu_c13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daDonketu_c.h"
#include "common.h"
#include "daBDonketu_c.h"
#include "decl_common.h"

extern "C" {
extern "C" void func_0201267c(u32 soundID, const Vector3 *pos);
extern "C" int func_ov064_02116110(char *self, s16 step);
int RandomIntInternal(void *seed);
extern int data_0209e650;
int func_ov064_0211616c(void *self);
extern int _ZN12dEnemyBase_c26UpdateKillByInvincibleCharER10dBgCh_ActrR9ModelAnimj(
char *self, dBgCh_Actr *wm, ModelAnim *ma, unsigned int flags);
extern char *_ZN8dActor_c5SpawnEjjRK7Vector3PK10Vector3_16as(
unsigned int actorId, unsigned int param, const Vector3 *pos,
const Vector3s *rot, int areaId, int f);
extern char *_ZN8dActor_c10FindWithIDEj(unsigned int id);
/* TUBUILD CONFLICT -- alternate declaration of RandomIntInternal, from the legacy file for _ZN11daDonketu_c8BehaviorEv, NOT applied: extern int RandomIntInternal(void *seed); */
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- _ZN11daDonketu_c13InitResourcesEv, 0x02117424, size 0x20 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c13InitResourcesEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daDonketu_c::InitResources()
{
    mBigBullyID = 0;
    mFileTable = (int)&data_ov064_0211b834;
    InitResourcesCommon();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- _ZN11daDonketu_c8BehaviorEv, 0x02117310, size 0x114 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c8BehaviorEv
/* recovered: named members + shared header, real C++ method
 *
 * The bully's whole update is delegated: dEnemyBase_c::UpdateKillByInvincibleChar
 * decides, from the mesh collision and the animation, whether anything
 * happened this frame. 0 means nothing did and the real behaviour worker
 * runs; 1 means handled; 2 is the death case, and only that arm has a body.
 *
 * On death the bully drops a coin (actor 0x120, subtype 2) 0x136000 above
 * itself, facing its own heading turned 0x8000 (180 degrees) plus a random
 * 10-bit spread, then gives the coin an upward launch: 0xa000 of vertical
 * speed and 0x50000 of terminal velocity, with the two acceleration slots
 * zeroed. Finally it looks up the actor whose unique ID sits in mBigBullyID and
 * bumps the byte at +0x3fe of it. The field is left unnamed on purpose: what
 * the bytes establish is that it holds an actor ID, not what that actor is.
 *
 * mAreaId is passed to Spawn as the area, which is what pins the s8 read;
 * mPrevAngleY (not mAngleY) is the heading the coin inherits.
 *
 * THE POSITION TEMPORARIES ARE LOAD-BEARING. Collapsing them into
 * `pos.y = mPosY + 0x136000` and friends costs 9 words of 69: the ROM reads
 * y, then z, then x, and materialises the offset into its own register
 * before the add. Measured, not assumed -- the sibling substitutions in the
 * same sweep (the angle temporary, and the `(long long)` round-trip on the
 * tally) were both free and are gone.
 */
int daDonketu_c::Behavior()
{
    int ret = _ZN12dEnemyBase_c26UpdateKillByInvincibleCharER10dBgCh_ActrR9ModelAnimj(
        (char *)this, &mWithMeshClsn, &mModelAnim, 3);
    if (ret != 0) {
        if (ret == 2) {
            int y = mPosY;
            int yoff = 0x136000;
            int z = mPosZ;
            int x = mPosX;
            int sum = y + yoff;
            Vector3 pos;
            pos.x = x;
            pos.y = sum;
            pos.z = z;
            int r = RandomIntInternal(&data_0209e650);
            int yrot = mPrevAngleY + 0x8000 + (int)(((unsigned)r >> 8) & 0x3ff);
            Vector3s rot;
            rot.x = 0;
            rot.z = 0;
            rot.y = (s16)yrot;

            char *coin = _ZN8dActor_c5SpawnEjjRK7Vector3PK10Vector3_16as(
                0x120, 2, &pos, &rot, mAreaId, -1);
            if (coin) {
                *(int *)(coin + 0x98) = 0xa000;
                *(int *)(coin + 0xa4) = 0;
                *(int *)(coin + 0xa8) = 0x50000;
                *(int *)(coin + 0xac) = 0;
            }
            char *spawner = _ZN8dActor_c10FindWithIDEj(mBigBullyID);
            if (spawner) {
                (*(u8 *)(spawner + 0x3fe))++;
            }
        }
        return 1;
    }
    return BehaviorCommon();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- _ZN11daDonketu_c16UpdateDeathStateEv, 0x02117220, size 0xf0 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c16UpdateDeathStateEv
void daDonketu_c::UpdateDeathState()
{
    if (func_ov064_0211616c(this) == 0)
        return;
    int pz = mPosZ;
    int py = mPosY + 0x136000;
    int px = mPosX;
    Vector3 pos;
    pos.x = px;
    pos.y = py;
    pos.z = pz;
    int r = RandomIntInternal(&data_0209e650);
    Vector3_16 rot;
    s16 ang = (s16)(mPrevAngleY + 0x8000 + (((u32)r >> 8) & 0x3ff));
    rot.x = 0;
    rot.z = 0;
    rot.y = ang;
    dActor_c *coin = dActor_c::Spawn(0x120, 2, pos, &rot, mAreaId, -1);
    if (coin) {
        coin->mHorzSpeed = 0xa000;
        coin->unk_0a4 = 0;
        coin->mVertSpeed = 0x50000;
        coin->unk_0ac = 0;
    }
    dActor_c *spawner = dActor_c::FindWithID(mBigBullyID);
    if (spawner) {
        daBDonketu_c *bigBully = (daBDonketu_c *)spawner;
        bigBully->mNumBulliesKilled++;
    }
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN11daDonketu_c14UpdateRunStateEv, 0x021171b0, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c14UpdateRunStateEv
int daDonketu_c::UpdateRunState()
{
    if (*(u16 *)&mStateTimer < 0xa) {
        mHorzSpeed = 0;
        int result = func_ov064_02116110((char *)this, 0x700);
        if (result != 0)
            return result;
        u16 *timer = (u16 *)&mStateTimer;
        if (*timer == 9)
            *timer = 0;
        return (int)timer;
    }
    mHorzSpeed = 0xf000;
    u16 *timer = (u16 *)&mStateTimer;
    u32 value = *timer;
    if (value > 0x2c) {
        value = 0;
        *timer = 0;
    }
    return value;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN11daDonketu_c13PlayStepSoundEv, 0x02117168, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c13PlayStepSoundEv
void daDonketu_c::PlayStepSound()
{
    if (mModelAnim.WillHitFrame(4) == 0) {
        if (mModelAnim.WillHitFrame(7) == 0)
            return;
    }
    func_0201267c(0xca, (const Vector3 *)&mCamSpacePosX);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN11daDonketu_c12PlayHitSoundEv, 0x02117154, size 0x14 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c12PlayHitSoundEv
void daDonketu_c::PlayHitSound()
{
    func_0201267c(0xcb, (const Vector3 *)&mCamSpacePosX);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN11daDonketu_c17PlayShellHitSoundEv, 0x02117140, size 0x14 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c17PlayShellHitSoundEv
void daDonketu_c::PlayShellHitSound()
{
    func_0201267c(0xc9, (const Vector3 *)&mCamSpacePosX);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN11daDonketu_c14PlayDeathSoundEv, 0x0211712c, size 0x14 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_c14PlayDeathSoundEv
void daDonketu_c::PlayDeathSound()
{
    func_0201267c(0xc8, (const Vector3 *)&mCamSpacePosX);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN11daDonketu_cD1Ev, 0x02117070, size 0x54 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN11daDonketu_cD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body
 *
 * Two vtable stores and five destructor calls, none of them written here: its own
 * vptr, then daOts_c's -- inlined, because that class's destructor is defined in its
 * class body -- then the base's four members in reverse declaration order, then
 * dEnemyBase_c. daDonketu_c adds no member with a destructor of its own.
 *
 * The two stores in a row are the tell that a base destructor was inlined rather
 * than called, and they are what said daOts_c owns all four members.
 */
daDonketu_c::~daDonketu_c()
{
}
