//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov036/daObjRcCarpet_c  (8 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM build.
 *
 * RECONCILED. InitResources, Behavior, Render and CleanupResources are real
 * `daObjRcCarpet_c::` methods over the names include/daObjRcCarpet_c.h already
 * carried -- the generated file did not even include that header. The shadow
 * `Base`/`Derived`/`Obj`/`MMC` structs standing in for real vtables and layouts
 * are gone. What still spells a mangled name says why at its own line: four are
 * the by-value Fix12<int> wall (6az), and D0/D1 are the documented PathLift
 * destructor wall below.
 *
 * Still 8/8 MATCH, objisolate clean, reloc-destinations clean.
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02112158  src/_ZN15daObjRcCarpet_cD1Ev.cpp
 *   [1] 0x021121c8  src/_ZN15daObjRcCarpet_cD0Ev.cpp
 *   [2] 0x0211224c  src/func_ov036_0211224c.cpp
 *   [3] 0x021122c0  src/func_ov036_021122c0.cpp
 *   [4] 0x02112318  src/_ZN15daObjRcCarpet_c16CleanupResourcesEv.cpp
 *   [5] 0x02112378  src/_ZN15daObjRcCarpet_c6RenderEv.cpp
 *   [6] 0x021123c8  src/_ZN15daObjRcCarpet_c8BehaviorEv.cpp
 *   [7] 0x0211244c  src/_ZN15daObjRcCarpet_c13InitResourcesEv.cpp
 */

/* Includes: the real headers this TU's code calls into. */
#include "common.h"
#include "SharedFilePtr.h"
#include "dBgW.h"
#include "daObjRcCarpet_c.h"

/* What is left after reconciliation; each remaining mangled spelling says why. */
extern "C" {
extern int _ZTV15daObjRcCarpet_c[];
extern int data_ov002_0210af70[];
extern int _ZTV10dBgActor_c[];
void _ZN9ModelAnimD1Ev(void*);
void __destroy_arr(void*,int,int,void*);
void _ZN10dBgW_KcMbgD1Ev(void*);
void _ZN5ModelD1Ev(void*);
void _ZN8dActor_cD2Ev(void*);
extern void _ZN6Memory10DeallocateEPvP4Heap(void*, void*);
/* reconciled: dropped the void*[] spelling; the int[] declaration above is
 * the one the ROM convention uses and both uses cast explicitly anyway. */
extern void* data_020a0eac;
extern void Matrix4x3_FromRotationXYZExt(void*, short, short, short);
extern int data_ov002_0210d9f0[];
/* reconciled: `data_ov036_02113f58` was spelled `void*[]` in CleanupResources and
 * `int[]` in InitResources; both are 4-byte elements so indexing is identical.
 * Kept the `int[]` spelling below, matching every other data symbol here. */
extern int data_ov036_0211419c[];
extern void func_ov036_021122c0(char* c);
extern void func_ov036_0211224c(char* c);
extern void _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(void* t, int a, int b);
int _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(void*,int,int,int,unsigned);
int _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(void*,int,Matrix4x3*,int,int,void*);
void func_020393d4(void* p, void* v);
}

/* NOT extern "C": declared as ordinary C++ so the compiler produces
 * _Z14ApproachLinearRiii itself, the way include/SharedFilePtr.h argues for. */
void ApproachLinear(int &value, int target, int step);

extern "C" {
void func_ov002_020efaf0(void* c);
extern int data_ov036_02113f58[];
/* TUBUILD CONFLICT -- alternate declaration of _ZN9ModelAnimD1Ev, from the legacy file for _ZN15daObjRcCarpet_cD0Ev, NOT applied: extern void _ZN9ModelAnimD1Ev(void*); */
/* TUBUILD CONFLICT -- alternate declaration of __destroy_arr, from the legacy file for _ZN15daObjRcCarpet_cD0Ev, NOT applied: extern void __destroy_arr(void* arr, int count, int size, void(*dtor)(void*)); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN10dBgW_KcMbgD1Ev, from the legacy file for _ZN15daObjRcCarpet_cD0Ev, NOT applied: extern void _ZN10dBgW_KcMbgD1Ev(void*); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN5ModelD1Ev, from the legacy file for _ZN15daObjRcCarpet_cD0Ev, NOT applied: extern void _ZN5ModelD1Ev(void*); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN8dActor_cD2Ev, from the legacy file for _ZN15daObjRcCarpet_cD0Ev, NOT applied: extern void _ZN8dActor_cD2Ev(void*); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov036_021122c0, from the legacy file for _ZN15daObjRcCarpet_c13InitResourcesEv, NOT applied: void func_ov036_021122c0(char* c); */
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- _ZN15daObjRcCarpet_c13InitResourcesEv, 0x0211244c, size 0xec */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c13InitResourcesEv
// tu_create.py: the definition was inside an extern "C" block; the block was closed before it and the definition given explicit C linkage
int daObjRcCarpet_c::InitResources()
{
  char *c = (char *)this;
  Model::LoadFile(*(SharedFilePtr *)data_ov002_0210d9f0);
  void *m = Model::LoadFile(*(SharedFilePtr *)data_ov036_02113f58[0]);
  mModelAnim.SetFile((BMD_File *)m, 1, -1);
  Animation::LoadFile(*(SharedFilePtr *)data_ov036_0211419c);
  /* SetAnim takes a by-value Fix12<int> -- wall 6az, the same one
     include/ModelAnim.h records against its own declaration. */
  _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(&mModelAnim, data_ov036_0211419c[1], 0, 0x1000, 0);
  func_ov036_021122c0(c);
  UpdateClsnPosAndRot();
  char *k = dBgW_Kc::LoadFile(*(SharedFilePtr *)data_ov036_02113f58[1]);
  /* by-value Fix12<int> again -- wall 6az */
  _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
      &mMeshCollider, (int)k, &mClsnMat, 0x199, mAngleY, (void *)data_ov036_02113f58[2]);
  func_020393d4(&mMeshCollider, (void *)&dBgW::UpdatePosAndAngs);
  /* 0x440, 0x43c and 0x42c fall inside PathLift's unwitnessed padding
     (include/PathLift.h pad_42c) -- no field name exists to use yet. */
  *(int*)(c+0x440) = 0xa000;
  mHorzSpeed = *(int*)(c+0x440);
  func_ov002_020efaf0(c);
  *(int*)(c+0x43c) = 1;
  *(unsigned char*)(c+0x42c) = 1;
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN15daObjRcCarpet_c8BehaviorEv, 0x021123c8, size 0x84 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c8BehaviorEv
int daObjRcCarpet_c::Behavior()
{
    if (mAfterClsnRan != 0)
        ApproachLinear(unk_4bc, -0x14000, 0x5000);
    else
        ApproachLinear(unk_4bc, 0, 0x5000);
    BaseBehavior();
    mModelAnim.Animation::Advance();
    func_ov036_021122c0((char *)this);
    func_ov036_0211224c((char *)this);
    /* two by-value Fix12<int> -- wall 6az */
    _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(this, 0, 0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN15daObjRcCarpet_c6RenderEv, 0x02112378, size 0x50 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c6RenderEv
int daObjRcCarpet_c::Render()
{
    /* 0x428 is inside PathLift's pad_410 -- unnamed, so still a raw read. */
    u16 *blink = (u16 *)((char *)this + 0x428);
    if (*blink < 0x5a && (*blink & 1)) return 1;
    mModelAnim.Render(0);   /* the ROM's blx on primary-vtable slot 5 */
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN15daObjRcCarpet_c16CleanupResourcesEv, 0x02112318, size 0x60 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c16CleanupResourcesEv
// tu_create.py: the definition was inside an extern "C" block; the block was closed before it and the definition given explicit C linkage
int daObjRcCarpet_c::CleanupResources()
{
  if (mMeshCollider.IsEnabled())
    mMeshCollider.Disable();
  ((SharedFilePtr *)(data_ov002_0210d9f0))->Release();
  ((SharedFilePtr *)(data_ov036_02113f58[0]))->Release();
  ((SharedFilePtr *)(data_ov036_02113f58[1]))->Release();
  ((SharedFilePtr *)(data_ov036_0211419c))->Release();
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- func_ov036_021122c0, 0x021122c0, size 0x58 */
/* -------------------------------------------------------------------------- */
// tu_create.py: the definition was inside an extern "C" block; the block was closed before it and the definition given explicit C linkage
extern "C" void func_ov036_021122c0(char *c){
  Matrix4x3_FromRotationXYZExt(c+0x46c, *(short*)(c+0x8c), *(short*)(c+0x8e), *(short*)(c+0x90));
  *(int*)(c+0x490) = *(int*)(c+0x5c) >> 3;
  *(int*)(c+0x494) = (*(int*)(c+0x60) + *(int*)(c+0x4bc)) >> 3;
  *(int*)(c+0x498) = *(int*)(c+0x64) >> 3;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov036_0211224c, 0x0211224c, size 0x74 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov036_0211224c
/* recovered: shared common types */
// tu_create.py: the definition was inside an extern "C" block; the block was closed before it and the definition given explicit C linkage
extern "C" void func_ov036_0211224c(char* self){
    daObjRcCarpet_c *o = (daObjRcCarpet_c *)self;
    /* 0x46c is inside daObjRcCarpet_c's ModelAnim (mModelAnim.mat4x3 at
       0x450 + 0x1c); the destination is dBgActor_c::mClsnMat at 0x2ec, and
       0x310/0x314/0x318 are its translation row. */
    o->mClsnMat = o->mModelAnim.mat4x3;
    *(int*)(self+0x310) = o->mPosX;
    *(int*)(self+0x314) = o->mPosY + o->unk_4bc;
    *(int*)(self+0x318) = o->mPosZ;
    o->mMeshCollider.Transform(o->mClsnMat, o->mAngleY);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN15daObjRcCarpet_cD0Ev, 0x021121c8, size 0x84 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_cD0Ev
/* recovered: vtable identified, declarations from a shared header. Same wall as
 * src/_ZN15daObjRcCarpet_cD1Ev.cpp: hand-written under the mangled D0 name
 * rather than a real `delete` expression, matching include/daObjPathLift_c.h's
 * precedent for a PathLift-derived class. */
// tu_create.py: the definition was inside an extern "C" block; the block was closed before it and the definition given explicit C linkage
extern "C" void* _ZN15daObjRcCarpet_cD0Ev(char* p){
  *(void***)p = (void**)_ZTV15daObjRcCarpet_c;
        /* NO `+ 2` here, unlike PoleLift/Squasher.  Those TUs are real C++ classes and
        * mwcc EMITS their `_ZTV`, so the symbol sits at the vtable object's start and
        * the store needs +8 to reach slot 0.  This TU has no class definition: the
        * object leaves `_ZTV15daObjRcCarpet_c` UNDEF and config/.../ov036/symbols.txt
        * already binds it to the slot array (0x02113f9c), which is exactly what the
        * ROM's reloc at 0x021121b8 targets.  Addend must be 0.
        * `verify` cannot see this -- match.compare wildcards a relocated word and
        * objisolate passed the addend-8 UNDEF -- only `linkcheck` catches it. */
  _ZN9ModelAnimD1Ev(p+0x450);
  *(void***)p = (void**)data_ov002_0210af70;
  __destroy_arr(p+0x320, 3, 0x50, _ZN5ModelD1Ev);
  *(void***)p = (void**)_ZTV10dBgActor_c;
  _ZN10dBgW_KcMbgD1Ev(p+0x124);
  _ZN5ModelD1Ev(p+0xd4);
  _ZN8dActor_cD2Ev(p);
  _ZN6Memory10DeallocateEPvP4Heap(p, data_020a0eac);
  return p;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN15daObjRcCarpet_cD1Ev, 0x02112158, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_cD1Ev
/* recovered: vtable identified, declarations from a shared header
 *
 * NOT a real out-of-line `daObjRcCarpet_c::~daObjRcCarpet_c()`: PathLift's own
 * destructor (include/PathLift.h) is genuinely out-of-line -- unlike
 * dBgActor_c's, which is inline on purpose precisely so every subclass inlines
 * it -- so a real derived-class destructor would call `_ZN8PathLiftD2Ev`, a
 * symbol that does not exist in the ROM. The ROM instead inlines PathLift's
 * own cleanup directly here, exactly as this free function under the mangled
 * D1 name reproduces (the same wall include/daObjPathLift_c.h's own D1 already
 * documents). `virtual ~daObjRcCarpet_c();` in the header stays a declaration
 * only -- nothing ever calls it through a real `delete`, so the linker never
 * needs a body, matching the never-define-the-key-function idiom in
 * include/dActor_c.h.
 */
extern "C" int _ZN15daObjRcCarpet_cD1Ev(char* c){
  *(int**)c=(int*)_ZTV15daObjRcCarpet_c;   /* no +2 -- see the note in D0Ev */
  _ZN9ModelAnimD1Ev(c+0x450);
  *(int**)c=(int*)data_ov002_0210af70;
  __destroy_arr(c+0x320,3,0x50,(void*)_ZN5ModelD1Ev);
  *(int**)c=(int*)_ZTV10dBgActor_c;
  _ZN10dBgW_KcMbgD1Ev(c+0x124);
  _ZN5ModelD1Ev(c+0xd4);
  _ZN8dActor_cD2Ev(c);
  return (int)c;
}
