//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov036/daObjRcCarpet_c  (9 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02112158  src/game/actors/daObjRcCarpet_c/_ZN15daObjRcCarpet_cD1Ev.cpp
 *   [1] 0x021121c8  src/game/actors/daObjRcCarpet_c/_ZN15daObjRcCarpet_cD0Ev.cpp
 *   [2] 0x0211224c  src/unnamed/ov036/0211/func_ov036_0211224c.cpp
 *   [3] 0x021122c0  src/unnamed/ov036/0211/func_ov036_021122c0.cpp
 *   [4] 0x02112318  src/game/actors/daObjRcCarpet_c/_ZN15daObjRcCarpet_c16CleanupResourcesEv.cpp
 *   [5] 0x02112378  src/game/actors/daObjRcCarpet_c/_ZN15daObjRcCarpet_c6RenderEv.cpp
 *   [6] 0x021123c8  src/game/actors/daObjRcCarpet_c/_ZN15daObjRcCarpet_c8BehaviorEv.cpp
 *   [7] 0x0211244c  src/game/actors/daObjRcCarpet_c/_ZN15daObjRcCarpet_c13InitResourcesEv.cpp
 *   [8] 0x02112538  src/game/actors/FlyingCarpet/FlyingCarpet_Spawn.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daObjRcCarpet_c.h"
#include "SharedFilePtr.h"
#include "dBgW.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow struct 'Base' */
struct Base { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void m(int); };

/* shadow struct 'Derived' */
struct Derived { char pad[0x428]; unsigned short fld; char pad2[0x450-0x42a]; Base base; };

extern "C" {
extern int _ZTV15daObjRcCarpet_c[];
extern int data_ov002_0210af70[];
extern int _ZTV10dBgActor_c[];
void _ZN9ModelAnimD1Ev(void*);
void __destroy_arr(void*,int,int,void(*)(void*));   /* reconciled: fn-ptr-typed 4th arg wins over the bare void* form */
void _ZN10dBgW_KcMbgD1Ev(void*);
void _ZN5ModelD1Ev(void*);
void _ZN8dActor_cD2Ev(void*);
extern int data_ov002_0210d9f0[];
extern void* data_ov036_02113f58[];
extern int data_ov036_0211419c[];
/* SetAnim and dBgW_KcMbg::SetFile carry by-value Fix12<int> parameters.
Their faithful member declarations trigger mwccarm's stack-homing ABI and
do not reproduce these call sites, so keep the verified scalar shims. */
int _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(void*,int,int,int,unsigned);
int _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(void*,int,void*,int,int,void*);
void func_020393d4(void* p, void* v);
void func_ov002_020efaf0(void* c);
void func_ov036_021122c0(char *self);   /* reconciled: matches the real definition's char* param */
extern void *data_ov036_02113f58[];
extern void _ZN4dBgW16UpdatePosAndAngsERS_P8dActor_cR5dBgPiR7Vector3P10Vector3_16S8_();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- FlyingCarpet_Spawn, 0x02112538, size 0x78 */
/* -------------------------------------------------------------------------- */
extern "C" {
void* _ZN7fBase_cnwEj(unsigned int);
void _ZN10dBgActor_cC2Ev(void*);
void func_020733a8(void*, int, int, void*, void*);
void _ZN7PathPtrC1Ev(void*);
void _ZN9ModelAnimC1Ev(void*);
extern int data_ov002_0210af70[];
extern int _ZTV15daObjRcCarpet_c[];
void _ZN5ModelD1Ev(void*);
void _ZN5ModelC1Ev(void*);
/* Factory for daObjRcCarpet_c (include/daObjRcCarpet_c.h): still hand-rolled,
   not `return new daObjRcCarpet_c()`, matching the daObjPathLift_c precedent
   (#1589) -- the PathPtr constructed at c+0x430 sits inside PathLift's own
   generic tail padding, not in any derived class's own storage, so the real
   compiler-synthesised constructor cannot place it there. */
void* FlyingCarpet_Spawn(void){
  char* c = (char*)_ZN7fBase_cnwEj(0x4c0);
  if(c){
    _ZN10dBgActor_cC2Ev(c);
    *(int*)c = (int)data_ov002_0210af70;
    func_020733a8(c+0x320, 3, 0x50, (void*)_ZN5ModelC1Ev, (void*)_ZN5ModelD1Ev);
    _ZN7PathPtrC1Ev(c+0x430);
    *(int*)c = (int)_ZTV15daObjRcCarpet_c;
    _ZN9ModelAnimC1Ev(c+0x450);
  }
  return c;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- _ZN15daObjRcCarpet_c13InitResourcesEv, 0x0211244c, size 0xec */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c13InitResourcesEv
int daObjRcCarpet_c::InitResources() {
  Model::LoadFile(*(SharedFilePtr *)data_ov002_0210d9f0);
  void *modelFile = Model::LoadFile(*(SharedFilePtr *)data_ov036_02113f58[0]);
  mModelAnim.SetFile((BMD_File *)modelFile, 1, -1);
  Animation::LoadFile(*(SharedFilePtr *)data_ov036_0211419c);
  _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(&mModelAnim, data_ov036_0211419c[1], 0, 0x1000, 0);
  func_ov036_021122c0((char*)this);
  UpdateClsnPosAndRot();
  void *clsnFile = dBgW_Kc::LoadFile(*(SharedFilePtr *)data_ov036_02113f58[1]);
  _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
      &mMeshCollider, (int)clsnFile, &mClsnMat, 0x199, mAngleY,
      data_ov036_02113f58[2]);
  func_020393d4(&mMeshCollider, (void*)_ZN4dBgW16UpdatePosAndAngsERS_P8dActor_cR5dBgPiR7Vector3P10Vector3_16S8_);
  *(int*)((char*)this + 0x440) = 0xa000;
  mHorzSpeed = *(int*)((char*)this + 0x440);
  func_ov002_020efaf0(this);
  *(int*)((char*)this + 0x43c) = 1;
  *(unsigned char*)((char*)this + 0x42c) = 1;
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN15daObjRcCarpet_c8BehaviorEv, 0x021123c8, size 0x84 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c8BehaviorEv
int ApproachLinear(int &value, int target, int step);
extern "C" {
extern void func_ov036_021122c0(char *self);
extern void func_ov036_0211224c(char *self);
/* The true signature carries two by-value Fix12<int> parameters, which mwccarm
   homes to the stack. Keep the verified scalar ABI spelling (runbook wall 6az). */
extern void _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(void* t, int a, int b);
}

int daObjRcCarpet_c::Behavior() {
    if (mAfterClsnRan != 0)
        ApproachLinear(unk_4bc, -0x14000, 0x5000);
    else
        ApproachLinear(unk_4bc, 0, 0x5000);
    BaseBehavior();
    mModelAnim.Advance();
    func_ov036_021122c0((char*)this);
    func_ov036_0211224c((char*)this);
    _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(this, 0, 0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN15daObjRcCarpet_c6RenderEv, 0x02112378, size 0x50 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c6RenderEv
/* daObjRcCarpet_c::Render -- vtable slot 9. Real C++ method over the shared
 * header; the u16 at +0x428 (PathLift's tail-padding, read by raw offset) and
 * the Model sub-object at +0x450 keep the recovered layout. */
int daObjRcCarpet_c::Render() {
    Derived *d = (Derived *)this;
    if (d->fld < 0x5a && (d->fld & 1)) return 1;
    Base *b = &d->base; b->m(0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN15daObjRcCarpet_c16CleanupResourcesEv, 0x02112318, size 0x60 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_c16CleanupResourcesEv
/* daObjRcCarpet_c::CleanupResources() -- vtable slot 3. Real C++ method over
 * the shared header. The dBgW at +0x124 is PathLift's, read by raw offset (the
 * header does not name it), and the SharedFilePtr globals are released. */
int daObjRcCarpet_c::CleanupResources(){
  if (((dBgW *)((char*)this+0x124))->IsEnabled())
    ((dBgW *)((char*)this+0x124))->Disable();
  ((SharedFilePtr *)(data_ov002_0210d9f0))->Release();
  ((SharedFilePtr *)(data_ov036_02113f58[0]))->Release();
  ((SharedFilePtr *)(data_ov036_02113f58[1]))->Release();
  ((SharedFilePtr *)(data_ov036_0211419c))->Release();
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- func_ov036_021122c0, 0x021122c0, size 0x58 */
/* -------------------------------------------------------------------------- */
extern "C" {
extern void Matrix4x3_FromRotationXYZExt(void*, short, short, short);
void func_ov036_021122c0(char *c){
  Matrix4x3_FromRotationXYZExt(c+0x46c, *(short*)(c+0x8c), *(short*)(c+0x8e), *(short*)(c+0x90));
  *(int*)(c+0x490) = *(int*)(c+0x5c) >> 3;
  *(int*)(c+0x494) = (*(int*)(c+0x60) + *(int*)(c+0x4bc)) >> 3;
  *(int*)(c+0x498) = *(int*)(c+0x64) >> 3;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov036_0211224c, 0x0211224c, size 0x74 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov036_0211224c
/* recovered: shared common types.
 *
 * LOCAL STRUCT COLLISION (decomp-tu-slicing / tu-cpp-census sec 6): the
 * standalone legacy file's own `#include "common.h"` defined `Matrix4x3` as
 * the flat `struct { s32 m[12]; }` under MATRIX4X3_DEFINED. In this merged
 * TU, daObjRcCarpet_c.h (via ModelAnim.h) pulls in math/Matrix.h FIRST,
 * which claims that same guard with a richer Matrix3x3-embedding type --
 * so this file's own `#include "common.h"` below is a silent no-op and
 * `Matrix4x3` here would resolve to the wrong type, scalarizing the
 * `o->m = *(...)` block copy and costing 0x18 bytes (0x8c vs the ROM's
 * 0x74). Use a private flat-array alias for the copy instead of fighting
 * include order (see decomp-cpp-class-form: "copy through a struct whose
 * only member is an array").
 */
#include "common.h"
extern "C" {

struct MMC { char p[0x124]; };
struct M4x3Flat { s32 m[12]; };   /* local flat alias -- see note above */
struct Obj { char p[0x2ec]; M4x3Flat m; };
int _ZN10dBgW_KcMbg9TransformERK9Matrix4x3s(MMC*, Matrix4x3&, short);
void func_ov036_0211224c(char* self){
    Obj* o = (Obj*)self;
    o->m = *(M4x3Flat*)(self + 0x46c);
    *(int*)(self+0x310) = *(int*)(self+0x5c);
    *(int*)(self+0x314) = *(int*)(self+0x60) + *(int*)(self+0x4bc);
    *(int*)(self+0x318) = *(int*)(self+0x64);
    _ZN10dBgW_KcMbg9TransformERK9Matrix4x3s((MMC*)(self+0x124), *(Matrix4x3*)&o->m, *(short*)(self+0x8e));
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN15daObjRcCarpet_cD0Ev, 0x021121c8, size 0x84 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_cD0Ev
/* recovered: vtable identified, declarations from a shared header. Same wall as
 * src/game/actors/daObjRcCarpet_c/_ZN15daObjRcCarpet_cD1Ev.cpp: hand-written under the mangled D0 name
 * rather than a real `delete` expression, matching include/daObjPathLift_c.h's
 * precedent for a PathLift-derived class. */
extern "C" {
/* _ZN9ModelAnimD1Ev, __destroy_arr, _ZN10dBgW_KcMbgD1Ev, _ZN5ModelD1Ev,
 * _ZTV15daObjRcCarpet_c, data_ov002_0210af70, _ZTV10dBgActor_c already
 * declared at file scope above; NOT re-declared here (a redeclaration with a
 * conflicting type -- these were void*[]/void* vs the file-scope int[]/
 * fn-ptr forms -- is a hard error, not an overload). */
extern void _ZN8dActor_cD2Ev(void*);
extern void _ZN6Memory10DeallocateEPvP4Heap(void*, void*);
extern void* data_020a0eac;


void* _ZN15daObjRcCarpet_cD0Ev(char* p){
  *(int**)p = (int*)_ZTV15daObjRcCarpet_c;
  _ZN9ModelAnimD1Ev(p+0x450);
  *(int**)p = (int*)data_ov002_0210af70;
  __destroy_arr(p+0x320, 3, 0x50, _ZN5ModelD1Ev);
  *(int**)p = (int*)_ZTV10dBgActor_c;
  _ZN10dBgW_KcMbgD1Ev(p+0x124);
  _ZN5ModelD1Ev(p+0xd4);
  _ZN8dActor_cD2Ev(p);
  _ZN6Memory10DeallocateEPvP4Heap(p, data_020a0eac);
  return p;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN15daObjRcCarpet_cD1Ev, 0x02112158, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN15daObjRcCarpet_cD1Ev
/* recovered: vtable identified, declarations from a shared header
 *
 * NOT a real out-of-line `daObjRcCarpet_c::~daObjRcCarpet_c()`: PathLift's own
 * destructor (include/PathLift.h) is genuinely out-of-line -- unlike
 * dBgActor_c's, which is inline on purpose precisely so every subclass inlines
 * it -- so a real derived-class destructor would call `_ZN8PathLiftD2Ev`, a
 * symbol that does not exist in the ROM. The ROM instead inlines PathLift's
 * own cleanup directly here, exactly as this free function under the mangled
 * D1 name reproduces (the same wall include/daObjPathLift_c.h's own D1 already
 * documents). `virtual ~daObjRcCarpet_c();` in the header stays a declaration
 * only -- nothing ever calls it through a real `delete`, so the linker never
 * needs a body, matching the never-define-the-key-function idiom in
 * include/dActor_c.h.
 */
extern "C" int _ZN15daObjRcCarpet_cD1Ev(char* c){
  *(int**)c=(int*)_ZTV15daObjRcCarpet_c;
  _ZN9ModelAnimD1Ev(c+0x450);
  *(int**)c=(int*)data_ov002_0210af70;
  __destroy_arr(c+0x320,3,0x50,_ZN5ModelD1Ev);
  *(int**)c=(int*)_ZTV10dBgActor_c;
  _ZN10dBgW_KcMbgD1Ev(c+0x124);
  _ZN5ModelD1Ev(c+0xd4);
  _ZN8dActor_cD2Ev(c);
  return (int)c;
}
