//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov062/daRFlag_c  (8 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x0211af38  src/_ZN9daRFlag_cD1Ev.cpp
 *   [1] 0x0211af70  src/_ZN9daRFlag_cD0Ev.c
 *   [2] 0x0211afbc  src/func_ov062_0211afbc.c
 *   [3] 0x0211b000  src/_ZN9daRFlag_c16CleanupResourcesEv.c
 *   [4] 0x0211b030  src/_ZN9daRFlag_c6RenderEv.cpp
 *   [5] 0x0211b05c  src/_ZN9daRFlag_c8BehaviorEv.cpp
 *   [6] 0x0211b168  src/_ZN9daRFlag_c13InitResourcesEv.cpp
 *   [7] 0x0211b208  src/daRFlag_c_classInit.c
 *
 * plus the .data run 0x0211dc18..0x0211dcd0 this TU also owns: _ZTS and _ZTI
 * for the class, g_profile_RACE_FLAG, and the 31-slot dActor_c-shaped vtable
 * whose 0x0211dc54 address point the factory installs.  tu_map splits the
 * unlabelled factory into a TU of its own; the manifest is extended over it by
 * hand, which config/tu_manifest.d/ov062/daRFlag_c.json records under
 * boundary_evidence.
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "ModelAnim.h"
#include "decl_Actor.h"
#include "decl_ModelAnim.h"
#include "decl_dCcAc_c.h"
#include "decl_common.h"
#include "daRFlag_c.h"
#include "decl_Timer.h"
#include "decl_ActorBase.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* No shadow dActor_c/dCcAc_c/daRFlag_c here: include/daRFlag_c.h is the real
 * view of this class, and it is what the promoted file must compile against.
 * The header declares the inline `virtual ~daRFlag_c() {}` FIRST among the
 * virtuals, so this TU emits exactly the ROM's D1/D0 pair in the ROM's order
 * and no homeless D2 -- the earlier out-of-line destructor here is what put
 * D0 before D1 and left six unlicensed symbols behind. */
extern "C" void _ZN6Memory10DeallocateEPvP4Heap(void *, void *);
extern "C" void *data_020a0eac;

/* shadow struct 'Base' */
struct Base { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void m(int); };

/* shadow struct 'Derived' */
struct Derived { char pad[0x108]; Base base; };

/* shadow struct 'SharedFilePtr' */
struct SharedFilePtr;

/* shadow struct 'BMD_File' */
struct BMD_File;

/* shadow struct 'BCA_File' */
struct BCA_File;

/* TUBUILD CONFLICT -- alternate body of struct 'dCcAc_c', from the legacy file for _ZN9daRFlag_c13InitResourcesEv, NOT applied:
struct dCcAc_c {
    void Init(dActor_c* a, Fix12i b, Fix12i c, unsigned int d, unsigned int e);
};
*/

extern "C" {
extern void *data_020a0eac;
extern void Matrix4x3_FromRotationY(void *, int);
extern void _ZN13SharedFilePtr7ReleaseEv(void *);
extern int data_ov062_0211e0d4[];
extern int data_ov062_0211e0dc[];
extern char *_ZN8dActor_c10FindWithIDEj(unsigned int id);
extern int _ZN5Sound7PlaySubEjjj5Fix12IiEb(unsigned int a, unsigned int b, unsigned int c, int d, int e);
extern void _ZN9Animation7AdvanceEv(void *a);
extern void _ZN5dCc_c5ClearEv(void *c);
extern void _ZN5dCc_c6UpdateEv(void *c);
extern char data_0209d4c8[];
extern "C" void _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(void *, BCA_File* f, int a, Fix12i b, unsigned int c);
extern "C" void _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj(void *, dActor_c* a, Fix12i b, Fix12i c, unsigned int d, unsigned int e);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- daRFlag_c_classInit, 0x0211b208, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol daRFlag_c_classInit
/* recovered: vtable identified, globals resolved, declarations from a shared header */
/* recovered: vtable identified, globals resolved */
/* resolved: VT0 = _ZTV9daRFlag_c */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int *daRFlag_c_classInit(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(372);
    if (p) {
        _ZN8dActor_cC2Ev(p);
        p[0] = (int)&_ZTV9daRFlag_c[2]; /* +8: this TU defines the vtable */
        _ZN7dCcAc_cC1Ev((char *)p + 0xd4);
        _ZN9ModelAnimC1Ev((char *)p + 0x108);
    }
    return p;
}
}

/* The 0x1c spawn descriptor at ov062 0x0211dc30, emitted right after the
 * factory it points at.  Field order and widths are the actor_profile_0x1c
 * layout the recovered fBase_c/dActor_c constructors read. */
struct RFlagSpawnInfo {
    int *(*classInit)();
    s16 profileIDAndExecuteOrder;
    s16 drawOrder;
    u32 actorFlags;
    s32 clipOffsetY;
    s32 clipRadius;
    s32 clipDistance;
    s32 farDistance;
};
typedef char RFlagSpawnInfo_size_must_be_0x1c[sizeof(RFlagSpawnInfo) == 0x1c ? 1 : -1];

// @symbol g_profile_RACE_FLAG
extern "C" RFlagSpawnInfo g_profile_RACE_FLAG = {
    daRFlag_c_classInit, 0x00cd, 0x001e, 0x00000002,
    0x00190000, 0x00190000, 0x013e8000, 0x013e8000
};

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN9daRFlag_c13InitResourcesEv, 0x0211b168, size 0xa0 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9daRFlag_c13InitResourcesEv
/* recovered: named members + shared header, real C++ method */
/* Model / ModelBase / Animation / ModelAnim are the real classes now, through
   this actor's header. */
/* Signature deliberately copied from the local declaration above: the
   ROM name carries by-value class parameters (e.g. Fix12<int>), which
   mwccarm passes differently at the call site, so declaring the true
   types breaks the byte match. See notes/mwccarm-codegen.md 6az. */
/* Signature deliberately copied from the local declaration above: the
   ROM name carries by-value class parameters (e.g. Fix12<int>), which
   mwccarm passes differently at the call site, so declaring the true
   types breaks the byte match. See notes/mwccarm-codegen.md 6az. */
int daRFlag_c::InitResources()
{
    ((ModelBase*)((char*)&mModelAnim))->SetFile(
        (BMD_File*)Model::LoadFile(*(SharedFilePtr*)data_ov062_0211e0d4), 1, -1);
    _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj((ModelAnim*)((char*)&mModelAnim), (BCA_File*)Animation::LoadFile(*(SharedFilePtr*)data_ov062_0211e0dc), 0, 0x1000, 0);
    _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj((dCcAc_c*)((char*)&mdCcAc_c), (dActor_c*)((char*)this), 0x35555, 0x294000, 0x280000c, 0);
    mHasTouchedFlag = 0xff;
    mVictoryTimer = 0;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN9daRFlag_c8BehaviorEv, 0x0211b05c, size 0x10c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9daRFlag_c8BehaviorEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daRFlag_c::Behavior()
{
    unsigned int id;
    char *a;
    int b;

    if (mHasTouchedFlag == 0) {
        /* 0xf8 lies inside the real dCcAc_c member, which has no name for it. */
        id = *(unsigned int *)((char *)this + 0xf8);
        if (id != 0) {
            a = _ZN8dActor_c10FindWithIDEj(id);
            if (a != 0) {
                b = *(unsigned short *)(a + 0xC);
                b = b == 0xBF;
                if (b) {
                    mHasTouchedFlag = 1;
                    _ZN5Timer9StopTimerEv(data_0209d4c8);
                    mVictoryTimer = 1;
                    _ZN5Sound7PlaySubEjjj5Fix12IiEb(0x1F, 0x14, 0x7F, 0x6B000, 0);
                }
            }
        }
    }

    if (mVictoryTimer != 0) {
        *(unsigned short *)(((int)((char *)this) + 0x16C)) += 1;
        if (mVictoryTimer >= 0x5A) {
            if (_ZN5Sound7PlaySubEjjj5Fix12IiEb(0x1F, 0x7F, 0, 0x8777, 0) != 0) {
                mVictoryTimer = 0;
            }
        }
    }

    _ZN9Animation7AdvanceEv((char *)(Animation *)&mModelAnim);
    func_ov062_0211afbc(((char *)this));
    _ZN5dCc_c5ClearEv((char *)&mdCcAc_c);
    _ZN5dCc_c6UpdateEv((char *)&mdCcAc_c);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN9daRFlag_c6RenderEv, 0x0211b030, size 0x2c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9daRFlag_c6RenderEv
/* recovered: named members + shared header, real C++ method */
int daRFlag_c::Render()
{
 Base *b = &((Derived *)this)->base; b->m(0); return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN9daRFlag_c16CleanupResourcesEv, 0x0211b000, size 0x30 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int _ZN9daRFlag_c16CleanupResourcesEv(void)
{
    _ZN13SharedFilePtr7ReleaseEv(data_ov062_0211e0d4);
    _ZN13SharedFilePtr7ReleaseEv(data_ov062_0211e0dc);
    return 1;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov062_0211afbc, 0x0211afbc, size 0x44 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov062_0211afbc(char *t)
{
    Matrix4x3_FromRotationY(t + 0x124, *(short *)(t + 0x8e));
    *(int *)(t + 0x148) = *(int *)(t + 0x5c) >> 3;
    *(int *)(t + 0x14c) = (*(int *)(t + 0x60) + 0x3c000) >> 3;
    *(int *)(t + 0x150) = *(int *)(t + 0x64) >> 3;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN9daRFlag_cD0Ev, 0x0211af70, size 0x4c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9daRFlag_cD0Ev
/* recovered: named members + shared header, vtable identified, declarations from a shared header */
/* recovered: named members + shared header, vtable identified */
/* vtable identified: VT0 = _ZTV9daRFlag_c */
extern "C" {  /* .c-derived member: C linkage for the whole block */
/* (no separate definition: the single ~daRFlag_c() below emits the D0 and D1
 * variants together -- a hand-mangled D0 next to a real destructor is the
 * known mwccarm ICE, ELFgen.c:483.) */
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN9daRFlag_cD1Ev, 0x0211af38, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9daRFlag_cD1Ev
/* (no definition here either. `virtual ~daRFlag_c() {}` in include/daRFlag_c.h
 * is what mwccarm turns into this D1 and the D0 above: it destroys mModelAnim
 * at 0x108, then mdCcAc_c at 0xd4, then runs the dActor_c base destructor --
 * the exact inverse of the construction order daRFlag_c_classInit performs,
 * which is what pins both member offsets. Writing either variant out of line
 * here reverses the emitted D0/D1 pair against the ROM and adds a D2 that no
 * caller reaches. */
