//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov027/daSnmBth_c+SnowmanBreathParticle  (16 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021120c4  src/_ZN10daSnmBth_cD1Ev.cpp
 *   [1] 0x02112104  src/_ZN10daSnmBth_cD0Ev.cpp
 *   [2] 0x02112158  src/_ZN21SnowmanBreathParticleD1Ev.cpp
 *   [3] 0x02112170  src/_ZN21SnowmanBreathParticle9HitPlayerEv.cpp
 *   [4] 0x0211233c  src/_ZN21SnowmanBreathParticle12CheckSnowmanEv.cpp
 *   [5] 0x021123b0  src/_ZN21SnowmanBreathParticle14UpdatePositionEv.cpp
 *   [6] 0x02112424  src/_ZN21SnowmanBreathParticle6RenderEv.cpp
 *   [7] 0x02112480  src/_ZN21SnowmanBreathParticle8BehaviorEv.cpp
 *   [8] 0x021124e4  src/_ZN21SnowmanBreathParticle8TrySpawnER6Player.cpp
 *   [9] 0x021125a8  src/_ZN21SnowmanBreathParticleC1Ev.cpp
 *   [10] 0x02112618  src/_ZN10daSnmBth_c15IsPlayerInRangeEv.cpp
 *   [11] 0x02112700  src/_ZN10daSnmBth_c16CleanupResourcesEv.cpp
 *   [12] 0x0211273c  src/_ZN10daSnmBth_c16OnPendingDestroyEv.cpp
 *   [13] 0x02112740  src/_ZN10daSnmBth_c6RenderEv.cpp
 *   [14] 0x021127a4  src/_ZN10daSnmBth_c8BehaviorEv.cpp
 *   [15] 0x021129dc  src/_ZN10daSnmBth_c13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daSnmBth_c.h"
#include "decl_Player.h"
#include "SharedFilePtr.h"
#include "types.h"
#include "decl_common.h"
#include "Model.h"

extern "C" {
void _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(u32, s32, s32, s32);
int _ZN6Player15IsCollectingCapEv(void *);
s16 Vec3_HorzAngle(const Vector3 *, const Vector3 *);
void _ZN6Player18SetNewHatCharacterEjjb(void *, u32, u32, int);
int _ZN8SaveData16HasPlayerLostCapEv();
void _ZN8SaveData13PlayerLoseCapEv();
extern Vector3 data_ov027_02113d10;
s32 Vec3_Dist(const Vector3 *, const Vector3 *);
extern Matrix4x3 data_020a0e68;
void Matrix4x3_FromRotationY(Matrix4x3 *, s16);
void Matrix4x3_ApplyInPlaceToRotationX(Matrix4x3 *, s16);
void Matrix4x3_ApplyInPlaceToTranslation(Matrix4x3 *, s32, s32, s32);
void AddVec3(const Vector3 *, const Vector3 *, Vector3 *);
extern "C" u32 _ZN8Particle6System3NewEjj5Fix12IiES2_S2_PK11Vector3_16fPNS_8CallbackE( u32, u32, s32, s32, s32, const void *, void *);
extern "C" int DecIfAbove0_Byte(void *);
s32 RandomIntInternal(s32 *);
extern s32 data_0209e650;
/* Fix12<int> by-value arguments are kept in their measured raw ABI view: a
* direct C++ definition of this imported signature hits the mwccarm 6az wall. */
void _ZN8dCcPos_c4InitERK7Vector35Fix12IiES4_jj(
dCcPos_c *, const Vector3 *, s32, s32, u32, u32);
void Vec3_Asr(Vector3 *, const Vector3 *, int);
void MulVec3Mat4x3(const Vector3 *, const Matrix4x3 *, Vector3 *);
void Vec3_LslInPlace(Vector3 *, int);
typedef struct { s32 words[12]; } MatrixWords;
extern SharedFilePtr data_ov002_0210da40;
extern SharedFilePtr data_ov002_0210d9a0;
extern SharedFilePtr data_ov002_0210d9c0;
extern unsigned char data_0209f2d8[];
extern u8 data_0209f2d8[];
extern int _ZN6Player9StartTalkER7fBase_cb(void *self, void *actor, int b);
/* Moved INSIDE the extern "C" block. A bare `extern` on a mangled name in a
//cpp file mangles it a second time -- this one was reaching the linker as
_Z48_ZN6Player11ShowMessage... and sat in the unresolved baseline. Byte
gates cannot see it, because relocations compare as wildcards; only
check_references does. */
extern int _ZN6Player11ShowMessageER7fBase_cjPK7Vector3hh(void *self, void *actor,
unsigned int msg,
const Vector3 *pos,
unsigned int a,
unsigned int b);
extern int _ZN6Player12GetTalkStateEv(void *self);
/* Same double-mangle defect as ShowMessage above: outside this block the
bare `extern` reached the linker as _Z33_ZN5Sound8PlayLongEjjjRK7Vector3sijjPvj. */
extern int _ZN5Sound8PlayLongEjjjRK7Vector3s(int handle, unsigned int a,
unsigned int b, void *pos,
unsigned int c);
extern void Matrix4x3_FromTranslation(Matrix4x3 *m, int x, int y, int z);
extern void Matrix4x3_ApplyInPlaceToRotationY(Matrix4x3 *m, short angY);
extern void InvMat4x3(Matrix4x3 *dst, const Matrix4x3 *src);
typedef struct { int w[12]; } M48;
/* TUBUILD CONFLICT -- alternate declaration of Vec3_Asr, from the legacy file for _ZN10daSnmBth_c13InitResourcesEv, NOT applied: extern void Vec3_Asr(Vector3 *d, const Vector3 *s, int sh); */
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 15 -- _ZN10daSnmBth_c13InitResourcesEv, 0x021129dc, size 0xd8 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_c13InitResourcesEv
/* recovered: named members + shared header, real C++ method */
int daSnmBth_c::InitResources()
{
    Model::LoadFile(data_ov002_0210da40);
    Model::LoadFile(data_ov002_0210d9a0);
    Model::LoadFile(data_ov002_0210d9c0);
    mPosX = 0x3fa770;
    mPosY = 0xcb2000;
    mPosZ = 0x46988e;
    mAngleY = 0x5d30;
    Vector3 pos;
    Vec3_Asr(&pos, (Vector3 *)&mPosX, 3);
    Matrix4x3_FromTranslation(&data_020a0e68, pos.x, pos.y, pos.z);
    Matrix4x3_ApplyInPlaceToRotationY(&data_020a0e68, mAngleY);
    InvMat4x3(&data_020a0e68, &data_020a0e68);
    *(M48*)&mInvModelMat = *(M48*)&data_020a0e68;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 14 -- _ZN10daSnmBth_c8BehaviorEv, 0x021127a4, size 0x238 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_c8BehaviorEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daSnmBth_c::Behavior()
{
    int b;
    SnowmanBreathParticle *slotBase;
    u8 *idx;
    Vector3 pos;
    int i;
    SnowmanBreathParticle *slot;
    int zero;

    b = data_0209f2d8[0];
    b = (b == 2);
    if (b) {
        return 1;
    }

    if (mTalkDone == 0) {
        switch (mTalkState) {
        case 0:
            if (IsPlayerInRange() == 0) {
                break;
            }
            if (_ZN6Player9StartTalkER7fBase_cb(mTalkPlayer, this, 1) == 0) {
                break;
            }
            mTalkState++;
            break;
        case 1:
            pos.x = mPosX;
            zero = 0;
            pos.y = mPosY;
            pos.z = mPosZ;
            pos.y = pos.y + 0x12c000;
            if (_ZN6Player11ShowMessageER7fBase_cjPK7Vector3hh(
                    mTalkPlayer, this, 0xbb, &pos, zero, zero) == 0) {
                break;
            }
            mTalkState++;
            break;
        case 2:
            if (_ZN6Player12GetTalkStateEv(mTalkPlayer) == -1) {
                _ZN6Player18HasFinishedTalkingEv(mTalkPlayer);
                mTalkDone = 1;
            }
            break;
        }
    } else {
        if (IsPlayerInRange() != 0) {
            mTalkTimer++;
            if ((mTalkTimer & 7) != 0) {
                slotBase = mParticles;
                idx = &mNextParticle;
                do {
                    slot = slotBase + mNextParticle;
                    b = slot->TrySpawn(*mTalkPlayer);
                    *idx = *idx + 1;
                    *idx = *idx % 0x32;
                } while (b == 0);
            }
            mSoundHandle =
                _ZN5Sound8PlayLongEjjjRK7Vector3s(mSoundHandle, 3, 0x184,
                                                  &mCamSpacePosX, 0);
        }
    }

    slot = mParticles;
    i = 0;
    do {
        slot->Behavior();
        i++;
        slot++;
    } while (i < 0x32);

    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 13 -- _ZN10daSnmBth_c6RenderEv, 0x02112740, size 0x64 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_c6RenderEv
int daSnmBth_c::Render()
{
  int b = data_0209f2d8[0];
  b = (b == 2);
  if(b) return 1;
  {
    int i;
    for(i=0;i<0x32;i++){
      mParticles[i].Render();
    }
  }
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 12 -- _ZN10daSnmBth_c16OnPendingDestroyEv, 0x0211273c, size 0x4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_c16OnPendingDestroyEv
/* daSnmBth_c::OnPendingDestroy -- vtable slot 12. The ROM body is empty: the
 * override exists only to occupy the slot. */
void daSnmBth_c::OnPendingDestroy()
{
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 11 -- _ZN10daSnmBth_c16CleanupResourcesEv, 0x02112700, size 0x3c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_c16CleanupResourcesEv
/* daSnmBth_c::CleanupResources -- vtable slot 3. Releases the three shared
 * files the class holds; it never touches `this`. */
int daSnmBth_c::CleanupResources()
{
    data_ov002_0210da40.Release();
    data_ov002_0210d9a0.Release();
    data_ov002_0210d9c0.Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 10 -- _ZN10daSnmBth_c15IsPlayerInRangeEv, 0x02112618, size 0xe8 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_c15IsPlayerInRangeEv
int daSnmBth_c::IsPlayerInRange()
{
    Player *player = ClosestPlayer();
    mTalkPlayer = player;

    Vector3 playerPos;
    Vec3_Asr(&playerPos, (Vector3 *)((char *)player + 0x5c), 3);
    *(MatrixWords *)&data_020a0e68 = *(MatrixWords *)&mInvModelMat;

    Vector3 localPos;
    MulVec3Mat4x3(&playerPos, &data_020a0e68, &localPos);
    Vec3_LslInPlace(&localPos, 3);

    if (localPos.x < -0xe1000)
        goto fail;
    if (localPos.x > 0xe1000)
        goto fail;
    if (localPos.y < -0x5000)
        goto fail;
    if (localPos.y > 0x300000)
        goto fail;
    if (localPos.z < -0x430000)
        goto fail;
    if (localPos.z > 0x430000)
        goto fail;
    return 1;
fail:
    return 0;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- _ZN21SnowmanBreathParticleC1Ev, 0x021125a8, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticleC1Ev
SnowmanBreathParticle::SnowmanBreathParticle()
{
    mPos = data_ov027_02113d10;
    _ZN8dCcPos_c4InitERK7Vector35Fix12IiES4_jj(
        &mCollider, &mPos, 0x32000, 0x28000, 0x800002, 0x800000);
    mTimer = 0;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- _ZN21SnowmanBreathParticle8TrySpawnER6Player, 0x021124e4, size 0xc4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticle8TrySpawnER6Player
int SnowmanBreathParticle::TrySpawn(Player &player)
{
    s32 angle;
    if (mTimer != 0)
        return 0;
    mPos = data_ov027_02113d10;
    angle = Vec3_HorzAngle(&mPos, (Vector3 *)((char *)&player + 0x5c));
    if (angle > 0x2af8)
        angle = 0x2af8;
    if (angle < 0x9de)
        angle = 0x9de;
    {
        s32 random = RandomIntInternal(&data_0209e650);
        mAngleX = 0xc1c;
        mAngleY = (s16)(angle + ((random & 0x1fff) - 0x1000));
    }
    mAngleZ = 0;
    mTimer = 0x16;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- _ZN21SnowmanBreathParticle8BehaviorEv, 0x02112480, size 0x64 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticle8BehaviorEv
void SnowmanBreathParticle::Behavior()
{
    if (DecIfAbove0_Byte(&mTimer) == 0)
        return;
    UpdatePosition();
    CheckSnowman();
    HitPlayer();
    mCollider.pos = mPos;
    mCollider.Clear();
    mCollider.Update();
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN21SnowmanBreathParticle6RenderEv, 0x02112424, size 0x5c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticle6RenderEv
void SnowmanBreathParticle::Render()
{
    if (mTimer == 0)
        return;
    mParticleID =
        _ZN8Particle6System3NewEjj5Fix12IiES2_S2_PK11Vector3_16fPNS_8CallbackE(
            mParticleID, 0x111, mPos.x, mPos.y, mPos.z, 0, 0);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN21SnowmanBreathParticle14UpdatePositionEv, 0x021123b0, size 0x74 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticle14UpdatePositionEv
void SnowmanBreathParticle::UpdatePosition()
{
    Matrix4x3_FromRotationY(&data_020a0e68, mAngleY);
    Matrix4x3_ApplyInPlaceToRotationX(&data_020a0e68, mAngleX);
    Matrix4x3_ApplyInPlaceToTranslation(&data_020a0e68, 0, 0, 0x50000);
    Vector3 offset;
    offset = data_020a0e68.t;
    AddVec3(&mPos, &offset, &mPos);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN21SnowmanBreathParticle12CheckSnowmanEv, 0x0211233c, size 0x74 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticle12CheckSnowmanEv
void SnowmanBreathParticle::CheckSnowman()
{
    dActor_c *snowman = dActor_c::FindWithActorID(0x102, 0);
    s32 threshold = mCollider.radius + 0x12b000;
    s32 distance = Vec3_Dist(&mPos, (Vector3 *)&snowman->mPosX);
    if (distance >= threshold)
        return;
    _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(
        0x100, mPos.x, mPos.y, mPos.z);
    mTimer = 0;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN21SnowmanBreathParticle9HitPlayerEv, 0x02112170, size 0x1cc */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticle9HitPlayerEv
void SnowmanBreathParticle::HitPlayer()
{
    u32 id = mCollider.otherOwner;
    if (id == 0)
        return;
    dActor_c *actor = dActor_c::FindWithID(id);
    if (actor == 0)
        return;
    if ((int)(actor->actorID == 0xbf) == 0)
        return;
    _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(
        0x100, mPos.x, mPos.y, mPos.z);

    char *player = (char *)actor;
    if (*(u8 *)(player + 0x6f9))
        return;
    if (*(u8 *)(player + 0x703))
        return;
    if (*(u8 *)(player + 0x6fd))
        return;
    _ZN6Player8BlowAwayEs(player, mAngleY);
    if (_ZN6Player15IsCollectingCapEv(player))
        return;
    if (*(u8 *)(player + 0x6ff))
        return;
    if (*(u8 *)(player + 0x6fb))
        return;

    s32 angle = Vec3_HorzAngle(&data_ov027_02113d10,
                               (Vector3 *)&actor->mPosX);
    Vector3_16 rotation;
    rotation.x = 0;
    rotation.y = (s16)angle;
    rotation.z = 0;
    if (*(u8 *)(player + 0x6d9) != actor->param1) {
        _ZN6Player18SetNewHatCharacterEjjb(
            player, *(u8 *)(player + 0x6d9), 0, 0);
    } else {
        if (_ZN8SaveData16HasPlayerLostCapEv())
            return;
        _ZN8SaveData13PlayerLoseCapEv();
    }

    Vector3 spawnPos;
    {
        s32 posX = mPos.x;
        s32 posZ = mPos.z;
        s32 posY = mPos.y + 0x96000;
        spawnPos.x = posX;
        spawnPos.y = posY;
        spawnPos.z = posZ;
    }
    dActor_c *cap = dActor_c::Spawn(
        0x10d, (actor->param1 << 8) | 3, spawnPos, &rotation, 0, -1);
    if (cap == 0)
        return;
    cap->unk_0a4 = 0;
    cap->mVertSpeed = 0x14000;
    cap->unk_0ac = 0;
    cap->mHorzSpeed = 0x1c000;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN21SnowmanBreathParticleD1Ev, 0x02112158, size 0x18 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN21SnowmanBreathParticleD1Ev
SnowmanBreathParticle::~SnowmanBreathParticle()
{
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN10daSnmBth_cD0Ev, 0x02112104, size 0x54 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_cD0Ev
/* (no separate definition: the single ~daSnmBth_c() below emits the D0 and D1
 * variants together -- a hand-mangled D0 next to a real destructor is the
 * known mwccarm ICE, ELFgen.c:483.) */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN10daSnmBth_cD1Ev, 0x021120c4, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10daSnmBth_cD1Ev
daSnmBth_c::~daSnmBth_c()
{
}
