//cpp
#pragma opt_loop_invariants off
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov006/dScMgTrampoline2_c  (42 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021225ac  src/_ZN18dScMgTrampoline2_cD1Ev.cpp
 *   [1] 0x021226b0  src/_ZN18dScMgTrampoline2_cD0Ev.cpp
 *   [2] 0x021227c8  src/func_ov006_021227c8.cpp
 *   [3] 0x02122814  src/func_ov006_02122814.cpp
 *   [4] 0x0212287c  src/func_ov006_0212287c.c
 *   [5] 0x021228bc  src/func_ov006_021228bc.cpp
 *   [6] 0x02122a1c  src/func_ov006_02122a1c.cpp
 *   [7] 0x02122a4c  src/func_ov006_02122a4c.c
 *   [8] 0x02122ab8  src/func_ov006_02122ab8.c
 *   [9] 0x02122b24  src/func_ov006_02122b24.c
 *   [10] 0x02122b88  src/func_ov006_02122b88.c
 *   [11] 0x02122c04  src/func_ov006_02122c04.c
 *   [12] 0x02122c68  src/func_ov006_02122c68.cpp
 *   [13] 0x02122c90  src/func_ov006_02122c90.c
 *   [14] 0x02122cb0  src/_ZN18dScMgTrampoline2_c9Virtual88Eiiii.cpp
 *   [15] 0x02122e20  src/func_ov006_02122e20.c
 *   [16] 0x02122f24  src/_ZN18dScMgTrampoline2_c11OnAttacked2Ev.cpp
 *   [17] 0x021230c4  src/_ZN18dScMgTrampoline2_c8OnPushedEv.cpp
 *   [18] 0x021230e8  src/_ZN18dScMgTrampoline2_c8OnKickedEv.cpp
 *   [19] 0x0212318c  src/_ZN18dScMgTrampoline2_c16CleanupResourcesEv.cpp
 *   [20] 0x021231ac  src/_ZN18dScMgTrampoline2_c6RenderEv.cpp
 *   [21] 0x02123340  src/_ZN18dScMgTrampoline2_c8BehaviorEv.cpp
 *   [22] 0x02123428  src/func_ov006_02123428.cpp
 *   [23] 0x0212373c  src/func_ov006_0212373c.c
 *   [24] 0x021237c8  src/func_ov006_021237c8.c
 *   [25] 0x0212382c  src/func_ov006_0212382c.c
 *   [26] 0x021238d0  src/func_ov006_021238d0.c
 *   [27] 0x02123938  src/func_ov006_02123938.c
 *   [28] 0x02123b20  src/func_ov006_02123b20.c
 *   [29] 0x02123b24  src/func_ov006_02123b24.c
 *   [30] 0x02123bf4  src/func_ov006_02123bf4.cpp
 *   [31] 0x02123c78  src/func_ov006_02123c78.c
 *   [32] 0x02123cb4  src/func_ov006_02123cb4.c
 *   [33] 0x02124040  src/func_ov006_02124040.c
 *   [34] 0x02124088  src/func_ov006_02124088.c
 *   [35] 0x02124228  src/func_ov006_02124228.c
 *   [36] 0x02124298  src/_ZN18dScMgTrampoline2_c13OnTurnIntoEggEi.cpp
 *   [37] 0x021242cc  src/_ZN18dScMgTrampoline2_c13OnYoshiTryEatEi.cpp
 *   [38] 0x021243ec  src/_ZN18dScMgTrampoline2_c13InitResourcesEv.cpp
 *   [39] 0x021245a8  src/func_ov006_021245a8.c
 *   [40] 0x0212471c  src/actors/MgTrampolineTerror.cpp#MgTrampolineTerror_Spawn
 *   [41] 0x021248a8  src/actors/MgTrampolineTerror.cpp#func_ov006_021248a8
 */

/* TUBUILD NOTE -- #pragma directive(s) were present in the legacy sources
 * of this TU. `#pragma long_calls` is POSITIONAL in mwccarm 2004/b56 and is
 * carried verbatim before its own member below, bracketed with `off` so it
 * cannot leak into later members (dropping it silently costs the pooled
 * cross-overlay tail-call -- a byte diff; see ShutterBob in ov014).
 * Any OTHER pragma is FILE-GLOBAL last-wins (opt_propagation,
 * optimize_for_size) and is still left out: carried into a merged TU it
 * would silently recompile every other member. Decide those by hand:
 *   _ZN18dScMgTrampoline2_c9Virtual88Eiiii: #pragma opt_loop_invariants off   [NOT carried -- review]
 *   func_ov006_02123428: #pragma opt_loop_invariants off   [NOT carried -- review]
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "common.h"
#include "types.h"
#define DSCMGTRAMPOLINE2_INLINE_DTOR
#include "dScMgTrampoline2_c.h"
#undef DSCMGTRAMPOLINE2_INLINE_DTOR
#define func_ov006_021227c8 func_ov006_021227c8_decl_common_shadow
#define func_ov006_02122c68 func_ov006_02122c68_decl_common_shadow
#include "decl_common.h"
#undef func_ov006_021227c8
#undef func_ov006_02122c68

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow struct 'C' */
struct C {
    virtual void v0();
    virtual void v1();
    virtual void v2();
    virtual void v3();
    virtual void v4();
    virtual void v5(void *arg);
};

/* shadow struct 'SharedFilePtr' */
struct SharedFilePtr { void Release(); };

/* shadow struct 'BMD_File' */
struct BMD_File;

/* shadow struct 'Obj' */
struct Obj {
    unsigned char pad0[0x68];
    unsigned char f68;
    unsigned char pad1[3];
    int f6c;
};

/* shadow struct 'Vector3_16f' */
struct Vector3_16f;

/* shadow typedef 'void' */
typedef void (dScMgTrampoline2_c::*dScMgTrampoline2_cState)();

/* shadow struct 'Vec3i' */
struct Vec3i {
    int x;
    int y;
    int z;
};

/* shadow struct 'B4' */
struct B4 {
    unsigned char v;
    unsigned char pad[3];
};

/* shadow struct 'Player' */
struct Player { void St_Null_Init(); };

/* shadow struct 'P2' */
struct P2 { int words[2]; };

/* shadow typedef 'u8' */
typedef unsigned char u8;

/* shadow typedef 'u16' */
typedef unsigned short u16;

/* shadow typedef 'SpawnDef' */
typedef struct {
    int count;
    int base;
    short *a;
    short *b;
    short *c;
} SpawnDef;

/* shadow struct 'S2' */
struct S2 { int words[2]; };

/* shadow typedef 'T' */
typedef struct {
    u8 pad0[0xbc];
    u32 unkBC;
    u8 pad1[0x7ac8 - 0xc0];
    u32 unk7AC8;
    u8 pad2[0x7b88 - 0x7acc];
    u32 unk7B88;
    u8 pad3[0x7b94 - 0x7b8c];
    u32 unk7B94;
    u32 unk7B98;
    s16 unk7B9C;
    s16 unk7B9E;
    s16 unk7BA0;
    s16 unk7BA2;
    s16 unk7BA4;
    u8 pad4[2];
    s16 unk7BA8;
} T;

/* shadow struct 'Base' */
struct Base {
    virtual void m00();
    virtual void m04();
    virtual void m08();
    virtual void m0c();
    virtual void m10();
    virtual void m14();
    virtual void m18();
    virtual void m1c();
    virtual void m20();
    virtual void m24();
    virtual void m28();
    virtual void m2c();
    virtual void m30();
    virtual void m34();
    virtual void m38();
    virtual void m3c();
    virtual void m40();
    virtual void m44();
    virtual void m48(int x);
};

/* TUBUILD CONFLICT -- alternate body of struct 'Model', from the legacy file for func_ov006_02122c68, NOT applied:
struct Model { ~Model(); };
*/

extern "C" {
extern "C" void Matrix4x3_FromTranslation(void *m, int x, int y, int z);
extern "C" void Matrix4x3_ApplyInPlaceToRotationZ(void *m, short angZ);
extern Matrix4x3 data_020a0e68;
extern "C" void func_ov006_02122814(char *c);
extern void _Z15ApproachLinear2Rsss(short* a, short b, short c);
extern void AddVec3(struct Vector3* a, struct Vector3* b, struct Vector3* c);
extern "C" SharedFilePtr data_ov006_02142f80;
extern "C" BMD_File* _ZN5Model8LoadFileER13SharedFilePtr(SharedFilePtr&);
extern "C" void _ZN9ModelBase7SetFileEP8BMD_Fileii(void* self, BMD_File*, int, int);
extern int data_ov006_02142f74;
extern unsigned char *data_ov006_02142f7c;
extern void func_ov006_0212287c(char *obj);
extern void func_ov006_021228bc(void *obj, void *kind);
extern void func_ov006_02122a1c(void* self);
extern int _ZN5ModelC1Ev(void *model);
extern void _ZN5ModelD1Ev(void *model);
extern int data_ov006_02142f78[];
extern void *func_02054efc(void);
extern void *func_02054ea8(void);
extern char *_ZN2G213GetBG2CharPtrEv(void);
extern int func_02054d88(void);
extern void MultiCopy_Int(int *dst, int *src, int len);
extern char *_ZN2G212GetBG0ScrPtrEv(void);
extern char *_ZN2G212GetBG2ScrPtrEv(void);
extern char *_ZN2G212GetBG3ScrPtrEv(void);
extern void MultiStore16(unsigned short val, char *dst, int nbytes);
extern void _ZN2GX10LoadBGPlttEPKvjj(const void *src, unsigned int a, unsigned int b);
extern const unsigned char data_ov006_0212f1ac[];
extern char* data_0209f5bc;
extern int data_ov006_0213fbc4;
unsigned int func_02012790(unsigned int a);
int func_ov006_020d0c38(u16* a, u16* b);
extern "C" void func_ov004_020ad90c(void);
void func_0203cd80(int *m, short angle);
int GetGameLanguage(void);
void DrawOamSprite(void *a0, void *a1, int a2, void *a3);
void RenderOamMainScreen(int a0, int a1, int a2, int a3, int a4);
void *_ZN8Particle6System17NewUnkCallback818Ejj5Fix12IiES2_S2_PK11Vector3_16f(
unsigned int a, unsigned int b, int c, int d, int e, const Vector3_16f *f);
void *_ZN8Particle6System12FromUniqueIDEj(unsigned int id);
void func_ov006_020eef90(void);
extern int RandomIntInternal(int *seed);
extern int data_0209e650;
extern int data_ov006_0212f328;
extern int func_ov006_021238d0(int kind);
extern unsigned short func_ov006_0212382c(int column, int side);
extern int func_ov006_021237c8(int kind);
extern int func_ov006_0212373c(int kind);
extern int _Z14ApproachLinearRiii(int *value, int target, int step);
extern void func_0203cc28(int *vector, int angle);
extern char *func_ov006_020cefa4(int resource, int *up, int variant, int face);
extern volatile unsigned char data_020a0e40[];
extern struct B4 data_020a0de8[];
extern struct B4 data_020a0de9[];
extern struct B4 data_020a0dea[];
extern struct B4 data_020a0deb[];
extern int func_ov004_020ae5c4(int a, int b, int c, int d, int e, int f, int g);
extern int func_020126e8(int a);
extern int func_02012468(int a, int b, int c, int d, int e, int f, int g, short h);
extern int data_ov006_0213fbd0[];
extern Player *func_ov006_020cedf0(void *c);
extern int func_ov006_020ca7b8(void);
extern double data_ov006_0213fbe0;
extern void func_ov006_020ca840(void *c);
extern struct P2 data_ov006_0213fbf0;
extern int data_ov006_02140818;
extern int data_ov006_0213b0f0;
extern int data_ov006_02140830;
extern int data_ov006_021405bc;
extern int data_ov006_02140828;
extern int data_ov006_0213fc10[];
extern SpawnDef data_ov006_0212f2b0[];
extern void func_ov006_020d0ac0(void);
extern void func_ov006_020cac30(void);
extern void func_ov006_020cad3c(int a);
extern void func_ov006_02123c78(char *c);
extern void func_ov006_020ca8e0(void);
extern void func_ov006_02123428(char *c);
extern void func_ov006_020caa08(void* a);
extern struct S2 data_ov006_0213fbe8;
extern void func_ov006_020d0b78(void);
extern void func_ov006_02124040(char *c);
extern int _ZN4cstd4fdivEii(int a, int b);
extern s16 data_ov006_0212e058;
extern s16 data_ov006_0212e050;
extern s16 data_ov006_0212e048;
extern short data_ov006_0212e044;
extern struct P2 data_ov006_0213fbd8;
extern "C" void _ZN3G2x13SetBlendAlphaEPVttttj(volatile void *p, u16 a, u16 b, u16 c, u16 d);
extern "C" void func_ov006_020d0b04(u32 a);
extern void func_ov006_02124228(char *self);
extern volatile s16 data_020a0dbc[];
extern void Camera_UpdateMatrices(void *cam);
extern u8 data_0209d45c;
extern int LoadFile(int handle);
extern void DecompressLZ16(int src, void *dst);
extern void _ZN2GX11LoadOBJPlttEPKvjj(const void *p, u32 a, u32 b);
extern void Deallocate(void *ptr);
extern void func_ov006_02122e20(void *self, int a);
extern int data_ov006_0213fc34[];
extern void *_ZN7fBase_cnwEj(unsigned int size);
extern void _ZN11dScMgBase_cC2Ev(void *scene);
extern void _ZN8Particle10SysTrackerC1Ev(void *tracker);
extern void func_020733a8(void *base, int count, int stride, void *ctor, void *dtor);
extern int _ZTV14dScMgD3DBase_c[];
extern void _ZN6Player29TryExitCharacterDoorWithIntroEv(void);
extern void func_ov006_020d100c(void);
extern void func_ov006_020efc08(void);
extern void func_ov006_021225a8(void);
extern void _ZN18TextureTransformerC1Ev(void *transformer);
extern void NullDestructor_0203d47c(void);
extern void func_0203d738(void);
extern int func_ov006_021227c8(char *object);
extern int func_ov006_02122c90(char *object);
extern Model *func_ov006_02122c68(Model *model);
/* TUBUILD CONFLICT -- alternate declaration of func_ov006_02122814, from the legacy file for func_ov006_02122a4c, NOT applied: extern void func_ov006_02122814(char *obj); */
/* TUBUILD CONFLICT -- alternate declaration of data_ov006_02142f7c, from the legacy file for func_ov006_02122b24, NOT applied: extern int data_ov006_02142f7c; */
/* TUBUILD CONFLICT -- alternate declaration of data_ov006_02142f7c, from the legacy file for func_ov006_02122b88, NOT applied: extern unsigned char *data_ov006_02142f7c; */
/* TUBUILD CONFLICT -- alternate declaration of data_ov006_02142f7c, from the legacy file for func_ov006_02122c04, NOT applied: extern int data_ov006_02142f7c; */
/* TUBUILD CONFLICT -- alternate declaration of data_ov006_02142f80, from the legacy file for func_ov006_02122c68, NOT applied: extern SharedFilePtr data_ov006_02142f80; */
/* TUBUILD CONFLICT -- alternate declaration of _ZN2G213GetBG2CharPtrEv, from the legacy file for func_ov006_02122e20, NOT applied: extern char *_ZN2G213GetBG2CharPtrEv(void); */
/* TUBUILD CONFLICT -- alternate declaration of func_02054efc, from the legacy file for func_ov006_02122e20, NOT applied: extern char *func_02054efc(void); */
/* TUBUILD CONFLICT -- alternate declaration of func_02054ea8, from the legacy file for func_ov006_02122e20, NOT applied: extern char *func_02054ea8(void); */
/* TUBUILD CONFLICT -- alternate declaration of func_02054d88, from the legacy file for func_ov006_02122e20, NOT applied: extern char *func_02054d88(void); */
/* TUBUILD CONFLICT -- alternate declaration of func_02054d88, from the legacy file for _ZN18dScMgTrampoline2_c11OnAttacked2Ev, NOT applied: int func_02054d88(void); */
/* TUBUILD CONFLICT -- alternate declaration of MultiStore16, from the legacy file for _ZN18dScMgTrampoline2_c11OnAttacked2Ev, NOT applied: void MultiStore16(u16 val, char* dst, int nbytes); */
/* TUBUILD CONFLICT -- alternate declaration of RandomIntInternal, from the legacy file for func_ov006_021237c8, NOT applied: extern int RandomIntInternal(void* seed); */
/* TUBUILD CONFLICT -- alternate declaration of MultiStore16, from the legacy file for func_ov006_02123b24, NOT applied: extern void MultiStore16(unsigned short a, int b, int c); */
/* TUBUILD CONFLICT -- alternate declaration of _Z14ApproachLinearRiii, from the legacy file for func_ov006_02123bf4, NOT applied: extern int _Z14ApproachLinearRiii(int &v, int a, int b); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov006_020cedf0, from the legacy file for func_ov006_02123cb4, NOT applied: extern void func_ov006_020cedf0(void); */
/* TUBUILD CONFLICT -- alternate declaration of _Z14ApproachLinearRiii, from the legacy file for func_ov006_02123cb4, NOT applied: extern int _Z14ApproachLinearRiii(int *v, int step, int rate); */
/* TUBUILD CONFLICT -- alternate declaration of func_0203cc28, from the legacy file for func_ov006_02123cb4, NOT applied: extern void func_0203cc28(int *p, int angle); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov006_020cefa4, from the legacy file for func_ov006_02123cb4, NOT applied: extern char *func_ov006_020cefa4(int a0, int *a1, int a2, int a3); */
/* TUBUILD CONFLICT -- alternate declaration of MultiStore16, from the legacy file for func_ov006_02124088, NOT applied: extern void MultiStore16(u16 val, char *dst, int nbytes); */
/* TUBUILD CONFLICT -- alternate declaration of func_02012718, from the legacy file for func_ov006_02124088, NOT applied: extern void func_02012718(void *a, int b); */
/* TUBUILD CONFLICT -- alternate declaration of func_02012468, from the legacy file for func_ov006_02124088, NOT applied: extern int func_02012468(int a, int b, int c, int d, int e, int f, int g, int h); */
/* TUBUILD CONFLICT -- alternate declaration of func_ov004_020ae5c4, from the legacy file for func_ov006_02124088, NOT applied: extern int func_ov004_020ae5c4(void *a, int b, int c, int d, int e, int f, int g); */
/* TUBUILD CONFLICT -- alternate declaration of data_ov006_0212e048, from the legacy file for func_ov006_02124228, NOT applied: extern short data_ov006_0212e048; */
/* TUBUILD CONFLICT -- alternate declaration of GetGameLanguage, from the legacy file for _ZN18dScMgTrampoline2_c13OnTurnIntoEggEi, NOT applied: extern int GetGameLanguage(void); */
/* TUBUILD CONFLICT -- alternate declaration of GetGameLanguage, from the legacy file for _ZN18dScMgTrampoline2_c13OnYoshiTryEatEi, NOT applied: extern "C" s32 GetGameLanguage(void); */
/* TUBUILD CONFLICT -- alternate declaration of MultiStore16, from the legacy file for _ZN18dScMgTrampoline2_c13OnYoshiTryEatEi, NOT applied: extern "C" void MultiStore16(u16 val, char *dst, int nbytes); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN4cstd4fdivEii, from the legacy file for _ZN18dScMgTrampoline2_c13InitResourcesEv, NOT applied: extern s32 _ZN4cstd4fdivEii(s32 a, s32 b); */
/* TUBUILD CONFLICT -- alternate declaration of GetGameLanguage, from the legacy file for func_ov006_021245a8, NOT applied: extern s32 GetGameLanguage(void); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN2G213GetBG2CharPtrEv, from the legacy file for func_ov006_021245a8, NOT applied: extern char *_ZN2G213GetBG2CharPtrEv(void); */
/* TUBUILD CONFLICT -- alternate declaration of MultiStore16, from the legacy file for func_ov006_021245a8, NOT applied: extern void MultiStore16(u16 val, char *dst, int nbytes); */
/* TUBUILD CONFLICT -- alternate declaration of _ZN2GX10LoadBGPlttEPKvjj, from the legacy file for func_ov006_021245a8, NOT applied: extern void _ZN2GX10LoadBGPlttEPKvjj(const void *p, u32 a, u32 b); */
}

/* This overload is C++, unlike the address-spelled C ABI declarations above. */
extern void ApproachLinear(int &x, int target, int step);

/* -------------------------------------------------------------------------- */
/* ROM ordinal 41 -- func_ov006_021248a8, 0x021248a8, size 0x60 */
/* -------------------------------------------------------------------------- */
extern "C" void *func_ov006_021248a8(char *object)
{
    _ZN5ModelC1Ev(object + 0xa0);
    _ZN5ModelC1Ev(object + 0xf0);
    _ZN5ModelC1Ev(object + 0x140);
    _ZN18TextureTransformerC1Ev(object + 0x194);
    func_020733a8(object + 0x1a8, 5, 8,
                  (void *)func_0203d738, (void *)NullDestructor_0203d47c);
    return object;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 40 -- MgTrampolineTerror_Spawn, 0x0212471c, size 0x18c */
/* -------------------------------------------------------------------------- */
extern "C" void *MgTrampolineTerror_Spawn(void)
{
    char *scene = (char *)_ZN7fBase_cnwEj(0x7bac);
    if (scene) {
        char *it;
        _ZN11dScMgBase_cC2Ev(scene);
        *(int *)scene = (int)_ZTV14dScMgD3DBase_c;
        *(short *)(scene + 0x4664) = 0;
        it = scene + 0x466c;
        {
		char *end = scene;
		end += 0x47e4;
            do {
                it += 0xbc;
            } while (it != end);
        }
        _ZN8Particle10SysTrackerC1Ev(scene + 0x47e4);
        *(int *)scene = (int)(&_ZTV18dScMgTrampoline2_c + 2);
        func_020733a8(scene + 0x500c, 5, 0xdc,
                      (void *)_ZN6Player29TryExitCharacterDoorWithIntroEv,
                      (void *)func_ov006_020ca604);
        func_020733a8(scene + 0x5458, 3, 0x32c,
                      (void *)func_ov006_020d100c,
                      (void *)func_ov006_020d1008);
        func_020733a8(scene + 0x5ddc, 0xa, 0x1d0,
                      (void *)func_ov006_021248a8,
                      (void *)func_ov006_021227c8);
        func_020733a8(scene + 0x6ffc, 0xa, 0x24,
                      (void *)func_ov006_020efc08,
                      (void *)func_ov006_020eed64);
        func_020733a8(scene + 0x7164, 0x14, 0x78,
                      (void *)func_ov006_02122c90,
                      (void *)func_ov006_02122c68);
        func_020733a8(scene + 0x7ad0, 5, 0x24,
                      (void *)func_ov006_021225a8,
                      (void *)func_ov006_02120938);
    }
    return scene;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 39 -- func_ov006_021245a8, 0x021245a8, size 0x174 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_021245a8(void *arg0)
{
    void *sb = arg0;
    int r8, r7, r6, r5, r4;
    volatile u16 sp0;

    r8 = LoadFile(data_ov006_0213fc34[GetGameLanguage()]);
    r7 = LoadFile(0x108);
    r6 = LoadFile(0xa2);
    r5 = LoadFile(0xa4);
    r4 = LoadFile(0xa3);

    *(volatile u16 *)0x400000c = (*(volatile u16 *)0x400000c & ~3) | 2;
    *(volatile u16 *)0x400000c = (*(volatile u16 *)0x400000c & 0x43) | 0x9110;
    *(volatile u16 *)0x400000c &= ~0x40;

    {
        char *dst = _ZN2G213GetBG2CharPtrEv();
        sp0 = 0;
        MultiStore16(sp0, dst, 0x4000);
    }
    DecompressLZ16(r6, (void *)(_ZN2G213GetBG2CharPtrEv() + 0x4000));
    DecompressLZ16(r5, _ZN2G212GetBG2ScrPtrEv());
    _ZN2GX10LoadBGPlttEPKvjj((const void *)r4, 0x1a0, 0x60);

    *(volatile u16 *)0x400000e = (*(volatile u16 *)0x400000e & ~3) | 1;
    *(volatile u16 *)0x400000e = (*(volatile u16 *)0x400000e & 0x43) | 0x1318;
    *(volatile u16 *)0x400000e &= ~0x40;

    DecompressLZ16(r8, (void *)0x6400000);
    _ZN2GX11LoadOBJPlttEPKvjj((const void *)r7, 0, 0x60);

    Deallocate((void *)r6);
    Deallocate((void *)r5);
    Deallocate((void *)r4);
    Deallocate((void *)r8);
    Deallocate((void *)r7);

    func_ov006_02122e20(sb, 3);
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 38 -- _ZN18dScMgTrampoline2_c13InitResourcesEv, 0x021243ec, size 0x1bc */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c13InitResourcesEv
/* dScMgTrampoline2_c::InitResources -- vtable slot 0.
 *
 * Attributed by tools/rtti_vtables.py --own dScMgTrampoline2_c, this class's own
 * slot 0 (fBase_c::InitResources). The old file's `recovered name:
 * dScMgTrampoline2_c_InitResources` agreed.
 *
 * The final `((Base *)base)->m48(-1)` is a self-dispatch through this class's own
 * vtable slot 18 -- left as a raw vtable-shim call, same shape the pre-migration
 * file used, just through `this` instead of a `char *base` parameter. */
s32 dScMgTrampoline2_c::InitResources()
{
    char *base = (char *)this;
    s32 fov;

    func_ov006_021245a8(base);
    data_0209d45c = 0x1d;
    _ZN3G3X6SetFogEbiii(0, 0, 2, 0x1000);
    *(u16 *)0x4000060 = (*(u16 *)0x4000060 & ~0x3000) | 8;
    InitialiseVramGlobals();
    *(u16 *)0x4000008 = (*(u16 *)0x4000008 & ~3) | 1;
    fov = _ZN4cstd4fdivEii(0xc0000, (s32)data_02082414);
    this->mCamera0EyeX = 0;
    this->mCamera0EyeY = -0x64000;
    this->mCamera0EyeZ = 0;
    this->mCamera0TargetX = 0;
    this->mCamera0TargetY = 0;
    this->mCamera0TargetZ = fov;
    this->mCamera0Angle = 0x400;
    Camera_UpdateMatrices(base + 0x466c);
    this->mCamera1EyeX = 0;
    this->mCamera1EyeY = 0x82000;
    this->mCamera1EyeZ = 0;
    this->mCamera1TargetX = 0;
    this->mCamera1TargetY = 0;
    this->mCamera1TargetZ = fov;
    this->mCamera1Angle = 0x400;
    Camera_UpdateMatrices(base + 0x4728);
    if (func_ov006_020cae9c(base + 0x500c, 5) == 0)
        return 0;
    func_ov006_02120d8c(base + 0x7ad0, 5);
    func_ov006_020d0b2c();
    func_ov006_020cef14((char *)(base + 0x5ddc), 10);
    func_ov006_020ef0d4((int)(base + 0x6ffc), 10);
    data_ov006_021421b4 = 0;
    func_ov006_02122c04((int)(base + 0x7164), 0x14);
    func_ov004_020b04d0(0x10);
    ((Base *)base)->m48(-1);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 37 -- _ZN18dScMgTrampoline2_c13OnYoshiTryEatEi, 0x021242cc, size 0x120 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c13OnYoshiTryEatEi
// recovered name: dScMgTrampoline2_c_OnYoshiTryEat_021242cc
/* recovered: renamed to Class_Method, declarations from a shared header */
/* recovered: renamed to Class_Method, vtable slot 18 -- an override of
   dScMgBase_c::OnYoshiTryEat(int). The signature must repeat the base
   declaration exactly, or mwcc appends a slot instead of overriding. */
void dScMgTrampoline2_c::OnYoshiTryEat(int /* arg */)
{
    T *self = (T *)this;

    _ZN3G2x13SetBlendAlphaEPVttttj((volatile void *)0x4000050, 1, 0x2e, 0x10, 0x10);

    self->unk7BA0 = data_020a0dbc[0];
    self->unk7BA2 = data_020a0dbc[1];
    self->unk7B9C = data_020a0dbc[0];
    self->unk7B9E = data_020a0dbc[1];

    self->unkBC = 0;
    if (self->unkBC > 0x270e)
        self->unkBC = 0x270e;

    func_ov006_020cad3c(0x1000);
    func_ov006_020cac9c(self->unkBC);
    data_ov006_021405bc = 1;
    func_ov006_020d0b04(self->unkBC);
    func_ov006_020cee5c(self->unkBC);
    func_ov006_020eeff0();
    func_ov006_02122b24();
    func_ov006_02120ca0();
    func_ov006_020c8a9c(0, data_ov006_0213fc20[GetGameLanguage()]);

    self->unk7BA4 = 0;
    self->unk7BA8 = 0;
    self->unk7B88 = 0;
    self->unk7B94 = 0;
    self->unk7B98 = 0;
    self->unk7AC8 = 0x14000;

    {
        volatile u16 z;
        char *dst = (char *)func_02054d88();
        z = 0;
        MultiStore16(z, dst, 0x6000);
    }

    func_ov006_02124228((char *)self);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 36 -- _ZN18dScMgTrampoline2_c13OnTurnIntoEggEi, 0x02124298, size 0x34 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c13OnTurnIntoEggEi
// recovered name: dScMgTrampoline2_c_OnTurnIntoEgg
/* recovered: renamed to Class_Method, declarations from a shared header */
/* recovered: renamed to Class_Method */
/* dScMgTrampoline2_c::OnTurnIntoEgg - recovered from vtable slot identity */
int dScMgTrampoline2_c::OnTurnIntoEgg(int /* mode */)
{
    func_ov006_020c8a9c(0, data_ov006_0213fc20[GetGameLanguage()]);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 35 -- func_ov006_02124228, 0x02124228, size 0x70 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124228(char* c) {
    short a, b;
    *(int*)(c + 0x7b84) = 0x5a;
    a = data_ov006_0212e044;
    *(short*)(c + 0x7ba0) = a;
    b = data_ov006_0212e048;
    *(short*)(c + 0x7ba2) = b;
    *(short*)(c + 0x7b9c) = a;
    *(short*)(c + 0x7b9e) = b;
    *(int*)(c + 0x7b8c) = 0;
    *(int*)(c + 0x7b90) = 0x3e8;
    *(struct P2*)(c + 0x5004) = data_ov006_0213fbd8;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 34 -- func_ov006_02124088, 0x02124088, size 0x1a0 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124088(char *c)
{
    int counter;

    func_ov006_020d0ac0();
    *(int *)(c + 0x7b84) -= 1;
    counter = *(int *)(c + 0x7b84);

    if (counter == 0) {
        if (*(u8 *)(c + 0xc4) == 0) {
            *(u8 *)(c + 0xc3) = 1;
            *(u8 *)(c + 0xc4) = 1;
            *(s16 *)(c + 0xc0) = 0;
        }

        {
            int dst = func_02054d88();
            volatile u16 tmp = 0;
            MultiStore16(tmp, (char *)dst, 0x6000);
        }

        func_ov006_020d0b78();
        func_02012718(0x1af, 0x8000);
        func_ov006_02124040(c);
        return;
    }

    {
        int t = _ZN4cstd4fdivEii(counter << 12, 0x5a000);
        volatile s16 old9c = *(s16 *)(c + 0x7b9c);
        volatile s16 old9e = *(s16 *)(c + 0x7b9e);
        int mixRaw = data_ov006_0212e050 * t + data_ov006_0212e058 * (0x1000 - t);
        *(s16 *)(c + 0x7b9c) = (s16)(mixRaw >> 12);
        *(s16 *)(c + 0x7b9e) = data_ov006_0212e048;

        *(s16 *)(c + 0x7b9e) +=
            ((((int)((unsigned int)(RandomIntInternal(&data_0209e650) & ~0x80000000) >> 19) - 0x800) << 2) >> 12);

        func_ov004_020ae5c4((int)c, old9c, old9e, *(s16 *)(c + 0x7b9c), *(s16 *)(c + 0x7b9e), 2, 0xc);

        *(int *)(c + 0x7b8c) = func_02012468(*(int *)(c + 0x7b8c), 2, 0x1b0, 2, 0,
                                              func_020126e8(mixRaw), 0, 0);
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 33 -- func_ov006_02124040, 0x02124040, size 0x48 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124040(char* c){
  *(int*)(c+0x7b84) = 0xb4;
  *(short*)(c+0x7ba4) = 1;
  func_ov006_020caa08(c+0x7b00);
  *(struct S2*)(c+0x5004) = data_ov006_0213fbe8;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 32 -- func_ov006_02123cb4, 0x02123cb4, size 0x38c */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02123cb4(char *c)
{
    int old;

    old = data_ov006_02140818;
    func_ov006_020d0ac0();
    ((void (*)(void))func_ov006_020cedf0)();
    func_ov006_020cac30();
    if (old < data_ov006_02140818) {
        int n = data_ov006_02140818 - old;
        int i;
        for (i = 0; i < n; i++)
            _Z14ApproachLinearRiii((int *)(c + 0x7ac8), 0x7000, -0x800);
        if (data_ov006_02140818 == 3)
            *(u8 *)(c + 0xc3) = 0;
    }
    func_ov006_020cad3c((data_ov006_02140818 / 10) * 64 + 0x1000);
    if (data_ov006_0213b0f0 == 0) {
        *(u16 *)(c + 0x7ba4) = 0;
        func_ov006_02123c78(c);
        return;
    }
    if (data_ov006_02140830 >= *(int *)(c + 0x7b90) && data_ov006_021405bc < 5) {
        unsigned int v;
        func_ov006_020ca8e0();
        {
            int *p = (int *)((int)c + 0xbc);
            *p = *p + 1;
        }
        if (*(unsigned int *)(c + 0xbc) > 0x270e)
            *(unsigned int *)(c + 0xbc) = 0x270e;
        v = *(unsigned int *)(c + 0xbc);
        if (v < 4)
            *(int *)(c + 0x7b90) = data_ov006_0213fc10[v];
        else
            *(int *)(c + 0x7b90) = 0x7fffffff;
        return;
    }
    if (data_ov006_02140828 != 0)
        return;
    if (_Z14ApproachLinearRiii((int *)(c + 0x7b84), 0, 1) == 0)
        return;
    if (*(int *)(c + 0x7b94) == 0) {
        SpawnDef *d = &data_ov006_0212f2b0[*(int *)(c + 0x7b88)];
        int i;
        Vec3i vecA;
        for (i = 0; i < d->count; i++) {
            vecA.x = 0;
            vecA.y = 0x1000;
            vecA.z = 0;
            func_0203cc28((int *)&vecA, d->a[i]);
            func_ov006_020cefa4(d->base + i * 0xc, (int *)&vecA, d->b[i], d->c[i]);
        }
        if (_Z14ApproachLinearRiii((int *)(c + 0x7b88), 6, 1)) {
            *(int *)(c + 0x7b94) = 1;
            *(int *)(c + 0x7b98) = 0;
        }
    } else {
        if (_Z14ApproachLinearRiii((int *)(c + 0x7b98), 4, 1)) {
            unsigned int rnd = (unsigned int)RandomIntInternal(&data_0209e650) & 0x7fffffff;
            SpawnDef *d = &data_ov006_0212f2b0[(int)((rnd >> 19) * 6) >> 12];
            int i;
            Vec3i vecB;
            for (i = 0; i < d->count; i++) {
                vecB.x = 0;
                vecB.y = 0x1000;
                vecB.z = 0;
                func_0203cc28((int *)&vecB, d->a[i]);
                func_ov006_020cefa4(d->base + i * 0xc, (int *)&vecB, d->b[i], d->c[i]);
            }
            *(int *)(c + 0x7b98) = 0;
        } else {
            func_ov006_02123428(c);
        }
    }
    *(int *)(c + 0x7b84) = 0x78;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 31 -- func_ov006_02123c78, 0x02123c78, size 0x3c */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02123c78(char *c) {
    func_ov006_020ca840(c);
    *(int*)(c + 0x7b84) = 0x5a;
    *(struct P2*)(c + 0x5004) = data_ov006_0213fbf0;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 30 -- func_ov006_02123bf4, 0x02123bf4, size 0x84 */
/* -------------------------------------------------------------------------- */
extern "C" void func_ov006_02123bf4(char *c)
{
    func_ov006_020cedf0(c)->St_Null_Init();
    if (_Z14ApproachLinearRiii((int *)(c + 0x7b84), 0, 1) == 0)
        return;
    if (func_ov006_020ca7b8() == 0)
        return;
    func_ov004_020b0a54(0x12);
    *(unsigned char *)(c + 0xc3) = 0;
    *(int *)(c + 0x7b84) = 0xb4;
    *(double *)(c + 0x5004) = data_ov006_0213fbe0;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 29 -- func_ov006_02123b24, 0x02123b24, size 0xd0 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02123b24(char *c)
{
    int idx, b;
    *(int *)(c + 0x7b84) -= 1;
    if (*(int *)(c + 0x7000 + 0xb84) != 0)
    {
        idx = data_020a0e40[0];
        b = 0;
        if (((unsigned char *)data_020a0de8)[idx * 4] != 0 &&
            ((unsigned char *)data_020a0de9)[idx * 4] != 0)
            b = 1;
        if (b == 0)
            return;
    }
    {
        int r;
        volatile unsigned short h;
        r = func_02054d88();
        h = 0;
        MultiStore16(h, (char *)r, 0x6000);
    }
    *(short *)(c + 0x7ba8) = 1;
    {
        int w0 = data_ov006_0213fbd0[0];
        int w1 = data_ov006_0213fbd0[1];
        w0 = w1 ? w0 : w0;
        *(int *)(c + 0x5004) = w0;
        *(int *)(c + 0x5008) = w1;
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 28 -- func_ov006_02123b20, 0x02123b20, size 0x4 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02123b20(void)
{
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 27 -- func_ov006_02123938, 0x02123938, size 0x1e8 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02123938(void *arg0)
{
    char *c = (char *)arg0;
    int i;
    int b;

    if (*(short *)(c + 0x7ba4) == 0 || *(unsigned char *)(c + 0x7bab) != 0) {
        *(unsigned char *)(c + 0x7baa) = 0;
        return;
    }

    i = data_020a0e40[0];
    b = (data_020a0de8[i].v != 0 && data_020a0de9[i].v != 0);
    if (b) {
        *(short *)(c + 0x7b9c) = data_020a0dea[i].v;
        *(short *)(c + 0x7ba0) = *(short *)(c + 0x7b9c);
        *(short *)(c + 0x7b9e) = data_020a0deb[i].v;
        *(short *)(c + 0x7ba2) = *(short *)(c + 0x7b9e);
        *(unsigned char *)(c + 0x7baa) = 1;
        *(int *)(c + 0x7b8c) = 0;
    }

    if (*(unsigned char *)(c + 0x7baa) != 1) return;

    i = data_020a0e40[0];
    if (data_020a0de8[i].v != 0) {
        func_ov004_020ae5c4((int)c, *(short *)(c + 0x7b9c), *(short *)(c + 0x7b9e),
                            data_020a0dea[i].v, data_020a0deb[i].v, 2, 4);
        i = data_020a0e40[0];
        *(short *)(c + 0x7b9c) = data_020a0dea[i].v;
        *(short *)(c + 0x7b9e) = data_020a0deb[i].v;
        *(int *)(c + 0x7b8c) = func_02012468(*(int *)(c + 0x7b8c), 2, 0x1b0, 2, 0,
                                             func_020126e8(*(short *)(c + 0x7b9c) << 12), 0, 0);
    } else {
        b = (int)(data_020a0de8[i].v == 0 && data_020a0de9[i].v != 0);
        if (b != 0) {
            *(unsigned char *)(c + 0x7bab) = 1;
        }
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 26 -- func_ov006_021238d0, 0x021238d0, size 0x68 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int func_ov006_021238d0(int x) {
    switch (x) {
    case 0:
    case 1:
    case 2:
        return 0;
    case 5:
    case 8:
        return 1;
    case 3:
    case 4:
        return 2;
    case 6:
    case 9:
        return 3;
    case 7:
    case 10:
        return 4;
    }
    return 0;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 25 -- func_ov006_0212382c, 0x0212382c, size 0xa4 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
unsigned short func_ov006_0212382c(int sel, int b)
{
    unsigned short r = 0;
    switch (sel) {
    case 0:
        if (b == 0) r |= 4;
        break;
    case 1:
        if (b == 0) r |= 0x60;
        else r |= 2;
        break;
    case 2:
        if (b == 0) r |= 0x48;
        break;
    case 3:
        if (b == 0) r |= 0x100;
        else r |= 0x28;
        break;
    case 4:
        if (b == 1) r |= 0x80;
        break;
    }
    return r;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 24 -- func_ov006_021237c8, 0x021237c8, size 0x64 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int func_ov006_021237c8(int x) {
    int r;
    if (x < 5) {
        r = (int)(((unsigned int)RandomIntInternal(&data_0209e650) & 0x7fffffff) >> 0x13);
        return r < 0xc00 ? 4 : 5;
    }
    r = (int)(((unsigned int)RandomIntInternal(&data_0209e650) & 0x7fffffff) >> 0x13);
    return r < 0xc00 ? 6 : 7;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 23 -- func_ov006_0212373c, 0x0212373c, size 0x8c */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int func_ov006_0212373c(int a)
{
    int r;
    if (a < 5) {
        r = (int)(((unsigned int)RandomIntInternal(&data_0209e650) & 0x7fffffff) >> 0x13);
        if (r < 0xc00)
            return 4;
        if (r < 0xe00)
            return 5;
        return 8;
    }
    r = (int)(((unsigned int)RandomIntInternal(&data_0209e650) & 0x7fffffff) >> 0x13);
    if (r < 0xc00)
        return 6;
    if (r < 0xe00)
        return 8;
    return 7;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 22 -- func_ov006_02123428, 0x02123428, size 0x314 */
/* -------------------------------------------------------------------------- */
extern "C" void func_ov006_02123428(char *scene)
{
    int occupancy;
    int column;
    int kind;
    int kinds[7];
    short faces[7];
    Vec3i up;
    int i;
    int j;
    int variant;

    occupancy = 0;
    for (i = 0; i < 5; i++) {
        do {
            kind = (int)((((unsigned int)RandomIntInternal(&data_0209e650)
                           & 0x7fffffff) >> 0x13) * 11) >> 12;
        } while ((kind == 7 || kind == 10)
                 && (int)(((unsigned int)RandomIntInternal(&data_0209e650)
                            & 0x7fffffff) >> 0x13) > 0x400);

        for (;;) {
            for (j = 0; j < i; j++) {
                if (kind == kinds[j]) {
                    kind = (int)((((unsigned int)RandomIntInternal(&data_0209e650)
                                   & 0x7fffffff) >> 0x13) * 11) >> 12;
                    j = -1;
                }
            }

            column = func_ov006_021238d0(kind);
            {
                int shift = column * 2;
                int rightBit = 2 << shift;
                int leftBit = 1 << shift;
                int savedOccupancy;

                if ((occupancy & rightBit) != 0 &&
                    (occupancy & leftBit) != 0) {
                    do {
                        if (_Z14ApproachLinearRiii(&kind, 11, 1) != 0)
                            kind = 0;
                    } while ((kind == 7 || kind == 10)
                             && (int)(((unsigned int)RandomIntInternal(&data_0209e650)
                                       & 0x7fffffff) >> 0x13) > 0x800);
                    continue;
                }

                if ((savedOccupancy = (int)(volatile int)occupancy,
                     (savedOccupancy & rightBit) != 0)) {
                    kinds[i] = kind;
                    faces[i] = 8;
                    occupancy |= func_ov006_0212382c(column, 1);
                } else if ((savedOccupancy & leftBit) != 0) {
                    kinds[i] = kind;
                    faces[i] = (short)func_ov006_021237c8(kind);
                    occupancy |= func_ov006_0212382c(column, 0);
                } else {
                    kinds[i] = kind;
                    faces[i] = (short)func_ov006_0212373c(kind);
                    switch (faces[i]) {
                    case 4:
                    case 5:
                    case 6:
                    case 7:
                        occupancy |= func_ov006_0212382c(column, 0);
                        break;
                    default:
                        occupancy |= func_ov006_0212382c(column, 1);
                        break;
                    }
                }
            }
            break;
        }

        up.x = 0;
        up.y = 0x1000;
        up.z = 0;
        if (kind >= 5 ||
            ((kind & 1) != 0 && (faces[i] == 8 || faces[i] == 5))) {
            func_0203cc28((int *)&up, 0x4000);
        }

        variant = 1;
        if (faces[i] == 6)
            variant = 2;
        func_ov006_020cefa4((int)&data_ov006_0212f328 + kinds[i] * 0xc,
                            (int *)&up, variant, faces[i]);
    }
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 21 -- _ZN18dScMgTrampoline2_c8BehaviorEv, 0x02123340, size 0xe8 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c8BehaviorEv
/* dScMgTrampoline2_c::Behavior -- vtable slot 6, ov006 0x02123340.
 *
 * Attributed by the vtable: dScMgTrampoline2_c's own table is ov006 0x0213fc7c
 * and its slot 6 relocates here. The signature is include/dScMgBase_c.h's own
 * slot 6, `virtual s32 Behavior()`.
 *
 * IT READS THE GAP include/dScMgTrampoline2_c.h CALLS UNEVIDENCED. pad_7ac4 is
 * 0xc bytes between mArray5 and mArray6; this function uses the first word as
 * a Particle::System unique ID -- passed in and back out of NewUnkCallback818
 * each frame, exactly as dScMgJump2_c::Behavior does with its own unk_5a6c --
 * and the second as a fix12 value ramped towards 0x14000 and written into the
 * system's byte at +0x58. Both stay inside the pad rather than becoming named
 * fields: the third word is still unreached, and cutting the gap two-thirds of
 * the way along would assert a boundary nothing shows.
 *
 * The two Particle::System declarations keep the pre-migration file's local
 * `int` spelling rather than the true Fix12<int> their ROM names carry --
 * mwccarm passes by-value class parameters differently at the call site, so
 * declaring the real types breaks the byte match (notes/mwccarm-codegen.md
 * 6az). Its sibling src/_ZN12dScMgJump2_c8BehaviorEv.cpp says the same.
 *
 * ApproachLinear IS THE REAL OVERLOAD, `_Z14ApproachLinearRiii` at 0x0203ae58,
 * reached by declaring the C++ signature and letting the compiler mangle it --
 * not by decl_common.h's ApproachLinearI(int *, ...), which is a different
 * symbol.
 *
 * THE STATE CALLBACK IS A POINTER-TO-MEMBER STORED IN THE OBJECT, in the eight
 * bytes at 0x5004 the header calls pad_5004 -- the same arrangement, at the
 * same offset, dScMgJump2_c has, which is what two children of
 * dScMgD3DBase_c sharing a base ought to look like. */
s32 dScMgTrampoline2_c::Behavior()
{
    char *c = (char *)this;
    int saved = data_ov006_02140830;

    func_ov006_02120c40();
    func_ov006_020eef90();
    func_ov006_02122ab8();
    *(void **)(c + 0x7ac4) =
        _ZN8Particle6System17NewUnkCallback818Ejj5Fix12IiES2_S2_PK11Vector3_16f(
            *(unsigned int *)(c + 0x7ac4), 0xf0, 0x280000, 0x700000, -0x580000, 0);
    void *p = _ZN8Particle6System12FromUniqueIDEj(*(unsigned int *)(c + 0x7ac4));
    if (p != 0) {
        *(char *)((char *)p + 0x58) = (char)(*(int *)(c + 0x7ac8) >> 12);
        ApproachLinear(*(int *)(c + 0x7ac8), 0x14000, 0x200);
    }
    {
        dScMgTrampoline2_cState *pp = (dScMgTrampoline2_cState *)pad_5004;
        (this->**pp)();
    }
    func_ov006_02123938(this);
    if (saved != data_ov006_02140830) {
        func_ov004_020adb1c(data_ov006_02140830);
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 20 -- _ZN18dScMgTrampoline2_c6RenderEv, 0x021231ac, size 0x194 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c6RenderEv
/* dScMgTrampoline2_c::Render -- vtable slot 9, ov006 0x021231ac.
 *
 * Attributed by the vtable: dScMgTrampoline2_c's own table is ov006 0x0213fc7c
 * and its slot 9 relocates here. The signature is include/dScMgBase_c.h's own
 * slot 9, `virtual s32 Render()`.
 *
 * The two volatile stores are the 3D engine's fog/clear registers at
 * 0x040004c8 and 0x040004cc, the same pair dScMgSingle3DBase_c's own
 * AfterCleanupResources writes -- here the colour is built from a rotated
 * vector rather than being a constant. They stay `volatile` because this is
 * memory-mapped I/O, not codegen steering.
 *
 * unk_7ba8 is this class's own, and reads as a member; the three-word `m` is a
 * local the rotation helper fills in place. */
s32 dScMgTrampoline2_c::Render()
{
    int m[3];
    int count;
    int a1v;
    int i;

    m[0] = 0;
    m[1] = 0;
    m[2] = 0xfffff008;
    func_0203cd80(m, -0x4000);

    *(volatile int *)0x40004c8 =
        (((short)m[0] >> 3) & 0x3ff) |
        ((((short)m[1] >> 3) & 0x3ff) << 10) |
        ((((short)m[2] >> 3) & 0x3ff) << 20);
    *(volatile int *)0x40004cc = 0x7fff;
    *(volatile int *)0x40004cc = 0x40007fff;

    func_ov006_02120c08();
    func_ov006_020eef58();

    if (*(u16 *)((char *)this + 0x4664) == 1) {
        count = data_ov006_0213b0f0;
        a1v = 0x6e;
        if (GetOwnerLanguage() == 5 || GetOwnerLanguage() == 4)
            a1v -= 4;
        for (i = 0; i < 3; i++) {
            if (i >= count) {
                int idx = GetGameLanguage();
                DrawOamSprite((void *)data_ov006_0213fc48[idx][1], (void *)a1v, 0xc, (void *)0);
            } else {
                RenderOamMainScreen(data_ov006_02134ecc, a1v, 0xc, -1, -1);
            }
            a1v += 0x12;
        }
    }

    func_ov004_020b1a5c(data_ov006_02140830, 6);

    if (unk_7ba8 == 0) {
        func_ov006_020caadc();
        func_ov006_020d09e0();
        func_ov006_020ced84();
    }
    func_ov006_02122a4c();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 19 -- _ZN18dScMgTrampoline2_c16CleanupResourcesEv, 0x0212318c, size 0x20 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c16CleanupResourcesEv
/* dScMgTrampoline2_c::CleanupResources -- vtable slot 3, ov006 0x0212318c.
 *
 * Attributed by the vtable: dScMgTrampoline2_c's own table is ov006 0x0213fc7c
 * (the address include/dScMgTrampoline2_c.h's banner records) and its slot 3
 * relocates here, so this is this class's own override and not
 * dScMgD3DBase_c's. The signature is include/fBase_c.h's own slot 3,
 * `virtual s32 CleanupResources()`.
 *
 * Takes no argument in the ROM's own terms and reads nothing off the scene --
 * two teardown calls and a constant. func_ov004_020ad90c is spelled with no
 * parameter here and with one in dScMgMCarlo2_c's own CleanupResources;
 * `this` is already in r0 either way, so neither spelling is evidence about
 * its real arity. */
s32 dScMgTrampoline2_c::CleanupResources()
{
    func_ov006_020ceedc();
    func_ov004_020ad90c();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 18 -- _ZN18dScMgTrampoline2_c8OnKickedEv, 0x021230e8, size 0xa4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c8OnKickedEv
// recovered name: dScMgTrampoline2_c_OnKicked
/* recovered: renamed to Class_Method, declarations from a shared header */
/* recovered: renamed to Class_Method */
/* dScMgTrampoline2_c::OnKicked - recovered from vtable slot identity */
int dScMgTrampoline2_c::OnKicked()
{
    void *thiz = (void *)this;

    unsigned char *c = (unsigned char *)thiz;
    if (!_ZN14dScMgD3DBase_c8OnKickedEv(c)) return 0;
    if (*(int *)(c + 0x4628) == 0) {
        if (*(unsigned short *)(c + 0x4664) == 0) {
            data_0209d45c = data_0209d45c & ~8;
            SetBg2Offset(0, 0);
            *(int *)0x4000018 = 0;
        } else {
            data_0209d45c = data_0209d45c | 8;
            SetBg2Offset(0, 0xc0);
            *(int *)0x4000018 = 0xc00000;
        }
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 17 -- _ZN18dScMgTrampoline2_c8OnPushedEv, 0x021230c4, size 0x24 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c8OnPushedEv
// recovered name: dScMgTrampoline2_c_OnPushed
/* recovered: renamed to Class_Method, declarations from a shared header */
/* recovered: renamed to Class_Method */
/* dScMgTrampoline2_c::OnPushed - recovered from vtable slot identity */
int dScMgTrampoline2_c::OnPushed()
{
    void *t = (void *)this;
 return _ZN14dScMgD3DBase_c8OnPushedEv(t) != 0; }

/* -------------------------------------------------------------------------- */
/* ROM ordinal 16 -- _ZN18dScMgTrampoline2_c11OnAttacked2Ev, 0x02122f24, size 0x1a0 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c11OnAttacked2Ev
// recovered name: dScMgTrampoline2_c_OnAttacked2
/* recovered: renamed to Class_Method */
/* dScMgTrampoline2_c::OnAttacked2 - recovered from vtable slot identity */
int dScMgTrampoline2_c::OnAttacked2()
{
    char *self = (char *)this;

    u16 buf[5];

    if (!_ZN11dScMgBase_c11OnAttacked2Ev(this))
        return 0;

    {
        char* obj = data_0209f5bc;
        int (*vf)(char*) = *(int (**)(char*))(*(char**)obj + 0x14);
        if (vf(obj)) {
            data_ov006_0213fbc4 = 0;
        } else {
            char* obj2 = data_0209f5bc;
            int (*vf2)(char*) = *(int (**)(char*))(*(char**)obj2 + 0x1c);
            if (vf2(obj2))
                data_ov006_0213fbc4 = 1;
        }
    }

    if (data_ov006_0213fbc4 != 0)
        return 0;

    if (*(int*)(self + 0x4628) != 0)
        return 0;

    if (*(u8*)(self + 0x7bab) != 0) {
        s16 a = *(volatile s16*)(self + 0x7ba0);
        if ((a < 0x18 && *(volatile s16*)(self + 0x7b9c) < 0x18) ||
            (a > 0xe8 && *(volatile s16*)(self + 0x7b9c) > 0xe8)) {
            func_02012790(0xe);
        } else {
            buf[1] = *(s16*)(self + 0x7ba0);
            buf[2] = *(s16*)(self + 0x7ba2);
            buf[3] = *(s16*)(self + 0x7b9c);
            buf[4] = *(s16*)(self + 0x7b9e);
            if (func_ov006_020d0c38(&buf[1], &buf[3])) {
                func_02012718(0x1af, (*(s16*)(self + 0x7ba0) + *(s16*)(self + 0x7b9c)) << 11);
            } else {
                func_02012790(0xe);
            }
        }
        {
            char* dst = (char*)func_02054d88();
            buf[0] = 0;
            MultiStore16(buf[0], dst, 0x6000);
        }
        *(u8*)(self + 0x7baa) = 0;
        *(u8*)(self + 0x7bab) = 0;
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 15 -- func_ov006_02122e20, 0x02122e20, size 0x104 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02122e20(void *arg0, int arg1)
{
    struct Obj *self = (struct Obj *)arg0;
    volatile unsigned short t0;
    volatile unsigned short t1;
    int v = 0x7000;
    char *scrPtr;
    char *charPtr;
    int i;

    self->f68 = 1;
    self->f6c = arg1;

    switch (self->f6c) {
    case 0:
        scrPtr = _ZN2G212GetBG0ScrPtrEv();
        charPtr = (char *)func_02054efc();
        break;
    case 1:
        scrPtr = (char *)_ZN2G212GetBG1ScrPtrEv();
        charPtr = (char *)func_02054ea8();
        break;
    case 2:
        scrPtr = _ZN2G212GetBG2ScrPtrEv();
        charPtr = _ZN2G213GetBG2CharPtrEv();
        break;
    case 3:
        scrPtr = _ZN2G212GetBG3ScrPtrEv();
        charPtr = (char *)func_02054d88();
        break;
    default:
        return;
    }

    for (i = 0; i < 0x300; i++) {
        t0 = v;
        MultiStore16(t0, scrPtr, 2);
        v = (unsigned short)(v + 1);
        scrPtr += 2;
    }

    t1 = 0;
    MultiStore16(t1, charPtr, 0x6000);
    _ZN2GX10LoadBGPlttEPKvjj(data_ov006_0212f1ac, 0xe0, 0x20);
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 14 -- _ZN18dScMgTrampoline2_c9Virtual88Eiiii, 0x02122cb0, size 0x170 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN18dScMgTrampoline2_c9Virtual88Eiiii
/* dScMgTrampoline2_c::Virtual88 - slot 34.

   dScMgTrampoline_c's body again, reading data_ov006_02142f78 instead of
   _02142f6c.  They are separate addresses in the ROM rather than one shared
   one because dScMgD3DBase_c does not override this slot, so there is no common
   ancestor body for them to inherit. */
void dScMgTrampoline2_c::Virtual88(int x_base, int y, int val, int n)
{
    void *obj = (void *)this;

    int half;
    int x0;
    int j;
    int x;
    int *addr;
    int i;
    int yy;
    int mask = 0xf;

    half = n / 2;
    j = 0;
    if (j < n)
    {
        yy = y - half;
        x0 = x_base - half;
        do
        {
            for (i = 0; i < n; i++)
            {
                x = i + x0;
                if (x >= 0 && x < 0x100)
                {
                    if (yy >= 0 && yy < 0xc0)
                    {
                        void *ret;
                        int mode = *(int *)((char *)obj + 0x6c);

                        switch (mode)
                        {
                            case 0:
                                ret = func_02054efc();
                                break;
                            case 1:
                                ret = func_02054ea8();
                                break;
                            case 2:
                                ret = _ZN2G213GetBG2CharPtrEv();
                                break;
                            case 3:
                                ret = (void *)func_02054d88();
                                break;
                            default:
                                return;
                        }

                        addr = (int *)((char *)ret +
                            ((x / 8) + (yy / 8) * 32) * 32 +
                            (yy & 7) * 4);

                        MultiCopy_Int(addr, data_ov006_02142f78, 4);
                        data_ov006_02142f78[0] =
                            (data_ov006_02142f78[0] &
                             (-1 ^ (mask << ((x & 7) * 4)))) |
                            (val << ((x & 7) * 4));
                        MultiCopy_Int(data_ov006_02142f78, addr, 4);
                    }
                }
            }
            yy++;
            j++;
        } while (j < n);
    }
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 13 -- func_ov006_02122c90, 0x02122c90, size 0x20 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int func_ov006_02122c90(char *t)
{
    _ZN5ModelC1Ev(t);
    *(short *)(t + 0x76) = 0;
    return (int)t;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 12 -- func_ov006_02122c68, 0x02122c68, size 0x28 */
/* -------------------------------------------------------------------------- */
extern "C" Model* func_ov006_02122c68(Model* m){
  data_ov006_02142f80.Release();
  _ZN5ModelD1Ev(m);
  return m;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 11 -- func_ov006_02122c04, 0x02122c04, size 0x64 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02122c04(int x, int count) {
    int i;
    data_ov006_02142f7c = (unsigned char *)x;
    data_ov006_02142f74 = count;
    for (i = 0; i < data_ov006_02142f74; i++) {
        func_ov006_02122a1c((void*)(data_ov006_02142f7c + i * 0x78));
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 10 -- func_ov006_02122b88, 0x02122b88, size 0x7c */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02122b88(unsigned char *c)
{
  int i = 0;
  int n = data_ov006_02142f74;
  unsigned char *base;
  unsigned char *p;
  if (n <= 0)
  {
    return;
  }
  base = data_ov006_02142f7c;
  p = base;
  do
  {
    if ((*((short *) (p + 0x76))) == 0)
    {
      func_ov006_021228bc(base + (i * 0x78), c);
      return;
    }
    i++;
    p += 0x78;
  }
  while (i < data_ov006_02142f74);
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- func_ov006_02122b24, 0x02122b24, size 0x64 */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02122b24(void){
  int i = 0;
  if(data_ov006_02142f74 > 0){
    int off = 0;
    do {
      *(short*)(data_ov006_02142f7c + off + 0x76) = 0;
      i++;
      off += 0x78;
    } while(i < data_ov006_02142f74);
  }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- func_ov006_02122ab8, 0x02122ab8, size 0x6c */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02122ab8(void)
{
    int i;
    for (i = 0; i < data_ov006_02142f74; i++) {
        char *obj = (char *)data_ov006_02142f7c + i * 0x78;
        if (*(short *)(obj + 0x76) != 0) {
            func_ov006_0212287c(obj);
        }
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- func_ov006_02122a4c, 0x02122a4c, size 0x6c */
/* -------------------------------------------------------------------------- */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02122a4c(void)
{
    int i;
    for (i = 0; i < data_ov006_02142f74; i++) {
        char *obj = (char *)data_ov006_02142f7c + i * 0x78;
        if (*(short *)(obj + 0x76) != 0) {
            func_ov006_02122814(obj);
        }
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- func_ov006_02122a1c, 0x02122a1c, size 0x30 */
/* -------------------------------------------------------------------------- */
extern "C" void func_ov006_02122a1c(void* self)
{
    BMD_File* f = _ZN5Model8LoadFileER13SharedFilePtr(data_ov006_02142f80);
    _ZN9ModelBase7SetFileEP8BMD_Fileii(self, f, 1, -1);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- func_ov006_021228bc, 0x021228bc, size 0x160 */
/* -------------------------------------------------------------------------- */
extern "C" {
struct Tbl { int a, b, c; };
extern struct Tbl data_ov006_0213fbf8;
extern unsigned short data_ov006_0212f144[];
extern int RandomIntInternal(int* seed);
extern void func_020169f4(char* self, int kind);

void func_ov006_021228bc(void *r0, void *r1) {
    char* r5 = (char *)r0;
    int r4 = (int)r1;
    struct Tbl t = data_ov006_0213fbf8;
    unsigned int rnd = ((unsigned int)RandomIntInternal(&data_0209e650) & 0x7fffffff) >> 0x13;
    int idx;
    if ((int)rnd < t.a) {
        idx = 0;
    } else if ((int)rnd < t.b) {
        idx = 1;
    } else if ((int)rnd < t.c) {
        idx = 2;
    } else {
        idx = 3;
    }
    func_020169f4(r5, data_ov006_0212f144[idx]);
    int r1_4 = r4 * 0xA00;
    *(short*)(r5 + 0x76) = 0xF0;
    if (r1_4 > 0x4000) {
        r1_4 = 0x4000;
    }
    int r0_5 = r1_4 + 0x4000;
    *(int*)(r5 + 0x50) = r0_5;
    *(int*)(r5 + 0x54) = r0_5;
    *(int*)(r5 + 0x58) = r0_5;
    *(int*)(r5 + 0x5c) = 0x60000;
    *(int*)(r5 + 0x60) = 0x100000;
    *(int*)(r5 + 0x64) = 0x18000;
    int r1_9 = -0x1C00;
    *(int*)(r5 + 0x68) = r1_9;
    *(int*)(r5 + 0x6c) = r1_9;
    *(int*)(r5 + 0x70) = 0;
    unsigned int rnd2 = (unsigned int)RandomIntInternal(&data_0209e650);
    int* p1 = (int*)(r5 + 0x5c);
    int v1 = *p1 + ((((rnd2 & 0x7fffffff) >> 0x13) - 0x800) * 0x40);
    *p1 = v1;
    int rnd3 = RandomIntInternal(&data_0209e650);
    int* p2 = (int*)(r5 + 0x68);
    int adj3 = (int)(((unsigned int)rnd3 & 0x7fffffff) >> 0x13);
    *p2 -= adj3 >> 1;
    int rnd4 = RandomIntInternal(&data_0209e650);
    int* p3 = (int*)(r5 + 0x6c);
    int adj4 = (int)(((unsigned int)rnd4 & 0x7fffffff) >> 0x13);
    *p3 -= adj4 >> 1;
    func_02016a14(r5, 0);
    func_02016a04(r5, 0);
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- func_ov006_0212287c, 0x0212287c, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_0212287c
/* recovered: shared common types */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_0212287c(char* o){
  _Z15ApproachLinear2Rsss((short*)(o+0x76), 0, 1);
  short* p = (short*)((int)o + 0x74);
  *p = *p + 0x400;
  AddVec3((struct Vector3*)(o+0x5c), (struct Vector3*)(o+0x68), (struct Vector3*)(o+0x5c));
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- func_ov006_02122814, 0x02122814, size 0x68 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02122814
/* recovered: shared common types */
extern "C" void func_ov006_02122814(char *c) {
    Matrix4x3_FromTranslation(&data_020a0e68, *(int *)(c + 0x5c), *(int *)(c + 0x60), *(int *)(c + 0x64));
    Matrix4x3_ApplyInPlaceToRotationZ(&data_020a0e68, *(short *)(c + 0x74));
    *(Matrix4x3 *)(c + 0x1c) = data_020a0e68;
    ((C *)c)->v5(c + 0x50);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov006_021227c8, 0x021227c8, size 0x4c */
/* -------------------------------------------------------------------------- */
extern "C" {
extern void __destroy_arr(void* a, int b, int c, void* d);
extern void NullDestructor_0203d47c(void);
extern void _ZN18TextureTransformerD1Ev(void*);
extern void _ZN5ModelD1Ev(void*);
int func_ov006_021227c8(char* c){
  __destroy_arr(c+0x1a8, 5, 8, (void*)NullDestructor_0203d47c);
  _ZN18TextureTransformerD1Ev(c+0x194);
  _ZN5ModelD1Ev(c+0x140);
  _ZN5ModelD1Ev(c+0xf0);
  _ZN5ModelD1Ev(c+0xa0);
  return (int)c;
}
}

/* ROM ordinal 1 -- _ZN18dScMgTrampoline2_cD0Ev is generated from the one
   real destructor definition below. */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN18dScMgTrampoline2_cD1Ev, 0x021225ac, size 0x104 */
