//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov045/ExtendingPlatform  (9 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02111840  src/_ZN17ExtendingPlatformD1Ev.cpp
 *   [1] 0x02111878  src/_ZN17ExtendingPlatformD0Ev.cpp
 *   [2] 0x021118c4  src/_ZN17ExtendingPlatform23UpdateColliderTransformEv.cpp
 *   [3] 0x021118f8  src/_ZN17ExtendingPlatform20UpdateModelTransformEv.cpp
 *   [4] 0x02111938  src/_ZN17ExtendingPlatform16CleanupResourcesEv.cpp
 *   [5] 0x02111970  src/_ZN17ExtendingPlatform16OnPendingDestroyEv.cpp
 *   [6] 0x02111974  src/_ZN17ExtendingPlatform6RenderEv.cpp
 *   [7] 0x021119c0  src/_ZN17ExtendingPlatform8BehaviorEv.cpp
 *   [8] 0x02111a30  src/_ZN17ExtendingPlatform13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "ExtendingPlatform.h"
#include "SharedFilePtr.h"

extern "C" {
extern "C" void Matrix4x3_FromRotationY(Matrix4x3 *, s32);
extern SharedFilePtr PoleLift_ClsnFile;
extern SharedFilePtr PoleLift_ModelFile;
extern "C" s32 func_0203aad0(dBgW_KcMbgSclY *);
extern "C" void _ZN14dBgW_KcMbgSclY9SetScaleYE5Fix12IiE( dBgW_KcMbgSclY *, s32);
extern "C" CLPS_Block data_ov045_021125b0;
extern "C" void _ZN14dBgW_KcMbgSclY7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block( dBgW_KcMbgSclY *, KCL_File *, const Matrix4x3 &, s32, s16, CLPS_Block &);
extern "C" void func_020396c0(void *, s32);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- _ZN17ExtendingPlatform13InitResourcesEv, 0x02111a30, size 0xa4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatform13InitResourcesEv
/* SetFile's by-value Fix12<int> is the same measured definition-side ABI wall
 * as SetScaleY. Keep the cartridge spelling at this call boundary. */
int ExtendingPlatform::InitResources()
{
    mModel.SetFile((BMD_File *)Model::LoadFile(PoleLift_ModelFile), 1, -1);
    UpdateModelTransform();
    UpdateColliderTransform();

    _ZN14dBgW_KcMbgSclY7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
        &mCollider, (KCL_File *)dBgW_Kc::LoadFile(PoleLift_ClsnFile),
        mColliderTransform, 0x1000, mAngleY, data_ov045_021125b0);
    func_020396c0(&mCollider, 4);
    mCollider.unk_4d = 1;
    mCollider.Enable(this);
    mGrowing = 1;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- _ZN17ExtendingPlatform8BehaviorEv, 0x021119c0, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatform8BehaviorEv
/* SetScaleY's ROM symbol carries a by-value Fix12<int>. Its definition remains
 * at the measured class-parameter ABI wall, so this caller preserves the exact
 * extern-C entry point while using the real owned collider. */
int ExtendingPlatform::Behavior()
{
    s32 scaleY = func_0203aad0(&mCollider);
    if (mGrowing) {
        _ZN14dBgW_KcMbgSclY9SetScaleYE5Fix12IiE(&mCollider, scaleY + 8);
        if (func_0203aad0(&mCollider) > 0x1000)
            mGrowing = 0;
    } else {
        _ZN14dBgW_KcMbgSclY9SetScaleYE5Fix12IiE(&mCollider, scaleY - 8);
        if (func_0203aad0(&mCollider) < 0x800)
            mGrowing = 1;
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN17ExtendingPlatform6RenderEv, 0x02111974, size 0x4c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatform6RenderEv
int ExtendingPlatform::Render()
{
    Vector3 scale;
    scale.x = 0x1000;
    scale.y = func_0203aad0(&mCollider);
    scale.z = 0x1000;
    mModel.Render(&scale);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN17ExtendingPlatform16OnPendingDestroyEv, 0x02111970, size 0x4 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatform16OnPendingDestroyEv
void ExtendingPlatform::OnPendingDestroy()
{
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN17ExtendingPlatform16CleanupResourcesEv, 0x02111938, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatform16CleanupResourcesEv
int ExtendingPlatform::CleanupResources()
{
    mCollider.Disable();
    PoleLift_ModelFile.Release();
    PoleLift_ClsnFile.Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN17ExtendingPlatform20UpdateModelTransformEv, 0x021118f8, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatform20UpdateModelTransformEv
void ExtendingPlatform::UpdateModelTransform()
{
    Matrix4x3_FromRotationY(&mModel.mat4x3, mAngleY);
    mModel.mat4x3.t.x = mPosX >> 3;
    mModel.mat4x3.t.y = mPosY >> 3;
    mModel.mat4x3.t.z = mPosZ >> 3;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN17ExtendingPlatform23UpdateColliderTransformEv, 0x021118c4, size 0x34 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatform23UpdateColliderTransformEv
void ExtendingPlatform::UpdateColliderTransform()
{
    Matrix4x3_FromRotationY(&mColliderTransform, mAngleY);
    mColliderTransform.t.x = mPosX;
    mColliderTransform.t.y = mPosY;
    mColliderTransform.t.z = mPosZ;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN17ExtendingPlatformD1Ev, 0x02111840, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN17ExtendingPlatformD1Ev
/* Real compiler-spelled complete destructor. The member layout makes mwccarm
 * destroy the collider, then the model, then the dActor_c base. */
ExtendingPlatform::~ExtendingPlatform()
{
}
