//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov006/MgBingoBallSlotsShot  (2 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02119824  src/MgBingoBallSlotsShot_Spawn.cpp
 *   [1] 0x02119900  src/func_ov006_02119900.c
 */

extern "C" {
extern void *_ZN7fBase_cnwEj(unsigned int sz);
extern int func_ov004_020b2adc(void *p);
extern void func_020733a8(void *obj, int a, int b, void *cb1, void *cb2);
extern int _ZTV16dScMgSmartball_c[];
extern void func_0203d738(void);
extern void NullDestructor_0203d47c(void);
extern void func_ov006_02119900(void);
extern void func_ov006_0210d894(void);
void *MgBingoBallSlotsShot_Spawn(void);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- func_ov006_02119900, 0x02119900, size 0x4 */
/* -------------------------------------------------------------------------- */
extern "C" void func_ov006_02119900(void)
{
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- MgBingoBallSlotsShot_Spawn, 0x02119824, size 0xdc */
/* -------------------------------------------------------------------------- */
// tu_create.py: the definition was inside an extern "C" block; the block was closed before it and the definition given explicit C linkage
extern "C" void *MgBingoBallSlotsShot_Spawn(void) {
    char *o = (char *)_ZN7fBase_cnwEj(0x629c);
    if (o != 0) {
        func_ov004_020b2adc(o);
        *(int *)o = (int)_ZTV16dScMgSmartball_c;
        func_020733a8(o + 0x47c8, 5, 8, (void *)func_0203d738, (void *)NullDestructor_0203d47c);
        func_020733a8(o + 0x4854, 0x10, 8, (void *)func_0203d738, (void *)NullDestructor_0203d47c);
        func_020733a8(o + 0x48d4, 0x10, 8, (void *)func_0203d738, (void *)NullDestructor_0203d47c);
        func_020733a8(o + 0x599c, 0x40, 0x24, (void *)func_ov006_02119900, (void *)func_ov006_0210d894);
    }
    return o;
}
