//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov006/MgPicturePoker  (3 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM build.
 *
 * REVIEWED. Almost every declaration below is irreducible, and that is the
 * finding rather than an omission: this TU is a `*_Spawn` factory that hand-rolls
 * construction over raw memory, so its callees are either ROM functions no header
 * can name (`func_ovNNN_########`, still unidentified) or C++ constructors invoked
 * on storage that holds no object yet, which no real C++ spelling reaches.
 * `fBase_c::operator new` is deliberately undeclared in include/fBase_c.h (CW
 * rejects the in-class form). The vtable symbols stay hand-declared because these
 * scene classes have no C++ definition yet.
 *
 * What WAS reducible is fixed: the redundant `extern "C"` nested inside the
 * `extern "C"` block, and two different spellings of the same vtable idiom.
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x020dbd54  src/MgPicturePoker_Spawn.cpp
 *   [1] 0x020dbe14  src/func_ov006_020dbe14.c
 *   [2] 0x020dbe30  src/func_ov006_020dbe30.c
 */

extern "C" {
void* _ZN7fBase_cnwEj(unsigned int);
void func_ov004_020b2adc(void*);
void _ZN8Particle10SysTrackerC1Ev(void*);
void func_ov006_020c1d80(void*);
void func_020733a8(void*, int, int, void*, void*);
extern int _ZTV19dScMgSingle3DBase_c[];
extern int _ZTV11dScMgCard_c[];
void func_ov006_020d96e0(void);
void func_ov006_020dbe30(int *);   /* reconciled: this TU defines it with a real signature */
void func_ov006_020d96f0(void);
void func_ov006_020dbe14(int *);   /* reconciled: this TU defines it with a real signature */
extern int data_ov006_0213bccc[];
extern int data_ov006_0213bcf4[];
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov006_020dbe30, 0x020dbe30, size 0x10 */
/* -------------------------------------------------------------------------- */
extern "C" void func_ov006_020dbe30(int *p) { p[0] = (int)data_ov006_0213bccc; }

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- func_ov006_020dbe14, 0x020dbe14, size 0x1c */
/* -------------------------------------------------------------------------- */
extern "C" void func_ov006_020dbe14(int *c){
  *c=(int)data_ov006_0213bccc;
  *c=(int)data_ov006_0213bcf4;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- MgPicturePoker_Spawn, 0x020dbd54, size 0xc0 */
/* -------------------------------------------------------------------------- */
extern "C" void* MgPicturePoker_Spawn(void){
  char* p = (char*)_ZN7fBase_cnwEj(0x539c);
  if (p) {
    func_ov004_020b2adc(p);
    *(int*)p = (int)_ZTV19dScMgSingle3DBase_c;
    _ZN8Particle10SysTrackerC1Ev(p + 0x471c);
    *(int*)p = (int)_ZTV11dScMgCard_c;
    func_ov006_020c1d80(p + 0x4f38);
    func_020733a8(p + 0x51a8, 5, 0x30, (void*)func_ov006_020dbe30, (void*)func_ov006_020d96e0);
    func_020733a8(p + 0x5298, 5, 0x30, (void*)func_ov006_020dbe14, (void*)func_ov006_020d96f0);
  }
  return p;
}
