//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov026/Submarine  (5 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021118b8  src/_ZN9SubmarineD1Ev.cpp
 *   [1] 0x021118fc  src/_ZN9SubmarineD0Ev.cpp
 *   [2] 0x02111954  src/_ZN9Submarine16CleanupResourcesEv.cpp
 *   [3] 0x02111998  src/_ZN9Submarine6RenderEv.cpp
 *   [4] 0x021119c0  src/_ZN9Submarine13InitResourcesEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "Submarine.h"
#include "decl_common.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow struct 'Base' */
struct Base { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void m(int); };

/* shadow struct 'Derived' */
struct Derived { char pad[0xd4]; Base base; };

extern "C" {
extern int Submarine_ClsnFile[];
extern void _ZN13SharedFilePtr7ReleaseEv(void *);
extern int Submarine_ModelFile[];
extern int _ZN5Model8LoadFileER13SharedFilePtr(void *);
extern void _ZN9ModelBase7SetFileEP8BMD_Fileii(void *, int, int, int);
extern void _ZN10dBgActor_c21UpdateModelPosAndRotYEv(void *);
extern void _ZN10dBgActor_c19UpdateClsnPosAndRotEv(void *);
extern int _ZN7dBgW_Kc8LoadFileER13SharedFilePtr(void *);
extern void _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(void *, int, void *, int, int, void *);
extern void _ZN4dBgW6EnableEP8dActor_c(void *, void *);
extern char data_0209caa0[];
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN9Submarine13InitResourcesEv, 0x021119c0, size 0xb0 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9Submarine13InitResourcesEv
// recovered name: daObjWlSubmarine_c_InitResources
/* recovered: renamed to Class_Method, declarations from a shared header */
/* recovered: renamed to Class_Method */
/* daObjWlSubmarine_c::InitResources - recovered from vtable slot identity */
s32 Submarine::InitResources() {
    char * c = (char *)this;
  void *m = (void*)_ZN5Model8LoadFileER13SharedFilePtr(data_ov026_02113ee4);
  _ZN9ModelBase7SetFileEP8BMD_Fileii(c+0xd4,(int)m,1,-1);
  _ZN10dBgActor_c21UpdateModelPosAndRotYEv(c);
  _ZN10dBgActor_c19UpdateClsnPosAndRotEv(c);
  {
    void *k = (void*)_ZN7dBgW_Kc8LoadFileER13SharedFilePtr(data_ov026_02113edc);
    _ZN10dBgW_KcMbg7SetFileEP8KCL_FileRK9Matrix4x35Fix12IiEsR10CLPS_Block(
        c+0x124,(int)k,c+0x2ec,0x199,*(short*)(c+0x8e),(void*)data_ov026_02112fd4);
  }
  if(*(int*)(data_0209caa0+4) & 0x204) return 0;
  _ZN4dBgW6EnableEP8dActor_c(c+0x124,c);
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN9Submarine6RenderEv, 0x02111998, size 0x28 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9Submarine6RenderEv
// recovered name: daObjWlSubmarine_c_Render
/* recovered: renamed to Class_Method */
/* daObjWlSubmarine_c::Render - recovered from vtable slot identity */
s32 Submarine::Render() {
    Derived * d = (Derived *)this; Base *b = &d->base; b->m(0); return 1; }

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- _ZN9Submarine16CleanupResourcesEv, 0x02111954, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9Submarine16CleanupResourcesEv
// recovered name: daObjWlSubmarine_c_CleanupResources
/* recovered: renamed to Class_Method, declarations from a shared header */
/* recovered: renamed to Class_Method */
/* daObjWlSubmarine_c::CleanupResources - recovered from vtable slot identity */
s32 Submarine::CleanupResources() {
    void * t = (void *)this;
    if (_ZN4dBgW9IsEnabledEv((char *)t + 0x124)) {
        _ZN4dBgW7DisableEv((char *)t + 0x124);
    }
    _ZN13SharedFilePtr7ReleaseEv(Submarine_ModelFile);
    _ZN13SharedFilePtr7ReleaseEv(Submarine_ClsnFile);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN9SubmarineD1Ev, 0x021118b8, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN9SubmarineD1Ev
/* recovered: real C++ destructor -- the compiler emits the whole body.
 * Vtable slot 16: one vtable store, the members in reverse, then ~dBgActor_c. */
Submarine::~Submarine()
{
}
