#!/usr/bin/env python3
"""gen_vs_char_groups.py -- bake the bros' category -> palette-index sets into a
C header the port compiles in.

WHAT THIS IS. The game side of per-character VS colour customisation
(SM64DS_VS_CHAR_COLORS) recolours Mario, Luigi and Wario by CATEGORY -- hat +
undershirt (tied as one colour), overalls, gloves, buttons and shoes -- using
the SAME Oklab family transform Yoshi already uses (port/hal/vs_palette_gen.h,
apply_transform / family_edit). That transform is generic over any index set;
what it needs per category is WHICH palette indices, in WHICH served BMD file,
under WHICH palette name, belong to that category on that character.

That membership already exists: it is the tangOS SM64DS Edition palette editor's
groups.json (app/exports/palettes/groups.json), whose overrides[] carry
{family, file, index, pal} rows the editor's user hand-corrected. This script
reads those overrides and emits port/hal/vs_char_groups.h -- a baked, flat table
of {char, category, file, pal, [indices]} records. Nothing is invented: an index
appears here only if it appears in groups.json.

WHAT IS TIED, AND WHAT IS MISSING (flagged, never invented):
  * Tango's category 1 is HAT + UNDERSHIRT as ONE colour, so the "Hat" and
    "Undershirt" families both map to category 0 here. They live in different
    files (hat in the head BMD, undershirt in the body BMD), so one colour drives
    two family_edit passes, each shaded from its own ROM anchor.
  * groups.json has NO "Buttons" override rows for ANY bro (the auto-clustered
    "torso yellow" family the editor renamed "Buttons" was never hand-overridden,
    so it is not in overrides[]), so category 3 (buttons) ships EMPTY for all
    three. Wario additionally has no "Undershirt" and no "Buttons" rename at all,
    plus a stray "jh4" family (auto "shoes yellow") that is not one of Tango's
    five categories; none of those contribute rows. These gaps are reported on
    stderr and left empty rather than guessed.

Run from the port worktree root:
    python port/tools/gen_vs_char_groups.py \
        --groups <path to groups.json> \
        --out port/hal/vs_char_groups.h
Defaults resolve groups.json in the sibling tangOS-SM64DS checkout.
"""
import argparse
import collections
import json
import os
import sys

# Tango's five categories, in his numbering (1..5 -> 0..4 here), each fed from
# one or more groups.json family names. HAT + UNDERSHIRT are tied into one.
CATEGORIES = [
    ("hat_undershirt", ("Hat", "Undershirt")),
    ("overalls",       ("Overalls",)),
    ("gloves",         ("Gloves",)),
    ("buttons",        ("Buttons",)),
    ("shoes",          ("Shoes",)),
]
CHARS = ["mario", "luigi", "wario"]   # engine order: 0 Mario, 1 Luigi, 2 Wario


def family_to_cat(family):
    for ci, (_name, fams) in enumerate(CATEGORIES):
        if family in fams:
            return ci
    return -1


def collect(groups):
    """Return records: list of dicts {chr, cat, file, pal, idx:[...]}, plus a
    gaps report keyed by (char, category_name)."""
    records = []
    present = collections.defaultdict(set)   # (char, cat) -> set of families seen
    for ci, char in enumerate(CHARS):
        cfg = groups.get(char)
        if not isinstance(cfg, dict):
            print("WARN: no override block for %s" % char, file=sys.stderr)
            continue
        # (cat, file, pal) -> sorted unique indices
        bucket = collections.defaultdict(set)
        for ov in cfg.get("overrides", []):
            cat = family_to_cat(ov["family"])
            if cat < 0:
                continue
            present[(char, cat)].add(ov["family"])
            bucket[(cat, ov["file"], ov["pal"])].add(int(ov["index"]))
        for (cat, fl, pal), idxs in bucket.items():
            records.append({
                "chr": ci, "cat": cat, "file": fl, "pal": pal,
                "idx": sorted(idxs),
            })
    records.sort(key=lambda r: (r["chr"], r["cat"], r["file"], r["pal"]))
    return records, present


def emit(records, present, groups_path):
    lines = []
    w = lines.append
    w("/* vs_char_groups.h -- GENERATED by port/tools/gen_vs_char_groups.py.")
    w(" * DO NOT EDIT BY HAND. Re-run the generator against the Studio's")
    w(" * groups.json to regenerate.")
    w(" *")
    w(" * The bros' category -> palette-index membership for VS per-character")
    w(" * colour (SM64DS_VS_CHAR_COLORS). Each record is one category's indices")
    w(" * in one served BMD's one named palette. Categories, in Tango's order:")
    w(" *   0 hat+undershirt (TIED)   1 overalls   2 gloves")
    w(" *   3 buttons                 4 shoes")
    w(" * Source: %s" % groups_path.replace("\\", "/"))
    w(" *")
    w(" * COVERAGE, measured from groups.json overrides (empty = no data, left")
    w(" * on the ROM, NOT invented):")
    catnames = [c[0] for c in CATEGORIES]
    for ci, char in enumerate(CHARS):
        parts = []
        for cat in range(len(CATEGORIES)):
            fams = present.get((char, cat))
            parts.append("%s=%s" % (catnames[cat],
                                    ",".join(sorted(fams)) if fams else "-"))
        w(" *   %-6s %s" % (char, "  ".join(parts)))
    w(" */")
    w("#ifndef PORT_HAL_VS_CHAR_GROUPS_H")
    w("#define PORT_HAL_VS_CHAR_GROUPS_H")
    w("")
    w("namespace vscg {")
    w("")
    w("enum { CAT_HAT_UNDERSHIRT = 0, CAT_OVERALLS = 1, CAT_GLOVES = 2,")
    w("       CAT_BUTTONS = 3, CAT_SHOES = 4, CAT_COUNT = 5 };")
    w("")
    w("struct Group {")
    w("    int         chr;    /* 0 Mario, 1 Luigi, 2 Wario */")
    w("    int         cat;    /* 0..4, the category above */")
    w("    const char *file;   /* served BMD path, e.g. data/player/mario_model.bmd */")
    w("    const char *pal;    /* palette name inside that BMD, e.g. mario_body_pl */")
    w("    int         count;  /* number of indices */")
    w("    const int  *idx;    /* the palette indices this category owns */")
    w("};")
    w("")
    # index arrays
    for i, r in enumerate(records):
        arr = ", ".join(str(x) for x in r["idx"])
        w("static const int kIdx_%d[%d] = { %s };" % (i, len(r["idx"]), arr))
    w("")
    w("static const Group kVscGroups[] = {")
    for i, r in enumerate(records):
        w('    { %d, %d, "%s", "%s", %d, kIdx_%d },'
          % (r["chr"], r["cat"], r["file"], r["pal"], len(r["idx"]), i))
    w("};")
    w("static const int kVscGroupCount = %d;" % len(records))
    w("")
    w("} /* namespace vscg */")
    w("")
    w("#endif /* PORT_HAL_VS_CHAR_GROUPS_H */")
    return "\n".join(lines) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    default_groups = os.path.normpath(os.path.join(
        here, "..", "..", "..", "tangOS-SM64DS", "app", "exports", "palettes",
        "groups.json"))
    default_out = os.path.normpath(os.path.join(here, "..", "hal",
                                                "vs_char_groups.h"))
    ap = argparse.ArgumentParser()
    ap.add_argument("--groups", default=default_groups)
    ap.add_argument("--out", default=default_out)
    args = ap.parse_args()

    with open(args.groups, "r", encoding="utf-8") as f:
        groups = json.load(f)

    records, present = collect(groups)

    # Report coverage + gaps on stderr.
    catnames = [c[0] for c in CATEGORIES]
    print("vs_char_groups: %d records from %s (v%s)"
          % (len(records), args.groups, groups.get("version")), file=sys.stderr)
    for ci, char in enumerate(CHARS):
        for cat in range(len(CATEGORIES)):
            recs = [r for r in records if r["chr"] == ci and r["cat"] == cat]
            if recs:
                total = sum(len(r["idx"]) for r in recs)
                srcs = ", ".join("%s:%s(%d)"
                                 % (r["file"].split("/")[-1], r["pal"],
                                    len(r["idx"])) for r in recs)
                print("  %-6s %-14s %2d idx  [%s]"
                      % (char, catnames[cat], total, srcs), file=sys.stderr)
            else:
                print("  %-6s %-14s  GAP: no groups.json data, left on ROM"
                      % (char, catnames[cat]), file=sys.stderr)

    text = emit(records, present, args.groups)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s" % args.out, file=sys.stderr)


if __name__ == "__main__":
    main()
