#!/usr/bin/env python3
"""Consolidate the per-emitter ROM-CLEAN parts into ONE runtime file + dispatch.

ROM-CLEAN (2026-08-10): romdata.py and each ovdata.py invocation write their ROM
bytes to a sidecar <out>.blobpart (+ .blobmap) instead of baking them into the
exe. This tool runs LAST (like ovdata's --cross pass), given every part, and:

  1. concatenates the parts, in a stable order, into build/assets/romdata.bin;
  2. writes build/assets/romdata.manifest -- the loud-trap contract the loader
     checks (whole-file sha, per-part base+size+sha, per-symbol size+sha);
  3. generates romdata_dispatch.c, whose port_romdata_load_all(blob) calls each
     part's port_<tag>_apply(blob + <that part's base>).

The exe links romdata_dispatch.c; hal/romdata_loader.cpp reads romdata.bin,
verifies it against the manifest, and calls port_romdata_load_all. No ROM bytes
live in the binary.

    python tools/romblob.py <romdata.bin> <manifest> <dispatch.c> \
        <part1.blobmap> <part2.blobmap> ...

A .blobmap's sibling .blobpart holds the bytes; the map holds the ordered
(name, size, sha) list and the emitter tag. Parts are ordered by tag so the
consolidated file is deterministic regardless of CMake's argument order.
"""

import hashlib
import json
import pathlib
import sys


def main():
    bin_path = pathlib.Path(sys.argv[1])
    manifest_path = pathlib.Path(sys.argv[2])
    dispatch_path = pathlib.Path(sys.argv[3])
    map_paths = [pathlib.Path(p) for p in sys.argv[4:]]

    parts = []
    for mp in map_paths:
        doc = json.loads(mp.read_text())
        part_bin = pathlib.Path(str(mp)[:-len(".blobmap")] + ".blobpart") \
            if str(mp).endswith(".blobmap") else mp.with_suffix(".blobpart")
        raw = part_bin.read_bytes()
        # The map's own sha must match its bytes -- a stale part (regenerated .c
        # without its .blobpart) is a loud failure here, not a silent short blob.
        if hashlib.sha256(raw).hexdigest() != doc["sha256"]:
            sys.exit(f"romblob: {part_bin} bytes do not match {mp} sha -- "
                     "stale part, rebuild it")
        # The declared symbol sizes must sum to the part length, or the apply's
        # memcpy offsets would walk off the blob.
        declared = sum(sz for _, sz, _ in doc["syms"])
        if declared != len(raw):
            sys.exit(f"romblob: {mp} symbols sum to {declared} but the part is "
                     f"{len(raw)} bytes")
        parts.append((doc["tag"], raw, doc["syms"]))

    parts.sort(key=lambda p: p[0])          # deterministic by tag

    # Consolidate.
    blob = bytearray()
    manifest_parts = []
    for tag, raw, syms in parts:
        base = len(blob)
        blob += raw
        manifest_parts.append((tag, base, len(raw),
                               hashlib.sha256(raw).hexdigest(), syms))
    whole = hashlib.sha256(bytes(blob)).hexdigest()

    bin_path.parent.mkdir(parents=True, exist_ok=True)
    bin_path.write_bytes(bytes(blob))

    # The manifest. One header line, then a `part` line per emitter and a `sym`
    # line per symbol. The loader verifies the whole-file sha, each part's sha,
    # and each symbol's size; a mismatch is a FATAL abort naming the file.
    ml = [f"# romdata-manifest v1 {whole} {len(blob)}"]
    for tag, base, size, sha, syms in manifest_parts:
        ml.append(f"part\t{tag}\t{base}\t{size}\t{sha}")
        off = base
        for name, sz, ssha in syms:
            ml.append(f"sym\t{tag}\t{name}\t{off}\t{sz}\t{ssha}")
            off += sz
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text("\n".join(ml) + "\n", encoding="ascii")

    # The dispatch TU: call each part's apply with its base into the loaded blob.
    dl = ["/* GENERATED by port/tools/romblob.py -- ROM-CLEAN dispatch. */",
          "typedef unsigned char u8;", ""]
    # THE BUILD-IDENTITY STAMP, and why the dispatch is where it belongs.
    #
    # The bases below are BAKED INTO THE EXE. port_romdata_load_all memcpys each
    # part out of `blob + <base>`, so the blob the loader hands it must be the
    # blob these bases were computed from. Nothing in romdata.manifest can
    # establish that: the manifest SHIPS BESIDE the blob, so an asset folder
    # from an older build carries an older blob AND its own matching manifest,
    # every hash agrees, and the exe then fills every ROM table from the wrong
    # slice. port/tools/install_mismatch_probe.py builds exactly that pair and
    # shows the result: a world with impossible level data, then an access
    # violation. No player has reported it -- the hole was found by reading the
    # loader -- and the mechanism is real whether or not one has yet.
    #
    # So the same run that computes the bases also states, IN THE EXE, which
    # blob it computed them from. hal/romdata_loader.cpp compares. The stamp
    # lives here rather than in a hand-written header for the reason every
    # generated contract does: it cannot drift from the thing it describes,
    # because one function writes both.
    dl.append("/* The blob THIS dispatch's offsets were computed from. "
              "hal/romdata_loader.cpp")
    dl.append(" * refuses a romdata.bin that is not this one -- see the note in "
              "romblob.py. */")
    dl.append(f'const char port_romdata_expect_sha[] = "{whole}";')
    dl.append(f"const unsigned long long port_romdata_expect_len = "
              f"{len(blob)}ULL;")
    dl.append("")
    for tag, *_ in manifest_parts:
        dl.append(f"void port_{tag}_apply(const u8 *blob);")
    dl.append("")
    dl.append("/* Called by hal/romdata_loader.cpp once romdata.bin is read and")
    dl.append(" * verified against the manifest. Each part fills its own zeroed")
    dl.append(" * arrays from its slice of the consolidated blob. */")
    dl.append("void port_romdata_load_all(const u8 *blob)")
    dl.append("{")
    for tag, base, *_ in manifest_parts:
        dl.append(f"    port_{tag}_apply(blob + {base});")
    dl.append("}")
    dispatch_path.parent.mkdir(parents=True, exist_ok=True)
    dispatch_path.write_text("\n".join(dl) + "\n", encoding="ascii")

    print(f"romblob: {len(parts)} parts, {len(blob)} bytes -> {bin_path}")
    print(f"         manifest -> {manifest_path}")
    print(f"         dispatch -> {dispatch_path}")


if __name__ == "__main__":
    main()
