#!/usr/bin/env python3
"""Emit the ROM data constants the gate-4b slice references.

These are read-only tables in the arm9 image (sine table, identity matrices,
texture-matrix constants). They are Nintendo's bytes, so they are never
committed: this reads the local decompressed arm9 (extracted/arm9_dec.bin,
flat image based at 0x02000000) and writes a C file under the build tree.
"""

import pathlib
import struct
import sys

# extracted/arm9_dec.bin: the DECOMPRESSED arm9, flat at base 0x02004000
# (verified by two code anchors: Copy36Bytes @0x0205a548, DecompressLZ16
# @0x0205a754). extracted/dsd/arm9/arm9.bin is the COMPRESSED payload
# (arm9.yaml: compressed true) and must not be read directly. Addresses at
# or past bss_start are runtime-initialized and belong in the HAL.
BASE = 0x02004000
BSS_START = 0x02094640

# (symbol address, byte length, C element type). BSS addresses do not belong
# here -- they are runtime-initialized and live in the HAL as storage.
TABLES = [
    # A fourth column names ROM symbols the decomp spells by NAME rather than
    # by address. Model's migrated constructor assigns IDENTITY_MATRIX4X3, not
    # data_02082128, so the alias is emitted here beside the definition rather
    # than in a HAL file: a HAL alias would point at a symbol port_refcheck
    # cannot find in src/ or include/, because this datum is generated and
    # deliberately kept out of git.
    (0x02082128, 48, "int", ["IDENTITY_MATRIX4X3"]),  # Model ctor default Matrix4x3
    (0x02082190, 48, "int"),        # matrix Render uses for a NULL argument
    (0x02082214, 0x4000, "short"),  # s16 trig table the material bind indexes
    (0x020755A0, 12, "char"),       # OBJ width table (shape x size)
    (0x020755AC, 12, "char"),       # OBJ height table
]


def main():
    root = pathlib.Path(__file__).resolve().parents[2]
    img = root / "extracted/arm9_dec.bin"
    if not img.exists():
        sys.exit(f"missing {img} -- extract the ROM first")
    anchor = img.read_bytes()
    a = 0x0205A548 - BASE
    if anchor[a:a + 4] != b"\x0c\x10\xb0\xe8":
        sys.exit("arm9_dec.bin failed the Copy36Bytes anchor -- wrong image/base")
    for addr, length, _, *_rest in TABLES:
        if addr + length > BSS_START:
            sys.exit(f"{addr:#x}+{length:#x} crosses into BSS -- not file-backed")
    data = img.read_bytes()
    out_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else (
        root / "build/port/host-src/romdata.c")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = ["/* GENERATED by port/tools/romdata.py from extracted/arm9_dec.bin.",
             " * ROM constants stay out of git; regenerate locally. */", ""]
    for addr, length, ctype, *rest in TABLES:
        off = addr - BASE
        blob = data[off:off + length]
        if len(blob) != length:
            sys.exit(f"short read at {addr:#x}")
        width = 4 if ctype == "int" else 2
        fmt = "<i" if ctype == "int" else "<h"
        vals = [struct.unpack_from(fmt, blob, i)[0] for i in range(0, length, width)]
        name = f"data_{addr:08x}"
        body = ", ".join(str(v) for v in vals)
        lines.append(f"{ctype} {name}[{len(vals)}] = {{ {body} }};")
        # MSVC decorates a C symbol with a leading underscore and a C++ one with
        # its type, and callers of both spellings have to reach the same bytes,
        # so each alias is emitted in both decorations.
        for alias in (rest[0] if rest else []):
            for dec in (f'_{alias}', f'?{alias}@@3UMatrix4x3@@A'):
                lines.append(
                    f'#pragma comment(linker, "/alternatename:{dec}=_{name}")')
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="ascii")
    print(f"romdata -> {out_path}")


if __name__ == "__main__":
    main()
