//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov002/daObjHeart_c  (8 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled daObjKm2_Ami_Bou_c::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x020bc5e0  src/_ZN12daObjHeart_cD1Ev.cpp
 *   [1] 0x020bc618  src/_ZN12daObjHeart_cD0Ev.c
 *   [2] 0x020bc664  src/func_ov002_020bc664.c
 *   [3] 0x020bc6a4  src/_ZN12daObjHeart_c16CleanupResourcesEv.cpp
 *   [4] 0x020bc6d4  src/_ZN12daObjHeart_c6RenderEv.cpp
 *   [5] 0x020bc6fc  src/_ZN12daObjHeart_c8BehaviorEv.cpp
 *   [6] 0x020bc81c  src/_ZN12daObjHeart_c13InitResourcesEv.cpp
 *   [7] 0x020bc8b4  src/daObjHeart_c_classInit.c
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "decl_Actor.h"
#include "decl_ModelAnim.h"
#include "decl_dCcAc_c.h"
#include "decl_common.h"
#include "daObjHeart_c.h"
#include "SharedFilePtr.h"
#include "decl_ActorBase.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win.
 * dActor_c/ModelAnim/dCcAc_c/daObjHeart_c shadow structs dropped here: real
 * definitions come from daObjHeart_c.h (and its own includes), included
 * above -- same reconciliation as WingFeather/#1727 and daObjWakame_c/#1728. */
extern "C" {
extern void *data_020a0eac;
extern void Matrix4x3_FromRotationY(void *, int);
void _ZN13SharedFilePtr7ReleaseEv(void *);
u8   DecIfAbove0_Byte(u8 *p);
void *_ZN8dActor_c10FindWithIDEj(u32 id);
void _ZN6Player4HealEi(char *player, int amount);
void _ZN5Sound9PlayBank3EjRK7Vector3(u32 id, const Vector3 *pos);
void Math_Function_0203b14c(int *p, int a, int b, int c, int d);
typedef int Fix12i;
struct BMD_File; struct BCA_File;
extern SharedFilePtr data_ov002_0210e104;
extern SharedFilePtr data_ov002_0210e0fc;
extern BMD_File* _ZN5Model8LoadFileER13SharedFilePtr(SharedFilePtr& f);
extern void _ZN9ModelBase7SetFileEP8BMD_Fileii(void* m, BMD_File* f, int a, int b);
extern BCA_File* _ZN9Animation8LoadFileER13SharedFilePtr(SharedFilePtr& f);
extern void _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(void* m, BCA_File* f, int a, Fix12i b, unsigned int c);
extern void _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj(void* m, void* a, Fix12i r, Fix12i h, unsigned int f1, unsigned int f2);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- daObjHeart_c_classInit, 0x020bc8b4, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol daObjHeart_c_classInit
/* recovered: vtable identified, globals resolved, declarations from a shared header */
/* recovered: vtable identified, globals resolved */
/* resolved: VT0 = _ZTV12daObjHeart_c */
extern "C" {  /* .c-derived member: C linkage for the whole block */
int *daObjHeart_c_classInit(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(372);
    if (p) {
        _ZN8dActor_cC2Ev(p);
        p[0] = (int)&_ZTV12daObjHeart_c[2]; /* +8: this TU defines the vtable */
        _ZN9ModelAnimC1Ev((char *)p + 0xd4);
        _ZN7dCcAc_cC1Ev((char *)p + 0x138);
    }
    return p;
}
}

/* The 0x1c spawn descriptor at ov002 0x02109c50, emitted right after the factory
 * it points at.  Field order and widths are the actor_profile_0x1c layout the
 * recovered fBase_c/dActor_c constructors read. */
struct HeartSpawnInfo {
    int *(*classInit)();
    s16 profileIDAndExecuteOrder;
    s16 drawOrder;
    u32 actorFlags;
    s32 clipOffsetY;
    s32 clipRadius;
    s32 clipDistance;
    s32 farDistance;
};
typedef char HeartSpawnInfo_size_must_be_0x1c[sizeof(HeartSpawnInfo) == 0x1c ? 1 : -1];

// @symbol g_profile_HEART
extern "C" HeartSpawnInfo g_profile_HEART = {
    daObjHeart_c_classInit, 0x0129, 0x00aa, 0x00000003,
    0x00060000, 0x00060000, 0x01000000, 0x01000000
};

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN12daObjHeart_c13InitResourcesEv, 0x020bc81c, size 0x98 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjHeart_c13InitResourcesEv
/* recovered: named members + shared header, real C++ method, declarations from a shared header */
/* recovered: named members + shared header, real C++ method */
int daObjHeart_c::InitResources()
{
  _ZN9ModelBase7SetFileEP8BMD_Fileii(((char*)this)+0xd4, _ZN5Model8LoadFileER13SharedFilePtr(data_ov002_0210e104), 1, -1);
  _ZN9ModelAnim7SetAnimEP8BCA_Filei5Fix12IiEj(((char*)this)+0xd4, _ZN9Animation8LoadFileER13SharedFilePtr(data_ov002_0210e0fc), 0, 0x1000, 0);
  _ZN7dCcAc_c4InitEP8dActor_c5Fix12IiES3_jj(((char*)this)+0x138, ((char*)this), 0x3c000, 0x78000, 0x100002, 0x8000);
  mAnimSpeed = 0x1000;
  func_ov002_020bc664(((char*)this));
  return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN12daObjHeart_c8BehaviorEv, 0x020bc6fc, size 0x120 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjHeart_c8BehaviorEv
/* daObjHeart_c::Behavior -- once something is standing in the collider, heal
 * that actor if it is the player (object id 0xbf), then start a 90-frame
 * cooldown. The heart spins slowly while idle and fast while cooling down.
 *
 * The heal amount is 0x100 up to 8 hit points and then 0x100 per four points
 * above that, which is the `(hp - 8) / 4 + 1' shifted into the same 8.8 form.
 *
 * dActor_c::FindWithID, Player::Heal, Sound::PlayBank3, DecIfAbove0_Byte and
 * Math_Function_0203b14c have no headers here, so those five stay extern-C.
 * The actor FindWithID hands back is reached by offset for the same reason the
 * player is in dBgActor_c::KillByMegaChar: this TU has no use for Player.h
 * beyond two words.
 */
int daObjHeart_c::Behavior()
{
    int spin = 0x1000;
    DecIfAbove0_Byte(&mHealTimer);

    if (mdCcAc_c.otherOwner != 0) {
        if (mWasTouched == 0) {
            mWasTouched = 1;
            mHealTimer = 0;
        }
        if (mHealTimer == 0) {
            char *other = (char *)_ZN8dActor_c10FindWithIDEj(mdCcAc_c.otherOwner);
            if (other != 0) {
                int isPlayer = (int)(*(u16 *)(other + 0xc) == 0xbf);
                if (isPlayer != 0) {
                    int hp = *(int *)(other + 0x98) / 0x1000;
                    int amount = 0x100;
                    if (hp >= 8) {
                        hp -= 8;
                        amount = (hp / 4 + 1) << 8;
                    }
                    _ZN6Player4HealEi(other, amount);
                    _ZN5Sound9PlayBank3EjRK7Vector3(0x61, (Vector3 *)&mCamSpacePosX);
                }
            }
            mHealTimer = 0x5a;
        }
    } else {
        mWasTouched = 0;
    }

    if (mHealTimer > 0x2d)
        spin = 0x8000;
    Math_Function_0203b14c(&mAnimSpeed, spin, 0x400, 0x2000, 0x80);
    mModelAnim.speed = mAnimSpeed;
    mModelAnim.Advance();
    mdCcAc_c.Clear();
    mdCcAc_c.Update();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN12daObjHeart_c6RenderEv, 0x020bc6d4, size 0x28 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjHeart_c6RenderEv
/* recovered: named members + shared header, real C++ method */
int daObjHeart_c::Render()
{
    mModelAnim.Render(0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN12daObjHeart_c16CleanupResourcesEv, 0x020bc6a4, size 0x30 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjHeart_c16CleanupResourcesEv
/* daObjHeart_c::CleanupResources -- vtable slot 3. Releases the two shared files the class
 * holds; it never touches `this`, which is why the legacy C form could declare
 * itself nullary and still reproduce. */
int daObjHeart_c::CleanupResources()
{
    data_ov002_0210e104.Release();
    data_ov002_0210e0fc.Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov002_020bc664, 0x020bc664, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov002_020bc664
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov002_020bc664(void *tv)
{
    char *t = (char *)tv;
    Matrix4x3_FromRotationY(t + 0xf0, *(short *)(t + 0x8e));
    *(int *)(t + 0x114) = *(int *)(t + 0x5c) >> 3;
    *(int *)(t + 0x118) = *(int *)(t + 0x60) >> 3;
    *(int *)(t + 0x11c) = *(int *)(t + 0x64) >> 3;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN12daObjHeart_cD0Ev, 0x020bc618, size 0x4c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjHeart_cD0Ev
/* Not written out. The destructor is inline in include/daObjHeart_c.h, so mwcc
 * emits the D1/D0 pair itself, in the ROM's own order and with no homeless D2.
 * A hand-written D0 free function beside a real out-of-line D1 in one TU is an
 * mwcc ICE (ELFgen.c:483) besides. */

/* -------------------------------------------------------------------------- */
/* ROM ordinal 0 -- _ZN12daObjHeart_cD1Ev, 0x020bc5e0, size 0x38 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjHeart_cD1Ev
/* Also compiler-emitted from the inline header destructor. The body it generates
 * destroys mdCcAc_c at +0x138 and mModelAnim at +0xd4, then chains to the
 * dActor_c base -- the member destruction the ROM's own D1 performs. */
