//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov013/daObjClock_c  (9 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled daObjKm2_Ami_Bou_c::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x021113bc  src/_ZN12daObjClock_cD1Ev.cpp
 *   [1] 0x021113ec  src/_ZN12daObjClock_cD0Ev.cpp
 *   [2] 0x02111430  src/func_ov013_02111430.c
 *   [3] 0x02111478  src/_ZN12daObjClock_c16CleanupResourcesEv.cpp
 *   [4] 0x021114a4  src/_ZN12daObjClock_c6RenderEv.cpp
 *   [5] 0x021114cc  src/_ZN12daObjClock_c8BehaviorEv.cpp
 *   [6] 0x021115cc  src/_ZN12daObjClock_c13InitResourcesEv.cpp
 *   [7] 0x0211163c  src/ClockPaintingHandShort_Spawn.cpp
 *   [8] 0x02111674  src/ClockPaintingHandLong_Spawn.c
 *
 * plus the two 0x1c actor descriptors this TU also owns, .data
 * 0x021121a4..0x0211227c: _ZTI/_ZTS for the class, g_profile_CLOCK_LONG,
 * g_profile_CLOCK_SHORT, and the _ZTV whose address point is 0x02112200.
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daObjClock_c.h"
#include "decl_common.h"
#include "SharedFilePtr.h"

extern "C" {
extern void Matrix4x3_FromRotationZXYExt(void *, int, int, int);
int IsAreaShowing(int areaId);
extern signed char data_02092110[];
extern unsigned char data_0209f2c0[];
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- ClockPaintingHandLong_Spawn, 0x02111674, size 0x38        */
/* ROM ordinal 7 -- ClockPaintingHandShort_Spawn, 0x0211163c, size 0x38       */
/* -------------------------------------------------------------------------- */
/* ONE CLASS, TWO PROFILES. CLOCK_LONG (actor 293) and CLOCK_SHORT (actor 292)
 * each own a descriptor and a byte-identical factory; both install the same
 * vtable at 0x02112200 and the same 0x128 allocation, and InitResources tells
 * them apart at run time by actorID.
 *
 * The factories keep their coined spellings. The registry's
 * factory_rename_recommended is `no` for both rows for exactly this reason
 * (not_apply=global_classinit_name_collision): the EAD convention would name
 * both daObjClock_c_classInit, and two C-linkage definitions cannot share one
 * name. Only the two profile records are renamed, to the spellings the ROM's
 * own debug string table proves -- CLOCK_SHORT at 0x02090230, CLOCK_LONG at
 * 0x0208ffa8. */
extern "C" {
extern void *_ZN7fBase_cnwEj(u32 size);
extern void _ZN8dActor_cC2Ev(void *self);
extern void _ZN5ModelC1Ev(void *self);
extern int _ZTV12daObjClock_c[];

// @symbol ClockPaintingHandLong_Spawn
int *ClockPaintingHandLong_Spawn(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(296);
    if (p) {
        _ZN8dActor_cC2Ev(p);
        /* &[2], not the bare symbol: this TU EMITS the vtable, so mwcc's symbol
         * is the object start at 0x021121f8 and +8 is what reaches the
         * 0x02112200 address point. The addend-0 spelling is right only for a
         * TU that imports its vtable. */
        p[0] = (int)&_ZTV12daObjClock_c[2];
        _ZN5ModelC1Ev((char *)p + 0xd4);
    }
    return p;
}

// @symbol ClockPaintingHandShort_Spawn
int *ClockPaintingHandShort_Spawn(void)
{
    int *p = (int *)_ZN7fBase_cnwEj(296);
    if (p) {
        _ZN8dActor_cC2Ev(p);
        p[0] = (int)&_ZTV12daObjClock_c[2];
        _ZN5ModelC1Ev((char *)p + 0xd4);
    }
    return p;
}
}

/* The 0x1c actor descriptor, `actor_profile_0x1c` in
 * symbols/profile_reconstruction_registry.tsv. Emitted in SOURCE order, which
 * is why CLOCK_LONG (0x021121c0) is written before CLOCK_SHORT (0x021121dc). */
struct ClockSpawnInfo {
    int *(*classInit)();
    s16 profileIDAndExecuteOrder;
    s16 drawOrder;
    u32 actorFlags;
    s32 clipOffsetY;
    s32 clipRadius;                 /* 0x1000 == 1.0 */
    s32 clipDistance;
    s32 farDistance;
};
typedef char ClockSpawnInfo_size_must_be_0x1c[sizeof(ClockSpawnInfo) == 0x1c ? 1 : -1];

// @symbol g_profile_CLOCK_LONG
extern "C" ClockSpawnInfo g_profile_CLOCK_LONG = {
    ClockPaintingHandLong_Spawn, 0x0125, 0x00a3, 0x00000006,
    0x00064000, 0x000fa000, 0x00c80000, 0x00640000
};

// @symbol g_profile_CLOCK_SHORT
extern "C" ClockSpawnInfo g_profile_CLOCK_SHORT = {
    ClockPaintingHandShort_Spawn, 0x0124, 0x00a2, 0x00000006,
    0x00064000, 0x000fa000, 0x00c80000, 0x00640000
};

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN12daObjClock_c13InitResourcesEv, 0x021115cc, size 0x70 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjClock_c13InitResourcesEv
/* recovered: typed actor, model, and shared-file ownership */
int daObjClock_c::InitResources()
{
    int isShortHand = (int)(actorID == 0x125);
    if (isShortHand != 0)
        mHandIndex = 0;
    else
        mHandIndex = 1;
    {
        unsigned char index = mHandIndex;
        SharedFilePtr &file = *(SharedFilePtr *)data_ov013_021116b0[index];
        mModel.SetFile((BMD_File *)Model::LoadFile(file), 1, -1);
    }
    func_ov013_02111430((char *)this);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- _ZN12daObjClock_c8BehaviorEv, 0x021114cc, size 0x100 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjClock_c8BehaviorEv
/* recovered: real C++ method over inherited actor fields */
int daObjClock_c::Behavior()
{
    if (data_02092110[0] <= 0) {
        mAngleZ += data_ov013_021116ac[mHandIndex];
    } else if (IsAreaShowing(mAreaId) && mHandIndex == 0) {
        unsigned short angle = (unsigned short)-mAngleZ;
        if (angle < 0x2000)
            data_0209f2c0[0] = 3;
        else if (angle < 0x6000 && angle >= 0x2000)
            data_0209f2c0[0] = 0;
        else if (angle < 0xa000 && angle >= 0x6000)
            data_0209f2c0[0] = 2;
        else if (angle < 0xe000 && angle >= 0xa000)
            data_0209f2c0[0] = 1;
        else if (angle >= 0xe000)
            data_0209f2c0[0] = 3;
    }
    func_ov013_02111430((char *)this);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- _ZN12daObjClock_c6RenderEv, 0x021114a4, size 0x28 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjClock_c6RenderEv
/* recovered: real C++ method over the owned Model */
int daObjClock_c::Render()
{
    mModel.Render(0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- _ZN12daObjClock_c16CleanupResourcesEv, 0x02111478, size 0x2c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjClock_c16CleanupResourcesEv
/* recovered: typed file ownership through the shared class APIs */
int daObjClock_c::CleanupResources()
{
    ((SharedFilePtr *)data_ov013_021116b0[mHandIndex])->Release();
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov013_02111430, 0x02111430, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov013_02111430
/* Not a vtable slot and not provably a member, so it keeps its func_ name and
 * its raw offsets: it reaches dActor_c's angle triple at +0x8c..+0x90 and the
 * matrix at +0xf0, none of which this class owns. The marker above is not
 * decoration -- without it tools/tiers.py folds this body into the preceding
 * member's fragment and scores these offsets against CleanupResources. */
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov013_02111430(char *t)
{
    Matrix4x3_FromRotationZXYExt(t + 0xf0, *(short *)(t + 0x8c), *(short *)(t + 0x8e), *(short *)(t + 0x90));
    *(int *)(t + 0x114) = *(int *)(t + 0x5c) >> 3;
    *(int *)(t + 0x118) = *(int *)(t + 0x60) >> 3;
    *(int *)(t + 0x11c) = *(int *)(t + 0x64) >> 3;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN12daObjClock_cD0Ev, 0x021113ec, size 0x44              */
/* ROM ordinal 0 -- _ZN12daObjClock_cD1Ev, 0x021113bc, size 0x30              */
/* -------------------------------------------------------------------------- */
// @symbol _ZN12daObjClock_cD1Ev
// @symbol _ZN12daObjClock_cD0Ev
/* Both destructors are emitted from the INLINE `~daObjClock_c() {}` in
 * include/daObjClock_c.h -- there is deliberately no body here.
 *
 * A complete-object destructor stores this class's vtable over the one the base
 * constructor left, destroys members in reverse declaration order, then runs the
 * base subobject destructor; the deleting destructor does that and calls
 * operator delete. All of it follows from `: dActor_c` and the member types, so
 * the compiler writes both bodies and the bytes still reproduce.
 *
 * Defining ~daObjClock_c() out of line HERE instead would break the TU two ways:
 * mwccarm would emit D0 at 0x021113ec's slot before D1 at 0x021113bc's,
 * reversing ROM order so objisolate refuses the entire TU, and it would emit a
 * third symbol, D2, which has no address anywhere in the cartridge. See the
 * vtable comment in the header.
 */
