//cpp
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov098/daObjFallBlock_c  (12 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order):
 *   [0] 0x02139f70  src/_ZN16daObjFallBlock_cD0Ev.cpp
 *   [1] 0x02139fc8  src/_ZN16daObjFallBlock_cD1Ev.cpp
 *   [2] 0x0213a00c  src/func_ov098_0213a00c.cpp
 *   [3] 0x0213a0a8  src/func_ov098_0213a0a8.cpp
 *   [4] 0x0213a0e8  src/func_ov098_0213a0e8.c
 *   [5] 0x0213a148  src/func_ov098_0213a148.c
 *   [6] 0x0213a17c  src/_ZN16daObjFallBlock_c4KillEv.cpp
 *   [7] 0x0213a23c  src/func_ov098_0213a23c.c
 *   [8] 0x0213a284  src/_ZN16daObjFallBlock_c15OnHitByMegaCharER6Player.cpp
 *   [9] 0x0213a2cc  src/func_ov098_0213a2cc.c
 *   [10] 0x0213a314  src/_ZN16daObjFallBlock_c6RenderEv.cpp
 *   [11] 0x0213a36c  src/_ZN16daObjFallBlock_c8BehaviorEv.cpp
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "daObjFallBlock_c.h"
#include "Sound.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow typedef 's16' */
typedef short s16;

/* shadow struct 'Vector3' */
struct Vector3;

/* shadow struct 'dActor_c' */
struct dActor_c;

#define U64 0xFFFFFFFFFFFFFFFFLL
#define BASE(c, off) ((char *)(((int)(c) + (off)) & U64))

extern "C" {
dActor_c* _ZN8dActor_c15FindWithActorIDEjPS_(unsigned int id, dActor_c* after);
s16 Vec3_HorzAngle(const Vector3 *v0, const Vector3 *v1);
int Vec3_Dist(const Vector3* a, const Vector3* b);
int AngleDiff(int a, int b);
void func_ov098_0213a00c(char *c);
extern "C" void _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_( u32 id, Fix12i x, Fix12i y, Fix12i z);
extern void Matrix4x3_FromRotationXYZExt(void *, int, int, int);
extern int _ZN4dBgW9IsEnabledEv(void *);
extern void _ZN4dBgW7DisableEv(void *);
extern void _ZN13SharedFilePtr7ReleaseEv(void *);
int DecIfAbove0_Byte(u8 *p);
int DecIfAbove0_Short(u16 *p);
void _ZN5Sound9PlayBank3EjRK7Vector3(unsigned id, void *pos);
void *_ZN8dActor_c13ClosestPlayerEv(void *self);
int Vec3_HorzDist(void *a, void *b);
int _ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(void *self, int a, int b);
void _ZN10dBgActor_c19UpdateClsnPosAndRotEv(void *self);
int func_ov098_0213a0a8(char *c);
void func_ov098_0213a0e8(char *c);
void func_ov098_0213a148(char *c);
void func_ov098_0213a23c(char *c);
extern s16 data_02082214[];
extern signed char data_0209f2f8;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 11 -- _ZN16daObjFallBlock_c8BehaviorEv, 0x0213a36c, size 0x428 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16daObjFallBlock_c8BehaviorEv
// Matched byte-for-byte with mwccarm 1.2/sp2p3 (ov098).
/* daObjFallBlock_c::Behavior - the whole fall-block state machine; see the
   class header for the field-by-field account. The draft cast `this` to a
   32-entry vtable-shim struct and called slot 31 (KillOrWhatever); that
   slot is Kill(), already a named virtual on this class (its own key
   function, per daObjFallBlock_c.h), so this calls it directly. UpdatePos
   is dActor_c's own named member (dActor_c.h), inherited; the
   dBgW calls go through the real named mMeshCollider member
   (dBgActor_c.h) instead of a raw offset-0x124 cast. The Fix12<int>-typed
   dBgActor_c calls stay spelled as their extern "C" mangled names -- see
   dBgActor_c.h's note on why declaring the true types there breaks the
   byte match. */
s32 daObjFallBlock_c::Behavior()
{
    char *c = (char *)this;
    int all;
    char *p;
    char *q;
    int is53;
    s16 yaw;
    int dist;
    int thresh;
    int flag;
    s16 sinv;
    u8 *st;
    char *b300;
    void *pl;

    is53 = (int)(*(u16 *)(c + 0xc) == 0x53);
    if (is53 != 0) {
        if (*(u8 *)(c + 0x342) != 0) {
            if (*(int *)(c + 0x330) == 0)
                func_ov098_0213a0e8(c);
            else
                func_ov098_0213a0a8(c);
            return 1;
        }
    }

    func_ov098_0213a00c(c);
    if (*(u8 *)(c + 0x33f) != 0) {
        if (DecIfAbove0_Byte((u8 *)BASE(c, 0x33f)) == 0) {
            if (mMeshCollider.IsEnabled() != 0)
                mMeshCollider.Disable();
        }
        return 1;
    }

    is53 = (int)(*(u16 *)(c + 0xc) == 0x53);
    if (is53 == 0) {
        if (*(int *)(c + 0x344) == 0) {
            p = c;
            all = 1;
            while (1) {
                if (*(u8 *)(p + 0x340) == 0) {
                    all = 0;
                    break;
                }
                p = *(char **)(p + 0x348);
                if (p == 0)
                    break;
            }
            if (all != 0) {
                q = c;
                while (1) {
                    if (q == 0)
                        break;
                    func_ov098_0213a148(q);
                    q = *(char **)(q + 0x348);
                }
            }
        }
    }

    switch (*(u8 *)(c + 0x33c)) {
    case 0:
        if (*(u8 *)(c + 0x33e) != 0) {
            *(u8 *)(c + 0x340) = 0;
            b300 = BASE(c, 0x300);
            *(s16 *)(b300 + 0x3a) = 4;
            st = (u8 *)BASE(c, 0x33c);
            *st = (u8)(*st + 1);
        }
        break;

    case 1:
        if (DecIfAbove0_Short((u16 *)BASE(c, 0x33a)) == 0) {
            st = (u8 *)BASE(c, 0x33c);
            *st = (u8)(*st + 1);
            _ZN5Sound9PlayBank3EjRK7Vector3(0x2d, c + 0x74);
            b300 = BASE(c, 0x300);
            *(s16 *)(b300 + 0x3a) = 0x5a;
        } else {
            b300 = BASE(c, 0x300);
            sinv = data_02082214[(*(u16 *)(b300 + 0x38) >> 4) << 1];
            *(int *)(c + 0x60) =
                *(int *)(c + 0x324)
                + (int)(((long long)sinv * 0x19000 + 0x800) >> 12);
            {
                s16 *p338 = (s16 *)BASE(c, 0x338);
                *p338 = (s16)(*p338 + 0x3000);
            }
        }
        break;

    case 2:
        if (*(s16 *)(c + 0x8c) < 0x400) {
            s16 *p334 = (s16 *)BASE(c, 0x334);
            *p334 = (s16)(*p334 + 0x80);
        } else {
            if (mMeshCollider.IsEnabled() != 0)
                mMeshCollider.Disable();
        }
        yaw = *(s16 *)(c + 0x90);
        if (yaw > -0x400) {
            if (yaw < 0x400) {
                s16 *p336 = (s16 *)BASE(c, 0x336);
                *p336 = (s16)(*p336 + 0x40);
            }
        }
        {
            s16 t = *(s16 *)(((int)c + 0x8c) & U64);
            t = (s16)(t + *(s16 *)(c + 0x334));
            *(s16 *)(((int)c + 0x8c) & U64) = t;
            t = (s16)(*(s16 *)(((int)c + 0x90) & U64) + *(s16 *)(c + 0x336));
            *(s16 *)(((int)c + 0x90) & U64) = t;
            UpdatePos(0);
        }
        if (DecIfAbove0_Short((u16 *)BASE(c, 0x33a)) == 0) {
            *(int *)(c + 0x5c) = *(int *)(c + 0x320);
            *(int *)(c + 0x60) = *(int *)(c + 0x324);
            *(int *)(c + 0x64) = *(int *)(c + 0x328);
            st = (u8 *)BASE(c, 0x33c);
            *st = (u8)(*st + 1);
        } else {
            if (*(int *)(c + 0x60) < *(int *)(c + 0x32c)) {
                Kill();
                *(int *)(c + 0x5c) = *(int *)(c + 0x320);
                *(int *)(c + 0x60) = *(int *)(c + 0x324);
                *(int *)(c + 0x64) = *(int *)(c + 0x328);
                st = (u8 *)BASE(c, 0x33c);
                *st = (u8)(*st + 1);
            }
        }
        break;

    case 3:
        *(int *)(c + 0x5c) = *(int *)(c + 0x320);
        *(int *)(c + 0x60) = *(int *)(c + 0x324);
        *(int *)(c + 0x64) = *(int *)(c + 0x328);
        is53 = (int)(*(u16 *)(c + 0xc) == 0x53);
        if (is53 == 0) {
            pl = _ZN8dActor_c13ClosestPlayerEv(c);
            dist = Vec3_HorzDist(c + 0x320, (char *)pl + 0x5c);
            thresh = 0x28a000;
            if (data_0209f2f8 == 0x2e)
                thresh = 0xa000;
            flag = (*(int *)(c + 0xb0) & 8) ? 1 : 0;
            if (flag != 0 && dist > thresh)
                *(u8 *)(c + 0x340) = 1;
            else
                *(u8 *)(c + 0x340) = 0;
        }
        break;

    default:
        break;
    }

    func_ov098_0213a23c(c);
    if (*(u8 *)(c + 0x33c) <= 1) {
        if (_ZN10dBgActor_c13IsClsnInRangeE5Fix12IiES1_(c, 0, 0) != 0)
            _ZN10dBgActor_c19UpdateClsnPosAndRotEv(c);
    }
    *(u8 *)(c + 0x33e) = 0;
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 10 -- _ZN16daObjFallBlock_c6RenderEv, 0x0213a314, size 0x58 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16daObjFallBlock_c6RenderEv
/* daObjFallBlock_c::Render - the draft cast the Model sub-object at
   offset 0xd4 to a 5-entry vtable-shim struct and called its slot-5
   method by index. That sub-object is dBgActor_c's own named
   `Model mModel;` field, and slot 5 is Model::Render(const Vector3*)
   (Model.h), so this calls it by name with a null scale. */
s32 daObjFallBlock_c::Render()
{
    if (mSuppressed) return 1;
    if (mState == 3) return 1;
    mModel.Render(0);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- func_ov098_0213a2cc, 0x0213a2cc, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov098_0213a2cc
extern "C" {  /* .c-derived member: C linkage for the whole block */
int func_ov098_0213a2cc(char *t, void **f){
  if(_ZN4dBgW9IsEnabledEv(t+0x124))
    _ZN4dBgW7DisableEv(t+0x124);
  _ZN13SharedFilePtr7ReleaseEv(f[0]);
  _ZN13SharedFilePtr7ReleaseEv(f[1]);
  return 1;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- _ZN16daObjFallBlock_c15OnHitByMegaCharER6Player, 0x0213a284, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16daObjFallBlock_c15OnHitByMegaCharER6Player
/* daObjFallBlock_c::OnHitByMegaChar - the draft cast `this` to a 32-entry
   vtable-shim struct and called its last slot (31); that slot is Kill(),
   already a named virtual on this class, so this calls it directly. The
   `player` parameter is never read, matching the ROM body, which only
   ever takes the one (`this`) argument. */
void daObjFallBlock_c::OnHitByMegaChar(Player &player)
{
    if (mRespawnDelay != 0) return;
    Kill();
    mRespawnDelay = 0xa;
    mState = 3;
    mStateTimer = 0x3c;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- func_ov098_0213a23c, 0x0213a23c, size 0x48 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov098_0213a23c
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov098_0213a23c(char *t)
{
    Matrix4x3_FromRotationXYZExt(t + 0xf0, *(short *)(t + 0x8c), *(short *)(t + 0x8e), *(short *)(t + 0x90));
    *(int *)(t + 0x114) = *(int *)(t + 0x5c) >> 3;
    *(int *)(t + 0x118) = *(int *)(t + 0x60) >> 3;
    *(int *)(t + 0x11c) = *(int *)(t + 0x64) >> 3;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- _ZN16daObjFallBlock_c4KillEv, 0x0213a17c, size 0xc0 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16daObjFallBlock_c4KillEv
/* daObjFallBlock_c::Kill() at ov098 0x0213a17c, 0xc0 bytes -- vtable slot 31.
 *
 * ATTRIBUTED BY THE VTABLE. _ZTV16daObjFallBlock_c (ov098 0x0213c5bc) carries
 * 0x0213a17c at slot 31 and _ZTV10dBgActor_c carries _ZN10dBgActor_c4KillEv at the
 * same slot, so this is this class's own override of dBgActor_c's Kill. The
 * header's own note lists the same six own-slots independently: 6, 9, 16, 17,
 * 27 and 31.
 *
 * The block plays its poof where it stands, 0x32000 -- fifty 20.12 units --
 * above itself, then does NOT destroy itself: it teleports back to mRestPos,
 * clears mReady and sets mStateTimer to 0x1e. That is the respawn, which is
 * why there is no MarkForDestruction here and why the other thirteen slot-31
 * overrides in this family end with one.
 *
 * dActor_c id 0x8b gets particle 0x49 instead of 0x48.
 *
 * The second Vector3 is memberwise on purpose: Vector3 declares a destructor
 * (types.h), so a whole-object assignment compiles to an ldm/stm pair, four
 * instructions where the ROM has six. Particle::System::NewSimple stays spelled
 * as its mangled name -- its parameters are Fix12<int> BY VALUE and declaring
 * the true types changes how the caller passes them. Both points are argued in
 * full in src/_ZN10dBgActor_c4KillEv.cpp. */
void daObjFallBlock_c::Kill()
{
    Vector3 pos;
    Vector3 dustPos;
    pos.x = mPosX;
    pos.y = mPosY;
    pos.z = mPosZ;
    pos.y += 0x32000;
    u32 id = 0x48;
    /* THE INTERMEDIATE IS LOAD-BEARING. `if (actorID == 0x8b)` folds the test
       into the conditional move -- `cmp r1,#0x8b; moveq r0,#0x49`, two
       instructions. The ROM materialises the comparison into a register first
       and then tests THAT: cmp/moveq #1/movne #0/cmp #0/movne, five. Writing
       the int is what asks for the second shape. */
    int isBigBlock = (actorID == 0x8b);
    if (isBigBlock) {
        id = 0x49;
    }
    _ZN8Particle6System9NewSimpleEj5Fix12IiES2_S2_(id, pos.x, pos.y, pos.z);
    dustPos.x = pos.x;
    dustPos.y = pos.y;
    dustPos.z = pos.z;
    PoofDustAt(dustPos);
    Sound::PlayBank3(0x41, *(Vector3 *)&mCamSpacePosX);
    mStateTimer = 0x1e;
    mPosX = mRestPos.x;
    mPosY = mRestPos.y;
    mPosZ = mRestPos.z;
    mReady = 0;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- func_ov098_0213a148, 0x0213a148, size 0x34 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov098_0213a148
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov098_0213a148(char *c) {
    *(unsigned char*)(c + 0x33c) = 0;
    *(short*)(c + 0x8c) = 0;
    *(short*)(c + 0x90) = 0;
    *(short*)(c + 0x334) = 0;
    *(short*)(c + 0x336) = 0;
    *(int*)(c + 0xa4) = 0;
    *(int*)(c + 0xa8) = 0;
    *(int*)(c + 0xac) = 0;
    *(short*)(c + 0x33a) = 4;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- func_ov098_0213a0e8, 0x0213a0e8, size 0x60 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov098_0213a0e8
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov098_0213a0e8(char* r5) {
    dActor_c* r1;
    r1 = _ZN8dActor_c15FindWithActorIDEjPS_(0xb2, 0);
    while (r1) {
        if (*(unsigned char*)((char*)r1 + 0x49d) == (*(int*)(r5 + 8) & 0xf)) {
            *(int*)(r5 + 0x330) = *(int*)((char*)r1 + 4);
        }
        r1 = _ZN8dActor_c15FindWithActorIDEjPS_(0xb2, r1);
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- func_ov098_0213a0a8, 0x0213a0a8, size 0x40 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov098_0213a0a8
extern "C" {
int _ZN7fBase_c18MarkForDestructionEv(void*);
void* _ZN8dActor_c10FindWithIDEj(unsigned int);
int func_ov098_0213a0a8(char* c){
  void* a = _ZN8dActor_c10FindWithIDEj(*(unsigned int*)(c+0x330));
  if (a == 0) return _ZN7fBase_c18MarkForDestructionEv(c);
  int v = *(int*)((char*)a+0x440);
  if (v == 4) { v = 0; *(unsigned char*)(c+0x342) = 0; }
  return v;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov098_0213a00c, 0x0213a00c, size 0x9c */
/* -------------------------------------------------------------------------- */
// @symbol func_ov098_0213a00c
void func_ov098_0213a00c(char *c)
{
    if (*(unsigned char*)(c+0x341) != 0) return;
    dActor_c *r = _ZN8dActor_c15FindWithActorIDEjPS_(*(unsigned short*)(c+0xc), 0);
    while (r) {
        if (r != (dActor_c*)c) {
            Vector3 *b = (Vector3*)((char*)r+0x5c);
            Vector3 *a = (Vector3*)(c+0x5c);
            int ang = Vec3_HorzAngle(a, b);
            if (Vec3_Dist(a, b) < 0x96000) {
                if (AngleDiff(ang, *(s16*)(c+0x8e)) < 0x4000)
                    *(dActor_c**)(c+0x348) = r;
                else
                    *(dActor_c**)(c+0x344) = r;
            }
        }
        r = _ZN8dActor_c15FindWithActorIDEjPS_(*(unsigned short*)(c+0xc), r);
    }
    *(unsigned char*)(c+0x341) = 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 1 -- _ZN16daObjFallBlock_cD1Ev, 0x02139fc8, size 0x44 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN16daObjFallBlock_cD1Ev
// @symbol _ZN16daObjFallBlock_cD0Ev
/* recovered: real C++ destructor pair -- NO SOURCE TEXT OF THEIR OWN.
 *
 * daObjFallBlock_c.h defines `~daObjFallBlock_c() {}` in the class body, and
 * the ROM carries the out-of-line D1 (0x02139fc8) and D0 (0x02139f70) anyway
 * because THIS TU owns the key function. The destructor is inline, so the key
 * function is the first non-inline, non-pure virtual -- Kill(), ROM ordinal 6
 * above -- and the TU that defines it emits _ZTV16daObjFallBlock_c together
 * with both destructor variants.
 *
 * The two legacy shards each carried a forcing scaffold for this reason: an
 * explicit `p->~daObjFallBlock_c()` call in one, a stub redefinition of Kill()
 * in the other. Merged, both are dead weight and the Kill() stub is an
 * outright redefinition of the real body above. Neither is needed and neither
 * changes the emission order (notes/agents/roles/writer.md, closed lever set),
 * so both are gone; the variants come in through the key function.
 */
