//cpp
/* File-global, and deliberately so. Two members -- func_ov006_02124cb4 and
 * func_ov006_021250e4 -- carried `#pragma opt_strength_reduction off` in their
 * legacy one-function sources, and tubuild left it out with a [NOT carried --
 * review] note because carrying a file-global pragma into a merged TU silently
 * recompiles every other member.
 *
 * Reviewed, and measured both ways. Bracketing the pragma around just those two
 * members (off before, on after) changes nothing -- unlike `long_calls`, this
 * pragma is NOT positional in mwccarm 2004/b56; it is file-global last-wins, so
 * the trailing `on` simply won and both members still grew. Set once at the top,
 * all nineteen members byte-match: the two that need it reproduce, and the other
 * seventeen -- which matched with it absent -- are unchanged by its presence.
 * Without it those two strength-reduce the `i * 8` induction variable, which
 * costs a register, spills two constants to stack (`sub sp,#0x14` where the
 * cartridge has `sub sp,#0xc`) and grows them by 0x4 and 0x10 bytes. */
#pragma opt_strength_reduction off
/* SHADOW translation unit -- generated by tools/tubuild.py create.
 * ov006/dScMgBSC_c  (19 function(s))
 *
 * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM
 * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations
 * below were carried verbatim from the legacy files, not reconciled against
 * real project headers -- that judgement call is left to a human/LLM review,
 * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand
 * (see notes/tu-reconstruction-pilot-report.md sec 5.2).
 *
 * FUNCTION ORDER IS DELIBERATELY THE REVERSE OF THE ROM'S -- mwccarm 2004/b56
 * emits one .text section per function, in the REVERSE of source order, so
 * the highest-address ROM function is written FIRST here. Do not reorder;
 * see notes/tu-reconstruction-pilot-report.md sec 3 for the one documented
 * exception (a destructor's D0/D1/D2 group has compiler-chosen order).
 *
 * Assembled from these legacy one-function sources (ROM address order).
 * All 19 were deleted by the promotion that created this file; the paths
 * are recorded for provenance and no longer resolve in the tree:
 *   [0] 0x02124908  src/_ZN10dScMgBSC_cD1Ev.cpp
 *   [1] 0x0212497c  src/_ZN10dScMgBSC_cD0Ev.cpp
 *   [2] 0x02124a04  src/func_ov006_02124a04.c
 *   [3] 0x02124a08  src/func_ov006_02124a08.c
 *   [4] 0x02124ae4  src/func_ov006_02124ae4.c
 *   [5] 0x02124b58  src/func_ov006_02124b58.c
 *   [6] 0x02124bb4  src/func_ov006_02124bb4.c
 *   [7] 0x02124cb4  src/func_ov006_02124cb4.c
 *   [8] 0x02124dc0  src/func_ov006_02124dc0.c
 *   [9] 0x02124e1c  src/func_ov006_02124e1c.cpp
 *   [10] 0x02124ec4  src/func_ov006_02124ec4.c
 *   [11] 0x02124fd8  src/func_ov006_02124fd8.c
 *   [12] 0x021250e4  src/func_ov006_021250e4.c
 *   [13] 0x02125248  src/func_ov006_02125248.c
 *   [14] 0x0212527c  src/func_ov006_0212527c.cpp
 *   [15] 0x02125364  src/func_ov006_02125364.cpp
 *   [16] 0x021253bc  src/_ZN10dScMgBSC_c6RenderEv.cpp
 *   [17] 0x021254c0  src/_ZN10dScMgBSC_c8BehaviorEv.cpp
 *   [18] 0x0212551c  src/_ZN10dScMgBSC_c13InitResourcesEv.cpp
 */

/* TUBUILD NOTE -- #pragma directive(s) were present in the legacy sources
 * of this TU. `#pragma long_calls` is POSITIONAL in mwccarm 2004/b56 and is
 * carried verbatim before its own member below, bracketed with `off` so it
 * cannot leak into later members (dropping it silently costs the pooled
 * cross-overlay tail-call -- a byte diff; see ShutterBob in ov014).
 * Any OTHER pragma is FILE-GLOBAL last-wins (opt_propagation,
 * optimize_for_size) and is still left out: carried into a merged TU it
 * would silently recompile every other member. Decide those by hand:
 *   func_ov006_02124cb4: #pragma opt_strength_reduction off   [REVIEWED -- carried, file-global at the top]
 *   func_ov006_021250e4: #pragma opt_strength_reduction off   [REVIEWED -- carried, file-global at the top]
 */

/* Includes: union of the legacy files', first-seen in ROM-ascending
 * processing order. NOT verified for header ordering constraints (e.g. a
 * common.h-before-X rule) -- watch for new compile errors after this. */
#include "dScMgBSC_c.h"
#include "types.h"
#include "decl_common.h"

/* Local shadow declarations carried from the legacy files verbatim.
 * NOT reconciled against real project headers -- check include/*.h for
 * each of these before compiling; a real header should usually win. */
/* shadow typedef 's32' */
typedef int s32;

/* shadow typedef 'Pair' */
typedef struct { int x, y; } Pair;

/* shadow typedef 'Obj' */
typedef struct Obj {
    char _a[0x4660];
    char f4660;
    char _b[0x4f38 - 0x4661];
    char f4f38;
    char _c[0x51a8 - 0x4f39];
    Pair pos[2];
    int count;
    char _d[0x51ca - 0x51bc];
    unsigned char b0[2];
    unsigned char b1[2];
} Obj;

/* shadow typedef 'void' */
typedef void (dScMgBSC_c::*BSCState)();

/* shadow struct 'dScMgBSC_c_StateEntry' */
struct dScMgBSC_c_StateEntry {
    BSCState mFn;
};

/* Second shadow view of `this`, distinct from the `Obj` layout typedef above:
 * two legacy files each spelled their own `struct Obj` for different purposes
 * and tubuild carried both in verbatim. This one exists only to reach vtable
 * slot 18, which neither dScMgBase_c.h nor this class's header declares yet,
 * so a self-dispatch cannot be written as a real virtual call. Named for what
 * it is rather than left colliding. */
struct SelfVtblShim {
    virtual void v0();virtual void v1();virtual void v2();virtual void v3();
    virtual void v4();virtual void v5();virtual void v6();virtual void v7();
    virtual void v8();virtual void v9();virtual void v10();virtual void v11();
    virtual void v12();virtual void v13();virtual void v14();virtual void v15();
    virtual void v16();virtual void v17();virtual void v18(int x);
    char pad[0x10000];
};

extern "C" {
extern short data_ov004_020bf9e4;
extern int Math_Function_0203b14c(void *p, int a, int b, int c, int d);
extern void func_ov004_020b0a38(void);
extern int func_ov006_020c1718(int* r0);
extern void func_ov004_020b56c8(int x);
extern void func_ov004_020b5ed0(void);
extern int data_ov004_020bfa18;
extern void func_ov006_020c0c80(void* c);
extern void func_ov006_020c0d68(void* c);
extern void func_ov004_020adb1c(int self);
extern void func_ov004_020b0a54(int v);
extern void func_ov004_020ad79c(int a, int b);
extern void _ZN5Sound12PlayBank2_2DEj(unsigned int a);
extern "C" int _Z14ApproachLinearRiii(int& v, int a, int b);
extern unsigned char data_020a0e40;
extern unsigned char data_020a0de8[];
extern unsigned char data_020a0de9[];
extern int data_ov006_0213fd44[];
extern int data_ov004_020bf9ec;
extern int RandomIntInternal(int* seed);
extern void func_ov006_020c1604(char* c, int unused, short a2, int a3);
extern int data_0209e650;
extern "C" int func_ov006_02125248(void *thisPtr);
extern "C" void FreeGfxSlotsById(int arg);
extern "C" void func_ov004_020b66d4(void);
void func_ov006_020c0aa8(void *camera);
void Hud_RenderSprite(void *sprite, int x, int y, int a3, int a4);
void func_ov004_020b1bc8(void *scene, int a1, int a2, int a3);
void func_ov004_020b1e34(void *scene, int a1, int a2, int a3);
void func_ov006_020c1804(void *table);
extern dScMgBSC_c_StateEntry data_ov006_02142f94[];
void func_ov004_020b65e4(void);
int  func_ov006_020c19d0(void *p);
extern unsigned char data_0209d45c[];
extern int data_0208ee44[];
extern void func_ov006_0210a534(void);
extern s32 GetGameLanguage(void);
extern u32 LoadCompressedFileAt(int fileID, void *target);
extern int LoadFile(int handle);
extern int func_ov006_020c1a88(void *p);
extern "C" void _ZN3GXS11LoadOBJPlttEPKvjj(void const *a, unsigned int b, unsigned int c);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 18 -- _ZN10dScMgBSC_c13InitResourcesEv, 0x0212551c, size 0xdc */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10dScMgBSC_c13InitResourcesEv
/* dScMgBSC_c::InitResources -- vtable slot 0.
 *
 * Attributed by tools/rtti_vtables.py --own dScMgBSC_c, which lists this address
 * as this class's own slot 0 (fBase_c::InitResources), distinct from
 * dScMgSingle3DBase_c's. The old file's `recovered name: dScMgBSC_c_InitResources`
 * agreed.
 *
 * The final call is a self-dispatch through this class's own vtable slot 18
 * (func_ov006_02125364, per the same rtti dump) -- neither dScMgBase_c.h nor this
 * header names that slot yet (both leave 18-35 undeclared), so it stays a raw
 * vtable-shim call exactly as the pre-migration file spelled it, just through
 * `this` instead of a `void *self` parameter. */
s32 dScMgBSC_c::InitResources()
{
    SelfVtblShim *o = (SelfVtblShim *)this;
    char *c = (char *)this;
    int fh;
    data_0209d45c[0] = 0x11;
    func_ov006_0210a534();
    LoadCompressedFileAt(data_ov006_0213fe78[GetGameLanguage()], (void *)0x6600000);
    fh = LoadFile(0xb3);
    _ZN3GXS11LoadOBJPlttEPKvjj((void *)fh, 0, 0x100);
    Deallocate((void *)fh);
    func_ov006_020c0aa8(c + 0x4660);
    if (func_ov006_020c1a88(c + 0x4f38) == 0)
        return 0;
    func_ov004_020b04d0(0x20);
    func_ov004_020b682c();
    data_0208ee44[0] = 1;
    *(int *)(c + 0xa8) = func_ov004_020ad8b8();
    *(int *)(c + 0xac) = *(int *)(c + 0xa8);
    o->v18(3);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 17 -- _ZN10dScMgBSC_c8BehaviorEv, 0x021254c0, size 0x5c */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10dScMgBSC_c8BehaviorEv
/* dScMgBSC_c::Behavior -- vtable slot 6, ov006 0x021254c0.
 *
 * Named from the table, not from the old file's `recovered name:` comment
 * (which agreed here): 0x021254c0 is the word slot 6 of _ZTV10dScMgBSC_c
 * holds where dScMgSingle3DBase_c's table holds something else, so it is
 * this class's own override of the virtual fBase_c declares.
 *
 * The dispatch is a pointer-to-member table indexed by unk_51b8 -- the
 * minigame's state. The pre-migration file had to invent a `struct C` with
 * a 0x51b8 pad just to spell that member pointer; with the real class it is
 * the field the header already names. */
s32 dScMgBSC_c::Behavior()
{
    (this->*(data_ov006_02142f94[unk_51b8].mFn))();
    func_ov004_020b65e4();
    func_ov006_020c19d0(mTable);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 16 -- _ZN10dScMgBSC_c6RenderEv, 0x021253bc, size 0x104 */
/* -------------------------------------------------------------------------- */
// @symbol _ZN10dScMgBSC_c6RenderEv
/* dScMgBSC_c::Render -- vtable slot 9, ov006 0x021253bc.
 *
 * Named from the table: 0x021253bc is the word slot 9 of _ZTV10dScMgBSC_c
 * holds where its base's table holds something else, so it is this class's
 * own override of the virtual fBase_c declares.
 *
 * THE SHADOW STRUCT SURVIVES THE RENAME ON PURPOSE. Three of the four things
 * this function reads past 0x51a8 -- the two 8-byte score positions and the
 * two pairs of sprite indices at 0x51ca/0x51cc -- fall inside spans
 * include/dScMgBSC_c.h deliberately leaves as raw bytes: mArray's element
 * type is unevidenced (its ROM destructor is NullDestructor_0203d47c, i.e.
 * POD of unknown shape) and 0x51bc..0x51d0 is pad. Naming them would be a
 * layout claim this rename has no evidence for, so `Obj` stays as the
 * pre-migration file spelled it and `this` is cast to it. Only unk_51b8, the
 * one field of that tail the header does name, is spelled as itself. */
s32 dScMgBSC_c::Render()
{
    Obj *self = (Obj *)this;
    int i;

    func_ov006_020c0aa8(&self->f4660);
    if (self->count >= 1) {
        for (i = 0; i < 2; i++) {
            if (self->b1[i] < 3) {
                Hud_RenderSprite(data_ov006_0213fe8c[self->b1[i]],
                                    self->pos[i].x >> 12,
                                    self->pos[i].y >> 12, -1, -1);
            } else {
                Hud_RenderSprite(
                    data_ov006_0213fe8c[self->b1[i] + self->b0[i] * 2],
                    self->pos[i].x >> 12,
                    self->pos[i].y >> 12, -1, -1);
            }
        }
    }
    func_ov004_020b6430();
    func_ov004_020b1bc8(self, 0xc, 0xc, 0);
    func_ov004_020b1e34(self, 0xe0, 0x14, 1);
    func_ov006_020c1804(&self->f4f38);
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 15 -- func_ov006_02125364, 0x02125364, size 0x58 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02125364
/* recovered: renamed to Class_Method, RTTI class fields named, declarations from a shared header */
/* recovered: renamed to Class_Method, RTTI class fields named */
// recovered name: dScMgBSC_c_OnYoshiTryEat_02125364
/* recovered: renamed to Class_Method */
/* The DELETING DESTRUCTOR, vtable slot 17. The old comment here called it
   OnYoshiTryEat, which is slot 18 -- off by one. This body stores the class
   vtable, destroys the members and calls Memory::Deallocate; no eat handler
   does any of that. */
extern "C" void func_ov006_02125364(char* c, int mode){
    dScMgBSC_c *self = (dScMgBSC_c *)(void *)c;
  if(mode != 4 && mode != 5 && mode == 3){
    self->mHudScore = func_ov004_020ad878();
    func_ov004_020adb1c(self->mHudScore);
  }
  func_ov004_020b66d4();
  data_ov004_020bc7d4 = 1;
  *(int*)(c+0x5000+0x1b8) = 0;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 14 -- func_ov006_0212527c, 0x0212527c, size 0xe8 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_0212527c
/* recovered: renamed to Class_Method, RTTI class fields named, declarations from a shared header */
/* recovered: renamed to Class_Method, RTTI class fields named */
// recovered name: dScMgBSC_c_OnTurnIntoEgg
/* recovered: renamed to Class_Method */
/* dScMgBSC_c::OnTurnIntoEgg - recovered from vtable slot identity */
extern "C" int func_ov006_0212527c(char* c, int mode)
{
    struct dScMgBSC_c *self = (struct dScMgBSC_c *)(void *)c;
    int st;
    short fl;
    if (self->unk_51b8 == 0xd) {
        if (func_ov006_020c1718((int*)(c + 0x4f38)) != 0) {
            if (mode == 4) {
                FreeGfxSlotsById(0x1d);
                self->unk_51b8 = 9;
            } else if (mode == 5) {
                FreeGfxSlotsById(0x1d);
                self->unk_51b8 = 0xa;
            }
        } else {
            return 0;
        }
    }
    st = self->unk_51b8;
    if (st >= 0xc) {
        fl = data_ov004_020bf9e4;
        if (fl == 1) goto do1;
    }
    return 0;
do1:
    if (st == 0xc && fl == 1) {
        func_ov004_020ad79c(self->unk_0a8, self->mHudScore);
    }
    return 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 13 -- func_ov006_02125248, 0x02125248, size 0x34 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02125248
/* recovered: renamed to Class_Method, RTTI class fields named, declarations from a shared header */
/* recovered: renamed to Class_Method, RTTI class fields named */
// recovered name: dScMgBSC_c_OnGroundPounded
/* recovered: renamed to Class_Method */
/* dScMgBSC_c::OnGroundPounded - recovered from vtable slot identity */
int func_ov006_02125248(void *thisPtr) {
    struct dScMgBSC_c *self = (struct dScMgBSC_c *)(void *)thisPtr;
    int x = self->mHudScore;
    int v = x / 5;
    if ((unsigned int)v > 3) {
        v = 3;
    }
    return func_ov004_020b6324(v + 1);
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 12 -- func_ov006_021250e4, 0x021250e4, size 0x164 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_021250e4
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_021250e4(char* base)
{
    unsigned char flags[5];
    unsigned char* p;
    int j;
    int i;
    unsigned char idx;

    p = flags;
    for (j = 0; j < 5; j++)
        *p++ = 0;

    for (i = 0; i < 2; i++) {
        *(int*)(base + i * 8 + 0x51a8) = 0x80000;
        *(int*)(base + i * 8 + 0x51ac) = -0x40000;
        idx = ((unsigned int)RandomIntInternal(&data_0209e650) >> 16) % 5u;
        for (;;) {
            if (flags[idx] == 0) {
                *(unsigned char*)(base + i + 0x51ca) = idx;
                flags[idx] = 1;
                break;
            }
            idx++;
            idx %= 5;
        }
        *(unsigned char*)(base + i + 0x51cc) = 0;
    }

    *(int*)(base + 0x51c4) = 0;
    *(int*)(base + 0x51c0) = 1;
    *(short*)(base + 0x51c8) = 0;
    func_ov006_020c1604(base + 0x4f38, 3, 2, (int)(base + 0x51c8));

    if (*(unsigned char*)(base + 0xc4) == 0) {
        *(unsigned char*)(base + 0xc3) = 1;
        *(unsigned char*)(base + 0xc4) = 1;
        *(unsigned short*)(base + 0xc0) = 0;
    }

    *(int*)(((int)base + 0x51b8)) += 1;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 11 -- func_ov006_02124fd8, 0x02124fd8, size 0x10c */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124fd8
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124fd8(char *c)
{
  int i;
  int fp;
  int sl;
  char *p;
  char *q;
  short count;

  fp = 0;
  i = 0;
  count = *(short *)(c + 0x51c8);
  if (count <= 0)
    goto after_loop;

  p = c + 0x51a8;
  q = c + 0x51ac;
  do {
    if (Math_Function_0203b14c(p, data_ov006_0213fd44[i], 0x800, 0x10000, 0x200) == 0)
      sl = 1;
    else
      sl = 0;

    if (Math_Function_0203b14c(q, 0x60000, 0x800, 0x10000, 0x200) == 0)
    {
      if (sl != 0)
        fp++;
    }
    p += 8;
    q += 8;
    i++;
    count = *(short *)(c + 0x51c8);
  } while (i < count);

after_loop:
  if (fp < 2)
    return;
  (*(int *)((int)c + 0x51b8))++;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 10 -- func_ov006_02124ec4, 0x02124ec4, size 0x114 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124ec4
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124ec4(char *sl)
{
    unsigned int i = data_020a0e40;
    int ok = 0;
    int sb;
    if (data_020a0de8[i * 4] != 0) {
        if (data_020a0de9[i * 4] != 0) ok = 1;
    }
    if (ok == 0) return;
    for (sb = 0; sb < 2; sb++) {
        unsigned char idx = *(volatile unsigned char *)&data_020a0e40;
        unsigned char *b = &data_020a0de8[(unsigned int)idx * 4];
        int v = (int)b[2] - (data_ov006_0213fd44[sb] >> 12);
        int w = (int)b[3] - 0x60;
        if (v < -0x10) continue;
        if (v > 0x10) continue;
        if (w < -0x18) continue;
        if (w > 0x18) continue;
        *(int *)(sl + 0x51c0) = sb;
        *(int *)(sl + 0x51c4) = sb ^ 1;
        *(unsigned char *)(sl + 0x51ce) = 0;
        *(int *)(sl + 0x51b8) += 1;
        data_ov004_020bf9ec = 1;
        _ZN5Sound12PlayBank2_2DEj(0x153);
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 9 -- func_ov006_02124e1c, 0x02124e1c, size 0xa8 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124e1c
extern "C" void func_ov006_02124e1c(char* c)
{
    int a = _Z14ApproachLinearRiii(((int*)(c + 0x51ac))[*(int*)(c + 0x51c0) * 2], 0x90000, 0x4000) & 1;
    int b = _Z14ApproachLinearRiii(((int*)(c + 0x51ac))[*(int*)(c + 0x51c4) * 2], 0x30000, 0x4000) & 1;

    if (a == 0) return;
    if (b == 0) return;

    *(int*)(c + 0x51bc) = 0x1e;
    (*(int *)(((int)c + 0x51b8))) += 1;
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 8 -- func_ov006_02124dc0, 0x02124dc0, size 0x5c */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124dc0
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124dc0(void* arg0)
{
    char* c = (char*)arg0;

    *(s32*)(((int)c + 0x51bc)) =
        *(s32*)(((int)c + 0x51bc)) - 1;
    if (*(s32*)(c + 0x51bc) > 0)
        return;
    _ZN5Sound12PlayBank2_2DEj(0x148);
    *(s32*)(((int)c + 0x51b8)) =
        *(s32*)(((int)c + 0x51b8)) + 1;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 7 -- func_ov006_02124cb4, 0x02124cb4, size 0x10c */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124cb4
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124cb4(char *o)
{
    int i;
    *(u8 *)(((int)o + 0x51ce)) += 1;
    if (*(u8 *)(o + 0x51ce) < 4)
        return;
    *(u8 *)(o + 0x51ce) = 0;
    for (i = 0; i < 2; i++)
        *(u8 *)(((int)o + i + 0x51cc)) += 1;
    if (*(u8 *)(o + *(int *)(o + 0x51c4) + 0x51cc) < 4)
        return;
    *(int *)(o + 0x51bc) = 0x1e;
    *(int *)(((int)o + 0x51b8)) += 1;
    o[0xc3] = 0;
    {
        u8 x = *(u8 *)(o + *(int *)(o + 0x51c0) + 0x51ca);
        u8 y = *(u8 *)(o + *(int *)(o + 0x51c4) + 0x51ca);
        int c = *(int *)(o + 0xa8);
        int d = *(int *)(o + 0xb4);
        if (x > y) {
            c += data_ov004_020bfa18 * 2;
            d = d + 1;
        } else {
            d = d - 1;
        }
        func_ov004_020ad79c(c, d);
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 6 -- func_ov006_02124bb4, 0x02124bb4, size 0x100 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124bb4
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124bb4(char *c)
{
    int *cnt;
    int *p;

    cnt = (int *)(((int)c + 0x51bc));
    *cnt = *cnt - 1;
    if (*(int *)(c + 0x5000 + 0x1bc) > 0)
        return;

    if (*(unsigned char *)(c + *(int *)(c + 0x5000 + 0x1c0) + 0x5000 + 0x1ca) >
        *(unsigned char *)(c + *(int *)(c + 0x5000 + 0x1c4) + 0x5000 + 0x1ca))
    {
        if (*(int *)(c + 0xb4) < 0x270f)
        {
            p = (int *)(((int)c + 0xb4));
            *p = *p + 1;
        }
        if (*(int *)(c + 0xb4) > *(int *)(c + 0xb8))
            *(int *)(c + 0xb8) = *(int *)(c + 0xb4);
        func_ov004_020adb1c(*(int *)(c + 0xb4));
        func_ov004_020b0a54(4);
        func_ov006_020c0c80(c + 0x4f38);
        *(int *)(c + 0x5000 + 0x1b8) = 0xd;
    }
    else
    {
        if (*(int *)(c + 0xb4) > 0)
        {
            p = (int *)(((int)c + 0xb4));
            *p = *p - 1;
        }
        func_ov004_020b0a54(5);
        func_ov006_020c0d68(c + 0x4f38);
        *(int *)(c + 0x5000 + 0x1b8) = 0xd;
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 5 -- func_ov006_02124b58, 0x02124b58, size 0x5c */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124b58
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124b58(char* c) {
    if (*(int*)(c + 0x51b8) == 7) {
        func_ov006_020c0c80(c + 0x4f38);
        *(int*)(c + 0x51b8) = 9;
    } else {
        func_ov006_020c0d68(c + 0x4f38);
        *(int*)(c + 0x51b8) = 0xa;
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 4 -- func_ov006_02124ae4, 0x02124ae4, size 0x74 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124ae4
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124ae4(char* c)
{
    if (func_ov006_020c1718((int*)(c + 0x4f38)) == 0) return;
    if (*(int*)(c + 0x5000 + 0x1b8) == 9) {
        func_ov004_020b56c8(data_ov004_020bfa18 << 1);
        *(int*)(c + 0x5000 + 0x1b8) = 0xc;
    } else {
        func_ov004_020b5ed0();
        *(int*)(c + 0x5000 + 0x1b8) = 0xb;
    }
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 3 -- func_ov006_02124a08, 0x02124a08, size 0xdc */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124a08
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124a08(void *self);
void func_ov006_02124a08(void *self)
{
  char *c = (char *) self;
  int sl;
  char *r4;
  int i;
  if (data_ov004_020bf9e4 != 1)
  {
 do { } while (0);
    return;
  }
  if ((*((int *) (c + 0xa8))) <= 0)
  {
    r4 = c + 0x5100;
    sl = 0;
    i = sl;
    if ((*((short *) (r4 + 0xc8))) > 0)
    {
      char *e = c + 0x51a8;
      do
      {
        if (0 == Math_Function_0203b14c(e, -0x40000, 0x800, 0xc000, 0x200))
        {
          sl++;
        }
        i++;
        e += 8;
      }
      while (i < (*((short *) ((c + 0x5100) + 0xc8))));
    }
    if (sl < 2)
    {
      return;
    }
  }
  func_ov004_020b0a38();
  *((int *) (c + 0x51b8)) = 0xc;
}
}

/* -------------------------------------------------------------------------- */
/* ROM ordinal 2 -- func_ov006_02124a04, 0x02124a04, size 0x4 */
/* -------------------------------------------------------------------------- */
// @symbol func_ov006_02124a04
extern "C" {  /* .c-derived member: C linkage for the whole block */
void func_ov006_02124a04(void)
{
}
}

/* --------------------------------------------------------------------------
 * ROM ordinals 0 and 1 -- _ZN10dScMgBSC_cD1Ev at 0x02124908 (0x74)
 *                     and _ZN10dScMgBSC_cD0Ev at 0x0212497c (0x88).
 *
 * Neither is written out here. ~dScMgBSC_c() is defined inline in the class
 * body (include/dScMgBSC_c.h), so it cannot be this TU's key function;
 * InitResources, the next virtual declared and non-inline, is, and this TU
 * defines it. That emits _ZTV10dScMgBSC_c right here, whose slots 16 and 17
 * name D1 and D0, odr-using both, and the compiler emits the pair out of
 * line for us.
 *
 * That is not a stylistic choice, it is what the cartridge's own layout
 * requires. Written out of line instead, the same two bodies still match
 * byte for byte, but mwcc emits the synthesized D0 ahead of the written D1
 * -- the reverse of the ROM, where D1 comes first -- and linkcheck's
 * pre-link audit refuses a TU whose licensed .text is not in ROM address
 * order. Leaning on the vtable, as dScMgSingle3DBase_c does one level up,
 * produces D1 then D0 and reproduces the cartridge's order exactly.
 * -------------------------------------------------------------------------- */
