/* The flat C spelling of BigBully -- daBDonketu_c is what the ROM's RTTI calls
 * that class, and include/BigBully.h models it properly as daOts_c ->
 * dEnemyBase_c -> dActor_c. Kept flat because its one includer,
 * src/unnamed/ov064/0211/func_ov064_021175cc.cpp, is a recovered handler that takes `this` as a
 * char*. Field names below are the ones the real chain uses at those offsets,
 * so the two headers cannot drift into describing one class two ways.
 *
 * Originally auto-generated by tools/deepen_rtti.py from 3 functions. */
#ifndef DABDONKETU_C_H
#define DABDONKETU_C_H
#include "types.h"

struct daBDonketu_c {
    u8  pad_000[0x5c];
    s32 mPosX;              /* 0x05c - dActor_c */
    s32 mPosY;              /* 0x060 - dActor_c */
    s32 mPosZ;              /* 0x064 - dActor_c */
    u8  pad_068[0x30];
    s32 mHorzSpeed;         /* 0x098 - dActor_c */
    u8  pad_09c[0x64];
    s16 mStateTimer;        /* 0x100 - dEnemyBase_c, and s16 there */
    u8  pad_102[0x2fa];
    u8  mStarID;            /* 0x3fc - BigBully.h names the same byte */
};

#endif
