/* AUTO-GENERATED by tools/deepen_rtti.py from 7 functions
 * class daBgSnwmn_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DABGSNWMN_C_H
#define DABGSNWMN_C_H
#include "types.h"

struct daBgSnwmn_c {
    u8  pad_000[0x5c];
    s32 unk_05c;            /* 0x05c */
    s32 unk_060;            /* 0x060 */
    s32 unk_064;            /* 0x064 */
    u8  pad_068[0x18];
    s32 unk_080;            /* 0x080 */
    s32 unk_084;            /* 0x084 */
    s32 unk_088;            /* 0x088 */
    u8  pad_08c[0x2];
    s16 unk_08e;            /* 0x08e */
    u8  pad_090[0x4];
    s16 unk_094;            /* 0x094 */
    u8  pad_096[0x2];
    s32 unk_098;            /* 0x098 */
    s32 unk_09c;            /* 0x09c */
    s32 unk_0a0;            /* 0x0a0 */
    u8  pad_0a4[0x4];
    s32 unk_0a8;            /* 0x0a8 */
    u8  pad_0ac[0x20];
    s8  unk_0cc;            /* 0x0cc */
    u8  pad_0cd[0x3];
    s32 unk_0d0;            /* 0x0d0 */
    u8  pad_0d4[0x294];
    s32 unk_368;            /* 0x368 */
};

#endif
