/* AUTO-GENERATED by tools/deepen_rtti.py from 2 functions
 * class daDsn_c, recovered from ROM RTTI + vtable slot identity.
 *
 * SM64DS proves this class as daDsn_c through RTTI, allocation size and
 * vtable identity. The factory and profile spellings below are reconstructed
 * source-style names -- evidence-bounded proposals, not recovered SM64DS
 * symbols.
 *
 * daDsn_c_classInit at 0x02132cb8 (historical alias Thwomp_Spawn) allocates
 * 0x3a4 and installs this class's cartridge vtable. It backs the DOSUN
 * registry profile, whose descriptor at 0x02135150 is reconstructed as
 * g_profile_DOSUN.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DADSN_C_H
#define DADSN_C_H
#include "types.h"

struct daDsn_c {
    u8  pad_000[0x5c];
    s32 mPosX;            /* 0x05c */
    s32 mPosY;            /* 0x060 */
    s32 mPosZ;            /* 0x064 */
};

#endif
