/* AUTO-GENERATED by tools/deepen_rtti.py from 6 functions
 * class daKpa3Bg_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAKPA3BG_C_H
#define DAKPA3BG_C_H
#include "types.h"

struct daKpa3Bg_c {
    u8  pad_000[0x5c];
    s32 mPosX;            /* 0x05c */
    s32 mPosY;            /* 0x060 */
    s32 mPosZ;            /* 0x064 */
    u8  pad_068[0x26];
    s16 mAngleY;            /* 0x08e */
    u8  pad_090[0xc];
    s32 mVertAccel;            /* 0x09c */
    s32 mTerminalVelocity;            /* 0x0a0 */
    u8  pad_0a4[0xa4];
    u32 unk_148;            /* 0x148 */
    u8  pad_14c[0x1d4];
    s32 unk_320;            /* 0x320 */
    u16 unk_324;            /* 0x324 */
    u16 unk_326;            /* 0x326 */
    u8  unk_328;            /* 0x328 */
    u8  unk_329;            /* 0x329 */
    u8  unk_32a;            /* 0x32a */
    u8  unk_32b;            /* 0x32b */
};

#endif
