/* AUTO-GENERATED by tools/deepen_rtti.py from 5 functions
 * class daObjBC_Switch_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAOBJBC_SWITCH_C_H
#define DAOBJBC_SWITCH_C_H
#include "types.h"

struct daObjBC_Switch_c {
    u8  pad_000[0x60];
    s32 mPosY;            /* 0x060 */
    u8  pad_064[0x2a];
    s16 mAngleY;            /* 0x08e */
    u8  pad_090[0x3c];
    s8  mAreaId;            /* 0x0cc */
    u8  pad_0cd[0x253];
    s32 mStopPosY;            /* 0x320 */
    u8  pad_324[0x6];
    u16 mCoinTimerSeed;            /* 0x32a */
    u8  mPressed;            /* 0x32c */
    u8  mEventBit;            /* 0x32d */
    u8  mHomeAreaId;            /* 0x32e */
};

#endif
