/* AUTO-GENERATED by tools/deepen_rtti.py from 1 functions
 * class daObjHmMaruta_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAOBJHMMARUTA_C_H
#define DAOBJHMMARUTA_C_H
#include "types.h"

struct daObjHmMaruta_c {
    u8  pad_000[0x98];
    s32 unk_098;            /* 0x098 */
    u8  pad_09c[0x94];
    s32 unk_130;            /* 0x130 */
    u8  pad_134[0x26c];
    s32 unk_3a0;            /* 0x3a0 */
    u8  pad_3a4[0x10];
    s32 unk_3b4;            /* 0x3b4 */
    u8  pad_3b8[0xf];
    s8  unk_3c7;            /* 0x3c7 */
};

#endif
