/* AUTO-GENERATED by tools/deepen_rtti.py from 8 functions
 * class daObjPushblock_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAOBJPUSHBLOCK_C_H
#define DAOBJPUSHBLOCK_C_H
#include "types.h"

struct daObjPushblock_c {
    u8  pad_000[0x5c];
    s32 unk_05c;            /* 0x05c */
    s32 unk_060;            /* 0x060 */
    s32 unk_064;            /* 0x064 */
    u8  pad_068[0x26];
    s16 unk_08e;            /* 0x08e */
    u8  pad_090[0x4];
    s16 unk_094;            /* 0x094 */
    u8  pad_096[0x2];
    s32 unk_098;            /* 0x098 */
    s32 unk_09c;            /* 0x09c */
    s32 unk_0a0;            /* 0x0a0 */
    u8  pad_0a4[0x438];
    s32 unk_4dc;            /* 0x4dc */
    s32 unk_4e0;            /* 0x4e0 */
    s32 unk_4e4;            /* 0x4e4 */
    s32 unk_4e8;            /* 0x4e8 */
    u32 unk_4ec;            /* 0x4ec */
    s32 unk_4f0;            /* 0x4f0 */
};

#endif
