/* AUTO-GENERATED by tools/deepen_rtti.py from 5 functions
 * class daObjRcBuranko_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAOBJRCBURANKO_C_H
#define DAOBJRCBURANKO_C_H
#include "types.h"

struct daObjRcBuranko_c {
    u8  pad_000[0x8e];
    s16 mAngleY;            /* 0x08e */
    s16 mAngleZ;            /* 0x090 */
};

#endif
