/* AUTO-GENERATED by tools/deepen_rtti.py from 5 functions
 * class daObjCtMecha05_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAOBJCTMECHA05_C_H
#define DAOBJCTMECHA05_C_H
#include "types.h"

struct daObjCtMecha05_c {
    u8  pad_000[0x5c];
    s32 unk_05c;            /* 0x05c */
    s32 unk_060;            /* 0x060 */
    s32 unk_064;            /* 0x064 */
    u8  pad_068[0x26];
    s16 unk_08e;            /* 0x08e */
    u8  pad_090[0x4];
    u16 unk_094;            /* 0x094 */
    u8  pad_096[0x2];
    s32 unk_098;            /* 0x098 */
    u8  pad_09c[0x284];
    s32 unk_320;            /* 0x320 */
    s32 unk_324;            /* 0x324 */
    s32 unk_328;            /* 0x328 */
    s32 unk_32c;            /* 0x32c */
    s32 unk_330;            /* 0x330 */
    s16 unk_334;            /* 0x334 */
    u8  unk_336;            /* 0x336 */
    u8  pad_337[0x1];
    s32 unk_338;            /* 0x338 */
};

#endif
