/* AUTO-GENERATED by tools/deepen_rtti.py from 5 functions
 * class daObjFl_Seesaw_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAOBJFL_SEESAW_C_H
#define DAOBJFL_SEESAW_C_H
#include "types.h"

struct daObjFl_Seesaw_c {
    u8  pad_000[0x8c];
    s16 mAngleX;            /* 0x08c */
    s16 mAngleY;            /* 0x08e */
    u8  pad_090[0x28e];
    s16 mSwingStep;            /* 0x31e */
    u8  mSwingCooldown;            /* 0x320 */
};

#endif
