/* AUTO-GENERATED by tools/deepen_rtti.py from 5 functions
 * class daObjKm1_Ukishima_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DAOBJKM1_UKISHIMA_C_FIELDS_H
#define DAOBJKM1_UKISHIMA_C_FIELDS_H
#include "types.h"

/* daObjKm1_Ukishima_c_classInit (historical alias DiamondLift_Spawn) allocates
 * 0x320 bytes, constructs dBgActor_c, and installs this RTTI class's vtable. */

/* SHADOW STRUCT, not the class. The real class header is
 * include/daObjKm1_Ukishima_c.h; this flat view exists only so the legacy
 * bodies can name the base's fields at their measured offsets. */
struct daObjKm1_Ukishima_c_fields {
    u8  pad_000[0x8e];
    s16 mAngleY;            /* 0x08e */
    u8  pad_090[0x4];
    s16 mPrevAngleY;            /* 0x094 */
    u8  pad_096[0x2];
    s32 mHorzSpeed;            /* 0x098 */
    u8  pad_09c[0x282];
    u8  unk_31e;            /* 0x31e */
};

#endif
