/* AUTO-GENERATED by tools/deepen_rtti.py from 3 functions
 * class daSoundObj_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DASOUNDOBJ_C_H
#define DASOUNDOBJ_C_H
#include "types.h"

struct daSoundObj_c {
    u8  pad_000[0xd4];
    s32 unk_0d4;            /* 0x0d4 */
    s32 unk_0d8;            /* 0x0d8 */
    u16 unk_0dc;            /* 0x0dc */
    u16 unk_0de;            /* 0x0de */
};

#endif
