/* A polygon hit produced by the background-collision system.
 *
 * ROM RTTI records dBgPc as the sole base. dBgPi introduces the hierarchy's
 * first virtual function, so mwccarm places its vptr at 0x00 and dBgPc at
 * 0x04. The remaining fields begin at 0x18. This is the layout generated by
 * the pinned compiler and the one used by the C1/C2/D1 ROM bodies.
 */
#ifndef DBGPI_H
#define DBGPI_H
#include "dBgPc.h"

#ifndef __cplusplus

struct dBgPi {
    void **vtable;          /* 0x000 */
    struct dBgPc base;      /* 0x004 */
    u16 triangleID;         /* 0x018 */
    u16 flags;              /* 0x01a */
    s32 clsnID;             /* 0x01c */
    s32 unk_020;            /* 0x020 */
    s32 unk_024;            /* 0x024 */
};

typedef char dBgPi_size_must_be_0x28[sizeof(struct dBgPi) == 0x28 ? 1 : -1];
typedef struct dBgPi dBgPi;

#else

extern "C" void _ZN6Memory16operator_delete2EPv(void *);

struct dBgPi : dBgPc {
    /* 0x00 is the vptr; the dBgPc base occupies 0x04..0x17. */
    u16 triangleID;         /* 0x018 */
    u16 flags;              /* 0x01a */
    s32 clsnID;             /* 0x01c */
    s32 unk_020;            /* 0x020 */
    s32 unk_024;            /* 0x024 */

    /* --- vtable, in ROM order. Do not reorder. --- */
    virtual ~dBgPi();       /* slots 0 (D1), 1 (D0) */

    /* WHAT LETS A REAL `~dBgPi()` REPRODUCE THE ROM'S DELETING DESTRUCTOR.
       mwcc builds D0 as "run the destructor body, then call operator delete
       on the class". With no class-specific operator delete in scope it calls
       the GLOBAL `_ZdlPv` (this image: 0x0203cbf0) where the ROM's D0 calls
       Memory::operator_delete2 (0x0203cbcc). That is ONE relocated word,
       which match.py and fdiff WILDCARD -- the isolated gate reports a clean
       MATCH and only the full link disagrees. It is why the dBgPi deleting
       destructor was rejected by the link in PR #1764.

       The ROM proves the destination: _ZN5dBgPiD0Ev's second `bl` is to
       0x0203cbcc = Memory::operator_delete2, the same heap path the sibling
       dBgCh family uses (include/dBgCh.h carries an identical copy).

       Declared here rather than on dBgPc because dBgPc is a non-polymorphic
       data record that is never deleted; dBgPi is the class whose D0 does the
       deallocation. Inline, in the class itself -- mwcc inlines it only when
       it finds it in the class or one level up. No layout effect: a
       non-virtual inline member adds no field and no vtable slot. */
    void operator delete(void *ptr) { _ZN6Memory16operator_delete2EPv(ptr); }

    /* Defined out of line; objisolate retains the enrolled C1/D1 variants and
       the compiler-generated siblings remain separately enrolled shells. */
    dBgPi();

    /* methods */
    dBgPi &operator=(const dBgPi &other);
    void CopyTo(dBgPi &dst) const;
    u32 GetClsnID() const;
};

/* Size is the dBgPi's own span AND the stride of the three consecutive results
   dBgCh_SphCrr holds at 0x74/0x9c/0xc4 -- notes/collision-system.md 3.2. */
typedef char dBgPi_size_must_be_0x28[sizeof(struct dBgPi) == 0x28 ? 1 : -1];

#endif /* __cplusplus */

#endif
