/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_TEXTURESEQUENCE_H
#define DECL_TEXTURESEQUENCE_H
#include "common.h"

extern void _ZN15TextureSequenceC1Ev(void*);

#endif
