/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_MOVINGCYLINDERCLSNWITHPOS_H
#define DECL_MOVINGCYLINDERCLSNWITHPOS_H
#include "common.h"

extern void _ZN25MovingCylinderClsnWithPosC1Ev(void*);

#endif
