/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_ACTORBASE_H
#define DECL_ACTORBASE_H
#include "common.h"

extern int _ZN9ActorBase14BeforeBehaviorEv(void*);
extern void*_ZN9ActorBasenwEj(unsigned);

#endif
