/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_HEAPALLOCATOR_H
#define DECL_HEAPALLOCATOR_H
#include "common.h"

extern void _ZN13HeapAllocatorC1EjPvPvj(void*, u32, void*, void*, u32);

#endif
