/* AUTO-GENERATED by tools/decl_headers.py - one declaration per symbol,
 * replacing copies that were repeated in every file that called them. */
#ifndef DECL_BLENDMODELANIM_H
#define DECL_BLENDMODELANIM_H
#include "common.h"

extern void _ZN14BlendModelAnimC1Ev(void*);
extern void _ZN14BlendModelAnimD1Ev(void*);

#endif
