/* AUTO-GENERATED by tools/deepen_rtti.py from 5 functions
 * class dScMgCoin_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DSCMGCOIN_C_H
#define DSCMGCOIN_C_H
#include "types.h"

struct dScMgCoin_c {
    u8  pad_000[0xa8];
    s32 unk_0a8;            /* 0x0a8 */
    s32 unk_0ac;            /* 0x0ac */
    u8  pad_0b0[0x5118];
    s32 unk_51c8;           /* 0x51c8 */
    u8  pad_51cc[0x8];
    s32 unk_51d4;           /* 0x51d4 */
    u8  pad_51d8[0x2];
    u8  unk_51da;           /* 0x51da */
    u8  unk_51db;           /* 0x51db */
#ifdef __cplusplus
    int Render();
#endif
};

#endif
