/* AUTO-GENERATED by tools/deepen_rtti.py from 7 functions
 * class dScMgMCarlo2_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DSCMGMCARLO2_C_H
#define DSCMGMCARLO2_C_H
#include "types.h"

struct dScMgMCarlo2_c {
    u8  pad_000[0xa8];
    s32 unk_0a8;            /* 0x0a8 */
    s32 unk_0ac;            /* 0x0ac */
    u8  pad_0b0[0x4ea2];
    s16 unk_4f52;           /* 0x4f52 */
    u8  pad_4f54[0x1ca];
    s16 unk_511e;           /* 0x511e */
    u8  pad_5120[0x808];
    s16 unk_5928;           /* 0x5928 */
    s16 unk_592a;           /* 0x592a */
    u8  pad_592c[0x2];
    s16 unk_592e;           /* 0x592e */
};

#endif
