/* AUTO-GENERATED by tools/deepen_rtti.py from 10 functions
 * class dScMgTrampoline_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DSCMGTRAMPOLINE_C_H
#define DSCMGTRAMPOLINE_C_H
#include "types.h"

struct dScMgTrampoline_c {
    u8  pad_000[0xbc];
    s32 unk_0bc;            /* 0x0bc */
    u8  pad_0c0[0x4568];
    s32 unk_4628;           /* 0x4628 */
    u8  pad_462c[0x38];
    u16 unk_4664;           /* 0x4664 */
    u8  pad_4666[0xa6];
    s32 unk_470c;           /* 0x470c */
    s32 unk_4710;           /* 0x4710 */
    s32 unk_4714;           /* 0x4714 */
    s32 unk_4718;           /* 0x4718 */
    s32 unk_471c;           /* 0x471c */
    s32 unk_4720;           /* 0x4720 */
    u16 unk_4724;           /* 0x4724 */
    u8  pad_4726[0xa2];
    s32 unk_47c8;           /* 0x47c8 */
    s32 unk_47cc;           /* 0x47cc */
    s32 unk_47d0;           /* 0x47d0 */
    s32 unk_47d4;           /* 0x47d4 */
    s32 unk_47d8;           /* 0x47d8 */
    s32 unk_47dc;           /* 0x47dc */
    u16 unk_47e0;           /* 0x47e0 */
    u8  pad_47e2[0x15b2];
    s32 unk_5d94;           /* 0x5d94 */
    s32 unk_5d98;           /* 0x5d98 */
    s32 unk_5d9c;           /* 0x5d9c */
    s32 unk_5da0;           /* 0x5da0 */
    s32 unk_5da4;           /* 0x5da4 */
    s32 unk_5da8;           /* 0x5da8 */
    u8  pad_5dac[0x4];
    s16 unk_5db0;           /* 0x5db0 */
    s16 unk_5db2;           /* 0x5db2 */
    s16 unk_5db4;           /* 0x5db4 */
    s16 unk_5db6;           /* 0x5db6 */
    s16 unk_5db8;           /* 0x5db8 */
    s16 unk_5dba;           /* 0x5dba */
    s16 unk_5dbc;           /* 0x5dbc */
    s16 unk_5dbe;           /* 0x5dbe */
    s16 unk_5dc0;           /* 0x5dc0 */
    s16 unk_5dc2;           /* 0x5dc2 */
    u8  unk_5dc4;           /* 0x5dc4 */
    u8  unk_5dc5;           /* 0x5dc5 */
};

#endif
