/* AUTO-GENERATED by tools/deepen_rtti.py from 10 functions
 * class dScMgFlower_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DSCMGFLOWER_C_H
#define DSCMGFLOWER_C_H
#include "types.h"

struct dScMgFlower_c {
    u8  pad_000[0xc0];
    u16 unk_0c0;            /* 0x0c0 */
    u8  pad_0c2[0x1];
    u8  unk_0c3;            /* 0x0c3 */
    u8  unk_0c4;            /* 0x0c4 */
    u8  pad_0c5[0x5ef3];
    s32 unk_5fb8;           /* 0x5fb8 */
    s32 unk_5fbc;           /* 0x5fbc */
    s32 unk_5fc0;           /* 0x5fc0 */
    s32 unk_5fc4;           /* 0x5fc4 */
    s32 unk_5fc8;           /* 0x5fc8 */
    u8  unk_5fcc;           /* 0x5fcc */
    u8  unk_5fcd;           /* 0x5fcd */
    u8  pad_5fce[0x2];
    s32 unk_5fd0;           /* 0x5fd0 */
    s32 unk_5fd4;           /* 0x5fd4 */
    s32 unk_5fd8;           /* 0x5fd8 */
    s32 unk_5fdc;           /* 0x5fdc */
    s32 unk_5fe0;           /* 0x5fe0 */
    s32 unk_5fe4;           /* 0x5fe4 */
    s32 unk_5fe8;           /* 0x5fe8 */
    s32 unk_5fec;           /* 0x5fec */
    s32 unk_5ff0;           /* 0x5ff0 */
    u16 unk_5ff4;           /* 0x5ff4 */
};

#endif
