/* AUTO-GENERATED by tools/deepen_rtti.py from 5 functions
 * class dScMgCurling_c, recovered from ROM RTTI + vtable slot identity.
 * Offsets/widths are observed. Names are placeholders. */
#ifndef DSCMGCURLING_C_H
#define DSCMGCURLING_C_H
#include "types.h"

struct dScMgCurling_c {
    u8  pad_000[0xa4];
    s32 unk_0a4;            /* 0x0a4 */
    u8  pad_0a8[0x4e04];
    s32 unk_4eac;           /* 0x4eac */
    u8  pad_4eb0[0x28];
    s32 unk_4ed8;           /* 0x4ed8 */
    u8  pad_4edc[0x4];
    u16 unk_4ee0;           /* 0x4ee0 */
    u16 unk_4ee2;           /* 0x4ee2 */
    u8  pad_4ee4[0x3];
    u8  unk_4ee7;           /* 0x4ee7 */
};

#endif
