#!/usr/bin/env python3
"""Move partial-link-verified reconstructed TUs into canonical production.

This is a structural promotion only.  It does not delete the one-function sources:
they remain exact comparison oracles, while ``rombuild.py`` compiles each canonical
TU once and substitutes its manifest functions at those existing object paths.
The default is a dry run; ``--apply`` performs the moves and manifest/registry edits.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys


REPO = pathlib.Path(__file__).resolve().parent.parent
MANIFEST_ROOT = REPO / "config" / "tu_manifest.d"
REGISTRY = REPO / "config" / "production-tus.json"
ATTRIBUTION = REPO / "attribution.json"
sys.path.insert(0, str(REPO / "tools"))
import chaos_db_ci as CDB  # noqa: E402


class PromotionError(RuntimeError):
    pass


def load_entries():
    entries = {}
    for path in sorted(MANIFEST_ROOT.rglob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        tu_id = data.get("id")
        if not tu_id:
            continue
        if tu_id in entries:
            raise PromotionError(f"duplicate manifest id {tu_id!r}")
        entries[tu_id] = (path, data)
    return entries


def target_for(entry):
    source = pathlib.PurePosixPath(entry["source"])
    if len(source.parts) < 3 or source.parts[0] != "src_tu":
        raise PromotionError(
            f"{entry['id']}: expected a source under src_tu/, got {source}")
    category = source.parts[1]
    if category in ("stage", "scene"):
        parent = pathlib.PurePosixPath("src/game/stages")
    elif category == "actors":
        legacy = [pathlib.PurePosixPath(row["legacy_source"])
                  for row in entry.get("functions", [])]
        minigame = sum(len(path.parts) > 1 and path.parts[1] == "minigames"
                       for path in legacy)
        parent = (pathlib.PurePosixPath("src/minigames")
                  if legacy and minigame * 2 > len(legacy)
                  else pathlib.PurePosixPath("src/game/actors"))
    else:
        raise PromotionError(
            f"{entry['id']}: no Candidate-2 destination rule for src_tu/{category}/")
    return parent / source.name


def canonical_comment(text, function_count):
    text = text.replace(
        "/* SHADOW translation unit -- generated by tools/tubuild.py create.",
        "/* Canonical production translation unit -- reconstructed with tools/tubuild.py.",
        1,
    )
    old = (
        " * NOT ENROLLED, NOT CANONICAL. This file contributes nothing to the ROM\n"
        " * build. It is a STARTING POINT (plan sec 7.3): local shadow declarations\n"
        " * below were carried verbatim from the legacy files, not reconciled against\n"
        " * real project headers -- that judgement call is left to a human/LLM review,\n"
        " * the way pilot #1 reconciled PoleLift::Render and ::CleanupResources by hand\n"
        " * (see notes/tu-reconstruction-pilot-report.md sec 5.2).\n"
    )
    new = (
        f" * The default stock build compiles this file once, derives its {function_count}\n"
        " * exact text contributions, and substitutes them for retained one-function\n"
        " * comparison objects. The manifest partial-link proof and ordinary ROM build\n"
        " * both require the linked module and final ROM to remain byte-identical.\n"
    )
    if old in text:
        text = text.replace(old, new, 1)
    return text


def plan(ids):
    manifests = load_entries()
    rows = []
    for tu_id in ids:
        found = manifests.get(tu_id)
        if found is None:
            raise PromotionError(f"no manifest for {tu_id!r}")
        path, entry = found
        partial = entry.get("partial_isolation") or {}
        state = partial.get("state")
        rom = partial.get("rom") or {}
        full_link_proven = (rom.get("matchesStockRom") is True or
                            ((partial.get("phases") or {}).get("rom") is True
                             and partial.get("moduleFidelityPassed") is True))
        if state != "partial-link-verified" or not full_link_proven:
            raise PromotionError(
                f"{tu_id}: partial isolation has no stock-ROM-identical proof")
        if (entry.get("partitioned_link") or {}).get("state") \
                == "partitioned-link-verified":
            raise PromotionError(
                f"{tu_id}: already has stronger non-text partitioned production proof")
        target = target_for(entry)
        source_path = REPO / pathlib.Path(entry["source"])
        target_path = REPO / pathlib.Path(target.as_posix())
        if not source_path.is_file():
            raise PromotionError(f"{tu_id}: source is missing: {entry['source']}")
        if target_path.exists():
            raise PromotionError(f"{tu_id}: destination already exists: {target}")
        try:
            source_path.resolve().relative_to((REPO / "src_tu").resolve())
            target_path.resolve().relative_to((REPO / "src").resolve())
        except ValueError as exc:
            raise PromotionError(f"{tu_id}: move escapes the intended source roots") from exc
        rows.append((tu_id, path, entry, source_path, target_path, target.as_posix()))
    return rows


def apply(rows):
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if registry.get("schema_version") != 1:
        raise PromotionError("production registry needs schema_version 1")
    partitioned = set(registry.get("partitioned_tus", []))
    derived = list(registry.get("derived_text_tus", []))
    if any(tu_id in partitioned or tu_id in derived for tu_id, *_rest in rows):
        raise PromotionError("one or more requested TUs is already in production registry")

    for tu_id, manifest_path, entry, source_path, target_path, target in rows:
        target_path.parent.mkdir(parents=True, exist_ok=True)
        text = canonical_comment(
            source_path.read_text(encoding="utf-8"), len(entry.get("functions", [])))
        source_path.replace(target_path)
        target_path.write_text(text, encoding="utf-8", newline="\n")
        entry["source"] = target
        entry["promoted_source"] = target
        entry["production_mode"] = "derived-text"
        manifest_path.write_text(json.dumps(entry, indent=2) + "\n",
                                 encoding="utf-8", newline="\n")
        derived.append(tu_id)

    registry["derived_text_tus"] = derived
    REGISTRY.write_text(json.dumps(registry, indent=2) + "\n",
                        encoding="utf-8", newline="\n")


def sync_attribution(entries, ids):
    """Preserve every legacy function's contributor on its canonical TU member."""
    data = json.loads(ATTRIBUTION.read_text(encoding="utf-8"))
    overrides = data.get("overrides")
    if not isinstance(overrides, dict):
        raise PromotionError("attribution.json has no overrides object")
    first = CDB.first_matchers("HEAD")
    finishers = CDB.match_finishers("HEAD")
    added = 0
    for tu_id in ids:
        found = entries.get(tu_id)
        if found is None:
            raise PromotionError(f"production attribution has no manifest {tu_id!r}")
        _path, entry = found
        source = entry.get("source")
        if not isinstance(source, str) or not source.startswith("src/"):
            raise PromotionError(f"{tu_id}: canonical attribution source is invalid")
        for row in entry.get("functions", []):
            legacy = row.get("legacy_source")
            symbol = row.get("symbol")
            author = (overrides.get(legacy) or finishers.get(legacy)
                      or first.get(legacy))
            if not author:
                raise PromotionError(
                    f"{tu_id}: no contributor lineage for {legacy!r}")
            key = f"{source}#{symbol}"
            previous = overrides.get(key)
            if previous is not None and previous != author:
                raise PromotionError(
                    f"{key}: existing attribution {previous!r} conflicts with {author!r}")
            if previous is None:
                overrides[key] = author
                added += 1
    ATTRIBUTION.write_text(json.dumps(data, indent=2) + "\n",
                           encoding="utf-8", newline="\n")
    return added


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ids", nargs="*", help="manifest TU ids to promote")
    parser.add_argument("--all-verified", action="store_true",
                        help="select every unpromoted partial-link-verified TU")
    parser.add_argument("--apply", action="store_true",
                        help="perform the moves and JSON edits (default: dry run)")
    parser.add_argument("--sync-attribution", action="store_true",
                        help="write path#symbol credit for every configured production TU")
    args = parser.parse_args()
    entries = load_entries()
    ids = list(args.ids)
    if args.all_verified:
        ids.extend(
            tu_id for tu_id, (_path, entry) in entries.items()
            if entry.get("source", "").startswith("src_tu/")
            and (entry.get("partial_isolation") or {}).get("state")
                == "partial-link-verified"
            and (entry.get("partitioned_link") or {}).get("state")
                != "partitioned-link-verified"
        )
    ids = list(dict.fromkeys(ids))
    if not ids and not args.sync_attribution:
        parser.error("pass TU ids or --all-verified")
    rows = plan(ids) if ids else []
    for tu_id, _path, _entry, source, target, _target_rel in rows:
        print(f"{tu_id}: {source.relative_to(REPO).as_posix()} -> "
              f"{target.relative_to(REPO).as_posix()}")
    if args.apply:
        apply(rows)
        print(f"promoted {len(rows)} derived-text TU(s)")
    elif rows:
        print(f"dry run: {len(rows)} TU(s); pass --apply to perform")
    if args.sync_attribution:
        registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
        production_ids = [*registry.get("partitioned_tus", []),
                          *registry.get("derived_text_tus", [])]
        entries = load_entries()
        added = sync_attribution(entries, production_ids)
        print(f"added {added} production TU member attribution override(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
