"""One place that answers "where does symbol X live in src/".

AGENTS.md fixes the convention: one matched function per file, and the filename IS the
symbol. That used to be spelled `SRC / f"{name}.{ext}"` inline in a dozen tools, which is
what kept `src/` a permanently flat directory of 11,203 files: giving any one file a home
meant finding and fixing every copy. Every one of those call sites now comes through here
-- chaos_db_ci, clone, enroll, import_symbols, knowledge, ledger, name_evidence,
nonmatching, progress, rebuild_ledger, reconcile_names, reverify_corpus, verify_mangled,
worklist -- so the directory is a decision this module makes alone.

The convention itself does not change: filename is still the symbol, still one function
per file. `enroll` is the one that makes this load-bearing rather than cosmetic -- it
writes each source's path into `config/**/delinks.txt` for the ROM link, so a file that
moves has to stay findable or its function silently drops back to ROM bytes.

WHY THERE IS NO COMMITTED INDEX
-------------------------------
The obvious implementation is a checked-in symbol -> path map. Do not do that while
`src/` is flat: an 11k-entry file regenerated by every batch would conflict on
essentially every PR, in a repo landing one every few minutes. Resolution is instead:

1. the direct hit `src/<symbol>.c|.cpp` -- O(1), no scan, and correct for every file
   in the tree today, so the common path costs nothing;
2. failing that, a lazily built map of everything under `src/` -- one `rglob`, cached,
   which is what makes a subdirectory layout work the day a file moves.

A committed index only earns its keep once most of the tree has moved and the scan is
the common path rather than the fallback. That is a Phase-3 decision, not this one.

Note `symbol_for` is deliberately `Path.stem`, matching what pr_linkcheck already does
to derive the symbol it link-checks. Keep the two in step.
"""
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC = REPO / "src"
SOURCE_SUFFIXES = (".c", ".cpp")

_scan_cache = None


def symbol_for(path):
    """The symbol a source file claims. The filename IS the symbol (AGENTS.md)."""
    return pathlib.Path(path).stem


def _scan():
    """symbol -> [paths], built once from the whole tree. Only reached when the direct
    hit misses, i.e. once files start living in subdirectories."""
    global _scan_cache
    if _scan_cache is None:
        found = {}
        if SRC.is_dir():
            for p in SRC.rglob("*"):
                if p.is_file() and p.suffix in SOURCE_SUFFIXES:
                    found.setdefault(p.stem, []).append(p)
        _scan_cache = found
    return _scan_cache


def invalidate():
    """Drop the scan cache. Call after writing or moving files in a long-lived process."""
    global _scan_cache
    _scan_cache = None


def set_root(repo):
    """Resolve against a different checkout. Returns the previous ``(REPO, SRC)``.

    Reassigning REPO/SRC by hand works, but silently keeps a scan cache built from the
    old tree -- a confusing way to fail. Tools that accept a redirected source directory
    (worklist did, and its tests rely on it) go through this instead, so the cache
    invariant is not something a caller can forget.
    """
    global REPO, SRC
    saved = (REPO, SRC)
    REPO = pathlib.Path(repo)
    SRC = REPO / "src"
    invalidate()
    return saved


def paths_for(symbol):
    """Every existing source file for ``symbol``, `.c` before `.cpp`.

    More than one is not normal -- a symbol with both a .c and a .cpp is the ambiguity
    ledger.bank refuses -- so callers that need exactly one should use ``path_for``."""
    direct = [SRC / f"{symbol}{ext}" for ext in SOURCE_SUFFIXES]
    hits = [p for p in direct if p.is_file()]
    if hits:
        return hits
    found = _scan().get(symbol, [])
    return sorted(found, key=lambda p: SOURCE_SUFFIXES.index(p.suffix))


def path_for(symbol):
    """The source file for ``symbol``, or None. `.c` wins when both exist."""
    hits = paths_for(symbol)
    return hits[0] if hits else None


def new_path_for(symbol, ext):
    """Where a NEW file for ``symbol`` goes. ``ext`` is "c" or "cpp", with or without
    the dot. Writers use this instead of composing the path themselves, so the choice of
    directory stays in one place once `src/` gains structure."""
    ext = ext if ext.startswith(".") else "." + ext
    if ext not in SOURCE_SUFFIXES:
        raise ValueError(f"not a source extension: {ext!r}")
    existing = path_for(symbol)
    if existing is not None:
        # Keep a symbol where it already lives; changing the extension is the caller's
        # business, relocating it is not.
        return existing.with_suffix(ext)
    return SRC / f"{symbol}{ext}"


def iter_sources():
    """Every source file under src/, in sorted order."""
    if not SRC.is_dir():
        return
    for p in sorted(SRC.rglob("*")):
        if p.is_file() and p.suffix in SOURCE_SUFFIXES:
            yield p


def build_index():
    """symbol -> repo-relative posix path, for tooling that wants the whole map.

    Resolves collisions the same way ``path_for`` does (`.c` before `.cpp`) rather than
    letting directory order decide -- a handful of symbols in the tree have both, and an
    index that disagreed with the resolver would be worse than no index at all."""
    out = {}
    for p in iter_sources():
        prev = out.get(p.stem)
        if prev is None or (SOURCE_SUFFIXES.index(p.suffix)
                            < SOURCE_SUFFIXES.index(pathlib.PurePosixPath(prev).suffix)):
            out[p.stem] = p.relative_to(REPO).as_posix()
    return out


if __name__ == "__main__":
    import argparse
    import json

    ap = argparse.ArgumentParser(description="resolve a symbol to its src/ path")
    ap.add_argument("symbol", nargs="?", help="symbol to look up")
    ap.add_argument("--index", action="store_true", help="dump the whole map as JSON")
    a = ap.parse_args()
    if a.index:
        print(json.dumps(build_index(), indent=1))
    elif a.symbol:
        p = path_for(a.symbol)
        print(p.relative_to(REPO).as_posix() if p else f"{a.symbol}: not in src/")
    else:
        ap.error("pass a symbol or --index")
