"""One place that answers "where does symbol X live in src/".

AGENTS.md fixes the convention: one matched function per file, and the filename IS the
symbol. That used to be spelled `SRC / f"{name}.{ext}"` inline in a dozen tools, which is
what kept `src/` a permanently flat directory of 11,203 files: giving any one file a home
meant finding and fixing every copy. Every one of those call sites now comes through here
-- actor_names, chaos_db_ci, clone, cpp_index, cpp_rename, enroll, import_symbols,
knowledge, ledger, name_evidence, nonmatching, progress, rebuild_ledger,
reconcile_names, reverify_corpus, rombuild_versions, sigaudit, stamp_provenance,
verify_mangled, worklist -- so the directory is a decision this module makes alone.

The convention still holds for legacy one-function sources, and `enroll` is what makes
it load-bearing rather than cosmetic -- it writes each source's path into
`config/**/delinks.txt` for the ROM link, so a file that moves has to stay findable or
its function silently drops back to ROM bytes.

But the convention is not the only answer, and it is no longer the FIRST one. See
`_enrolment` below: delinks.txt already records which file owns which address range, and
that record is what dsd compiles. A merged translation unit -- two functions, one file,
a name that is neither symbol -- is invisible to the convention and perfectly visible to
the enrolment table. Ask the table first, fall back to the convention. Where one source
owns one same-named function, nothing changes; shared-source entries also round-trip.

WHY THERE IS NO COMMITTED INDEX
-------------------------------
The obvious implementation is a checked-in symbol -> path map. Do not do that while
`src/` is flat: an 11k-entry file regenerated by every batch would conflict on
essentially every PR, in a repo landing one every few minutes. Resolution is instead:

0. the enrolment table -- 106 delinks.txt plus 106 symbols.txt, parsed once into a dict
   in 0.08s, cached. Authoritative, because it is what the linker reads;
1. the direct hit `src/<symbol>.c|.cpp` -- O(1), no scan, and correct for ordinary
   one-function sources, so the common path costs nothing;
2. failing that, a lazily built map of everything under `src/` -- one `rglob`, cached,
   which is what makes a subdirectory layout work the day a file moves.

A committed index only earns its keep once most of the tree has moved and the scan is
the common path rather than the fallback. That is a Phase-3 decision, not this one.
Note that step 0 is not that index: it is derived from files the repo already commits
for the link, so it cannot drift from them and adds nothing to conflict over.

`symbol_for` is deliberately `Path.stem` and stays that way -- it answers what a file
CLAIMS by its name. `symbols_for` answers what a file OWNS, which is the question
pr_linkcheck has to ask once a file can own two functions. Keep those two distinct.

PLACEMENT FOLLOWS MIGRATION, IT DOES NOT LEAD IT
------------------------------------------------
`new_path_for` used to answer `src/<symbol>.ext` unconditionally, which is why #970 and
#975 did not stick: they moved 164 files into subdirectories, and every match landed
afterwards went back to the root regardless. Measured over the 30 days to 2026-08-04,
`src/` grew from 9,102 files to 11,242 and every one of the new ones was flat.

So placement is a rule now, but a deliberately timid one. A new file goes nested only
when the files it belongs with are ALREADY nested, and only when they agree on where:

  * an address-named symbol (`func_ov063_021160c4`) goes to `src/unnamed/<module>/`
    **if that directory exists**. Creating it is the migration's explicit opt-in; until
    then its module's files stay in the root, which is where the rest of them are.
  * a class-named symbol goes wherever its class already lives, if its existing files
    occupy exactly one subdirectory. `_ZN7daTrs_c6RenderEv` follows the other seven `daTrs_c`
    files into `src/game/actors/daTrs_c/`; a `Player` method stays flat because all 248 of them
    are still flat.
  * anything else -- free functions, thunks, plain names -- stays in the root.

Two directories can never be inferred, so a half-migrated class is left alone rather
than guessed at. The effect is that migrating a module makes it *stay* migrated, and
nothing moves that a human did not already move.
"""
import bisect
import pathlib
import re

import relocs

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC = REPO / "src"
SOURCE_SUFFIXES = (".c", ".cpp")

# src/unnamed/<module>/ -- the bucket #975 established for symbols whose name carries no
# class, only an address. Spelled once, here, so the convention is one edit to revisit.
UNNAMED_DIR = "unnamed"

_UNNAMED_RE = re.compile(r"^(?:func|FUN|__sinit)_(?:(ov\d+)_)?[0-9a-fA-F]{8}$")
_SPAWN_RE = re.compile(r"^(\w+)_Spawn$")

_scan_cache = None
_cohort_cache = None
_enrolment_cache = None
_definition_ownership_cache = None


def symbol_for(path):
    """The filename-based symbol for a legacy one-function source.

    Use :func:`symbols_for` when enrollment may map several functions to one source.
    """
    return pathlib.Path(path).stem


def _scan():
    """symbol -> [paths], built once from the whole tree. Only reached when the direct
    hit misses, i.e. once files start living in subdirectories."""
    global _scan_cache
    if _scan_cache is None:
        found = {}
        if SRC.is_dir():
            for p in SRC.rglob("*"):
                if p.is_file() and p.suffix in SOURCE_SUFFIXES:
                    found.setdefault(p.stem, []).append(p)
        _scan_cache = found
    return _scan_cache


def invalidate():
    """Drop the caches. Call after writing or moving files in a long-lived process.

    The enrolment index is dropped too: `enroll` and `tubuild promote` both rewrite
    delinks.txt, and a stale index would keep answering with the file they replaced."""
    global _scan_cache, _cohort_cache, _enrolment_cache, _definition_ownership_cache
    _scan_cache = None
    _cohort_cache = None
    _enrolment_cache = None
    _definition_ownership_cache = None


# One delinks entry opens with an unindented `<path>:` and owns the indented
# `.<section> start:0x.. end:0x..` lines under it. Indented lines BEFORE the first entry
# are the module's own section header -- `.text start:0x02004000 end:0x020736f4
# kind:code align:32`, 74 of them tree-wide -- which describes the whole module and owns
# nothing. Reading those as an entry's sections would hand one file every function in
# its module.
_DELINKS_SECTION_RE = re.compile(r"\.\w+\s+start:0x([0-9a-fA-F]+)\s+end:0x([0-9a-fA-F]+)")
_SYMBOL_FUNC_RE = re.compile(
    r"^(\S+)\s+kind:function\([^,]+,size=0x([0-9a-fA-F]+)\)"
    r"\s+addr:0x([0-9a-fA-F]+)"
)


def definition_symbols(rel, rows):
    """Collapse only the proven legacy outer-owner alias shape.

    ``rows`` is ``[(address, size, symbol)]``. A convention-named legacy source
    can own nested symbol records inside its one outer definition; a reconstructed
    TU whose filename names no member must define every disjoint owned symbol.
    """
    stem = pathlib.PurePosixPath(rel).stem
    ordered = sorted(rows)
    owners = [(addr, size, name) for addr, size, name in ordered if name == stem]
    if len(owners) == 1:
        owner_addr, owner_size, owner_name = owners[0]
        owner_end = owner_addr + owner_size
        if all(owner_addr <= addr and addr + size <= owner_end
               for addr, size, _name in ordered):
            return [owner_name]
    return [name for _addr, _size, name in ordered]


def _enrolment():
    """``(symbol -> src path, src path -> [symbols, ROM order])`` off the enrolment table.

    THE SECOND ANSWER TO "WHICH FILE OWNS THIS SYMBOL"
    --------------------------------------------------
    The convention says `src/<symbol>.c`. The enrolment table says: the delinks entry
    whose section range contains the symbol's address is the file dsd compiles for that
    range. Most sources still agree with the convention; a source that owns several
    symbol addresses legitimately does not. The live-tree round-trip is measured by
    ``test_enrolment_round_trips_single_and_multi_symbol_sources``.

    They stop agreeing the moment one file owns two functions, which is what TU
    reconstruction produces: a promoted `src/actors/ActorBase_SceneNode.cpp` is the
    enrolled owner of 0x0203b4ac..0x0203b4dc, and neither symbol in it can be found by
    filename. The
    convention then answers None, and every tool built on it concludes the functions
    have no source at all -- they drop out of `matched`, out of the byte-verified count,
    and their authors lose credit -- while the ROM build goes on compiling and
    byte-comparing them exactly as before. A coverage loss that is purely an artefact of
    how the question was asked.

    So the enrolment table is consulted FIRST and the convention is the fallback. That
    ordering is the safe one in both directions: where they agree it changes nothing,
    and where they disagree the enrolment table is the one the linker reads. A stale
    one-function file left behind beside a promoted TU is then correctly ignored rather
    than counted as a match nothing builds.

    `mods/` ENTRIES ARE EXCLUDED, deliberately and load-bearingly. A delinks entry can
    point at `mods/<Symbol>.c` -- an intentional divergence from the cartridge, not a
    reproduction of it -- and `rombuild_profile._stock_delinks` swaps it back to its
    `src/` counterpart for a stock link *by calling path_for on the mods stem*. Letting
    the mod win here would make that swap a no-op and leak the mod into the stock ROM.
    This module's first line is "where does symbol X live in src/", and that is exactly
    the rule: only entries under `src/`. (`mods/` is currently empty, but the exclusion
    stays load-bearing for the next divergence someone adds there.)"""
    global _enrolment_cache, _definition_ownership_cache
    if _enrolment_cache is None:
        by_symbol, by_path = {}, {}
        for symbols_path, _label in relocs.module_universe(repo=REPO):
            delinks = symbols_path.parent / "delinks.txt"
            if not delinks.is_file():
                continue
            funcs = []
            for line in symbols_path.read_text(encoding="utf-8",
                                               errors="ignore").splitlines():
                m = _SYMBOL_FUNC_RE.match(line.strip())
                if m:
                    funcs.append((int(m.group(3), 16), int(m.group(2), 16), m.group(1)))
            funcs.sort()
            addrs = [addr for addr, _size, _name in funcs]
            entry = None
            for line in delinks.read_text(encoding="utf-8",
                                          errors="ignore").splitlines():
                if not line.strip():
                    continue
                if not line[0].isspace():
                    entry = line.strip().rstrip(":")
                    continue
                if entry is None or not entry.startswith("src/"):
                    continue
                m = _DELINKS_SECTION_RE.search(line)
                if not m:
                    continue
                start, end = int(m.group(1), 16), int(m.group(2), 16)
                i = bisect.bisect_left(addrs, start)
                while i < len(addrs) and addrs[i] < end:
                    by_symbol[funcs[i][2]] = entry
                    by_path.setdefault(entry, []).append(funcs[i])
                    i += 1
        _definition_ownership_cache = {
            path: definition_symbols(path, rows) for path, rows in by_path.items()
        }
        _enrolment_cache = (
            by_symbol,
            {path: [name for _addr, _size, name in sorted(rows)]
             for path, rows in by_path.items()},
        )
    return _enrolment_cache


def enrolment_index():
    """symbol -> repo-relative `src/` path, for every function the ROM build compiles."""
    return _enrolment()[0]


def source_ownership_index():
    """Repo-relative source path -> owned symbols in ROM address order."""
    return {path: list(symbols) for path, symbols in _enrolment()[1].items()}


def source_definition_index():
    """Repo-relative source path -> function definitions expected from its object."""
    _enrolment()
    return {path: list(symbols)
            for path, symbols in (_definition_ownership_cache or {}).items()}


def enrolled_path_for(symbol):
    """The file the ROM build compiles for ``symbol``, or None if it is not enrolled.

    None is not a failure: unfinished or ROM-byte-backed work may have no source-owned
    delinks range even when a convention-named draft already exists. ``path_for`` adds
    that filename fallback when callers want either kind of answer."""
    rel = enrolment_index().get(symbol)
    if rel is None:
        return None
    path = REPO / rel
    return path if path.is_file() else None


def symbols_for(path):
    """Every symbol ``path`` owns, in ROM address order.

    The inverse of ``path_for``, and the half a merged TU makes necessary: `symbol_for`
    reads one symbol off the filename, which is right for legacy one-function sources
    and wrong for every source that owns more than one function. Falls back to the
    filename so an unenrolled file answers exactly as it always did."""
    owned = _enrolment()[1].get(_repo_relative(path))
    if owned:
        return list(owned)
    return [symbol_for(path)]


def _repo_relative(path):
    """``path`` as a repo-relative posix string, or None if it is outside the tree."""
    path = pathlib.Path(path)
    try:
        return (path if path.is_absolute() else REPO / path).resolve().relative_to(
            REPO.resolve()).as_posix()
    except ValueError:
        return None


def module_of(symbol):
    """`arm9` or `ovNNN` for an address-named symbol, else None.

    Read off the SYMBOL, never delinks.txt: at the moment a writer asks where a new file
    goes, the function it holds is not enrolled anywhere yet."""
    m = _UNNAMED_RE.match(symbol)
    return (m.group(1) or "arm9") if m else None


def class_of(symbol):
    """The class an Itanium-mangled or `<Class>_Spawn` symbol belongs to, else None.

    The OUTER component, deliberately. `_ZN5Sound6Player19SetPlayableSeqCountEii` is
    `Sound::Player`, and taking the second component would file it under the unrelated
    actor `Player`. A bare `_Z<len><name>` is a FREE function with no class at all --
    29 of those are in the tree, and reading the name as a class invents a directory
    apiece. `_ZTV`/`_ZTI`/`_ZThn` have no leading length either and fall out here."""
    m = _SPAWN_RE.match(symbol)
    if m:
        return m.group(1)
    if not symbol.startswith("_ZN"):
        return None
    rest = symbol[3:]
    if rest.startswith("K"):                      # const method: _ZNK...
        rest = rest[1:]
    m = re.match(r"(\d+)", rest)
    if not m:
        return None
    n, tail = int(m.group(1)), rest[len(m.group(1)):]
    return tail[:n] if len(tail) >= n else None


def _cohort_index():
    """class -> {directories holding its files}, off the same single scan."""
    global _cohort_cache
    if _cohort_cache is None:
        idx = {}
        for stem, paths in _scan().items():
            cls = class_of(stem)
            if cls:
                idx.setdefault(cls, set()).update(p.parent for p in paths)
        _cohort_cache = idx
    return _cohort_cache


def placement_for(symbol):
    """The subdirectory a NEW file for ``symbol`` belongs in, or None for the root.

    None is the honest answer for most of the tree today and is not a failure: it means
    nobody has moved this symbol's neighbours yet, so the root is still where they are."""
    mod = module_of(symbol)
    if mod is not None:
        d = SRC / UNNAMED_DIR / mod
        return d if d.is_dir() else None
    cls = class_of(symbol)
    if cls:
        # Flat siblings do not vote. The root is the unmigrated default, not a rival
        # choice, so a partly-moved class still follows the subdirectory it has. Two
        # subdirectories are real disagreement and are left alone.
        nested = {d for d in _cohort_index().get(cls, ()) if d != SRC}
        if len(nested) == 1:
            return nested.pop()
    return None


def _fits(directory, symbol):
    """Is ``directory`` a legal home for ``symbol``?

    Only the unnamed buckets have a rule strict enough to answer. Every other directory
    is a human's deliberate choice, so the honest answer there is yes -- leave it be."""
    try:
        rest = directory.relative_to(SRC / UNNAMED_DIR)
    except ValueError:
        return True
    return bool(rest.parts) and module_of(symbol) == rest.parts[0]


def rename_target(path, new_symbol):
    """Where a file must live once its symbol is renamed to ``new_symbol``.

    Renaming in place is the norm and stays the norm; this differs only when the old
    directory would become a lie. A `func_ov006_*` that becomes `_ZN7daTrs_c6RenderEv` cannot
    stay in `src/unnamed/ov006/`: that directory means "address-named symbols of ov006".
    Leaving it there misfiles the file and, worse, puts class `daTrs_c` in two directories at
    once -- which is exactly the state `placement_for` reads as disagreement, so every
    future `daTrs_c` method silently goes back to landing in the root.

    Renaming is the single most common way a file's correct home changes: 1,282 files
    went from `func_*` to a real name in the 60 days to 2026-08-04."""
    suffix = "".join(pathlib.Path(path).suffixes)
    home = placement_for(new_symbol)
    if home is None:
        home = path.parent if _fits(path.parent, new_symbol) else SRC
    return home / (new_symbol + suffix)


def set_root(repo):
    """Resolve against a different checkout. Returns the previous ``(REPO, SRC)``.

    Reassigning REPO/SRC by hand works, but silently keeps a scan cache built from the
    old tree -- a confusing way to fail. Tools that accept a redirected source directory
    (worklist did, and its tests rely on it) go through this instead, so the cache
    invariant is not something a caller can forget.
    """
    global REPO, SRC
    saved = (REPO, SRC)
    REPO = pathlib.Path(repo)
    SRC = REPO / "src"
    invalidate()
    return saved


def paths_for(symbol):
    """Every existing source file for ``symbol``, the enrolled owner first.

    More than one is not normal -- a symbol with both a .c and a .cpp is the ambiguity
    ledger.bank refuses -- so callers that need exactly one should use ``path_for``.
    The enrolled owner leads rather than replacing the list, so the ambiguity stays
    visible to the tools that look for it while ``path_for`` answers with the file the
    linker actually reads. No enrolled symbol in the tree has both a .c and a .cpp, so
    this reorders nothing today."""
    owner = enrolled_path_for(symbol)
    direct = [SRC / f"{symbol}{ext}" for ext in SOURCE_SUFFIXES]
    hits = [p for p in direct if p.is_file()]
    if not hits:
        hits = sorted(_scan().get(symbol, []),
                      key=lambda p: SOURCE_SUFFIXES.index(p.suffix))
    if owner is None:
        return hits
    return [owner] + [p for p in hits if p != owner]


def path_for(symbol):
    """The source file for ``symbol``, or None. `.c` wins when both exist."""
    hits = paths_for(symbol)
    return hits[0] if hits else None


def new_path_for(symbol, ext):
    """Where a NEW file for ``symbol`` goes. ``ext`` is "c" or "cpp", with or without
    the dot. Writers use this instead of composing the path themselves, so the choice of
    directory stays in one place once `src/` gains structure."""
    ext = ext if ext.startswith(".") else "." + ext
    if ext not in SOURCE_SUFFIXES:
        raise ValueError(f"not a source extension: {ext!r}")
    existing = path_for(symbol)
    if existing is not None:
        # Keep a symbol where it already lives; changing the extension is the caller's
        # business, relocating it is not.
        return existing.with_suffix(ext)
    return (placement_for(symbol) or SRC) / f"{symbol}{ext}"


def iter_sources():
    """Every source file under src/, in sorted order."""
    if not SRC.is_dir():
        return
    for p in sorted(SRC.rglob("*")):
        if p.is_file() and p.suffix in SOURCE_SUFFIXES:
            yield p


def build_index():
    """symbol -> repo-relative posix path, for tooling that wants the whole map.

    Resolves collisions the same way ``path_for`` does (`.c` before `.cpp`) rather than
    letting directory order decide -- a handful of symbols in the tree have both, and an
    index that disagreed with the resolver would be worse than no index at all. The
    enrolment table is applied last for the same reason: an index that could not name
    the symbols inside a merged TU would disagree with ``path_for`` about exactly the
    files this module exists to keep findable."""
    out = {}
    for p in iter_sources():
        prev = out.get(p.stem)
        if prev is None or (SOURCE_SUFFIXES.index(p.suffix)
                            < SOURCE_SUFFIXES.index(pathlib.PurePosixPath(prev).suffix)):
            out[p.stem] = p.relative_to(REPO).as_posix()
    for symbol, rel in enrolment_index().items():
        if (REPO / rel).is_file():
            out[symbol] = rel
    return out


if __name__ == "__main__":
    import argparse
    import json

    ap = argparse.ArgumentParser(description="resolve a symbol to its src/ path")
    ap.add_argument("symbol", nargs="?", help="symbol to look up")
    ap.add_argument("--index", action="store_true", help="dump the whole map as JSON")
    a = ap.parse_args()
    if a.index:
        print(json.dumps(build_index(), indent=1))
    elif a.symbol:
        p = path_for(a.symbol)
        print(p.relative_to(REPO).as_posix() if p else f"{a.symbol}: not in src/")
    else:
        ap.error("pass a symbol or --index")
